//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
//
// On Thu Sep 10 12:52:46 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_put_operands               O     1
// get_result                     O   128 reg
// RDY_get_result                 O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_operands_a                 I   128 reg
// put_operands_b                 I   128 reg
// put_operands_c                 I   128 reg
// put_operands_d                 I   128 reg
// EN_put_operands                I     1
// EN_get_result                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkAblation_r8(CLK,
		     RST_N,

		     put_operands_a,
		     put_operands_b,
		     put_operands_c,
		     put_operands_d,
		     EN_put_operands,
		     RDY_put_operands,

		     EN_get_result,
		     get_result,
		     RDY_get_result);
  input  CLK;
  input  RST_N;

  // action method put_operands
  input  [127 : 0] put_operands_a;
  input  [127 : 0] put_operands_b;
  input  [127 : 0] put_operands_c;
  input  [127 : 0] put_operands_d;
  input  EN_put_operands;
  output RDY_put_operands;

  // actionvalue method get_result
  input  EN_get_result;
  output [127 : 0] get_result;
  output RDY_get_result;

  // signals for module outputs
  wire [127 : 0] get_result;
  wire RDY_get_result, RDY_put_operands;

  // ports of submodule i_lanes_0
  wire [15 : 0] i_lanes_0$get_result,
		i_lanes_0$put_operands_a,
		i_lanes_0$put_operands_b,
		i_lanes_0$put_operands_c,
		i_lanes_0$put_operands_d;
  wire i_lanes_0$EN_get_result,
       i_lanes_0$EN_put_operands,
       i_lanes_0$RDY_get_result,
       i_lanes_0$RDY_put_operands;

  // ports of submodule i_lanes_1
  wire [15 : 0] i_lanes_1$get_result,
		i_lanes_1$put_operands_a,
		i_lanes_1$put_operands_b,
		i_lanes_1$put_operands_c,
		i_lanes_1$put_operands_d;
  wire i_lanes_1$EN_get_result,
       i_lanes_1$EN_put_operands,
       i_lanes_1$RDY_get_result,
       i_lanes_1$RDY_put_operands;

  // ports of submodule i_lanes_2
  wire [15 : 0] i_lanes_2$get_result,
		i_lanes_2$put_operands_a,
		i_lanes_2$put_operands_b,
		i_lanes_2$put_operands_c,
		i_lanes_2$put_operands_d;
  wire i_lanes_2$EN_get_result,
       i_lanes_2$EN_put_operands,
       i_lanes_2$RDY_get_result,
       i_lanes_2$RDY_put_operands;

  // ports of submodule i_lanes_3
  wire [15 : 0] i_lanes_3$get_result,
		i_lanes_3$put_operands_a,
		i_lanes_3$put_operands_b,
		i_lanes_3$put_operands_c,
		i_lanes_3$put_operands_d;
  wire i_lanes_3$EN_get_result,
       i_lanes_3$EN_put_operands,
       i_lanes_3$RDY_get_result,
       i_lanes_3$RDY_put_operands;

  // ports of submodule i_lanes_4
  wire [15 : 0] i_lanes_4$get_result,
		i_lanes_4$put_operands_a,
		i_lanes_4$put_operands_b,
		i_lanes_4$put_operands_c,
		i_lanes_4$put_operands_d;
  wire i_lanes_4$EN_get_result,
       i_lanes_4$EN_put_operands,
       i_lanes_4$RDY_get_result,
       i_lanes_4$RDY_put_operands;

  // ports of submodule i_lanes_5
  wire [15 : 0] i_lanes_5$get_result,
		i_lanes_5$put_operands_a,
		i_lanes_5$put_operands_b,
		i_lanes_5$put_operands_c,
		i_lanes_5$put_operands_d;
  wire i_lanes_5$EN_get_result,
       i_lanes_5$EN_put_operands,
       i_lanes_5$RDY_get_result,
       i_lanes_5$RDY_put_operands;

  // ports of submodule i_lanes_6
  wire [15 : 0] i_lanes_6$get_result,
		i_lanes_6$put_operands_a,
		i_lanes_6$put_operands_b,
		i_lanes_6$put_operands_c,
		i_lanes_6$put_operands_d;
  wire i_lanes_6$EN_get_result,
       i_lanes_6$EN_put_operands,
       i_lanes_6$RDY_get_result,
       i_lanes_6$RDY_put_operands;

  // ports of submodule i_lanes_7
  wire [15 : 0] i_lanes_7$get_result,
		i_lanes_7$put_operands_a,
		i_lanes_7$put_operands_b,
		i_lanes_7$put_operands_c,
		i_lanes_7$put_operands_d;
  wire i_lanes_7$EN_get_result,
       i_lanes_7$EN_put_operands,
       i_lanes_7$RDY_get_result,
       i_lanes_7$RDY_put_operands;

  // remaining internal signals
  wire i_lanes_1_RDY_get_result__9_AND_i_lanes_2_RDY__ETC___d71,
       i_lanes_1_RDY_put_operands__4_AND_i_lanes_2_RD_ETC___d46;

  // action method put_operands
  assign RDY_put_operands =
	     i_lanes_0$RDY_put_operands &&
	     i_lanes_1_RDY_put_operands__4_AND_i_lanes_2_RD_ETC___d46 ;

  // actionvalue method get_result
  assign get_result =
	     { i_lanes_7$get_result,
	       i_lanes_6$get_result,
	       i_lanes_5$get_result,
	       i_lanes_4$get_result,
	       i_lanes_3$get_result,
	       i_lanes_2$get_result,
	       i_lanes_1$get_result,
	       i_lanes_0$get_result } ;
  assign RDY_get_result =
	     i_lanes_0$RDY_get_result &&
	     i_lanes_1_RDY_get_result__9_AND_i_lanes_2_RDY__ETC___d71 ;

  // submodule i_lanes_0
  mkBF16_SIMD i_lanes_0(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_0$put_operands_a),
			.put_operands_b(i_lanes_0$put_operands_b),
			.put_operands_c(i_lanes_0$put_operands_c),
			.put_operands_d(i_lanes_0$put_operands_d),
			.EN_put_operands(i_lanes_0$EN_put_operands),
			.EN_get_result(i_lanes_0$EN_get_result),
			.RDY_put_operands(i_lanes_0$RDY_put_operands),
			.get_result(i_lanes_0$get_result),
			.RDY_get_result(i_lanes_0$RDY_get_result));

  // submodule i_lanes_1
  mkBF16_SIMD i_lanes_1(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_1$put_operands_a),
			.put_operands_b(i_lanes_1$put_operands_b),
			.put_operands_c(i_lanes_1$put_operands_c),
			.put_operands_d(i_lanes_1$put_operands_d),
			.EN_put_operands(i_lanes_1$EN_put_operands),
			.EN_get_result(i_lanes_1$EN_get_result),
			.RDY_put_operands(i_lanes_1$RDY_put_operands),
			.get_result(i_lanes_1$get_result),
			.RDY_get_result(i_lanes_1$RDY_get_result));

  // submodule i_lanes_2
  mkBF16_SIMD i_lanes_2(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_2$put_operands_a),
			.put_operands_b(i_lanes_2$put_operands_b),
			.put_operands_c(i_lanes_2$put_operands_c),
			.put_operands_d(i_lanes_2$put_operands_d),
			.EN_put_operands(i_lanes_2$EN_put_operands),
			.EN_get_result(i_lanes_2$EN_get_result),
			.RDY_put_operands(i_lanes_2$RDY_put_operands),
			.get_result(i_lanes_2$get_result),
			.RDY_get_result(i_lanes_2$RDY_get_result));

  // submodule i_lanes_3
  mkBF16_SIMD i_lanes_3(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_3$put_operands_a),
			.put_operands_b(i_lanes_3$put_operands_b),
			.put_operands_c(i_lanes_3$put_operands_c),
			.put_operands_d(i_lanes_3$put_operands_d),
			.EN_put_operands(i_lanes_3$EN_put_operands),
			.EN_get_result(i_lanes_3$EN_get_result),
			.RDY_put_operands(i_lanes_3$RDY_put_operands),
			.get_result(i_lanes_3$get_result),
			.RDY_get_result(i_lanes_3$RDY_get_result));

  // submodule i_lanes_4
  mkBF16_SIMD i_lanes_4(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_4$put_operands_a),
			.put_operands_b(i_lanes_4$put_operands_b),
			.put_operands_c(i_lanes_4$put_operands_c),
			.put_operands_d(i_lanes_4$put_operands_d),
			.EN_put_operands(i_lanes_4$EN_put_operands),
			.EN_get_result(i_lanes_4$EN_get_result),
			.RDY_put_operands(i_lanes_4$RDY_put_operands),
			.get_result(i_lanes_4$get_result),
			.RDY_get_result(i_lanes_4$RDY_get_result));

  // submodule i_lanes_5
  mkBF16_SIMD i_lanes_5(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_5$put_operands_a),
			.put_operands_b(i_lanes_5$put_operands_b),
			.put_operands_c(i_lanes_5$put_operands_c),
			.put_operands_d(i_lanes_5$put_operands_d),
			.EN_put_operands(i_lanes_5$EN_put_operands),
			.EN_get_result(i_lanes_5$EN_get_result),
			.RDY_put_operands(i_lanes_5$RDY_put_operands),
			.get_result(i_lanes_5$get_result),
			.RDY_get_result(i_lanes_5$RDY_get_result));

  // submodule i_lanes_6
  mkBF16_SIMD i_lanes_6(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_6$put_operands_a),
			.put_operands_b(i_lanes_6$put_operands_b),
			.put_operands_c(i_lanes_6$put_operands_c),
			.put_operands_d(i_lanes_6$put_operands_d),
			.EN_put_operands(i_lanes_6$EN_put_operands),
			.EN_get_result(i_lanes_6$EN_get_result),
			.RDY_put_operands(i_lanes_6$RDY_put_operands),
			.get_result(i_lanes_6$get_result),
			.RDY_get_result(i_lanes_6$RDY_get_result));

  // submodule i_lanes_7
  mkBF16_SIMD i_lanes_7(.CLK(CLK),
			.RST_N(RST_N),
			.put_operands_a(i_lanes_7$put_operands_a),
			.put_operands_b(i_lanes_7$put_operands_b),
			.put_operands_c(i_lanes_7$put_operands_c),
			.put_operands_d(i_lanes_7$put_operands_d),
			.EN_put_operands(i_lanes_7$EN_put_operands),
			.EN_get_result(i_lanes_7$EN_get_result),
			.RDY_put_operands(i_lanes_7$RDY_put_operands),
			.get_result(i_lanes_7$get_result),
			.RDY_get_result(i_lanes_7$RDY_get_result));

  // submodule i_lanes_0
  assign i_lanes_0$put_operands_a = put_operands_a[15:0] ;
  assign i_lanes_0$put_operands_b = put_operands_b[15:0] ;
  assign i_lanes_0$put_operands_c = put_operands_c[15:0] ;
  assign i_lanes_0$put_operands_d = put_operands_d[15:0] ;
  assign i_lanes_0$EN_put_operands = EN_put_operands ;
  assign i_lanes_0$EN_get_result = EN_get_result ;

  // submodule i_lanes_1
  assign i_lanes_1$put_operands_a = put_operands_a[31:16] ;
  assign i_lanes_1$put_operands_b = put_operands_b[31:16] ;
  assign i_lanes_1$put_operands_c = put_operands_c[31:16] ;
  assign i_lanes_1$put_operands_d = put_operands_d[31:16] ;
  assign i_lanes_1$EN_put_operands = EN_put_operands ;
  assign i_lanes_1$EN_get_result = EN_get_result ;

  // submodule i_lanes_2
  assign i_lanes_2$put_operands_a = put_operands_a[47:32] ;
  assign i_lanes_2$put_operands_b = put_operands_b[47:32] ;
  assign i_lanes_2$put_operands_c = put_operands_c[47:32] ;
  assign i_lanes_2$put_operands_d = put_operands_d[47:32] ;
  assign i_lanes_2$EN_put_operands = EN_put_operands ;
  assign i_lanes_2$EN_get_result = EN_get_result ;

  // submodule i_lanes_3
  assign i_lanes_3$put_operands_a = put_operands_a[63:48] ;
  assign i_lanes_3$put_operands_b = put_operands_b[63:48] ;
  assign i_lanes_3$put_operands_c = put_operands_c[63:48] ;
  assign i_lanes_3$put_operands_d = put_operands_d[63:48] ;
  assign i_lanes_3$EN_put_operands = EN_put_operands ;
  assign i_lanes_3$EN_get_result = EN_get_result ;

  // submodule i_lanes_4
  assign i_lanes_4$put_operands_a = put_operands_a[79:64] ;
  assign i_lanes_4$put_operands_b = put_operands_b[79:64] ;
  assign i_lanes_4$put_operands_c = put_operands_c[79:64] ;
  assign i_lanes_4$put_operands_d = put_operands_d[79:64] ;
  assign i_lanes_4$EN_put_operands = EN_put_operands ;
  assign i_lanes_4$EN_get_result = EN_get_result ;

  // submodule i_lanes_5
  assign i_lanes_5$put_operands_a = put_operands_a[95:80] ;
  assign i_lanes_5$put_operands_b = put_operands_b[95:80] ;
  assign i_lanes_5$put_operands_c = put_operands_c[95:80] ;
  assign i_lanes_5$put_operands_d = put_operands_d[95:80] ;
  assign i_lanes_5$EN_put_operands = EN_put_operands ;
  assign i_lanes_5$EN_get_result = EN_get_result ;

  // submodule i_lanes_6
  assign i_lanes_6$put_operands_a = put_operands_a[111:96] ;
  assign i_lanes_6$put_operands_b = put_operands_b[111:96] ;
  assign i_lanes_6$put_operands_c = put_operands_c[111:96] ;
  assign i_lanes_6$put_operands_d = put_operands_d[111:96] ;
  assign i_lanes_6$EN_put_operands = EN_put_operands ;
  assign i_lanes_6$EN_get_result = EN_get_result ;

  // submodule i_lanes_7
  assign i_lanes_7$put_operands_a = put_operands_a[127:112] ;
  assign i_lanes_7$put_operands_b = put_operands_b[127:112] ;
  assign i_lanes_7$put_operands_c = put_operands_c[127:112] ;
  assign i_lanes_7$put_operands_d = put_operands_d[127:112] ;
  assign i_lanes_7$EN_put_operands = EN_put_operands ;
  assign i_lanes_7$EN_get_result = EN_get_result ;

  // remaining internal signals
  assign i_lanes_1_RDY_get_result__9_AND_i_lanes_2_RDY__ETC___d71 =
	     i_lanes_1$RDY_get_result && i_lanes_2$RDY_get_result &&
	     i_lanes_3$RDY_get_result &&
	     i_lanes_4$RDY_get_result &&
	     i_lanes_5$RDY_get_result &&
	     i_lanes_6$RDY_get_result &&
	     i_lanes_7$RDY_get_result ;
  assign i_lanes_1_RDY_put_operands__4_AND_i_lanes_2_RD_ETC___d46 =
	     i_lanes_1$RDY_put_operands && i_lanes_2$RDY_put_operands &&
	     i_lanes_3$RDY_put_operands &&
	     i_lanes_4$RDY_put_operands &&
	     i_lanes_5$RDY_put_operands &&
	     i_lanes_6$RDY_put_operands &&
	     i_lanes_7$RDY_put_operands ;
endmodule  // mkAblation_r8

