/*
 * Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
 * 
 * On Mon Oct 27 08:19:01 UTC 2025
 * 
 */

/* Generation options: */
#ifndef __mkBF16_PE_h__
#define __mkBF16_PE_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkBF16_PE module */
class MOD_mkBF16_PE : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_activation_out_reg;
  MOD_Reg<tUInt32> INST_psum_out_reg;
  MOD_Reg<tUInt32> INST_weight_reg;
 
 /* Constructor */
 public:
  MOD_mkBF16_PE(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_load_weight(tUInt32 ARG_load_weight_w);
  tUInt8 METH_RDY_load_weight();
  void METH_compute(tUInt32 ARG_compute_act_in, tUInt32 ARG_compute_psum_in);
  tUInt8 METH_RDY_compute();
  tUInt32 METH_get_activation_out();
  tUInt8 METH_RDY_get_activation_out();
  tUInt32 METH_get_psum_out();
  tUInt8 METH_RDY_get_psum_out();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBF16_PE &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBF16_PE &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBF16_PE &backing);
};

#endif /* ifndef __mkBF16_PE_h__ */
