/*
 * Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
 * 
 * On Mon Oct 27 11:48:42 UTC 2025
 * 
 */

/* Generation options: */
#ifndef __mkBF16_16x16SA_h__
#define __mkBF16_16x16SA_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBF16_PE.h"


/* Class declaration for the mkBF16_16x16SA module */
class MOD_mkBF16_16x16SA : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_computing;
  MOD_Reg<tUInt32> INST_cycle_count;
  MOD_Reg<tUInt32> INST_mat_a_0;
  MOD_Reg<tUInt32> INST_mat_a_1;
  MOD_Reg<tUInt32> INST_mat_a_10;
  MOD_Reg<tUInt32> INST_mat_a_11;
  MOD_Reg<tUInt32> INST_mat_a_12;
  MOD_Reg<tUInt32> INST_mat_a_13;
  MOD_Reg<tUInt32> INST_mat_a_14;
  MOD_Reg<tUInt32> INST_mat_a_15;
  MOD_Reg<tUInt32> INST_mat_a_2;
  MOD_Reg<tUInt32> INST_mat_a_3;
  MOD_Reg<tUInt32> INST_mat_a_4;
  MOD_Reg<tUInt32> INST_mat_a_5;
  MOD_Reg<tUInt32> INST_mat_a_6;
  MOD_Reg<tUInt32> INST_mat_a_7;
  MOD_Reg<tUInt32> INST_mat_a_8;
  MOD_Reg<tUInt32> INST_mat_a_9;
  MOD_Reg<tUInt32> INST_mat_w_0_0;
  MOD_Reg<tUInt32> INST_mat_w_0_1;
  MOD_Reg<tUInt32> INST_mat_w_0_10;
  MOD_Reg<tUInt32> INST_mat_w_0_11;
  MOD_Reg<tUInt32> INST_mat_w_0_12;
  MOD_Reg<tUInt32> INST_mat_w_0_13;
  MOD_Reg<tUInt32> INST_mat_w_0_14;
  MOD_Reg<tUInt32> INST_mat_w_0_15;
  MOD_Reg<tUInt32> INST_mat_w_0_2;
  MOD_Reg<tUInt32> INST_mat_w_0_3;
  MOD_Reg<tUInt32> INST_mat_w_0_4;
  MOD_Reg<tUInt32> INST_mat_w_0_5;
  MOD_Reg<tUInt32> INST_mat_w_0_6;
  MOD_Reg<tUInt32> INST_mat_w_0_7;
  MOD_Reg<tUInt32> INST_mat_w_0_8;
  MOD_Reg<tUInt32> INST_mat_w_0_9;
  MOD_Reg<tUInt32> INST_mat_w_10_0;
  MOD_Reg<tUInt32> INST_mat_w_10_1;
  MOD_Reg<tUInt32> INST_mat_w_10_10;
  MOD_Reg<tUInt32> INST_mat_w_10_11;
  MOD_Reg<tUInt32> INST_mat_w_10_12;
  MOD_Reg<tUInt32> INST_mat_w_10_13;
  MOD_Reg<tUInt32> INST_mat_w_10_14;
  MOD_Reg<tUInt32> INST_mat_w_10_15;
  MOD_Reg<tUInt32> INST_mat_w_10_2;
  MOD_Reg<tUInt32> INST_mat_w_10_3;
  MOD_Reg<tUInt32> INST_mat_w_10_4;
  MOD_Reg<tUInt32> INST_mat_w_10_5;
  MOD_Reg<tUInt32> INST_mat_w_10_6;
  MOD_Reg<tUInt32> INST_mat_w_10_7;
  MOD_Reg<tUInt32> INST_mat_w_10_8;
  MOD_Reg<tUInt32> INST_mat_w_10_9;
  MOD_Reg<tUInt32> INST_mat_w_11_0;
  MOD_Reg<tUInt32> INST_mat_w_11_1;
  MOD_Reg<tUInt32> INST_mat_w_11_10;
  MOD_Reg<tUInt32> INST_mat_w_11_11;
  MOD_Reg<tUInt32> INST_mat_w_11_12;
  MOD_Reg<tUInt32> INST_mat_w_11_13;
  MOD_Reg<tUInt32> INST_mat_w_11_14;
  MOD_Reg<tUInt32> INST_mat_w_11_15;
  MOD_Reg<tUInt32> INST_mat_w_11_2;
  MOD_Reg<tUInt32> INST_mat_w_11_3;
  MOD_Reg<tUInt32> INST_mat_w_11_4;
  MOD_Reg<tUInt32> INST_mat_w_11_5;
  MOD_Reg<tUInt32> INST_mat_w_11_6;
  MOD_Reg<tUInt32> INST_mat_w_11_7;
  MOD_Reg<tUInt32> INST_mat_w_11_8;
  MOD_Reg<tUInt32> INST_mat_w_11_9;
  MOD_Reg<tUInt32> INST_mat_w_12_0;
  MOD_Reg<tUInt32> INST_mat_w_12_1;
  MOD_Reg<tUInt32> INST_mat_w_12_10;
  MOD_Reg<tUInt32> INST_mat_w_12_11;
  MOD_Reg<tUInt32> INST_mat_w_12_12;
  MOD_Reg<tUInt32> INST_mat_w_12_13;
  MOD_Reg<tUInt32> INST_mat_w_12_14;
  MOD_Reg<tUInt32> INST_mat_w_12_15;
  MOD_Reg<tUInt32> INST_mat_w_12_2;
  MOD_Reg<tUInt32> INST_mat_w_12_3;
  MOD_Reg<tUInt32> INST_mat_w_12_4;
  MOD_Reg<tUInt32> INST_mat_w_12_5;
  MOD_Reg<tUInt32> INST_mat_w_12_6;
  MOD_Reg<tUInt32> INST_mat_w_12_7;
  MOD_Reg<tUInt32> INST_mat_w_12_8;
  MOD_Reg<tUInt32> INST_mat_w_12_9;
  MOD_Reg<tUInt32> INST_mat_w_13_0;
  MOD_Reg<tUInt32> INST_mat_w_13_1;
  MOD_Reg<tUInt32> INST_mat_w_13_10;
  MOD_Reg<tUInt32> INST_mat_w_13_11;
  MOD_Reg<tUInt32> INST_mat_w_13_12;
  MOD_Reg<tUInt32> INST_mat_w_13_13;
  MOD_Reg<tUInt32> INST_mat_w_13_14;
  MOD_Reg<tUInt32> INST_mat_w_13_15;
  MOD_Reg<tUInt32> INST_mat_w_13_2;
  MOD_Reg<tUInt32> INST_mat_w_13_3;
  MOD_Reg<tUInt32> INST_mat_w_13_4;
  MOD_Reg<tUInt32> INST_mat_w_13_5;
  MOD_Reg<tUInt32> INST_mat_w_13_6;
  MOD_Reg<tUInt32> INST_mat_w_13_7;
  MOD_Reg<tUInt32> INST_mat_w_13_8;
  MOD_Reg<tUInt32> INST_mat_w_13_9;
  MOD_Reg<tUInt32> INST_mat_w_14_0;
  MOD_Reg<tUInt32> INST_mat_w_14_1;
  MOD_Reg<tUInt32> INST_mat_w_14_10;
  MOD_Reg<tUInt32> INST_mat_w_14_11;
  MOD_Reg<tUInt32> INST_mat_w_14_12;
  MOD_Reg<tUInt32> INST_mat_w_14_13;
  MOD_Reg<tUInt32> INST_mat_w_14_14;
  MOD_Reg<tUInt32> INST_mat_w_14_15;
  MOD_Reg<tUInt32> INST_mat_w_14_2;
  MOD_Reg<tUInt32> INST_mat_w_14_3;
  MOD_Reg<tUInt32> INST_mat_w_14_4;
  MOD_Reg<tUInt32> INST_mat_w_14_5;
  MOD_Reg<tUInt32> INST_mat_w_14_6;
  MOD_Reg<tUInt32> INST_mat_w_14_7;
  MOD_Reg<tUInt32> INST_mat_w_14_8;
  MOD_Reg<tUInt32> INST_mat_w_14_9;
  MOD_Reg<tUInt32> INST_mat_w_15_0;
  MOD_Reg<tUInt32> INST_mat_w_15_1;
  MOD_Reg<tUInt32> INST_mat_w_15_10;
  MOD_Reg<tUInt32> INST_mat_w_15_11;
  MOD_Reg<tUInt32> INST_mat_w_15_12;
  MOD_Reg<tUInt32> INST_mat_w_15_13;
  MOD_Reg<tUInt32> INST_mat_w_15_14;
  MOD_Reg<tUInt32> INST_mat_w_15_15;
  MOD_Reg<tUInt32> INST_mat_w_15_2;
  MOD_Reg<tUInt32> INST_mat_w_15_3;
  MOD_Reg<tUInt32> INST_mat_w_15_4;
  MOD_Reg<tUInt32> INST_mat_w_15_5;
  MOD_Reg<tUInt32> INST_mat_w_15_6;
  MOD_Reg<tUInt32> INST_mat_w_15_7;
  MOD_Reg<tUInt32> INST_mat_w_15_8;
  MOD_Reg<tUInt32> INST_mat_w_15_9;
  MOD_Reg<tUInt32> INST_mat_w_1_0;
  MOD_Reg<tUInt32> INST_mat_w_1_1;
  MOD_Reg<tUInt32> INST_mat_w_1_10;
  MOD_Reg<tUInt32> INST_mat_w_1_11;
  MOD_Reg<tUInt32> INST_mat_w_1_12;
  MOD_Reg<tUInt32> INST_mat_w_1_13;
  MOD_Reg<tUInt32> INST_mat_w_1_14;
  MOD_Reg<tUInt32> INST_mat_w_1_15;
  MOD_Reg<tUInt32> INST_mat_w_1_2;
  MOD_Reg<tUInt32> INST_mat_w_1_3;
  MOD_Reg<tUInt32> INST_mat_w_1_4;
  MOD_Reg<tUInt32> INST_mat_w_1_5;
  MOD_Reg<tUInt32> INST_mat_w_1_6;
  MOD_Reg<tUInt32> INST_mat_w_1_7;
  MOD_Reg<tUInt32> INST_mat_w_1_8;
  MOD_Reg<tUInt32> INST_mat_w_1_9;
  MOD_Reg<tUInt32> INST_mat_w_2_0;
  MOD_Reg<tUInt32> INST_mat_w_2_1;
  MOD_Reg<tUInt32> INST_mat_w_2_10;
  MOD_Reg<tUInt32> INST_mat_w_2_11;
  MOD_Reg<tUInt32> INST_mat_w_2_12;
  MOD_Reg<tUInt32> INST_mat_w_2_13;
  MOD_Reg<tUInt32> INST_mat_w_2_14;
  MOD_Reg<tUInt32> INST_mat_w_2_15;
  MOD_Reg<tUInt32> INST_mat_w_2_2;
  MOD_Reg<tUInt32> INST_mat_w_2_3;
  MOD_Reg<tUInt32> INST_mat_w_2_4;
  MOD_Reg<tUInt32> INST_mat_w_2_5;
  MOD_Reg<tUInt32> INST_mat_w_2_6;
  MOD_Reg<tUInt32> INST_mat_w_2_7;
  MOD_Reg<tUInt32> INST_mat_w_2_8;
  MOD_Reg<tUInt32> INST_mat_w_2_9;
  MOD_Reg<tUInt32> INST_mat_w_3_0;
  MOD_Reg<tUInt32> INST_mat_w_3_1;
  MOD_Reg<tUInt32> INST_mat_w_3_10;
  MOD_Reg<tUInt32> INST_mat_w_3_11;
  MOD_Reg<tUInt32> INST_mat_w_3_12;
  MOD_Reg<tUInt32> INST_mat_w_3_13;
  MOD_Reg<tUInt32> INST_mat_w_3_14;
  MOD_Reg<tUInt32> INST_mat_w_3_15;
  MOD_Reg<tUInt32> INST_mat_w_3_2;
  MOD_Reg<tUInt32> INST_mat_w_3_3;
  MOD_Reg<tUInt32> INST_mat_w_3_4;
  MOD_Reg<tUInt32> INST_mat_w_3_5;
  MOD_Reg<tUInt32> INST_mat_w_3_6;
  MOD_Reg<tUInt32> INST_mat_w_3_7;
  MOD_Reg<tUInt32> INST_mat_w_3_8;
  MOD_Reg<tUInt32> INST_mat_w_3_9;
  MOD_Reg<tUInt32> INST_mat_w_4_0;
  MOD_Reg<tUInt32> INST_mat_w_4_1;
  MOD_Reg<tUInt32> INST_mat_w_4_10;
  MOD_Reg<tUInt32> INST_mat_w_4_11;
  MOD_Reg<tUInt32> INST_mat_w_4_12;
  MOD_Reg<tUInt32> INST_mat_w_4_13;
  MOD_Reg<tUInt32> INST_mat_w_4_14;
  MOD_Reg<tUInt32> INST_mat_w_4_15;
  MOD_Reg<tUInt32> INST_mat_w_4_2;
  MOD_Reg<tUInt32> INST_mat_w_4_3;
  MOD_Reg<tUInt32> INST_mat_w_4_4;
  MOD_Reg<tUInt32> INST_mat_w_4_5;
  MOD_Reg<tUInt32> INST_mat_w_4_6;
  MOD_Reg<tUInt32> INST_mat_w_4_7;
  MOD_Reg<tUInt32> INST_mat_w_4_8;
  MOD_Reg<tUInt32> INST_mat_w_4_9;
  MOD_Reg<tUInt32> INST_mat_w_5_0;
  MOD_Reg<tUInt32> INST_mat_w_5_1;
  MOD_Reg<tUInt32> INST_mat_w_5_10;
  MOD_Reg<tUInt32> INST_mat_w_5_11;
  MOD_Reg<tUInt32> INST_mat_w_5_12;
  MOD_Reg<tUInt32> INST_mat_w_5_13;
  MOD_Reg<tUInt32> INST_mat_w_5_14;
  MOD_Reg<tUInt32> INST_mat_w_5_15;
  MOD_Reg<tUInt32> INST_mat_w_5_2;
  MOD_Reg<tUInt32> INST_mat_w_5_3;
  MOD_Reg<tUInt32> INST_mat_w_5_4;
  MOD_Reg<tUInt32> INST_mat_w_5_5;
  MOD_Reg<tUInt32> INST_mat_w_5_6;
  MOD_Reg<tUInt32> INST_mat_w_5_7;
  MOD_Reg<tUInt32> INST_mat_w_5_8;
  MOD_Reg<tUInt32> INST_mat_w_5_9;
  MOD_Reg<tUInt32> INST_mat_w_6_0;
  MOD_Reg<tUInt32> INST_mat_w_6_1;
  MOD_Reg<tUInt32> INST_mat_w_6_10;
  MOD_Reg<tUInt32> INST_mat_w_6_11;
  MOD_Reg<tUInt32> INST_mat_w_6_12;
  MOD_Reg<tUInt32> INST_mat_w_6_13;
  MOD_Reg<tUInt32> INST_mat_w_6_14;
  MOD_Reg<tUInt32> INST_mat_w_6_15;
  MOD_Reg<tUInt32> INST_mat_w_6_2;
  MOD_Reg<tUInt32> INST_mat_w_6_3;
  MOD_Reg<tUInt32> INST_mat_w_6_4;
  MOD_Reg<tUInt32> INST_mat_w_6_5;
  MOD_Reg<tUInt32> INST_mat_w_6_6;
  MOD_Reg<tUInt32> INST_mat_w_6_7;
  MOD_Reg<tUInt32> INST_mat_w_6_8;
  MOD_Reg<tUInt32> INST_mat_w_6_9;
  MOD_Reg<tUInt32> INST_mat_w_7_0;
  MOD_Reg<tUInt32> INST_mat_w_7_1;
  MOD_Reg<tUInt32> INST_mat_w_7_10;
  MOD_Reg<tUInt32> INST_mat_w_7_11;
  MOD_Reg<tUInt32> INST_mat_w_7_12;
  MOD_Reg<tUInt32> INST_mat_w_7_13;
  MOD_Reg<tUInt32> INST_mat_w_7_14;
  MOD_Reg<tUInt32> INST_mat_w_7_15;
  MOD_Reg<tUInt32> INST_mat_w_7_2;
  MOD_Reg<tUInt32> INST_mat_w_7_3;
  MOD_Reg<tUInt32> INST_mat_w_7_4;
  MOD_Reg<tUInt32> INST_mat_w_7_5;
  MOD_Reg<tUInt32> INST_mat_w_7_6;
  MOD_Reg<tUInt32> INST_mat_w_7_7;
  MOD_Reg<tUInt32> INST_mat_w_7_8;
  MOD_Reg<tUInt32> INST_mat_w_7_9;
  MOD_Reg<tUInt32> INST_mat_w_8_0;
  MOD_Reg<tUInt32> INST_mat_w_8_1;
  MOD_Reg<tUInt32> INST_mat_w_8_10;
  MOD_Reg<tUInt32> INST_mat_w_8_11;
  MOD_Reg<tUInt32> INST_mat_w_8_12;
  MOD_Reg<tUInt32> INST_mat_w_8_13;
  MOD_Reg<tUInt32> INST_mat_w_8_14;
  MOD_Reg<tUInt32> INST_mat_w_8_15;
  MOD_Reg<tUInt32> INST_mat_w_8_2;
  MOD_Reg<tUInt32> INST_mat_w_8_3;
  MOD_Reg<tUInt32> INST_mat_w_8_4;
  MOD_Reg<tUInt32> INST_mat_w_8_5;
  MOD_Reg<tUInt32> INST_mat_w_8_6;
  MOD_Reg<tUInt32> INST_mat_w_8_7;
  MOD_Reg<tUInt32> INST_mat_w_8_8;
  MOD_Reg<tUInt32> INST_mat_w_8_9;
  MOD_Reg<tUInt32> INST_mat_w_9_0;
  MOD_Reg<tUInt32> INST_mat_w_9_1;
  MOD_Reg<tUInt32> INST_mat_w_9_10;
  MOD_Reg<tUInt32> INST_mat_w_9_11;
  MOD_Reg<tUInt32> INST_mat_w_9_12;
  MOD_Reg<tUInt32> INST_mat_w_9_13;
  MOD_Reg<tUInt32> INST_mat_w_9_14;
  MOD_Reg<tUInt32> INST_mat_w_9_15;
  MOD_Reg<tUInt32> INST_mat_w_9_2;
  MOD_Reg<tUInt32> INST_mat_w_9_3;
  MOD_Reg<tUInt32> INST_mat_w_9_4;
  MOD_Reg<tUInt32> INST_mat_w_9_5;
  MOD_Reg<tUInt32> INST_mat_w_9_6;
  MOD_Reg<tUInt32> INST_mat_w_9_7;
  MOD_Reg<tUInt32> INST_mat_w_9_8;
  MOD_Reg<tUInt32> INST_mat_w_9_9;
  MOD_mkBF16_PE INST_pe_array_0_0;
  MOD_mkBF16_PE INST_pe_array_0_1;
  MOD_mkBF16_PE INST_pe_array_0_10;
  MOD_mkBF16_PE INST_pe_array_0_11;
  MOD_mkBF16_PE INST_pe_array_0_12;
  MOD_mkBF16_PE INST_pe_array_0_13;
  MOD_mkBF16_PE INST_pe_array_0_14;
  MOD_mkBF16_PE INST_pe_array_0_15;
  MOD_mkBF16_PE INST_pe_array_0_2;
  MOD_mkBF16_PE INST_pe_array_0_3;
  MOD_mkBF16_PE INST_pe_array_0_4;
  MOD_mkBF16_PE INST_pe_array_0_5;
  MOD_mkBF16_PE INST_pe_array_0_6;
  MOD_mkBF16_PE INST_pe_array_0_7;
  MOD_mkBF16_PE INST_pe_array_0_8;
  MOD_mkBF16_PE INST_pe_array_0_9;
  MOD_mkBF16_PE INST_pe_array_10_0;
  MOD_mkBF16_PE INST_pe_array_10_1;
  MOD_mkBF16_PE INST_pe_array_10_10;
  MOD_mkBF16_PE INST_pe_array_10_11;
  MOD_mkBF16_PE INST_pe_array_10_12;
  MOD_mkBF16_PE INST_pe_array_10_13;
  MOD_mkBF16_PE INST_pe_array_10_14;
  MOD_mkBF16_PE INST_pe_array_10_15;
  MOD_mkBF16_PE INST_pe_array_10_2;
  MOD_mkBF16_PE INST_pe_array_10_3;
  MOD_mkBF16_PE INST_pe_array_10_4;
  MOD_mkBF16_PE INST_pe_array_10_5;
  MOD_mkBF16_PE INST_pe_array_10_6;
  MOD_mkBF16_PE INST_pe_array_10_7;
  MOD_mkBF16_PE INST_pe_array_10_8;
  MOD_mkBF16_PE INST_pe_array_10_9;
  MOD_mkBF16_PE INST_pe_array_11_0;
  MOD_mkBF16_PE INST_pe_array_11_1;
  MOD_mkBF16_PE INST_pe_array_11_10;
  MOD_mkBF16_PE INST_pe_array_11_11;
  MOD_mkBF16_PE INST_pe_array_11_12;
  MOD_mkBF16_PE INST_pe_array_11_13;
  MOD_mkBF16_PE INST_pe_array_11_14;
  MOD_mkBF16_PE INST_pe_array_11_15;
  MOD_mkBF16_PE INST_pe_array_11_2;
  MOD_mkBF16_PE INST_pe_array_11_3;
  MOD_mkBF16_PE INST_pe_array_11_4;
  MOD_mkBF16_PE INST_pe_array_11_5;
  MOD_mkBF16_PE INST_pe_array_11_6;
  MOD_mkBF16_PE INST_pe_array_11_7;
  MOD_mkBF16_PE INST_pe_array_11_8;
  MOD_mkBF16_PE INST_pe_array_11_9;
  MOD_mkBF16_PE INST_pe_array_12_0;
  MOD_mkBF16_PE INST_pe_array_12_1;
  MOD_mkBF16_PE INST_pe_array_12_10;
  MOD_mkBF16_PE INST_pe_array_12_11;
  MOD_mkBF16_PE INST_pe_array_12_12;
  MOD_mkBF16_PE INST_pe_array_12_13;
  MOD_mkBF16_PE INST_pe_array_12_14;
  MOD_mkBF16_PE INST_pe_array_12_15;
  MOD_mkBF16_PE INST_pe_array_12_2;
  MOD_mkBF16_PE INST_pe_array_12_3;
  MOD_mkBF16_PE INST_pe_array_12_4;
  MOD_mkBF16_PE INST_pe_array_12_5;
  MOD_mkBF16_PE INST_pe_array_12_6;
  MOD_mkBF16_PE INST_pe_array_12_7;
  MOD_mkBF16_PE INST_pe_array_12_8;
  MOD_mkBF16_PE INST_pe_array_12_9;
  MOD_mkBF16_PE INST_pe_array_13_0;
  MOD_mkBF16_PE INST_pe_array_13_1;
  MOD_mkBF16_PE INST_pe_array_13_10;
  MOD_mkBF16_PE INST_pe_array_13_11;
  MOD_mkBF16_PE INST_pe_array_13_12;
  MOD_mkBF16_PE INST_pe_array_13_13;
  MOD_mkBF16_PE INST_pe_array_13_14;
  MOD_mkBF16_PE INST_pe_array_13_15;
  MOD_mkBF16_PE INST_pe_array_13_2;
  MOD_mkBF16_PE INST_pe_array_13_3;
  MOD_mkBF16_PE INST_pe_array_13_4;
  MOD_mkBF16_PE INST_pe_array_13_5;
  MOD_mkBF16_PE INST_pe_array_13_6;
  MOD_mkBF16_PE INST_pe_array_13_7;
  MOD_mkBF16_PE INST_pe_array_13_8;
  MOD_mkBF16_PE INST_pe_array_13_9;
  MOD_mkBF16_PE INST_pe_array_14_0;
  MOD_mkBF16_PE INST_pe_array_14_1;
  MOD_mkBF16_PE INST_pe_array_14_10;
  MOD_mkBF16_PE INST_pe_array_14_11;
  MOD_mkBF16_PE INST_pe_array_14_12;
  MOD_mkBF16_PE INST_pe_array_14_13;
  MOD_mkBF16_PE INST_pe_array_14_14;
  MOD_mkBF16_PE INST_pe_array_14_15;
  MOD_mkBF16_PE INST_pe_array_14_2;
  MOD_mkBF16_PE INST_pe_array_14_3;
  MOD_mkBF16_PE INST_pe_array_14_4;
  MOD_mkBF16_PE INST_pe_array_14_5;
  MOD_mkBF16_PE INST_pe_array_14_6;
  MOD_mkBF16_PE INST_pe_array_14_7;
  MOD_mkBF16_PE INST_pe_array_14_8;
  MOD_mkBF16_PE INST_pe_array_14_9;
  MOD_mkBF16_PE INST_pe_array_15_0;
  MOD_mkBF16_PE INST_pe_array_15_1;
  MOD_mkBF16_PE INST_pe_array_15_10;
  MOD_mkBF16_PE INST_pe_array_15_11;
  MOD_mkBF16_PE INST_pe_array_15_12;
  MOD_mkBF16_PE INST_pe_array_15_13;
  MOD_mkBF16_PE INST_pe_array_15_14;
  MOD_mkBF16_PE INST_pe_array_15_15;
  MOD_mkBF16_PE INST_pe_array_15_2;
  MOD_mkBF16_PE INST_pe_array_15_3;
  MOD_mkBF16_PE INST_pe_array_15_4;
  MOD_mkBF16_PE INST_pe_array_15_5;
  MOD_mkBF16_PE INST_pe_array_15_6;
  MOD_mkBF16_PE INST_pe_array_15_7;
  MOD_mkBF16_PE INST_pe_array_15_8;
  MOD_mkBF16_PE INST_pe_array_15_9;
  MOD_mkBF16_PE INST_pe_array_1_0;
  MOD_mkBF16_PE INST_pe_array_1_1;
  MOD_mkBF16_PE INST_pe_array_1_10;
  MOD_mkBF16_PE INST_pe_array_1_11;
  MOD_mkBF16_PE INST_pe_array_1_12;
  MOD_mkBF16_PE INST_pe_array_1_13;
  MOD_mkBF16_PE INST_pe_array_1_14;
  MOD_mkBF16_PE INST_pe_array_1_15;
  MOD_mkBF16_PE INST_pe_array_1_2;
  MOD_mkBF16_PE INST_pe_array_1_3;
  MOD_mkBF16_PE INST_pe_array_1_4;
  MOD_mkBF16_PE INST_pe_array_1_5;
  MOD_mkBF16_PE INST_pe_array_1_6;
  MOD_mkBF16_PE INST_pe_array_1_7;
  MOD_mkBF16_PE INST_pe_array_1_8;
  MOD_mkBF16_PE INST_pe_array_1_9;
  MOD_mkBF16_PE INST_pe_array_2_0;
  MOD_mkBF16_PE INST_pe_array_2_1;
  MOD_mkBF16_PE INST_pe_array_2_10;
  MOD_mkBF16_PE INST_pe_array_2_11;
  MOD_mkBF16_PE INST_pe_array_2_12;
  MOD_mkBF16_PE INST_pe_array_2_13;
  MOD_mkBF16_PE INST_pe_array_2_14;
  MOD_mkBF16_PE INST_pe_array_2_15;
  MOD_mkBF16_PE INST_pe_array_2_2;
  MOD_mkBF16_PE INST_pe_array_2_3;
  MOD_mkBF16_PE INST_pe_array_2_4;
  MOD_mkBF16_PE INST_pe_array_2_5;
  MOD_mkBF16_PE INST_pe_array_2_6;
  MOD_mkBF16_PE INST_pe_array_2_7;
  MOD_mkBF16_PE INST_pe_array_2_8;
  MOD_mkBF16_PE INST_pe_array_2_9;
  MOD_mkBF16_PE INST_pe_array_3_0;
  MOD_mkBF16_PE INST_pe_array_3_1;
  MOD_mkBF16_PE INST_pe_array_3_10;
  MOD_mkBF16_PE INST_pe_array_3_11;
  MOD_mkBF16_PE INST_pe_array_3_12;
  MOD_mkBF16_PE INST_pe_array_3_13;
  MOD_mkBF16_PE INST_pe_array_3_14;
  MOD_mkBF16_PE INST_pe_array_3_15;
  MOD_mkBF16_PE INST_pe_array_3_2;
  MOD_mkBF16_PE INST_pe_array_3_3;
  MOD_mkBF16_PE INST_pe_array_3_4;
  MOD_mkBF16_PE INST_pe_array_3_5;
  MOD_mkBF16_PE INST_pe_array_3_6;
  MOD_mkBF16_PE INST_pe_array_3_7;
  MOD_mkBF16_PE INST_pe_array_3_8;
  MOD_mkBF16_PE INST_pe_array_3_9;
  MOD_mkBF16_PE INST_pe_array_4_0;
  MOD_mkBF16_PE INST_pe_array_4_1;
  MOD_mkBF16_PE INST_pe_array_4_10;
  MOD_mkBF16_PE INST_pe_array_4_11;
  MOD_mkBF16_PE INST_pe_array_4_12;
  MOD_mkBF16_PE INST_pe_array_4_13;
  MOD_mkBF16_PE INST_pe_array_4_14;
  MOD_mkBF16_PE INST_pe_array_4_15;
  MOD_mkBF16_PE INST_pe_array_4_2;
  MOD_mkBF16_PE INST_pe_array_4_3;
  MOD_mkBF16_PE INST_pe_array_4_4;
  MOD_mkBF16_PE INST_pe_array_4_5;
  MOD_mkBF16_PE INST_pe_array_4_6;
  MOD_mkBF16_PE INST_pe_array_4_7;
  MOD_mkBF16_PE INST_pe_array_4_8;
  MOD_mkBF16_PE INST_pe_array_4_9;
  MOD_mkBF16_PE INST_pe_array_5_0;
  MOD_mkBF16_PE INST_pe_array_5_1;
  MOD_mkBF16_PE INST_pe_array_5_10;
  MOD_mkBF16_PE INST_pe_array_5_11;
  MOD_mkBF16_PE INST_pe_array_5_12;
  MOD_mkBF16_PE INST_pe_array_5_13;
  MOD_mkBF16_PE INST_pe_array_5_14;
  MOD_mkBF16_PE INST_pe_array_5_15;
  MOD_mkBF16_PE INST_pe_array_5_2;
  MOD_mkBF16_PE INST_pe_array_5_3;
  MOD_mkBF16_PE INST_pe_array_5_4;
  MOD_mkBF16_PE INST_pe_array_5_5;
  MOD_mkBF16_PE INST_pe_array_5_6;
  MOD_mkBF16_PE INST_pe_array_5_7;
  MOD_mkBF16_PE INST_pe_array_5_8;
  MOD_mkBF16_PE INST_pe_array_5_9;
  MOD_mkBF16_PE INST_pe_array_6_0;
  MOD_mkBF16_PE INST_pe_array_6_1;
  MOD_mkBF16_PE INST_pe_array_6_10;
  MOD_mkBF16_PE INST_pe_array_6_11;
  MOD_mkBF16_PE INST_pe_array_6_12;
  MOD_mkBF16_PE INST_pe_array_6_13;
  MOD_mkBF16_PE INST_pe_array_6_14;
  MOD_mkBF16_PE INST_pe_array_6_15;
  MOD_mkBF16_PE INST_pe_array_6_2;
  MOD_mkBF16_PE INST_pe_array_6_3;
  MOD_mkBF16_PE INST_pe_array_6_4;
  MOD_mkBF16_PE INST_pe_array_6_5;
  MOD_mkBF16_PE INST_pe_array_6_6;
  MOD_mkBF16_PE INST_pe_array_6_7;
  MOD_mkBF16_PE INST_pe_array_6_8;
  MOD_mkBF16_PE INST_pe_array_6_9;
  MOD_mkBF16_PE INST_pe_array_7_0;
  MOD_mkBF16_PE INST_pe_array_7_1;
  MOD_mkBF16_PE INST_pe_array_7_10;
  MOD_mkBF16_PE INST_pe_array_7_11;
  MOD_mkBF16_PE INST_pe_array_7_12;
  MOD_mkBF16_PE INST_pe_array_7_13;
  MOD_mkBF16_PE INST_pe_array_7_14;
  MOD_mkBF16_PE INST_pe_array_7_15;
  MOD_mkBF16_PE INST_pe_array_7_2;
  MOD_mkBF16_PE INST_pe_array_7_3;
  MOD_mkBF16_PE INST_pe_array_7_4;
  MOD_mkBF16_PE INST_pe_array_7_5;
  MOD_mkBF16_PE INST_pe_array_7_6;
  MOD_mkBF16_PE INST_pe_array_7_7;
  MOD_mkBF16_PE INST_pe_array_7_8;
  MOD_mkBF16_PE INST_pe_array_7_9;
  MOD_mkBF16_PE INST_pe_array_8_0;
  MOD_mkBF16_PE INST_pe_array_8_1;
  MOD_mkBF16_PE INST_pe_array_8_10;
  MOD_mkBF16_PE INST_pe_array_8_11;
  MOD_mkBF16_PE INST_pe_array_8_12;
  MOD_mkBF16_PE INST_pe_array_8_13;
  MOD_mkBF16_PE INST_pe_array_8_14;
  MOD_mkBF16_PE INST_pe_array_8_15;
  MOD_mkBF16_PE INST_pe_array_8_2;
  MOD_mkBF16_PE INST_pe_array_8_3;
  MOD_mkBF16_PE INST_pe_array_8_4;
  MOD_mkBF16_PE INST_pe_array_8_5;
  MOD_mkBF16_PE INST_pe_array_8_6;
  MOD_mkBF16_PE INST_pe_array_8_7;
  MOD_mkBF16_PE INST_pe_array_8_8;
  MOD_mkBF16_PE INST_pe_array_8_9;
  MOD_mkBF16_PE INST_pe_array_9_0;
  MOD_mkBF16_PE INST_pe_array_9_1;
  MOD_mkBF16_PE INST_pe_array_9_10;
  MOD_mkBF16_PE INST_pe_array_9_11;
  MOD_mkBF16_PE INST_pe_array_9_12;
  MOD_mkBF16_PE INST_pe_array_9_13;
  MOD_mkBF16_PE INST_pe_array_9_14;
  MOD_mkBF16_PE INST_pe_array_9_15;
  MOD_mkBF16_PE INST_pe_array_9_2;
  MOD_mkBF16_PE INST_pe_array_9_3;
  MOD_mkBF16_PE INST_pe_array_9_4;
  MOD_mkBF16_PE INST_pe_array_9_5;
  MOD_mkBF16_PE INST_pe_array_9_6;
  MOD_mkBF16_PE INST_pe_array_9_7;
  MOD_mkBF16_PE INST_pe_array_9_8;
  MOD_mkBF16_PE INST_pe_array_9_9;
  MOD_Reg<tUInt8> INST_result_captured_0;
  MOD_Reg<tUInt8> INST_result_captured_1;
  MOD_Reg<tUInt8> INST_result_captured_10;
  MOD_Reg<tUInt8> INST_result_captured_11;
  MOD_Reg<tUInt8> INST_result_captured_12;
  MOD_Reg<tUInt8> INST_result_captured_13;
  MOD_Reg<tUInt8> INST_result_captured_14;
  MOD_Reg<tUInt8> INST_result_captured_15;
  MOD_Reg<tUInt8> INST_result_captured_2;
  MOD_Reg<tUInt8> INST_result_captured_3;
  MOD_Reg<tUInt8> INST_result_captured_4;
  MOD_Reg<tUInt8> INST_result_captured_5;
  MOD_Reg<tUInt8> INST_result_captured_6;
  MOD_Reg<tUInt8> INST_result_captured_7;
  MOD_Reg<tUInt8> INST_result_captured_8;
  MOD_Reg<tUInt8> INST_result_captured_9;
  MOD_Reg<tUInt32> INST_result_matrix_0;
  MOD_Reg<tUInt32> INST_result_matrix_1;
  MOD_Reg<tUInt32> INST_result_matrix_10;
  MOD_Reg<tUInt32> INST_result_matrix_11;
  MOD_Reg<tUInt32> INST_result_matrix_12;
  MOD_Reg<tUInt32> INST_result_matrix_13;
  MOD_Reg<tUInt32> INST_result_matrix_14;
  MOD_Reg<tUInt32> INST_result_matrix_15;
  MOD_Reg<tUInt32> INST_result_matrix_2;
  MOD_Reg<tUInt32> INST_result_matrix_3;
  MOD_Reg<tUInt32> INST_result_matrix_4;
  MOD_Reg<tUInt32> INST_result_matrix_5;
  MOD_Reg<tUInt32> INST_result_matrix_6;
  MOD_Reg<tUInt32> INST_result_matrix_7;
  MOD_Reg<tUInt32> INST_result_matrix_8;
  MOD_Reg<tUInt32> INST_result_matrix_9;
 
 /* Constructor */
 public:
  MOD_mkBF16_16x16SA(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_start;
  tUWide PORT_load_weights_w;
  tUWide PORT_load_activations_act;
  tUWide PORT_get_result;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_start;
  tUInt8 DEF_NOT_computing___d937;
  tUInt8 DEF_NOT_cycle_count_SLT_31___d680;
  tUInt32 DEF_b__h29255;
  tUInt8 DEF_computing__h29246;
  tUInt8 DEF_cycle_count_SLT_31___d3;
 
 /* Local definitions */
 private:
  tUWide DEF_result_matrix_15_54_CONCAT_result_matrix_14_55_ETC___d974;
  tUWide DEF_result_matrix_15_54_CONCAT_result_matrix_14_55_ETC___d971;
  tUWide DEF_result_matrix_15_54_CONCAT_result_matrix_14_55_ETC___d968;
  tUWide DEF_result_matrix_15_54_CONCAT_result_matrix_14_55_ETC___d965;
  tUWide DEF_result_matrix_15_54_CONCAT_result_matrix_14_55_ETC___d962;
 
 /* Rules */
 public:
  void RL_systolic_compute();
  void RL_capture_out();
  void RL_stop_compute();
 
 /* Methods */
 public:
  void METH_load_weights(tUWide ARG_load_weights_w);
  tUInt8 METH_RDY_load_weights();
  void METH_load_activations(tUWide ARG_load_activations_act);
  tUInt8 METH_RDY_load_activations();
  void METH_start();
  tUInt8 METH_RDY_start();
  tUInt8 METH_is_done();
  tUInt8 METH_RDY_is_done();
  tUWide METH_get_result();
  tUInt8 METH_RDY_get_result();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBF16_16x16SA &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBF16_16x16SA &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBF16_16x16SA &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkBF16_16x16SA &backing);
};

#endif /* ifndef __mkBF16_16x16SA_h__ */
