/*
 * Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
 * 
 * On Mon Oct 27 07:01:48 UTC 2025
 * 
 */

/* Generation options: */
#ifndef __mkTb_COP_SA_h__
#define __mkTb_COP_SA_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkCOP.h"


/* Class declaration for the mkTb_COP_SA module */
class MOD_mkTb_COP_SA : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_comp_started;
  MOD_Reg<tUInt8> INST_current_input_chunk;
  MOD_Reg<tUInt8> INST_current_row_group;
  MOD_Reg<tUInt32> INST_cycle_count;
  MOD_mkCOP INST_dut;
  MOD_Reg<tUInt8> INST_test_started;
  MOD_Reg<tUInt32> INST_weights_loaded;
 
 /* Constructor */
 public:
  MOD_mkTb_COP_SA(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_cycle_count_EQ_0___d337;
  tUInt8 DEF_comp_started__h241106;
  tUInt8 DEF_dut_computation_done____d11;
  tUInt32 DEF_x__h302875;
  tUInt32 DEF_x__h302158;
  tUInt8 DEF_NOT_dut_computation_done__1___d12;
 
 /* Local definitions */
 private:
  tUInt8 DEF__read__h306;
  tUInt64 DEF_v__h302090;
  tUInt64 DEF_v__h292230;
  tUInt64 DEF_v__h380;
  tUWide DEF_dut_get_result____d232;
  tUInt8 DEF__read__h270;
  std::string DEF_IF_comp_started_0_THEN_STR_YES_ELSE_STR_NO___d344;
  std::string DEF_IF_dut_computation_done__1_THEN_STR_YES_ELSE_S_ETC___d345;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d213;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d210;
  tUWide DEF__1263766783573460981906112311700988867466442476_ETC___d212;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d201;
  tUWide DEF__2942436336477894759518355856884710647786135030_ETC___d206;
  tUWide DEF__1928355077474153109597949694367963970133121453_ETC___d209;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d186;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d194;
  tUWide DEF__4489801538815147032956475611701523815591636704_ETC___d200;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d165;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d176;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d185;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d138;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d152;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d164;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d105;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d122;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d137;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d66;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d86;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d104;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d44;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d65;
  tUWide DEF__1263766783573460981906112311700988867466442476_ETC___d211;
  tUWide DEF__2942436336477894759518355856884710647786135030_ETC___d205;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d193;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d175;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d151;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d85;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d121;
  tUWide DEF__1928355077474153109597949694367963970133121453_ETC___d208;
  tUWide DEF__4489801538815147032956475611701523815591636704_ETC___d199;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d184;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d163;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d136;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d103;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d43;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d64;
  tUWide DEF__2942436336477894759518355856884710647786135030_ETC___d204;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d192;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d174;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d150;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d84;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d120;
  tUWide DEF__1928355077474153109597949694367963970133121453_ETC___d207;
  tUWide DEF__4489801538815147032956475611701523815591636704_ETC___d198;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d183;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d162;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d135;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d102;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d42;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d63;
  tUWide DEF__2942436336477894759518355856884710647786135030_ETC___d203;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d191;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d173;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d149;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d83;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d119;
  tUWide DEF__4489801538815147032956475611701523815591636704_ETC___d197;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d182;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d161;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d134;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d101;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d41;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d62;
  tUWide DEF__2942436336477894759518355856884710647786135030_ETC___d202;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d190;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d172;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d148;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d82;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d118;
  tUWide DEF__4489801538815147032956475611701523815591636704_ETC___d196;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d181;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d160;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d133;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d100;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d40;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d61;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d189;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d171;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d147;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d81;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d117;
  tUWide DEF__4489801538815147032956475611701523815591636704_ETC___d195;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d180;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d159;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d132;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d99;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d39;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d60;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d188;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d170;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d146;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d80;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d116;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d179;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d158;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d131;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d98;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d38;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d59;
  tUWide DEF__6850893461326823475580559710237920861193293312_ETC___d187;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d169;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d145;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d79;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d115;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d178;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d157;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d130;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d97;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d37;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d58;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d168;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d144;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d78;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d114;
  tUWide DEF__10453633821604650078705688034420655610951680_C_ETC___d177;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d156;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d129;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d96;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d36;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d57;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d167;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d143;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d77;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d113;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d155;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d128;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d95;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d35;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d56;
  tUWide DEF__159509793420481110820094116736155023360_CONCAT_ETC___d166;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d142;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d76;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d112;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d154;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d127;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d94;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d34;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d55;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d141;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d75;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d111;
  tUWide DEF__2433926291206071637269502513674240_CONCAT_IF_c_ETC___d153;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d126;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d93;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d33;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d54;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d140;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d74;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d110;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d125;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d92;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d32;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d53;
  tUWide DEF__37138767871186395832359352320_CONCAT_IF_curren_ETC___d139;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d73;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d109;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d124;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d91;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d31;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d52;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d72;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d108;
  tUWide DEF__566692624987585385625600_CONCAT_IF_current_inp_ETC___d123;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d90;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d30;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d51;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d71;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d107;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d89;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d29;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d50;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d70;
  tUWide DEF__8647043227959982080_CONCAT_IF_current_input_ch_ETC___d106;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d88;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d28;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d49;
  tUWide DEF__2013296640_CONCAT_IF_current_input_chunk_8_EQ__ETC___d69;
  tUWide DEF__131943408629760_CONCAT_IF_current_input_chunk__ETC___d87;
  tUWide DEF__0_CONCAT_IF_current_input_chunk_8_EQ_0_9_THEN__ETC___d27;
  tUWide DEF__30720_CONCAT_IF_current_input_chunk_8_EQ_0_9_T_ETC___d48;
 
 /* Rules */
 public:
  void RL_start_computation();
  void RL_load_weights();
  void RL_check_done();
  void RL_count_cycles();
  void RL_initial_display();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb_COP_SA &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb_COP_SA &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb_COP_SA &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTb_COP_SA &backing);
};

#endif /* ifndef __mkTb_COP_SA_h__ */
