package Tb_TorchMaximum_SIMD_AblationPPA;

import BF16::*;
import TorchMaximum_SIMD::*;
import TorchMaximum_SIMD_AblationPPA::*;
import Vector::*;

// ============================================================
// STREAMING ABLATION TESTBENCH (elementwise-max version)
//
// Same family, same golden-data-driven per-element checking as
// Tb_BF16Divider_SIMD_AblationPPA.bsv / Tb_BF16Sigmoid_SIMD_AblationPPA.bsv,
// but collapsed to a SINGLE rule: because mkMaxAblationPPA_Generic
// is purely combinational (see TorchMaximum_SIMD_AblationPPA.bsv),
// there is no pipeline fill/drain, so there is no reason to split
// "feed" and "collect" into two rules that hand off to each other
// a few cycles apart, and no dut.hasResult() to gate on - the
// result for column k's inputs is available in the exact cycle
// those inputs are presented. This mirrors the original design's
// own reasoning (TorchMaximumVec768_Generic.bsv: "There is
// therefore no pipeline fill/drain to manage and no reason for a
// feed/collect rule split").
//
// TESTBENCH NOTE (carried over verbatim from
// TorchMaximumVec768_Configs_TB.bsv): the comparison here is
// BIT-EXACT using plain `==`, not the zero-tolerant bf16BitEq the
// divider/sigmoid TBs use, and not a tolerance check. maxBF16 is an
// exact selection (the output is always one of the two input bit
// patterns, verbatim), and the golden data was generated by
// replicating maxBF16's own decision rule, so the golden table
// already encodes exactly which raw bit pattern (including which
// specific +0/-0 encoding) the frozen scalar logic is expected to
// select - collapsing +0/-0 with bf16BitEq here would hide a
// genuine selection bug rather than tolerate a harmless rounding
// difference. This tests that the (r) wrapper correctly
// routes/addresses all 768 elements; it does not re-validate
// maxBF16's own comparison logic for every edge case (e.g.
// signed-zero handling) - that scalar algorithm is treated as
// already proven/frozen, exactly as the divider's and sigmoid's
// own arithmetic were.
//
// Two operations run back-to-back per config (op0 = the 16-value
// pattern, op1 = the 32-unique-value pattern), matching the
// original's coverage. The original bulk-interface TB's separate
// "anti-contamination" check is not needed here for the same
// reason it wasn't needed for sigmoid: every element of every
// column is checked against its own op-specific golden value on
// arrival, so stale or lane-swapped data already surfaces as an
// ordinary mismatch.
// ============================================================

// ------------------------------------------------------------
// Golden reference data - verbatim from TorchMaximumVec768_Configs_TB.bsv.
// Covers all three sign-combination branches (both positive, both
// negative, mixed signs) and cases where either operand wins.
// ------------------------------------------------------------

function Vector#(16, Bit#(16)) max16_a();
  Vector#(16, Bit#(16)) v = newVector;
  v[0]=16'h4040;  v[1]=16'h3fc0;  v[2]=16'hbf80;  v[3]=16'hc0a0;
  v[4]=16'h4000;  v[5]=16'hc080;  v[6]=16'h0000;  v[7]=16'h3f00;
  v[8]=16'h40e0;  v[9]=16'hbe80;  v[10]=16'h4120; v[11]=16'hc120;
  v[12]=16'h3e00; v[13]=16'hc100; v[14]=16'h40c0; v[15]=16'hc060;
  return v;
endfunction

function Vector#(16, Bit#(16)) max16_b();
  Vector#(16, Bit#(16)) v = newVector;
  v[0]=16'h4000;  v[1]=16'h4080;  v[2]=16'hc000;  v[3]=16'hbf00;
  v[4]=16'hc040;  v[5]=16'h3f80;  v[6]=16'h0000;  v[7]=16'h3f00;
  v[8]=16'h40e0;  v[9]=16'hbe80;  v[10]=16'hc120; v[11]=16'h4120;
  v[12]=16'hbe00; v[13]=16'hc108; v[14]=16'h40d0; v[15]=16'hc040;
  return v;
endfunction

function Vector#(16, Bit#(16)) max16_expected();
  Vector#(16, Bit#(16)) v = newVector;
  v[0]=16'h4040;  v[1]=16'h4080;  v[2]=16'hbf80;  v[3]=16'hbf00;
  v[4]=16'h4000;  v[5]=16'h3f80;  v[6]=16'h0000;  v[7]=16'h3f00;
  v[8]=16'h40e0;  v[9]=16'hbe80;  v[10]=16'h4120; v[11]=16'h4120;
  v[12]=16'h3e00; v[13]=16'hc100; v[14]=16'h40d0; v[15]=16'hc040;
  return v;
endfunction

function Vector#(32, Bit#(16)) max32_a();
  Vector#(32, Bit#(16)) v = newVector;
  v[0]=16'h4040;  v[1]=16'h3fc0;  v[2]=16'hbf80;  v[3]=16'hc0a0;
  v[4]=16'h4000;  v[5]=16'hc080;  v[6]=16'h0000;  v[7]=16'h3f00;
  v[8]=16'h40e0;  v[9]=16'hbe80;  v[10]=16'h4120; v[11]=16'hc120;
  v[12]=16'h3e00; v[13]=16'hc100; v[14]=16'h40c0; v[15]=16'hc060;
  v[16]=16'h42c8; v[17]=16'hc2c8; v[18]=16'h4248; v[19]=16'hc248;
  v[20]=16'h3a83; v[21]=16'hba83; v[22]=16'h3f80; v[23]=16'hbf80;
  v[24]=16'h4380; v[25]=16'hc380; v[26]=16'h0000; v[27]=16'h8000;
  v[28]=16'h4050; v[29]=16'hc050; v[30]=16'h461c; v[31]=16'hc61c;
  return v;
endfunction

function Vector#(32, Bit#(16)) max32_b();
  Vector#(32, Bit#(16)) v = newVector;
  v[0]=16'h4000;  v[1]=16'h4080;  v[2]=16'hc000;  v[3]=16'hbf00;
  v[4]=16'hc040;  v[5]=16'h3f80;  v[6]=16'h0000;  v[7]=16'h3f00;
  v[8]=16'h40e0;  v[9]=16'hbe80;  v[10]=16'hc120; v[11]=16'h4120;
  v[12]=16'hbe00; v[13]=16'hc108; v[14]=16'h40d0; v[15]=16'hc040;
  v[16]=16'h42c6; v[17]=16'hc2c6; v[18]=16'hc248; v[19]=16'h4248;
  v[20]=16'h3b03; v[21]=16'hbb03; v[22]=16'hbf80; v[23]=16'h3f80;
  v[24]=16'h437f; v[25]=16'hc37f; v[26]=16'h8000; v[27]=16'h0000;
  v[28]=16'h4048; v[29]=16'hc048; v[30]=16'h461c; v[31]=16'hc61c;
  return v;
endfunction

function Vector#(32, Bit#(16)) max32_expected();
  Vector#(32, Bit#(16)) v = newVector;
  v[0]=16'h4040;  v[1]=16'h4080;  v[2]=16'hbf80;  v[3]=16'hbf00;
  v[4]=16'h4000;  v[5]=16'h3f80;  v[6]=16'h0000;  v[7]=16'h3f00;
  v[8]=16'h40e0;  v[9]=16'hbe80;  v[10]=16'h4120; v[11]=16'h4120;
  v[12]=16'h3e00; v[13]=16'hc100; v[14]=16'h40d0; v[15]=16'hc040;
  v[16]=16'h42c8; v[17]=16'hc2c6; v[18]=16'h4248; v[19]=16'h4248;
  v[20]=16'h3b03; v[21]=16'hba83; v[22]=16'h3f80; v[23]=16'h3f80;
  v[24]=16'h4380; v[25]=16'hc37f; v[26]=16'h0000; v[27]=16'h0000;
  v[28]=16'h4050; v[29]=16'hc048; v[30]=16'h461c; v[31]=16'hc61c;
  return v;
endfunction

// op: 0 -> max16 (tiled mod 16), 1 -> max32 (tiled mod 32).
function Bit#(16) goldenA(UInt#(2) op, Bit#(11) flatIdx);
  return (op == 0) ? max16_a()[flatIdx[3:0]] : max32_a()[flatIdx[4:0]];
endfunction

function Bit#(16) goldenB(UInt#(2) op, Bit#(11) flatIdx);
  return (op == 0) ? max16_b()[flatIdx[3:0]] : max32_b()[flatIdx[4:0]];
endfunction

function Bit#(16) goldenExpected(UInt#(2) op, Bit#(11) flatIdx);
  return (op == 0) ? max16_expected()[flatIdx[3:0]] : max32_expected()[flatIdx[4:0]];
endfunction

// Fixed set of 12 scattered indices dumped in full for manual
// checking, per op. Fixed (not seeded-random) so a re-run shows
// the same elements.
function Bool isSpot(Bit#(11) i);
   return (i ==  0) || (i ==  13) || (i ==  45) || (i ==  63)
       || (i == 64) || (i == 130) || (i == 209) || (i == 300)
       || (i == 411) || (i == 512) || (i == 655) || (i == 767);
endfunction

// ------------------------------------------------------------
// Generic TB body. `cols` = 768/r columns to stream, per op;
// `expCyclesPerOp` = cols - 1 (see TorchMaximum_SIMD_AblationPPA.bsv
// for why this engine's formula has no "+4"/"+5" latency term).
// ------------------------------------------------------------
module mkTbBody#(IfcMaxAblationPPA#(r) dut,
                 Integer cols, Integer expCyclesPerOp, Integer nLabel, String label)(Empty)
   provisos (Add#(1, _unused, r));

   Integer rv = valueOf(r);

   Reg#(Bit#(32)) cyc              <- mkReg(0);
   Reg#(Bit#(11)) col              <- mkReg(0);
   Reg#(UInt#(2)) op                <- mkReg(0);
   Reg#(Bit#(32)) op_start          <- mkReg(0);
   Reg#(UInt#(16)) mismatches       <- mkReg(0);
   Reg#(UInt#(16)) total_mismatches <- mkReg(0);

   rule count_cycles;
      cyc <= cyc + 1;
   endrule

   // ---- The only rule: one column of r elements in AND out, same
   // cycle, checked immediately - no feed/collect split needed. ----
   rule process (op < 2);
      if (col == 0) begin
         op_start <= cyc;
         $display("\n################################################################");
         $display("# CONFIG %s | r=%0d lanes | n=%0d (label only) | starting op %0d",
                  label, rv, nLabel, op);
         $display("# %s golden tile, tiled mod %0d, %0d columns x %0d lanes = 768 elements",
                  (op == 0) ? "op0: max16 (hand-picked, all 3 sign branches)" : "op1: max32 (lane-order coverage)",
                  (op == 0) ? 16 : 32, cols, rv);
         $display("# expected: %0d cycles for this op (zero-latency: same-cycle result)", expCyclesPerOp);
         $display("################################################################");
      end

      Vector#(r, BF16) a_vec = newVector;
      Vector#(r, BF16) b_vec = newVector;
      for (Integer l = 0; l < rv; l = l + 1) begin
         Bit#(11) idx = col * fromInteger(rv) + fromInteger(l);
         a_vec[l] = toBF16(goldenA(op, idx));
         b_vec[l] = toBF16(goldenB(op, idx));
      end

      // Purely combinational - no <-, no Action, no waiting.
      Vector#(r, BF16) res = dut.get_max(a_vec, b_vec);

      UInt#(16) mismatchesThisCycle = 0;
      for (Integer l = 0; l < rv; l = l + 1) begin
         Bit#(11) idx      = col * fromInteger(rv) + fromInteger(l);
         Bit#(16) got      = fromBF16(res[l]);
         Bit#(16) a_in     = goldenA(op, idx);
         Bit#(16) b_in     = goldenB(op, idx);
         Bit#(16) expected = goldenExpected(op, idx);
         Bool     ok       = (got == expected);   // bit-exact, deliberately not bf16BitEq (see header note)

         if (isSpot(idx)) begin
            $display("+---------------------------------------------------------------");
            $display("| SPOT CHECK  op=%0d  elem=%0d   col=%0d  lane=%0d  cyc=%0d",
                     op, idx, col, l, cyc);
            $display("|    a = %h     b = %h", a_in, b_in);
            $display("|    max(a,b)   = %h   <- golden reference", expected);
            $display("|    DUT result = %h   %s", got, ok ? "OK" : "** MISMATCH **");
            $display("+---------------------------------------------------------------");
         end
         if (!ok) begin
            mismatchesThisCycle = mismatchesThisCycle + 1;
            $display("[cycle %0d] MISMATCH lane=%0d col=%0d elem=%0d a=%h b=%h -> got=%h expected=%h",
                     cyc, l, col, idx, a_in, b_in, got, expected);
         end
      end

      Bool lastCol = (col == fromInteger(cols - 1));
      UInt#(16) mismatches_bumped = mismatches + mismatchesThisCycle;

      // Default (always-on) progress ping every ~64 columns.
      if (!lastCol && (col != 0) && ((col & 63) == 0))
         $display("  [%s] op=%0d progress: %0d/%0d columns processed (cyc=%0d, mismatches so far=%0d)",
                  label, op, col, cols, cyc, mismatches_bumped);

      if (lastCol) begin
         Bit#(32) elapsed = cyc - op_start;
         $display("[cycle %0d] op %0d complete in %0d cycles (expected %0d) %s: %0d mismatches out of 768",
                  cyc, op, elapsed, expCyclesPerOp,
                  (elapsed == fromInteger(expCyclesPerOp)) ? "MATCH  " : "**DIFF**",
                  mismatches_bumped);

         if (mismatches_bumped == 0)
            $display("Max (r=%0d,n=%0d) op%0d: functional check PASS (768/768 elements bit-exact)", rv, nLabel, op);
         else
            $display("Max (r=%0d,n=%0d) op%0d: functional check FAIL (%0d mismatches)", rv, nLabel, op, mismatches_bumped);

         total_mismatches <= total_mismatches + mismatches_bumped;

         if (op == 1) begin
            $display("\n================================================");
            if (total_mismatches + mismatches_bumped == 0)
               $display("    TEST RESULT: PASS  (r=%0d, n=%0d)", rv, nLabel);
            else
               $display("    TEST RESULT: FAIL  (r=%0d, n=%0d)", rv, nLabel);
            $display("================================================\n");
            $finish(0);
         end else begin
            op <= 1;
         end
      end

      col         <= lastCol ? 0 : col + 1;
      mismatches  <= lastCol ? 0 : mismatches_bumped;
   endrule

   rule rl_timeout (cyc > fromInteger(expCyclesPerOp * 4 + 2000));
      $display("\nERROR: Timeout at cycle %0d (r=%0d n=%0d, op=%0d, col=%0d)", cyc, rv, nLabel, op, col);
      $finish(1);
   endrule

endmodule

// ------------------------------------------------------------
// One TB per (r, n) row of the sweep: 15 rows, but only 8
// distinct DUTs. cols = 768/r, expected cycles/op = cols - 1.
// ------------------------------------------------------------
(* synthesize *) module mkTbMax_r1_n64 (Empty);
   IfcMax_r1  d <- mkMaxAblation_r1();  Empty t <- mkTbBody(d, 768, 767,  64, "r1_n64 ");  return t; endmodule
(* synthesize *) module mkTbMax_r2_n64 (Empty);
   IfcMax_r2  d <- mkMaxAblation_r2();  Empty t <- mkTbBody(d, 384, 383,  64, "r2_n64 ");  return t; endmodule
(* synthesize *) module mkTbMax_r3_n64 (Empty);
   IfcMax_r3  d <- mkMaxAblation_r3();  Empty t <- mkTbBody(d, 256, 255,  64, "r3_n64 ");  return t; endmodule
(* synthesize *) module mkTbMax_r4_n64 (Empty);
   IfcMax_r4  d <- mkMaxAblation_r4();  Empty t <- mkTbBody(d, 192, 191,  64, "r4_n64 ");  return t; endmodule
(* synthesize *) module mkTbMax_r6_n64 (Empty);
   IfcMax_r6  d <- mkMaxAblation_r6();  Empty t <- mkTbBody(d, 128, 127,  64, "r6_n64 ");  return t; endmodule
(* synthesize *) module mkTbMax_r12_n64 (Empty);
   IfcMax_r12 d <- mkMaxAblation_r12();  Empty t <- mkTbBody(d,  64,  63,  64, "r12_n64");  return t; endmodule
(* synthesize *) module mkTbMax_r4_n16 (Empty);
   IfcMax_r4  d <- mkMaxAblation_r4();  Empty t <- mkTbBody(d, 192, 191,  16, "r4_n16 ");  return t; endmodule
(* synthesize *) module mkTbMax_r4_n32 (Empty);
   IfcMax_r4  d <- mkMaxAblation_r4();  Empty t <- mkTbBody(d, 192, 191,  32, "r4_n32 ");  return t; endmodule
(* synthesize *) module mkTbMax_r4_n96 (Empty);
   IfcMax_r4  d <- mkMaxAblation_r4();  Empty t <- mkTbBody(d, 192, 191,  96, "r4_n96 ");  return t; endmodule
(* synthesize *) module mkTbMax_r4_n192 (Empty);
   IfcMax_r4  d <- mkMaxAblation_r4();  Empty t <- mkTbBody(d, 192, 191, 192, "r4_n192");  return t; endmodule
(* synthesize *) module mkTbMax_r8_n32 (Empty);
   IfcMax_r8  d <- mkMaxAblation_r8();  Empty t <- mkTbBody(d,  96,  95,  32, "r8_n32 ");  return t; endmodule
(* synthesize *) module mkTbMax_r8_n96 (Empty);
   IfcMax_r8  d <- mkMaxAblation_r8();  Empty t <- mkTbBody(d,  96,  95,  96, "r8_n96 ");  return t; endmodule
(* synthesize *) module mkTbMax_r2_n128 (Empty);
   IfcMax_r2  d <- mkMaxAblation_r2();  Empty t <- mkTbBody(d, 384, 383, 128, "r2_n128");  return t; endmodule
(* synthesize *) module mkTbMax_r6_n128 (Empty);
   IfcMax_r6  d <- mkMaxAblation_r6();  Empty t <- mkTbBody(d, 128, 127, 128, "r6_n128");  return t; endmodule
(* synthesize *) module mkTbMax_r16_n48 (Empty);
   IfcMax_r16 d <- mkMaxAblation_r16();  Empty t <- mkTbBody(d,  48,  47,  48, "r16_n48");  return t; endmodule

endpackage
