//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e9)
//
// On Fri Nov 14 08:21:41 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_configure                  O     1 const
// RDY_load_and_step              O     1
// ready_for_input                O     1
// RDY_ready_for_input            O     1 const
// output_valid                   O     1 reg
// RDY_output_valid               O     1 const
// get_output                     O    21 reg
// RDY_get_output                 O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// configure_cfg                  I    52 unused
// load_and_step_v_t              I    16
// load_and_step_refr             I     4
// load_and_step_x_t              I    16
// EN_configure                   I     1 unused
// EN_load_and_step               I     1
// EN_get_output                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBF16_LIF_LoadStep(CLK,
			   RST_N,

			   configure_cfg,
			   EN_configure,
			   RDY_configure,

			   load_and_step_v_t,
			   load_and_step_refr,
			   load_and_step_x_t,
			   EN_load_and_step,
			   RDY_load_and_step,

			   ready_for_input,
			   RDY_ready_for_input,

			   output_valid,
			   RDY_output_valid,

			   EN_get_output,
			   get_output,
			   RDY_get_output);
  input  CLK;
  input  RST_N;

  // action method configure
  input  [51 : 0] configure_cfg;
  input  EN_configure;
  output RDY_configure;

  // action method load_and_step
  input  [15 : 0] load_and_step_v_t;
  input  [3 : 0] load_and_step_refr;
  input  [15 : 0] load_and_step_x_t;
  input  EN_load_and_step;
  output RDY_load_and_step;

  // value method ready_for_input
  output ready_for_input;
  output RDY_ready_for_input;

  // value method output_valid
  output output_valid;
  output RDY_output_valid;

  // actionvalue method get_output
  input  EN_get_output;
  output [20 : 0] get_output;
  output RDY_get_output;

  // signals for module outputs
  wire [20 : 0] get_output;
  wire RDY_configure,
       RDY_get_output,
       RDY_load_and_step,
       RDY_output_valid,
       RDY_ready_for_input,
       output_valid,
       ready_for_input;

  // register conf
  reg [51 : 0] conf;
  wire [51 : 0] conf$D_IN;
  wire conf$EN;

  // register config_valid
  reg config_valid;
  wire config_valid$D_IN, config_valid$EN;

  // register inv_tau_cached
  reg [15 : 0] inv_tau_cached;
  wire [15 : 0] inv_tau_cached$D_IN;
  wire inv_tau_cached$EN;

  // register output_reg
  reg [21 : 0] output_reg;
  wire [21 : 0] output_reg$D_IN;
  wire output_reg$EN;

  // register stage1_data
  reg [37 : 0] stage1_data;
  wire [37 : 0] stage1_data$D_IN;
  wire stage1_data$EN;

  // register stage2_data
  reg [37 : 0] stage2_data;
  wire [37 : 0] stage2_data$D_IN;
  wire stage2_data$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_pipeline_stage2, WILL_FIRE_RL_pipeline_stage3;

  // inputs to muxes for submodule ports
  wire [37 : 0] MUX_stage1_data$write_1__VAL_2,
		MUX_stage2_data$write_1__VAL_2;
  wire [21 : 0] MUX_output_reg$write_1__VAL_2;

  // remaining internal signals
  wire [31 : 0] _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37;
  wire [20 : 0] IF_load_and_step_refr_EQ_0_05_THEN_IF_load_and_ETC___d571;
  wire [19 : 0] IF_IF_IF_IF_stage2_data_BIT_37_THEN_stage2_dat_ETC___d402;
  wire [15 : 0] IF_NOT_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_T_ETC__q4,
		IF_conf_71_BITS_34_TO_27_11_EQ_0_12_AND_conf_7_ETC___d564,
		IF_load_and_step_v_t_BITS_14_TO_7_06_EQ_0_07_A_ETC___d565,
		IF_load_and_step_v_t_BITS_14_TO_7_06_EQ_0_07_A_ETC___d566,
		_theResult___snd__h1595,
		a__h2557,
		result_raw__h2910,
		result_raw__h4132,
		result_raw__h4385,
		stage1_data_BITS_20_TO_5__q1,
		stage2_data_BITS_20_TO_5__q3,
		stage2_data_BITS_36_TO_21__q2;
  wire [14 : 0] IF_IF_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_ETC___d231,
		IF_IF_IF_load_and_step_v_t_BIT_15_25_THEN_SEXT_ETC___d560,
		IF_IF_IF_stage2_data_BIT_37_THEN_stage2_data_B_ETC___d366,
		IF_inv_tau_cached_4_BITS_14_TO_7_0_EQ_0_1_AND__ETC___d232;
  wire [10 : 0] IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d450,
		IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d460,
		SEXT__0_CONCAT_IF_conf_71_BITS_34_TO_27_11_EQ__ETC___d447,
		SEXT__0_CONCAT_IF_load_and_step_v_t_BITS_14_TO_ETC___d438,
		SEXT__0_CONCAT_IF_load_and_step_x_t_BITS_14_TO_ETC___d457,
		x__h4179;
  wire [9 : 0] IF_NOT_x179_BIT_7_AND_NOT_x179_BITS_9_TO_0_EQ__ETC__q6,
	       _theResult_____1_fst__h4492,
	       _theResult___fst__h1594,
	       _theResult___fst__h1632,
	       _theResult___fst__h1669,
	       _theResult___fst__h1706,
	       _theResult___fst__h1743,
	       _theResult___fst__h1780,
	       _theResult___fst__h1817,
	       _theResult___fst__h1854,
	       _theResult___fst__h1891,
	       _theResult___fst__h1928,
	       _theResult___fst__h1965,
	       _theResult___fst__h2002,
	       _theResult___snd__h1557,
	       exp_temp__h1442,
	       ext_a__h4166,
	       ext_b__h4167,
	       ext_c__h4168,
	       final_exp_10__h1448,
	       final_exp_10__h1521,
	       final_exp_10__h1560,
	       raw_exp_10__h1443,
	       shifted_exp___10__h1704,
	       shifted_exp___11__h1667,
	       shifted_exp___12__h1630,
	       shifted_exp___13__h1592,
	       shifted_exp___1__h2037,
	       shifted_exp___2__h2000,
	       shifted_exp___3__h1963,
	       shifted_exp___4__h1926,
	       shifted_exp___5__h1889,
	       shifted_exp___6__h1852,
	       shifted_exp___7__h1815,
	       shifted_exp___8__h1778,
	       shifted_exp___9__h1741;
  wire [8 : 0] IF_NOT_tmp907_BIT_7_AND_NOT_tmp907_EQ_0_THEN_t_ETC__q5,
	       _theResult_____1_fst__h3154,
	       _theResult_____2_snd__h2990,
	       a_exp_eff__h1439,
	       b_exp_eff__h1440,
	       exp_sum__h1441,
	       man_result__h2961,
	       man_result__h3054,
	       man_result__h3056,
	       tmp__h2907;
  wire [7 : 0] _theResult_____1_snd__h3150,
	       _theResult_____1_snd__h3155,
	       _theResult_____1_snd__h3192,
	       _theResult_____1_snd__h3229,
	       _theResult_____1_snd__h3266,
	       _theResult_____1_snd__h3303,
	       _theResult_____1_snd__h3340,
	       _theResult_____1_snd__h3377,
	       _theResult_____1_snd__h4488,
	       _theResult_____1_snd__h4493,
	       _theResult_____1_snd__h4530,
	       _theResult_____1_snd__h4567,
	       _theResult_____1_snd__h4604,
	       _theResult_____1_snd__h4641,
	       _theResult_____1_snd__h4678,
	       _theResult_____1_snd__h4715,
	       _theResult_____2__h4159,
	       _theResult____h4158,
	       _theResult___fst_exp__h2986,
	       a_full_mant__h1436,
	       b_full_mant__h1437,
	       bigger_m__h2900,
	       exp_diff__h2977,
	       exp_diff__h2981,
	       exp_diff_a__h4160,
	       exp_diff_b__h4161,
	       exp_diff_c__h4162,
	       final_exp__h3114,
	       final_exp__h3119,
	       final_exp__h4420,
	       final_exp__h4452,
	       final_exp__h4457,
	       man_a__h4163,
	       man_b__h4164,
	       man_c__h4165,
	       smaller_m__h2901,
	       smaller_m__h2979,
	       smaller_m__h2983;
  wire [6 : 0] IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d262,
	       _theResult_____1_snd__h2050,
	       _theResult___fst__h1556,
	       final_mant__h1447;
  wire IF_IF_IF_stage2_data_BIT_37_THEN_stage2_data_B_ETC___d391,
       IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d376,
       IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d377,
       IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d382,
       IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d259,
       IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d260,
       NOT_IF_IF_stage2_data_BIT_37_THEN_stage2_data__ETC___d388,
       NOT_stage2_data_BIT_4_41_42_AND_IF_IF_IF_stage_ETC___d395,
       _0b1_CONCAT_IF_IF_stage2_data_BIT_37_THEN_stage_ETC___d271,
       _theResult_____2_fst__h2989,
       delta_v_sign__h1164,
       result_sign__h2911,
       result_sign__h2962,
       result_sign__h3057,
       val_sign__h4134;

  // action method configure
  assign RDY_configure = 1'd1 ;

  // action method load_and_step
  assign RDY_load_and_step = config_valid && !stage1_data[37] ;

  // value method ready_for_input
  assign ready_for_input = config_valid && !stage1_data[37] ;
  assign RDY_ready_for_input = 1'd1 ;

  // value method output_valid
  assign output_valid = output_reg[21] ;
  assign RDY_output_valid = 1'd1 ;

  // actionvalue method get_output
  assign get_output = output_reg[20:0] ;
  assign RDY_get_output = output_reg[21] ;

  // rule RL_pipeline_stage2
  assign WILL_FIRE_RL_pipeline_stage2 =
	     config_valid && stage1_data[37] && !stage2_data[37] ;

  // rule RL_pipeline_stage3
  assign WILL_FIRE_RL_pipeline_stage3 =
	     config_valid && stage2_data[37] && !output_reg[21] ;

  // inputs to muxes for submodule ports
  assign MUX_output_reg$write_1__VAL_2 =
	     { 1'd1,
	       NOT_stage2_data_BIT_4_41_42_AND_IF_IF_IF_stage_ETC___d395,
	       stage2_data[4] ?
		 { conf[35:20], stage2_data[3:0] } :
		 IF_IF_IF_IF_stage2_data_BIT_37_THEN_stage2_dat_ETC___d402 } ;
  assign MUX_stage1_data$write_1__VAL_2 =
	     { 1'd1,
	       load_and_step_v_t,
	       IF_load_and_step_refr_EQ_0_05_THEN_IF_load_and_ETC___d571 } ;
  assign MUX_stage2_data$write_1__VAL_2 =
	     { 1'd1,
	       stage1_data[36:21],
	       stage1_data[4] ?
		 { 17'd1, stage1_data[3:0] } :
		 { delta_v_sign__h1164,
		   IF_inv_tau_cached_4_BITS_14_TO_7_0_EQ_0_1_AND__ETC___d232,
		   1'd0,
		   stage1_data[3:0] } } ;

  // register conf
  assign conf$D_IN = 52'h0 ;
  assign conf$EN = 1'b0 ;

  // register config_valid
  assign config_valid$D_IN = 1'b0 ;
  assign config_valid$EN = 1'b0 ;

  // register inv_tau_cached
  assign inv_tau_cached$D_IN = 16'h0 ;
  assign inv_tau_cached$EN = 1'b0 ;

  // register output_reg
  assign output_reg$D_IN =
	     EN_get_output ? 22'd699050 : MUX_output_reg$write_1__VAL_2 ;
  assign output_reg$EN = EN_get_output || WILL_FIRE_RL_pipeline_stage3 ;

  // register stage1_data
  assign stage1_data$D_IN =
	     WILL_FIRE_RL_pipeline_stage2 ?
	       38'h0AAAAAAAAA :
	       MUX_stage1_data$write_1__VAL_2 ;
  assign stage1_data$EN = WILL_FIRE_RL_pipeline_stage2 || EN_load_and_step ;

  // register stage2_data
  assign stage2_data$D_IN =
	     WILL_FIRE_RL_pipeline_stage3 ?
	       38'h0AAAAAAAAA :
	       MUX_stage2_data$write_1__VAL_2 ;
  assign stage2_data$EN =
	     WILL_FIRE_RL_pipeline_stage3 || WILL_FIRE_RL_pipeline_stage2 ;

  // remaining internal signals
  assign IF_IF_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_ETC___d231 =
	     (final_exp_10__h1448[9] || final_exp_10__h1448 == 10'd0) ?
	       { 8'b0, _theResult_____1_snd__h2050 } :
	       ((final_exp_10__h1448 < 10'd255) ?
		  { final_exp_10__h1448[7:0], final_mant__h1447 } :
		  15'd32640) ;
  assign IF_IF_IF_IF_stage2_data_BIT_37_THEN_stage2_dat_ETC___d402 =
	     (IF_IF_IF_stage2_data_BIT_37_THEN_stage2_data_B_ETC___d391 ||
	      a__h2557 == conf[51:36]) ?
	       { conf[35:20], conf[3:0] } :
	       { a__h2557, 4'd0 } ;
  assign IF_IF_IF_load_and_step_v_t_BIT_15_25_THEN_SEXT_ETC___d560 =
	     x__h4179[8] ?
	       { final_exp__h4452, x__h4179[7:1] } :
	       { final_exp__h4457,
		 IF_NOT_x179_BIT_7_AND_NOT_x179_BITS_9_TO_0_EQ__ETC__q6[6:0] } ;
  assign IF_IF_IF_stage2_data_BIT_37_THEN_stage2_data_B_ETC___d366 =
	     tmp__h2907[8] ?
	       { final_exp__h3114, tmp__h2907[7:1] } :
	       { final_exp__h3119,
		 IF_NOT_tmp907_BIT_7_AND_NOT_tmp907_EQ_0_THEN_t_ETC__q5[6:0] } ;
  assign IF_IF_IF_stage2_data_BIT_37_THEN_stage2_data_B_ETC___d391 =
	     (a__h2557[15] == conf[51]) ?
	       (a__h2557[15] ?
		  IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d382 :
		  NOT_IF_IF_stage2_data_BIT_37_THEN_stage2_data__ETC___d388) :
	       !a__h2557[15] ;
  assign IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d262 =
	     IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d260 ?
	       stage2_data_BITS_20_TO_5__q3[6:0] :
	       stage2_data_BITS_36_TO_21__q2[6:0] ;
  assign IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d376 =
	     a__h2557[14:7] <= conf[50:43] ;
  assign IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d377 =
	     a__h2557[14:7] < conf[50:43] ;
  assign IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d382 =
	     IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d376 &&
	     (IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d377 ||
	      a__h2557[6:0] < conf[42:36]) ;
  assign IF_NOT_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_T_ETC__q4 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[13] &&
	      _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[15:0] !=
	      16'd0) ?
	       _theResult___snd__h1595 :
	       _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[15:0] ;
  assign IF_NOT_tmp907_BIT_7_AND_NOT_tmp907_EQ_0_THEN_t_ETC__q5 =
	     (!tmp__h2907[7] && tmp__h2907 != 9'd0) ?
	       _theResult_____1_fst__h3154 :
	       tmp__h2907 ;
  assign IF_NOT_x179_BIT_7_AND_NOT_x179_BITS_9_TO_0_EQ__ETC__q6 =
	     (!x__h4179[7] && x__h4179[9:0] != 10'd0) ?
	       _theResult_____1_fst__h4492 :
	       x__h4179[9:0] ;
  assign IF_conf_71_BITS_34_TO_27_11_EQ_0_12_AND_conf_7_ETC___d564 =
	     (conf[34:27] == 8'd0 && conf[26:20] == 7'd0 &&
	      load_and_step_x_t[14:7] == 8'd0 &&
	      load_and_step_x_t[6:0] == 7'd0) ?
	       result_raw__h4132 :
	       ((x__h4179[9:0] == 10'd0) ? 16'b0 : result_raw__h4385) ;
  assign IF_inv_tau_cached_4_BITS_14_TO_7_0_EQ_0_1_AND__ETC___d232 =
	     (inv_tau_cached[14:7] == 8'd0 && inv_tau_cached[6:0] == 7'd0 ||
	      stage1_data_BITS_20_TO_5__q1[14:7] == 8'd0 &&
	      stage1_data_BITS_20_TO_5__q1[6:0] == 7'd0) ?
	       15'b0 :
	       IF_IF_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_ETC___d231 ;
  assign IF_load_and_step_refr_EQ_0_05_THEN_IF_load_and_ETC___d571 =
	     (load_and_step_refr == 4'd0) ?
	       { (load_and_step_v_t[14:7] == 8'd0 &&
		  load_and_step_v_t[6:0] == 7'd0 &&
		  conf[34:27] == 8'd0 &&
		  conf[26:20] == 7'd0 &&
		  load_and_step_x_t[14:7] == 8'd0 &&
		  load_and_step_x_t[6:0] == 7'd0) ?
		   16'b0 :
		   IF_load_and_step_v_t_BITS_14_TO_7_06_EQ_0_07_A_ETC___d566,
		 5'd0 } :
	       { 17'd1, load_and_step_refr - 4'd1 } ;
  assign IF_load_and_step_v_t_BITS_14_TO_7_06_EQ_0_07_A_ETC___d565 =
	     (load_and_step_v_t[14:7] == 8'd0 &&
	      load_and_step_v_t[6:0] == 7'd0 &&
	      load_and_step_x_t[14:7] == 8'd0 &&
	      load_and_step_x_t[6:0] == 7'd0) ?
	       conf[35:20] :
	       IF_conf_71_BITS_34_TO_27_11_EQ_0_12_AND_conf_7_ETC___d564 ;
  assign IF_load_and_step_v_t_BITS_14_TO_7_06_EQ_0_07_A_ETC___d566 =
	     (load_and_step_v_t[14:7] == 8'd0 &&
	      load_and_step_v_t[6:0] == 7'd0 &&
	      conf[34:27] == 8'd0 &&
	      conf[26:20] == 7'd0) ?
	       load_and_step_x_t :
	       IF_load_and_step_v_t_BITS_14_TO_7_06_EQ_0_07_A_ETC___d565 ;
  assign IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d450 =
	     (load_and_step_v_t[15] ?
		SEXT__0_CONCAT_IF_load_and_step_v_t_BITS_14_TO_ETC___d438 :
		-SEXT__0_CONCAT_IF_load_and_step_v_t_BITS_14_TO_ETC___d438) +
	     (conf[35] ?
		-SEXT__0_CONCAT_IF_conf_71_BITS_34_TO_27_11_EQ__ETC___d447 :
		SEXT__0_CONCAT_IF_conf_71_BITS_34_TO_27_11_EQ__ETC___d447) ;
  assign IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d460 =
	     IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d450 +
	     (load_and_step_x_t[15] ?
		-SEXT__0_CONCAT_IF_load_and_step_x_t_BITS_14_TO_ETC___d457 :
		SEXT__0_CONCAT_IF_load_and_step_x_t_BITS_14_TO_ETC___d457) ;
  assign IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d259 =
	     stage2_data_BITS_36_TO_21__q2[15] ==
	     stage2_data_BITS_20_TO_5__q3[15] ;
  assign IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d260 =
	     stage2_data_BITS_36_TO_21__q2[14:7] <
	     stage2_data_BITS_20_TO_5__q3[14:7] ;
  assign NOT_IF_IF_stage2_data_BIT_37_THEN_stage2_data__ETC___d388 =
	     !IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d376 ||
	     !IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d377 &&
	     a__h2557[6:0] > conf[42:36] ;
  assign NOT_stage2_data_BIT_4_41_42_AND_IF_IF_IF_stage_ETC___d395 =
	     !stage2_data[4] &&
	     (IF_IF_IF_stage2_data_BIT_37_THEN_stage2_data_B_ETC___d391 ||
	      a__h2557 == conf[51:36]) ;
  assign SEXT__0_CONCAT_IF_conf_71_BITS_34_TO_27_11_EQ__ETC___d447 =
	     { ext_b__h4167[9], ext_b__h4167 } ;
  assign SEXT__0_CONCAT_IF_load_and_step_v_t_BITS_14_TO_ETC___d438 =
	     { ext_a__h4166[9], ext_a__h4166 } ;
  assign SEXT__0_CONCAT_IF_load_and_step_x_t_BITS_14_TO_ETC___d457 =
	     { ext_c__h4168[9], ext_c__h4168 } ;
  assign _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37 =
	     { 8'd0, a_full_mant__h1436 } * { 8'd0, b_full_mant__h1437 } ;
  assign _0b1_CONCAT_IF_IF_stage2_data_BIT_37_THEN_stage_ETC___d271 =
	     bigger_m__h2900 < smaller_m__h2901 ;
  assign _theResult_____1_fst__h3154 =
	     { (!tmp__h2907[6] && tmp__h2907[7:0] != 8'd0) ?
		 ((!tmp__h2907[5] && { tmp__h2907[6:0], 1'd0 } != 8'd0) ?
		    ((!tmp__h2907[4] && { tmp__h2907[5:0], 2'd0 } != 8'd0) ?
		       ((!tmp__h2907[3] &&
			 { tmp__h2907[4:0], 3'd0 } != 8'd0) ?
			  ((!tmp__h2907[2] &&
			    { tmp__h2907[3:0], 4'd0 } != 8'd0) ?
			     ((!tmp__h2907[1] &&
			       { tmp__h2907[2:0], 5'd0 } != 8'd0) ?
				((!tmp__h2907[0] &&
				  { tmp__h2907[1:0], 6'd0 } != 8'd0) ?
				   8'd0 :
				   { tmp__h2907[1:0], 6'd0 }) :
				{ tmp__h2907[2:0], 5'd0 }) :
			     { tmp__h2907[3:0], 4'd0 }) :
			  { tmp__h2907[4:0], 3'd0 }) :
		       { tmp__h2907[5:0], 2'd0 }) :
		    { tmp__h2907[6:0], 1'd0 }) :
		 tmp__h2907[7:0],
	       1'd0 } ;
  assign _theResult_____1_fst__h4492 =
	     { (!x__h4179[6] && x__h4179[8:0] != 9'd0) ?
		 { (!x__h4179[5] && { x__h4179[7:0], 1'd0 } != 9'd0) ?
		     { (!x__h4179[4] && { x__h4179[6:0], 2'd0 } != 9'd0) ?
			 { (!x__h4179[3] && { x__h4179[5:0], 3'd0 } != 9'd0) ?
			     { (!x__h4179[2] &&
				{ x__h4179[4:0], 4'd0 } != 9'd0) ?
				 { (!x__h4179[1] &&
				    { x__h4179[3:0], 5'd0 } != 9'd0) ?
				     { (!x__h4179[0] &&
					{ x__h4179[2:0], 6'd0 } != 9'd0) ?
					 { x__h4179[1:0], 1'd0 } :
					 x__h4179[2:0],
				       1'd0 } :
				     x__h4179[3:0],
				   1'd0 } :
				 x__h4179[4:0],
			       1'd0 } :
			     x__h4179[5:0],
			   1'd0 } :
			 x__h4179[6:0],
		       1'd0 } :
		     x__h4179[7:0],
		   1'd0 } :
		 x__h4179[8:0],
	       1'd0 } ;
  assign _theResult_____1_snd__h2050 =
	     (final_exp_10__h1448 == 10'd0) ? final_mant__h1447 : 7'b0 ;
  assign _theResult_____1_snd__h3150 =
	     (!tmp__h2907[7] && tmp__h2907 != 9'd0) ?
	       _theResult_____1_snd__h3155 :
	       8'd0 ;
  assign _theResult_____1_snd__h3155 =
	     (!tmp__h2907[6] && tmp__h2907[7:0] != 8'd0) ?
	       _theResult_____1_snd__h3192 :
	       8'd1 ;
  assign _theResult_____1_snd__h3192 =
	     (!tmp__h2907[5] && { tmp__h2907[6:0], 1'd0 } != 8'd0) ?
	       _theResult_____1_snd__h3229 :
	       8'd2 ;
  assign _theResult_____1_snd__h3229 =
	     (!tmp__h2907[4] && { tmp__h2907[5:0], 2'd0 } != 8'd0) ?
	       _theResult_____1_snd__h3266 :
	       8'd3 ;
  assign _theResult_____1_snd__h3266 =
	     (!tmp__h2907[3] && { tmp__h2907[4:0], 3'd0 } != 8'd0) ?
	       _theResult_____1_snd__h3303 :
	       8'd4 ;
  assign _theResult_____1_snd__h3303 =
	     (!tmp__h2907[2] && { tmp__h2907[3:0], 4'd0 } != 8'd0) ?
	       _theResult_____1_snd__h3340 :
	       8'd5 ;
  assign _theResult_____1_snd__h3340 =
	     (!tmp__h2907[1] && { tmp__h2907[2:0], 5'd0 } != 8'd0) ?
	       _theResult_____1_snd__h3377 :
	       8'd6 ;
  assign _theResult_____1_snd__h3377 =
	     (!tmp__h2907[0] && { tmp__h2907[1:0], 6'd0 } != 8'd0) ?
	       8'd8 :
	       8'd7 ;
  assign _theResult_____1_snd__h4488 =
	     (!x__h4179[7] && x__h4179[9:0] != 10'd0) ?
	       _theResult_____1_snd__h4493 :
	       8'd0 ;
  assign _theResult_____1_snd__h4493 =
	     (!x__h4179[6] && x__h4179[8:0] != 9'd0) ?
	       _theResult_____1_snd__h4530 :
	       8'd1 ;
  assign _theResult_____1_snd__h4530 =
	     (!x__h4179[5] && { x__h4179[7:0], 1'd0 } != 9'd0) ?
	       _theResult_____1_snd__h4567 :
	       8'd2 ;
  assign _theResult_____1_snd__h4567 =
	     (!x__h4179[4] && { x__h4179[6:0], 2'd0 } != 9'd0) ?
	       _theResult_____1_snd__h4604 :
	       8'd3 ;
  assign _theResult_____1_snd__h4604 =
	     (!x__h4179[3] && { x__h4179[5:0], 3'd0 } != 9'd0) ?
	       _theResult_____1_snd__h4641 :
	       8'd4 ;
  assign _theResult_____1_snd__h4641 =
	     (!x__h4179[2] && { x__h4179[4:0], 4'd0 } != 9'd0) ?
	       _theResult_____1_snd__h4678 :
	       8'd5 ;
  assign _theResult_____1_snd__h4678 =
	     (!x__h4179[1] && { x__h4179[3:0], 5'd0 } != 9'd0) ?
	       _theResult_____1_snd__h4715 :
	       8'd6 ;
  assign _theResult_____1_snd__h4715 =
	     (!x__h4179[0] && { x__h4179[2:0], 6'd0 } != 9'd0) ? 8'd8 : 8'd7 ;
  assign _theResult_____2__h4159 =
	     (load_and_step_x_t[14:7] <= _theResult____h4158) ?
	       _theResult____h4158 :
	       load_and_step_x_t[14:7] ;
  assign _theResult_____2_fst__h2989 =
	     _0b1_CONCAT_IF_IF_stage2_data_BIT_37_THEN_stage_ETC___d271 ?
	       result_sign__h3057 :
	       result_sign__h2962 ;
  assign _theResult_____2_snd__h2990 =
	     _0b1_CONCAT_IF_IF_stage2_data_BIT_37_THEN_stage_ETC___d271 ?
	       man_result__h3056 :
	       man_result__h3054 ;
  assign _theResult____h4158 =
	     (conf[34:27] <= load_and_step_v_t[14:7]) ?
	       load_and_step_v_t[14:7] :
	       conf[34:27] ;
  assign _theResult___fst__h1556 =
	     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[14] ?
	       _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[13:7] :
	       IF_NOT_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_T_ETC__q4[13:7] ;
  assign _theResult___fst__h1594 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[12] &&
	      _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[14:0] !=
	      15'd0) ?
	       _theResult___fst__h1632 :
	       shifted_exp___13__h1592 ;
  assign _theResult___fst__h1632 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[11] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[13:0],
		1'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1669 :
	       shifted_exp___12__h1630 ;
  assign _theResult___fst__h1669 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[10] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[12:0],
		2'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1706 :
	       shifted_exp___11__h1667 ;
  assign _theResult___fst__h1706 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[9] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[11:0],
		3'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1743 :
	       shifted_exp___10__h1704 ;
  assign _theResult___fst__h1743 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[8] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[10:0],
		4'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1780 :
	       shifted_exp___9__h1741 ;
  assign _theResult___fst__h1780 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[7] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[9:0],
		5'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1817 :
	       shifted_exp___8__h1778 ;
  assign _theResult___fst__h1817 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[6] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[8:0],
		6'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1854 :
	       shifted_exp___7__h1815 ;
  assign _theResult___fst__h1854 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[5] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[7:0],
		7'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1891 :
	       shifted_exp___6__h1852 ;
  assign _theResult___fst__h1891 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[4] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[6:0],
		8'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1928 :
	       shifted_exp___5__h1889 ;
  assign _theResult___fst__h1928 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[3] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[5:0],
		9'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1965 :
	       shifted_exp___4__h1926 ;
  assign _theResult___fst__h1965 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[2] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[4:0],
		10'd0 } !=
	      15'd0) ?
	       _theResult___fst__h2002 :
	       shifted_exp___3__h1963 ;
  assign _theResult___fst__h2002 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[1] &&
	      { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[3:0],
		11'd0 } !=
	      15'd0) ?
	       shifted_exp___1__h2037 :
	       shifted_exp___2__h2000 ;
  assign _theResult___fst_exp__h2986 =
	     IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d260 ?
	       stage2_data_BITS_20_TO_5__q3[14:7] :
	       stage2_data_BITS_36_TO_21__q2[14:7] ;
  assign _theResult___snd__h1557 =
	     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[14] ?
	       raw_exp_10__h1443 :
	       final_exp_10__h1560 ;
  assign _theResult___snd__h1595 =
	     { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[12] &&
		_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[14:0] !=
		15'd0) ?
		 { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[11] &&
		    { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[13:0],
		      1'd0 } !=
		    15'd0) ?
		     { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[10] &&
			{ _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[12:0],
			  2'd0 } !=
			15'd0) ?
			 { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[9] &&
			    { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[11:0],
			      3'd0 } !=
			    15'd0) ?
			     { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[8] &&
				{ _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[10:0],
				  4'd0 } !=
				15'd0) ?
				 { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[7] &&
				    { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[9:0],
				      5'd0 } !=
				    15'd0) ?
				     { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[6] &&
					{ _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[8:0],
					  6'd0 } !=
					15'd0) ?
					 { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[5] &&
					    { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[7:0],
					      7'd0 } !=
					    15'd0) ?
					     { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[4] &&
						{ _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[6:0],
						  8'd0 } !=
						15'd0) ?
						 { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[3] &&
						    { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[5:0],
						      9'd0 } !=
						    15'd0) ?
						     { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[2] &&
							{ _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[4:0],
							  10'd0 } !=
							15'd0) ?
							 { (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[1] &&
							    { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[3:0],
							      11'd0 } !=
							    15'd0) ?
							     { _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[2:0],
							       1'd0 } :
							     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[3:0],
							   1'd0 } :
							 _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[4:0],
						       1'd0 } :
						     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[5:0],
						   1'd0 } :
						 _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[6:0],
					       1'd0 } :
					     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[7:0],
					   1'd0 } :
					 _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[8:0],
				       1'd0 } :
				     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[9:0],
				   1'd0 } :
				 _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[10:0],
			       1'd0 } :
			     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[11:0],
			   1'd0 } :
			 _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[12:0],
		       1'd0 } :
		     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[13:0],
		   1'd0 } :
		 _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[14:0],
	       1'd0 } ;
  assign a__h2557 =
	     (stage2_data_BITS_36_TO_21__q2[14:7] == 8'd0 &&
	      stage2_data_BITS_36_TO_21__q2[6:0] == 7'd0) ?
	       stage2_data[20:5] :
	       ((stage2_data_BITS_20_TO_5__q3[14:7] == 8'd0 &&
		 stage2_data_BITS_20_TO_5__q3[6:0] == 7'd0) ?
		  stage2_data[36:21] :
		  result_raw__h2910) ;
  assign a_exp_eff__h1439 =
	     (inv_tau_cached[14:7] == 8'd0) ?
	       9'd1 :
	       { 1'd0, inv_tau_cached[14:7] } ;
  assign a_full_mant__h1436 =
	     { inv_tau_cached[14:7] != 8'd0, inv_tau_cached[6:0] } ;
  assign b_exp_eff__h1440 =
	     (stage1_data_BITS_20_TO_5__q1[14:7] == 8'd0) ?
	       9'd1 :
	       { 1'd0, stage1_data_BITS_20_TO_5__q1[14:7] } ;
  assign b_full_mant__h1437 =
	     { stage1_data_BITS_20_TO_5__q1[14:7] != 8'd0,
	       stage1_data_BITS_20_TO_5__q1[6:0] } ;
  assign bigger_m__h2900 =
	     { 1'b1,
	       IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d262 } ;
  assign delta_v_sign__h1164 =
	     inv_tau_cached[15] ^ stage1_data_BITS_20_TO_5__q1[15] ;
  assign exp_diff__h2977 =
	     stage2_data_BITS_36_TO_21__q2[14:7] -
	     stage2_data_BITS_20_TO_5__q3[14:7] ;
  assign exp_diff__h2981 =
	     stage2_data_BITS_20_TO_5__q3[14:7] -
	     stage2_data_BITS_36_TO_21__q2[14:7] ;
  assign exp_diff_a__h4160 =
	     _theResult_____2__h4159 - load_and_step_v_t[14:7] ;
  assign exp_diff_b__h4161 = _theResult_____2__h4159 - conf[34:27] ;
  assign exp_diff_c__h4162 =
	     _theResult_____2__h4159 - load_and_step_x_t[14:7] ;
  assign exp_sum__h1441 = a_exp_eff__h1439 + b_exp_eff__h1440 ;
  assign exp_temp__h1442 = { 1'd0, exp_sum__h1441 } ;
  assign ext_a__h4166 = { 2'd0, man_a__h4163 } ;
  assign ext_b__h4167 = { 2'd0, man_b__h4164 } ;
  assign ext_c__h4168 = { 2'd0, man_c__h4165 } ;
  assign final_exp_10__h1448 =
	     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[15] ?
	       final_exp_10__h1521 :
	       _theResult___snd__h1557 ;
  assign final_exp_10__h1521 = raw_exp_10__h1443 + 10'd1 ;
  assign final_exp_10__h1560 =
	     (!_0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[13] &&
	      _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[15:0] !=
	      16'd0) ?
	       _theResult___fst__h1594 :
	       raw_exp_10__h1443 ;
  assign final_exp__h3114 = _theResult___fst_exp__h2986 + 8'd1 ;
  assign final_exp__h3119 =
	     _theResult___fst_exp__h2986 - _theResult_____1_snd__h3150 ;
  assign final_exp__h4420 = _theResult_____2__h4159 + 8'd2 ;
  assign final_exp__h4452 = _theResult_____2__h4159 + 8'd1 ;
  assign final_exp__h4457 =
	     _theResult_____2__h4159 - _theResult_____1_snd__h4488 ;
  assign final_mant__h1447 =
	     _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[15] ?
	       _0_CONCAT_NOT_inv_tau_cached_4_BITS_14_TO_7_0_E_ETC___d37[14:8] :
	       _theResult___fst__h1556 ;
  assign man_a__h4163 =
	     (load_and_step_v_t[14:7] == 8'd0 &&
	      load_and_step_v_t[6:0] == 7'd0) ?
	       8'd0 :
	       { 1'b1, load_and_step_v_t[6:0] } >> exp_diff_a__h4160 ;
  assign man_b__h4164 =
	     (conf[34:27] == 8'd0 && conf[26:20] == 7'd0) ?
	       8'd0 :
	       { 1'b1, conf[26:20] } >> exp_diff_b__h4161 ;
  assign man_c__h4165 =
	     (load_and_step_x_t[14:7] == 8'd0 &&
	      load_and_step_x_t[6:0] == 7'd0) ?
	       8'd0 :
	       { 1'b1, load_and_step_x_t[6:0] } >> exp_diff_c__h4162 ;
  assign man_result__h2961 =
	     { 2'd1,
	       IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d262 } +
	     { 1'd0, smaller_m__h2901 } ;
  assign man_result__h3054 =
	     { 2'd1,
	       IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d262 } -
	     { 1'd0, smaller_m__h2901 } ;
  assign man_result__h3056 =
	     { 1'd0, smaller_m__h2901 } -
	     { 2'd1,
	       IF_IF_stage2_data_BIT_37_THEN_stage2_data_BITS_ETC___d262 } ;
  assign raw_exp_10__h1443 = exp_temp__h1442 - 10'd127 ;
  assign result_raw__h2910 =
	     { result_sign__h2911,
	       IF_IF_IF_stage2_data_BIT_37_THEN_stage2_data_B_ETC___d366 } ;
  assign result_raw__h4132 = { val_sign__h4134, load_and_step_v_t[14:0] } ;
  assign result_raw__h4385 =
	     { IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d460[10],
	       x__h4179[9] ?
		 { final_exp__h4420, x__h4179[8:2] } :
		 IF_IF_IF_load_and_step_v_t_BIT_15_25_THEN_SEXT_ETC___d560 } ;
  assign result_sign__h2911 =
	     IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d259 ?
	       result_sign__h2962 :
	       _theResult_____2_fst__h2989 ;
  assign result_sign__h2962 =
	     IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d260 ?
	       stage2_data_BITS_20_TO_5__q3[15] :
	       stage2_data_BITS_36_TO_21__q2[15] ;
  assign result_sign__h3057 =
	     IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d260 ?
	       stage2_data_BITS_36_TO_21__q2[15] :
	       stage2_data_BITS_20_TO_5__q3[15] ;
  assign shifted_exp___10__h1704 = shifted_exp___11__h1667 - 10'd1 ;
  assign shifted_exp___11__h1667 = shifted_exp___12__h1630 - 10'd1 ;
  assign shifted_exp___12__h1630 = shifted_exp___13__h1592 - 10'd1 ;
  assign shifted_exp___13__h1592 = raw_exp_10__h1443 - 10'd1 ;
  assign shifted_exp___1__h2037 = shifted_exp___2__h2000 - 10'd1 ;
  assign shifted_exp___2__h2000 = shifted_exp___3__h1963 - 10'd1 ;
  assign shifted_exp___3__h1963 = shifted_exp___4__h1926 - 10'd1 ;
  assign shifted_exp___4__h1926 = shifted_exp___5__h1889 - 10'd1 ;
  assign shifted_exp___5__h1889 = shifted_exp___6__h1852 - 10'd1 ;
  assign shifted_exp___6__h1852 = shifted_exp___7__h1815 - 10'd1 ;
  assign shifted_exp___7__h1815 = shifted_exp___8__h1778 - 10'd1 ;
  assign shifted_exp___8__h1778 = shifted_exp___9__h1741 - 10'd1 ;
  assign shifted_exp___9__h1741 = shifted_exp___10__h1704 - 10'd1 ;
  assign smaller_m__h2901 =
	     IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d260 ?
	       smaller_m__h2983 :
	       smaller_m__h2979 ;
  assign smaller_m__h2979 =
	     { 1'b1, stage2_data_BITS_20_TO_5__q3[6:0] } >> exp_diff__h2977 ;
  assign smaller_m__h2983 =
	     { 1'b1, stage2_data_BITS_36_TO_21__q2[6:0] } >> exp_diff__h2981 ;
  assign stage1_data_BITS_20_TO_5__q1 = stage1_data[20:5] ;
  assign stage2_data_BITS_20_TO_5__q3 = stage2_data[20:5] ;
  assign stage2_data_BITS_36_TO_21__q2 = stage2_data[36:21] ;
  assign tmp__h2907 =
	     IF_stage2_data_BIT_37_THEN_stage2_data_BITS_36_ETC___d259 ?
	       man_result__h2961 :
	       _theResult_____2_snd__h2990 ;
  assign val_sign__h4134 = ~load_and_step_v_t[15] ;
  assign x__h4179 =
	     IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d460[10] ?
	       -IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d460 :
	       IF_load_and_step_v_t_BIT_15_25_THEN_SEXT__0_CO_ETC___d460 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        conf <= `BSV_ASSIGNMENT_DELAY 52'h3F8000003DCC2;
	config_valid <= `BSV_ASSIGNMENT_DELAY 1'd1;
	inv_tau_cached <= `BSV_ASSIGNMENT_DELAY 16'd15820;
	output_reg <= `BSV_ASSIGNMENT_DELAY 22'd699050;
	stage1_data <= `BSV_ASSIGNMENT_DELAY 38'h0AAAAAAAAA;
	stage2_data <= `BSV_ASSIGNMENT_DELAY 38'h0AAAAAAAAA;
      end
    else
      begin
        if (conf$EN) conf <= `BSV_ASSIGNMENT_DELAY conf$D_IN;
	if (config_valid$EN)
	  config_valid <= `BSV_ASSIGNMENT_DELAY config_valid$D_IN;
	if (inv_tau_cached$EN)
	  inv_tau_cached <= `BSV_ASSIGNMENT_DELAY inv_tau_cached$D_IN;
	if (output_reg$EN)
	  output_reg <= `BSV_ASSIGNMENT_DELAY output_reg$D_IN;
	if (stage1_data$EN)
	  stage1_data <= `BSV_ASSIGNMENT_DELAY stage1_data$D_IN;
	if (stage2_data$EN)
	  stage2_data <= `BSV_ASSIGNMENT_DELAY stage2_data$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    conf = 52'hAAAAAAAAAAAAA;
    config_valid = 1'h0;
    inv_tau_cached = 16'hAAAA;
    output_reg = 22'h2AAAAA;
    stage1_data = 38'h2AAAAAAAAA;
    stage2_data = 38'h2AAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkBF16_LIF_LoadStep

