//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e9)
//
// On Fri Nov 14 08:22:22 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_put_data                   O     1 const
// getResult                      O   128 reg
// RDY_getResult                  O     1
// hasResult                      O     1 reg
// RDY_hasResult                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_data_data                  I   128 reg
// EN_put_data                    I     1
// EN_getResult                   I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBF16SigmoidVector8(CLK,
			    RST_N,

			    put_data_data,
			    EN_put_data,
			    RDY_put_data,

			    EN_getResult,
			    getResult,
			    RDY_getResult,

			    hasResult,
			    RDY_hasResult);
  input  CLK;
  input  RST_N;

  // action method put_data
  input  [127 : 0] put_data_data;
  input  EN_put_data;
  output RDY_put_data;

  // actionvalue method getResult
  input  EN_getResult;
  output [127 : 0] getResult;
  output RDY_getResult;

  // value method hasResult
  output hasResult;
  output RDY_hasResult;

  // signals for module outputs
  wire [127 : 0] getResult;
  wire RDY_getResult, RDY_hasResult, RDY_put_data, hasResult;

  // register inputs_fed
  reg [31 : 0] inputs_fed;
  wire [31 : 0] inputs_fed$D_IN;
  wire inputs_fed$EN;

  // register outputs_collected
  reg [31 : 0] outputs_collected;
  wire [31 : 0] outputs_collected$D_IN;
  wire outputs_collected$EN;

  // ports of submodule sigmoid_units_0
  wire [15 : 0] sigmoid_units_0$getResult, sigmoid_units_0$put_data_data;
  wire sigmoid_units_0$EN_getResult,
       sigmoid_units_0$EN_put_data,
       sigmoid_units_0$RDY_getResult,
       sigmoid_units_0$hasResult;

  // ports of submodule sigmoid_units_1
  wire [15 : 0] sigmoid_units_1$getResult, sigmoid_units_1$put_data_data;
  wire sigmoid_units_1$EN_getResult,
       sigmoid_units_1$EN_put_data,
       sigmoid_units_1$RDY_getResult;

  // ports of submodule sigmoid_units_2
  wire [15 : 0] sigmoid_units_2$getResult, sigmoid_units_2$put_data_data;
  wire sigmoid_units_2$EN_getResult,
       sigmoid_units_2$EN_put_data,
       sigmoid_units_2$RDY_getResult;

  // ports of submodule sigmoid_units_3
  wire [15 : 0] sigmoid_units_3$getResult, sigmoid_units_3$put_data_data;
  wire sigmoid_units_3$EN_getResult,
       sigmoid_units_3$EN_put_data,
       sigmoid_units_3$RDY_getResult;

  // ports of submodule sigmoid_units_4
  wire [15 : 0] sigmoid_units_4$getResult, sigmoid_units_4$put_data_data;
  wire sigmoid_units_4$EN_getResult,
       sigmoid_units_4$EN_put_data,
       sigmoid_units_4$RDY_getResult;

  // ports of submodule sigmoid_units_5
  wire [15 : 0] sigmoid_units_5$getResult, sigmoid_units_5$put_data_data;
  wire sigmoid_units_5$EN_getResult,
       sigmoid_units_5$EN_put_data,
       sigmoid_units_5$RDY_getResult;

  // ports of submodule sigmoid_units_6
  wire [15 : 0] sigmoid_units_6$getResult, sigmoid_units_6$put_data_data;
  wire sigmoid_units_6$EN_getResult,
       sigmoid_units_6$EN_put_data,
       sigmoid_units_6$RDY_getResult;

  // ports of submodule sigmoid_units_7
  wire [15 : 0] sigmoid_units_7$getResult, sigmoid_units_7$put_data_data;
  wire sigmoid_units_7$EN_getResult,
       sigmoid_units_7$EN_put_data,
       sigmoid_units_7$RDY_getResult;

  // remaining internal signals
  wire sigmoid_units_2_RDY_getResult__7_AND_sigmoid_u_ETC___d39;

  // action method put_data
  assign RDY_put_data = 1'd1 ;

  // actionvalue method getResult
  assign getResult =
	     { sigmoid_units_7$getResult,
	       sigmoid_units_6$getResult,
	       sigmoid_units_5$getResult,
	       sigmoid_units_4$getResult,
	       sigmoid_units_3$getResult,
	       sigmoid_units_2$getResult,
	       sigmoid_units_1$getResult,
	       sigmoid_units_0$getResult } ;
  assign RDY_getResult =
	     sigmoid_units_0$RDY_getResult && sigmoid_units_1$RDY_getResult &&
	     sigmoid_units_2_RDY_getResult__7_AND_sigmoid_u_ETC___d39 ;

  // value method hasResult
  assign hasResult = sigmoid_units_0$hasResult ;
  assign RDY_hasResult = 1'd1 ;

  // submodule sigmoid_units_0
  mkBF16Sigmoid sigmoid_units_0(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_0$put_data_data),
				.EN_put_data(sigmoid_units_0$EN_put_data),
				.EN_getResult(sigmoid_units_0$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_0$getResult),
				.RDY_getResult(sigmoid_units_0$RDY_getResult),
				.hasResult(sigmoid_units_0$hasResult),
				.RDY_hasResult());

  // submodule sigmoid_units_1
  mkBF16Sigmoid sigmoid_units_1(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_1$put_data_data),
				.EN_put_data(sigmoid_units_1$EN_put_data),
				.EN_getResult(sigmoid_units_1$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_1$getResult),
				.RDY_getResult(sigmoid_units_1$RDY_getResult),
				.hasResult(),
				.RDY_hasResult());

  // submodule sigmoid_units_2
  mkBF16Sigmoid sigmoid_units_2(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_2$put_data_data),
				.EN_put_data(sigmoid_units_2$EN_put_data),
				.EN_getResult(sigmoid_units_2$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_2$getResult),
				.RDY_getResult(sigmoid_units_2$RDY_getResult),
				.hasResult(),
				.RDY_hasResult());

  // submodule sigmoid_units_3
  mkBF16Sigmoid sigmoid_units_3(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_3$put_data_data),
				.EN_put_data(sigmoid_units_3$EN_put_data),
				.EN_getResult(sigmoid_units_3$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_3$getResult),
				.RDY_getResult(sigmoid_units_3$RDY_getResult),
				.hasResult(),
				.RDY_hasResult());

  // submodule sigmoid_units_4
  mkBF16Sigmoid sigmoid_units_4(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_4$put_data_data),
				.EN_put_data(sigmoid_units_4$EN_put_data),
				.EN_getResult(sigmoid_units_4$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_4$getResult),
				.RDY_getResult(sigmoid_units_4$RDY_getResult),
				.hasResult(),
				.RDY_hasResult());

  // submodule sigmoid_units_5
  mkBF16Sigmoid sigmoid_units_5(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_5$put_data_data),
				.EN_put_data(sigmoid_units_5$EN_put_data),
				.EN_getResult(sigmoid_units_5$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_5$getResult),
				.RDY_getResult(sigmoid_units_5$RDY_getResult),
				.hasResult(),
				.RDY_hasResult());

  // submodule sigmoid_units_6
  mkBF16Sigmoid sigmoid_units_6(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_6$put_data_data),
				.EN_put_data(sigmoid_units_6$EN_put_data),
				.EN_getResult(sigmoid_units_6$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_6$getResult),
				.RDY_getResult(sigmoid_units_6$RDY_getResult),
				.hasResult(),
				.RDY_hasResult());

  // submodule sigmoid_units_7
  mkBF16Sigmoid sigmoid_units_7(.CLK(CLK),
				.RST_N(RST_N),
				.put_data_data(sigmoid_units_7$put_data_data),
				.EN_put_data(sigmoid_units_7$EN_put_data),
				.EN_getResult(sigmoid_units_7$EN_getResult),
				.RDY_put_data(),
				.getResult(sigmoid_units_7$getResult),
				.RDY_getResult(sigmoid_units_7$RDY_getResult),
				.hasResult(),
				.RDY_hasResult());

  // register inputs_fed
  assign inputs_fed$D_IN = inputs_fed + 32'd1 ;
  assign inputs_fed$EN = EN_put_data ;

  // register outputs_collected
  assign outputs_collected$D_IN = outputs_collected + 32'd1 ;
  assign outputs_collected$EN = EN_getResult ;

  // submodule sigmoid_units_0
  assign sigmoid_units_0$put_data_data = put_data_data[15:0] ;
  assign sigmoid_units_0$EN_put_data = EN_put_data ;
  assign sigmoid_units_0$EN_getResult = EN_getResult ;

  // submodule sigmoid_units_1
  assign sigmoid_units_1$put_data_data = put_data_data[31:16] ;
  assign sigmoid_units_1$EN_put_data = EN_put_data ;
  assign sigmoid_units_1$EN_getResult = EN_getResult ;

  // submodule sigmoid_units_2
  assign sigmoid_units_2$put_data_data = put_data_data[47:32] ;
  assign sigmoid_units_2$EN_put_data = EN_put_data ;
  assign sigmoid_units_2$EN_getResult = EN_getResult ;

  // submodule sigmoid_units_3
  assign sigmoid_units_3$put_data_data = put_data_data[63:48] ;
  assign sigmoid_units_3$EN_put_data = EN_put_data ;
  assign sigmoid_units_3$EN_getResult = EN_getResult ;

  // submodule sigmoid_units_4
  assign sigmoid_units_4$put_data_data = put_data_data[79:64] ;
  assign sigmoid_units_4$EN_put_data = EN_put_data ;
  assign sigmoid_units_4$EN_getResult = EN_getResult ;

  // submodule sigmoid_units_5
  assign sigmoid_units_5$put_data_data = put_data_data[95:80] ;
  assign sigmoid_units_5$EN_put_data = EN_put_data ;
  assign sigmoid_units_5$EN_getResult = EN_getResult ;

  // submodule sigmoid_units_6
  assign sigmoid_units_6$put_data_data = put_data_data[111:96] ;
  assign sigmoid_units_6$EN_put_data = EN_put_data ;
  assign sigmoid_units_6$EN_getResult = EN_getResult ;

  // submodule sigmoid_units_7
  assign sigmoid_units_7$put_data_data = put_data_data[127:112] ;
  assign sigmoid_units_7$EN_put_data = EN_put_data ;
  assign sigmoid_units_7$EN_getResult = EN_getResult ;

  // remaining internal signals
  assign sigmoid_units_2_RDY_getResult__7_AND_sigmoid_u_ETC___d39 =
	     sigmoid_units_2$RDY_getResult && sigmoid_units_3$RDY_getResult &&
	     sigmoid_units_4$RDY_getResult &&
	     sigmoid_units_5$RDY_getResult &&
	     sigmoid_units_6$RDY_getResult &&
	     sigmoid_units_7$RDY_getResult &&
	     sigmoid_units_0$hasResult ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        inputs_fed <= `BSV_ASSIGNMENT_DELAY 32'd0;
	outputs_collected <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (inputs_fed$EN)
	  inputs_fed <= `BSV_ASSIGNMENT_DELAY inputs_fed$D_IN;
	if (outputs_collected$EN)
	  outputs_collected <= `BSV_ASSIGNMENT_DELAY outputs_collected$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    inputs_fed = 32'hAAAAAAAA;
    outputs_collected = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_getResult)
	$display("        [SIGVEC8] outputs_collected: %0d",
		 $unsigned(outputs_collected));
  end
  // synopsys translate_on
endmodule  // mkBF16SigmoidVector8

