//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e9)
//
// On Fri Nov 14 08:21:54 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_put_data                   O     1 const
// getResult                      O    16 reg
// RDY_getResult                  O     1 reg
// hasResult                      O     1 reg
// RDY_hasResult                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_data_data                  I    16 reg
// EN_put_data                    I     1
// EN_getResult                   I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBF16Exp(CLK,
		 RST_N,

		 put_data_data,
		 EN_put_data,
		 RDY_put_data,

		 EN_getResult,
		 getResult,
		 RDY_getResult,

		 hasResult,
		 RDY_hasResult);
  input  CLK;
  input  RST_N;

  // action method put_data
  input  [15 : 0] put_data_data;
  input  EN_put_data;
  output RDY_put_data;

  // actionvalue method getResult
  input  EN_getResult;
  output [15 : 0] getResult;
  output RDY_getResult;

  // value method hasResult
  output hasResult;
  output RDY_hasResult;

  // signals for module outputs
  wire [15 : 0] getResult;
  wire RDY_getResult, RDY_hasResult, RDY_put_data, hasResult;

  // register result_data
  reg [15 : 0] result_data;
  wire [15 : 0] result_data$D_IN;
  wire result_data$EN;

  // register result_valid
  reg result_valid;
  wire result_valid$D_IN, result_valid$EN;

  // register s1_input_z
  reg [15 : 0] s1_input_z;
  wire [15 : 0] s1_input_z$D_IN;
  wire s1_input_z$EN;

  // register s1_zc1
  reg [15 : 0] s1_zc1;
  wire [15 : 0] s1_zc1$D_IN;
  wire s1_zc1$EN;

  // register s2_input_z
  reg [15 : 0] s2_input_z;
  wire [15 : 0] s2_input_z$D_IN;
  wire s2_input_z$EN;

  // register s2_n
  reg [15 : 0] s2_n;
  wire [15 : 0] s2_n$D_IN;
  wire s2_n$EN;

  // register s2_y
  reg [15 : 0] s2_y;
  wire [15 : 0] s2_y$D_IN;
  wire s2_y$EN;

  // register s3_n
  reg [15 : 0] s3_n;
  wire [15 : 0] s3_n$D_IN;
  wire s3_n$EN;

  // register s3_x
  reg [15 : 0] s3_x;
  wire [15 : 0] s3_x$D_IN;
  wire s3_x$EN;

  // register s3_y
  reg [15 : 0] s3_y;
  wire [15 : 0] s3_y$D_IN;
  wire s3_y$EN;

  // register stage1
  reg [16 : 0] stage1;
  wire [16 : 0] stage1$D_IN;
  wire stage1$EN;

  // register stage2
  reg [16 : 0] stage2;
  wire [16 : 0] stage2$D_IN;
  wire stage2$EN;

  // register stage3
  reg [16 : 0] stage3;
  wire [16 : 0] stage3$D_IN;
  wire stage3$EN;

  // register stage4
  reg [16 : 0] stage4;
  wire [16 : 0] stage4$D_IN;
  wire stage4$EN;

  // remaining internal signals
  reg [7 : 0] b_exp__h2202;
  reg [6 : 0] b_mant__h2203;
  wire [31 : 0] _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289,
		_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632,
		_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085,
		_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15;
  wire [15 : 0] IF_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_ETC___d246,
		IF_0b1_CONCAT_s1_zc1_15_BITS_6_TO_0_26_CONCAT__ETC___d241,
		IF_15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_ETC___d244,
		IF_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc_ETC___d259,
		IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d252,
		IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d256,
		IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d264,
		IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d606,
		IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d607,
		IF_NOT_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1__ETC__q2,
		IF_NOT_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0__ETC__q4,
		IF_NOT_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068__ETC__q6,
		IF_NOT_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_ETC__q1,
		IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d247,
		IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d260,
		IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943,
		_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_127___d219,
		_127_MINUS_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCA_ETC___d267,
		_15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_ETC___d223,
		_theResult___snd__h1157,
		_theResult___snd__h4494,
		_theResult___snd__h7125,
		_theResult___snd__h9553,
		abs_val617_SL_x799__q3,
		abs_val__h5617,
		integer_part__h1962,
		integer_part__h2009,
		mantissa_with_implicit__h1955,
		neg_b__h5476,
		result__h4350,
		result_raw__h7793,
		result_raw__h8449,
		x__h1999,
		x__h2087,
		x__h6799;
  wire [14 : 0] IF_IF_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_1_ETC___d483,
		IF_IF_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_E_ETC___d824,
		IF_IF_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_E_ETC___d1279,
		IF_IF_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2__ETC___d207,
		IF_IF_INV_IF_s2_input_z_93_BITS_14_TO_7_94_EQ__ETC___d1056,
		IF_IF_s2_input_z_93_BIT_15_32_EQ_INV_NOT_s2_n__ETC___d940,
		IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825,
		IF_NOT_IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_9_ETC___d622,
		IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623,
		IF_s3_y_063_BITS_14_TO_7_068_EQ_0_069_AND_s3_y_ETC___d1280;
  wire [9 : 0] _theResult___fst__h1156,
	       _theResult___fst__h1194,
	       _theResult___fst__h1231,
	       _theResult___fst__h1268,
	       _theResult___fst__h1305,
	       _theResult___fst__h1342,
	       _theResult___fst__h1379,
	       _theResult___fst__h1416,
	       _theResult___fst__h1453,
	       _theResult___fst__h1490,
	       _theResult___fst__h1527,
	       _theResult___fst__h1564,
	       _theResult___fst__h4493,
	       _theResult___fst__h4530,
	       _theResult___fst__h4567,
	       _theResult___fst__h4604,
	       _theResult___fst__h4641,
	       _theResult___fst__h4678,
	       _theResult___fst__h4715,
	       _theResult___fst__h4752,
	       _theResult___fst__h4789,
	       _theResult___fst__h4826,
	       _theResult___fst__h4863,
	       _theResult___fst__h4900,
	       _theResult___fst__h7124,
	       _theResult___fst__h7161,
	       _theResult___fst__h7198,
	       _theResult___fst__h7235,
	       _theResult___fst__h7272,
	       _theResult___fst__h7309,
	       _theResult___fst__h7346,
	       _theResult___fst__h7383,
	       _theResult___fst__h7420,
	       _theResult___fst__h7457,
	       _theResult___fst__h7494,
	       _theResult___fst__h7531,
	       _theResult___fst__h9552,
	       _theResult___fst__h9589,
	       _theResult___fst__h9626,
	       _theResult___fst__h9663,
	       _theResult___fst__h9700,
	       _theResult___fst__h9737,
	       _theResult___fst__h9774,
	       _theResult___fst__h9811,
	       _theResult___fst__h9848,
	       _theResult___fst__h9885,
	       _theResult___fst__h9922,
	       _theResult___fst__h9959,
	       _theResult___snd__h1119,
	       _theResult___snd__h4456,
	       _theResult___snd__h7087,
	       _theResult___snd__h9515,
	       exp_temp__h4341,
	       exp_temp__h6960,
	       exp_temp__h9400,
	       exp_temp__h992,
	       final_exp_10__h1084,
	       final_exp_10__h1122,
	       final_exp_10__h4347,
	       final_exp_10__h4420,
	       final_exp_10__h4459,
	       final_exp_10__h6966,
	       final_exp_10__h7052,
	       final_exp_10__h7090,
	       final_exp_10__h9406,
	       final_exp_10__h9479,
	       final_exp_10__h9518,
	       final_exp_10__h998,
	       raw_exp_10__h4342,
	       raw_exp_10__h6961,
	       raw_exp_10__h9401,
	       raw_exp_10__h993,
	       shifted_exp___10__h1266,
	       shifted_exp___10__h4602,
	       shifted_exp___10__h7233,
	       shifted_exp___10__h9661,
	       shifted_exp___11__h1229,
	       shifted_exp___11__h4565,
	       shifted_exp___11__h7196,
	       shifted_exp___11__h9624,
	       shifted_exp___12__h1192,
	       shifted_exp___12__h4528,
	       shifted_exp___12__h7159,
	       shifted_exp___12__h9587,
	       shifted_exp___13__h1154,
	       shifted_exp___13__h4491,
	       shifted_exp___13__h7122,
	       shifted_exp___13__h9550,
	       shifted_exp___1__h1599,
	       shifted_exp___1__h4935,
	       shifted_exp___1__h7566,
	       shifted_exp___1__h9994,
	       shifted_exp___2__h1562,
	       shifted_exp___2__h4898,
	       shifted_exp___2__h7529,
	       shifted_exp___2__h9957,
	       shifted_exp___3__h1525,
	       shifted_exp___3__h4861,
	       shifted_exp___3__h7492,
	       shifted_exp___3__h9920,
	       shifted_exp___4__h1488,
	       shifted_exp___4__h4824,
	       shifted_exp___4__h7455,
	       shifted_exp___4__h9883,
	       shifted_exp___5__h1451,
	       shifted_exp___5__h4787,
	       shifted_exp___5__h7418,
	       shifted_exp___5__h9846,
	       shifted_exp___6__h1414,
	       shifted_exp___6__h4750,
	       shifted_exp___6__h7381,
	       shifted_exp___6__h9809,
	       shifted_exp___7__h1377,
	       shifted_exp___7__h4713,
	       shifted_exp___7__h7344,
	       shifted_exp___7__h9772,
	       shifted_exp___8__h1340,
	       shifted_exp___8__h4676,
	       shifted_exp___8__h7307,
	       shifted_exp___8__h9735,
	       shifted_exp___9__h1303,
	       shifted_exp___9__h4639,
	       shifted_exp___9__h7270,
	       shifted_exp___9__h9698;
  wire [8 : 0] IF_NOT_tmp446_BIT_7_AND_NOT_tmp446_EQ_0_THEN_t_ETC__q7,
	       IF_NOT_tmp790_BIT_7_AND_NOT_tmp790_EQ_0_THEN_t_ETC__q5,
	       _theResult_____1_fst__h8036,
	       _theResult_____1_fst__h8711,
	       _theResult_____2_snd__h7872,
	       _theResult_____2_snd__h8529,
	       a_exp_eff__h4338,
	       a_exp_eff__h6957,
	       a_exp_eff__h9397,
	       a_exp_eff__h989,
	       b_exp_eff__h4339,
	       b_exp_eff__h9398,
	       exp_sum__h4340,
	       exp_sum__h6959,
	       exp_sum__h9399,
	       exp_sum__h991,
	       man_result__h7843,
	       man_result__h7936,
	       man_result__h7938,
	       man_result__h8498,
	       man_result__h8610,
	       man_result__h8612,
	       tmp__h7790,
	       tmp__h8446;
  wire [7 : 0] _theResult_____1_snd__h8032,
	       _theResult_____1_snd__h8037,
	       _theResult_____1_snd__h8074,
	       _theResult_____1_snd__h8111,
	       _theResult_____1_snd__h8148,
	       _theResult_____1_snd__h8185,
	       _theResult_____1_snd__h8222,
	       _theResult_____1_snd__h8259,
	       _theResult_____1_snd__h8707,
	       _theResult_____1_snd__h8712,
	       _theResult_____1_snd__h8749,
	       _theResult_____1_snd__h8786,
	       _theResult_____1_snd__h8823,
	       _theResult_____1_snd__h8860,
	       _theResult_____1_snd__h8897,
	       _theResult_____1_snd__h8934,
	       _theResult___fst_exp__h7868,
	       _theResult___fst_exp__h8523,
	       a_exp__h2199,
	       a_full_mant__h4335,
	       a_full_mant__h6954,
	       a_full_mant__h9394,
	       a_full_mant__h986,
	       b_full_mant__h4336,
	       b_full_mant__h9395,
	       bigger_m__h7783,
	       bigger_m__h8439,
	       bigger_m__h8519,
	       exp_diff__h7859,
	       exp_diff__h7863,
	       exp_diff__h8514,
	       exp_diff__h8518,
	       final_exp__h7996,
	       final_exp__h8001,
	       final_exp__h8671,
	       final_exp__h8676,
	       smaller_m__h7784,
	       smaller_m__h7861,
	       smaller_m__h7865,
	       smaller_m__h8440,
	       smaller_m__h8516,
	       smaller_m__h8520;
  wire [6 : 0] IF_s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2__ETC___d836,
	       _theResult_____1_snd__h10007,
	       _theResult_____1_snd__h1612,
	       _theResult_____1_snd__h4948,
	       _theResult_____1_snd__h7579,
	       _theResult___fst__h1118,
	       _theResult___fst__h4455,
	       _theResult___fst__h7086,
	       _theResult___fst__h9514,
	       final_mant__h4346,
	       final_mant__h6965,
	       final_mant__h9405,
	       final_mant__h997;
  wire IF_IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AN_ETC___d959,
       IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d951,
       _0b1_CONCAT_IF_s2_input_z_93_BITS_14_TO_7_94_UL_ETC___d845,
       _theResult_____2_fst__h7871,
       _theResult_____2_fst__h8528,
       final_result_sign__h9204,
       result_sign__h7794,
       result_sign__h7844,
       result_sign__h7939,
       result_sign__h8450,
       result_sign__h8499,
       result_sign__h8613,
       s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2_n_9_ETC___d834,
       s2_input_z_93_BIT_15_32_EQ_INV_NOT_s2_n_91_EQ__ETC___d833,
       zn_sign__h5558;

  // action method put_data
  assign RDY_put_data = 1'd1 ;

  // actionvalue method getResult
  assign getResult = result_data ;
  assign RDY_getResult = result_valid ;

  // value method hasResult
  assign hasResult = result_valid ;
  assign RDY_hasResult = 1'd1 ;

  // register result_data
  assign result_data$D_IN =
	     { final_result_sign__h9204,
	       IF_s3_y_063_BITS_14_TO_7_068_EQ_0_069_AND_s3_y_ETC___d1280 } ;
  assign result_data$EN = stage4[0] ;

  // register result_valid
  assign result_valid$D_IN = stage4[0] ;
  assign result_valid$EN = stage4[0] || result_valid ;

  // register s1_input_z
  assign s1_input_z$D_IN = stage1[16:1] ;
  assign s1_input_z$EN = stage1[0] ;

  // register s1_zc1
  assign s1_zc1$D_IN =
	     { stage1[16],
	       (stage1[15:8] == 8'd0 && stage1[7:1] == 7'd0) ?
		 15'b0 :
		 IF_IF_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2__ETC___d207 } ;
  assign s1_zc1$EN = stage1[0] ;

  // register s2_input_z
  assign s2_input_z$D_IN = s1_input_z ;
  assign s2_input_z$EN = stage2[0] ;

  // register s2_n
  assign s2_n$D_IN =
	     IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d247 ;
  assign s2_n$EN = stage2[0] ;

  // register s2_y
  assign s2_y$D_IN =
	     (a_exp__h2199 == 8'd0 ||
	      b_exp__h2202 == 8'd0 && b_mant__h2203 == 7'd0) ?
	       16'd0 :
	       result__h4350 ;
  assign s2_y$EN = stage2[0] ;

  // register s3_n
  assign s3_n$D_IN = s2_n ;
  assign s3_n$EN = stage3[0] ;

  // register s3_x
  assign s3_x$D_IN =
	     (IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[14:7] ==
	      8'd0 &&
	      IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[6:0] ==
	      7'd0) ?
	       16'd16256 :
	       result_raw__h8449 ;
  assign s3_x$EN = stage3[0] ;

  // register s3_y
  assign s3_y$D_IN = s2_y ;
  assign s3_y$EN = stage3[0] ;

  // register stage1
  assign stage1$D_IN = { put_data_data, 1'd1 } ;
  assign stage1$EN = EN_put_data ;

  // register stage2
  assign stage2$D_IN = stage1[0] ? { stage1[16:1], 1'd1 } : 17'd0 ;
  assign stage2$EN = 1'd1 ;

  // register stage3
  assign stage3$D_IN = stage2[0] ? { stage2[16:1], 1'd1 } : 17'd0 ;
  assign stage3$EN = 1'd1 ;

  // register stage4
  assign stage4$D_IN = stage3[0] ? { stage3[16:1], 1'd1 } : 17'd0 ;
  assign stage4$EN = 1'd1 ;

  // remaining internal signals
  assign IF_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_ETC___d246 =
	     ((_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_127___d219 ^
	       16'h8000) <
	      16'd32783) ?
	       IF_15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_ETC___d244 :
	       (s1_zc1[15] ? 16'd32768 : 16'd32767) ;
  assign IF_0b1_CONCAT_s1_zc1_15_BITS_6_TO_0_26_CONCAT__ETC___d241 =
	     mantissa_with_implicit__h1955[x__h1999[3:0]] ?
	       integer_part__h1962 + 16'd1 :
	       integer_part__h1962 ;
  assign IF_15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_ETC___d244 =
	     ((_15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_ETC___d223 ^
	       16'h8000) <=
	      16'd32768) ?
	       (s1_zc1[15] ? -integer_part__h2009 : integer_part__h2009) :
	       (s1_zc1[15] ?
		  -IF_0b1_CONCAT_s1_zc1_15_BITS_6_TO_0_26_CONCAT__ETC___d241 :
		  IF_0b1_CONCAT_s1_zc1_15_BITS_6_TO_0_26_CONCAT__ETC___d241) ;
  assign IF_IF_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_1_ETC___d483 =
	     (final_exp_10__h4347[9] || final_exp_10__h4347 == 10'd0) ?
	       { 8'b0, _theResult_____1_snd__h4948 } :
	       ((final_exp_10__h4347 < 10'd255) ?
		  { final_exp_10__h4347[7:0], final_mant__h4346 } :
		  15'd32640) ;
  assign IF_IF_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_E_ETC___d824 =
	     (final_exp_10__h6966[9] || final_exp_10__h6966 == 10'd0) ?
	       { 8'b0, _theResult_____1_snd__h7579 } :
	       ((final_exp_10__h6966 < 10'd255) ?
		  { final_exp_10__h6966[7:0], final_mant__h6965 } :
		  15'd32640) ;
  assign IF_IF_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_E_ETC___d1279 =
	     (final_exp_10__h9406[9] || final_exp_10__h9406 == 10'd0) ?
	       { 8'b0, _theResult_____1_snd__h10007 } :
	       ((final_exp_10__h9406 < 10'd255) ?
		  { final_exp_10__h9406[7:0], final_mant__h9405 } :
		  15'd32640) ;
  assign IF_IF_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2__ETC___d207 =
	     (final_exp_10__h998[9] || final_exp_10__h998 == 10'd0) ?
	       { 8'b0, _theResult_____1_snd__h1612 } :
	       ((final_exp_10__h998 < 10'd255) ?
		  { final_exp_10__h998[7:0], final_mant__h997 } :
		  15'd32640) ;
  assign IF_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc_ETC___d259 =
	     IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d256[15] ?
	       IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d256 +
	       16'd16 :
	       IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d256 ;
  assign IF_IF_INV_IF_s2_input_z_93_BITS_14_TO_7_94_EQ__ETC___d1056 =
	     tmp__h8446[8] ?
	       { final_exp__h8671, tmp__h8446[7:1] } :
	       { final_exp__h8676,
		 IF_NOT_tmp446_BIT_7_AND_NOT_tmp446_EQ_0_THEN_t_ETC__q7[6:0] } ;
  assign IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d252 =
	     IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d247[15] ?
	       ((s1_zc1 == 16'h0 ||
		 _0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_127___d219[15]) ?
		  16'd0 :
		  -IF_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_ETC___d246) :
	       IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d247 ;
  assign IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d256 =
	     IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d247[15] ?
	       -{ 12'd0,
		  IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d252[3:0] } :
	       { 12'd0,
		 IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d252[3:0] } ;
  assign IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d264 =
	     (IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d260[15] ?
		-IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d260 :
		IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d260) >>
	     4 ;
  assign IF_IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AN_ETC___d959 =
	     bigger_m__h8439 < smaller_m__h8440 ;
  assign IF_IF_s2_input_z_93_BIT_15_32_EQ_INV_NOT_s2_n__ETC___d940 =
	     tmp__h7790[8] ?
	       { final_exp__h7996, tmp__h7790[7:1] } :
	       { final_exp__h8001,
		 IF_NOT_tmp790_BIT_7_AND_NOT_tmp790_EQ_0_THEN_t_ETC__q5[6:0] } ;
  assign IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d606 =
	     (abs_val__h5617[0] && !abs_val__h5617[1] && !abs_val__h5617[2] &&
	      !abs_val__h5617[3] &&
	      !abs_val__h5617[4] &&
	      !abs_val__h5617[5] &&
	      !abs_val__h5617[6] &&
	      !abs_val__h5617[7] &&
	      !abs_val__h5617[8] &&
	      !abs_val__h5617[9] &&
	      !abs_val__h5617[10] &&
	      !abs_val__h5617[11] &&
	      !abs_val__h5617[12] &&
	      !abs_val__h5617[13] &&
	      !abs_val__h5617[14] &&
	      !abs_val__h5617[15]) ?
	       16'd0 :
	       ((abs_val__h5617[1] && !abs_val__h5617[2] &&
		 !abs_val__h5617[3] &&
		 !abs_val__h5617[4] &&
		 !abs_val__h5617[5] &&
		 !abs_val__h5617[6] &&
		 !abs_val__h5617[7] &&
		 !abs_val__h5617[8] &&
		 !abs_val__h5617[9] &&
		 !abs_val__h5617[10] &&
		 !abs_val__h5617[11] &&
		 !abs_val__h5617[12] &&
		 !abs_val__h5617[13] &&
		 !abs_val__h5617[14] &&
		 !abs_val__h5617[15]) ?
		  16'd1 :
		  ((abs_val__h5617[2] && !abs_val__h5617[3] &&
		    !abs_val__h5617[4] &&
		    !abs_val__h5617[5] &&
		    !abs_val__h5617[6] &&
		    !abs_val__h5617[7] &&
		    !abs_val__h5617[8] &&
		    !abs_val__h5617[9] &&
		    !abs_val__h5617[10] &&
		    !abs_val__h5617[11] &&
		    !abs_val__h5617[12] &&
		    !abs_val__h5617[13] &&
		    !abs_val__h5617[14] &&
		    !abs_val__h5617[15]) ?
		     16'd2 :
		     ((abs_val__h5617[3] && !abs_val__h5617[4] &&
		       !abs_val__h5617[5] &&
		       !abs_val__h5617[6] &&
		       !abs_val__h5617[7] &&
		       !abs_val__h5617[8] &&
		       !abs_val__h5617[9] &&
		       !abs_val__h5617[10] &&
		       !abs_val__h5617[11] &&
		       !abs_val__h5617[12] &&
		       !abs_val__h5617[13] &&
		       !abs_val__h5617[14] &&
		       !abs_val__h5617[15]) ?
			16'd3 :
			((abs_val__h5617[4] && !abs_val__h5617[5] &&
			  !abs_val__h5617[6] &&
			  !abs_val__h5617[7] &&
			  !abs_val__h5617[8] &&
			  !abs_val__h5617[9] &&
			  !abs_val__h5617[10] &&
			  !abs_val__h5617[11] &&
			  !abs_val__h5617[12] &&
			  !abs_val__h5617[13] &&
			  !abs_val__h5617[14] &&
			  !abs_val__h5617[15]) ?
			   16'd4 :
			   ((abs_val__h5617[5] && !abs_val__h5617[6] &&
			     !abs_val__h5617[7] &&
			     !abs_val__h5617[8] &&
			     !abs_val__h5617[9] &&
			     !abs_val__h5617[10] &&
			     !abs_val__h5617[11] &&
			     !abs_val__h5617[12] &&
			     !abs_val__h5617[13] &&
			     !abs_val__h5617[14] &&
			     !abs_val__h5617[15]) ?
			      16'd5 :
			      ((abs_val__h5617[6] && !abs_val__h5617[7] &&
				!abs_val__h5617[8] &&
				!abs_val__h5617[9] &&
				!abs_val__h5617[10] &&
				!abs_val__h5617[11] &&
				!abs_val__h5617[12] &&
				!abs_val__h5617[13] &&
				!abs_val__h5617[14] &&
				!abs_val__h5617[15]) ?
				 16'd6 :
				 ((abs_val__h5617[7] && !abs_val__h5617[8] &&
				   !abs_val__h5617[9] &&
				   !abs_val__h5617[10] &&
				   !abs_val__h5617[11] &&
				   !abs_val__h5617[12] &&
				   !abs_val__h5617[13] &&
				   !abs_val__h5617[14] &&
				   !abs_val__h5617[15]) ?
				    16'd7 :
				    ((abs_val__h5617[8] &&
				      !abs_val__h5617[9] &&
				      !abs_val__h5617[10] &&
				      !abs_val__h5617[11] &&
				      !abs_val__h5617[12] &&
				      !abs_val__h5617[13] &&
				      !abs_val__h5617[14] &&
				      !abs_val__h5617[15]) ?
				       16'd8 :
				       ((abs_val__h5617[9] &&
					 !abs_val__h5617[10] &&
					 !abs_val__h5617[11] &&
					 !abs_val__h5617[12] &&
					 !abs_val__h5617[13] &&
					 !abs_val__h5617[14] &&
					 !abs_val__h5617[15]) ?
					  16'd9 :
					  ((abs_val__h5617[10] &&
					    !abs_val__h5617[11] &&
					    !abs_val__h5617[12] &&
					    !abs_val__h5617[13] &&
					    !abs_val__h5617[14] &&
					    !abs_val__h5617[15]) ?
					     16'd10 :
					     ((abs_val__h5617[11] &&
					       !abs_val__h5617[12] &&
					       !abs_val__h5617[13] &&
					       !abs_val__h5617[14] &&
					       !abs_val__h5617[15]) ?
						16'd11 :
						((abs_val__h5617[12] &&
						  !abs_val__h5617[13] &&
						  !abs_val__h5617[14] &&
						  !abs_val__h5617[15]) ?
						   16'd12 :
						   ((abs_val__h5617[13] &&
						     !abs_val__h5617[14] &&
						     !abs_val__h5617[15]) ?
						      16'd13 :
						      ((abs_val__h5617[14] &&
							!abs_val__h5617[15]) ?
							 16'd14 :
							 (abs_val__h5617[15] ?
							    16'd15 :
							    16'd0))))))))))))))) ;
  assign IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d607 =
	     IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d606 +
	     16'd127 ;
  assign IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825 =
	     (IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623[14:7] ==
	      8'd0 &&
	      IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623[6:0] ==
	      7'd0) ?
	       15'b0 :
	       IF_IF_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_E_ETC___d824 ;
  assign IF_NOT_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1__ETC__q2 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[13] &&
	      _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[15:0] !=
	      16'd0) ?
	       _theResult___snd__h4494 :
	       _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[15:0] ;
  assign IF_NOT_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0__ETC__q4 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[13] &&
	      _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[15:0] !=
	      16'd0) ?
	       _theResult___snd__h7125 :
	       _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[15:0] ;
  assign IF_NOT_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068__ETC__q6 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[13] &&
	      _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[15:0] !=
	      16'd0) ?
	       _theResult___snd__h9553 :
	       _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[15:0] ;
  assign IF_NOT_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_ETC__q1 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[13] &&
	      _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[15:0] !=
	      16'd0) ?
	       _theResult___snd__h1157 :
	       _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[15:0] ;
  assign IF_NOT_IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_9_ETC___d622 =
	     ((IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d607 ^
	       16'h8000) >
	      16'd32768 &&
	      (IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d607 ^
	       16'h8000) <
	      16'd33023) ?
	       { IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d607[7:0],
		 abs_val617_SL_x799__q3[14:8] } :
	       15'd0 ;
  assign IF_NOT_tmp446_BIT_7_AND_NOT_tmp446_EQ_0_THEN_t_ETC__q7 =
	     (!tmp__h8446[7] && tmp__h8446 != 9'd0) ?
	       _theResult_____1_fst__h8711 :
	       tmp__h8446 ;
  assign IF_NOT_tmp790_BIT_7_AND_NOT_tmp790_EQ_0_THEN_t_ETC__q5 =
	     (!tmp__h7790[7] && tmp__h7790 != 9'd0) ?
	       _theResult_____1_fst__h8036 :
	       tmp__h7790 ;
  assign IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d247 =
	     (s1_zc1 == 16'h0 ||
	      _0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_127___d219[15]) ?
	       16'd0 :
	       IF_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_ETC___d246 ;
  assign IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d260 =
	     IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d247 -
	     IF_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc_ETC___d259 ;
  assign IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943 =
	     (s2_input_z[14:7] == 8'd0 && s2_input_z[6:0] == 7'd0) ?
	       neg_b__h5476 :
	       ((IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[14:7] ==
		 8'd0 &&
		 IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[6:0] ==
		 7'd0) ?
		  s2_input_z :
		  result_raw__h7793) ;
  assign IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d951 =
	     IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[14:7] <=
	     8'd127 ;
  assign IF_s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2__ETC___d836 =
	     s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2_n_9_ETC___d834 ?
	       IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[6:0] :
	       s2_input_z[6:0] ;
  assign IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623 =
	     (s2_n == 16'd0) ?
	       15'd0 :
	       IF_NOT_IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_9_ETC___d622 ;
  assign IF_s3_y_063_BITS_14_TO_7_068_EQ_0_069_AND_s3_y_ETC___d1280 =
	     (s3_y[14:7] == 8'd0 && s3_y[6:0] == 7'd0 ||
	      s3_x[14:7] == 8'd0 && s3_x[6:0] == 7'd0) ?
	       15'b0 :
	       IF_IF_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_E_ETC___d1279 ;
  assign _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289 =
	     { 8'd0, a_full_mant__h4335 } * { 8'd0, b_full_mant__h4336 } ;
  assign _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632 =
	     { 8'd0, a_full_mant__h6954 } * 16'd177 ;
  assign _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085 =
	     { 8'd0, a_full_mant__h9394 } * { 8'd0, b_full_mant__h9395 } ;
  assign _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15 =
	     { 8'd0, a_full_mant__h986 } * 16'd185 ;
  assign _0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_127___d219 =
	     { 8'd0, s1_zc1[14:7] } - 16'd127 ;
  assign _0b1_CONCAT_IF_s2_input_z_93_BITS_14_TO_7_94_UL_ETC___d845 =
	     bigger_m__h7783 < smaller_m__h7784 ;
  assign _127_MINUS_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCA_ETC___d267 =
	     16'd127 -
	     (IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_15_B_ETC___d260[15] ?
		-IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d264 :
		IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc1_1_ETC___d264) ;
  assign _15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_ETC___d223 =
	     16'd15 -
	     _0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_MINUS_127___d219 ;
  assign _theResult_____1_fst__h8036 =
	     { (!tmp__h7790[6] && tmp__h7790[7:0] != 8'd0) ?
		 ((!tmp__h7790[5] && { tmp__h7790[6:0], 1'd0 } != 8'd0) ?
		    ((!tmp__h7790[4] && { tmp__h7790[5:0], 2'd0 } != 8'd0) ?
		       ((!tmp__h7790[3] &&
			 { tmp__h7790[4:0], 3'd0 } != 8'd0) ?
			  ((!tmp__h7790[2] &&
			    { tmp__h7790[3:0], 4'd0 } != 8'd0) ?
			     ((!tmp__h7790[1] &&
			       { tmp__h7790[2:0], 5'd0 } != 8'd0) ?
				((!tmp__h7790[0] &&
				  { tmp__h7790[1:0], 6'd0 } != 8'd0) ?
				   8'd0 :
				   { tmp__h7790[1:0], 6'd0 }) :
				{ tmp__h7790[2:0], 5'd0 }) :
			     { tmp__h7790[3:0], 4'd0 }) :
			  { tmp__h7790[4:0], 3'd0 }) :
		       { tmp__h7790[5:0], 2'd0 }) :
		    { tmp__h7790[6:0], 1'd0 }) :
		 tmp__h7790[7:0],
	       1'd0 } ;
  assign _theResult_____1_fst__h8711 =
	     { (!tmp__h8446[6] && tmp__h8446[7:0] != 8'd0) ?
		 ((!tmp__h8446[5] && { tmp__h8446[6:0], 1'd0 } != 8'd0) ?
		    ((!tmp__h8446[4] && { tmp__h8446[5:0], 2'd0 } != 8'd0) ?
		       ((!tmp__h8446[3] &&
			 { tmp__h8446[4:0], 3'd0 } != 8'd0) ?
			  ((!tmp__h8446[2] &&
			    { tmp__h8446[3:0], 4'd0 } != 8'd0) ?
			     ((!tmp__h8446[1] &&
			       { tmp__h8446[2:0], 5'd0 } != 8'd0) ?
				((!tmp__h8446[0] &&
				  { tmp__h8446[1:0], 6'd0 } != 8'd0) ?
				   8'd0 :
				   { tmp__h8446[1:0], 6'd0 }) :
				{ tmp__h8446[2:0], 5'd0 }) :
			     { tmp__h8446[3:0], 4'd0 }) :
			  { tmp__h8446[4:0], 3'd0 }) :
		       { tmp__h8446[5:0], 2'd0 }) :
		    { tmp__h8446[6:0], 1'd0 }) :
		 tmp__h8446[7:0],
	       1'd0 } ;
  assign _theResult_____1_snd__h10007 =
	     (final_exp_10__h9406 == 10'd0) ? final_mant__h9405 : 7'b0 ;
  assign _theResult_____1_snd__h1612 =
	     (final_exp_10__h998 == 10'd0) ? final_mant__h997 : 7'b0 ;
  assign _theResult_____1_snd__h4948 =
	     (final_exp_10__h4347 == 10'd0) ? final_mant__h4346 : 7'b0 ;
  assign _theResult_____1_snd__h7579 =
	     (final_exp_10__h6966 == 10'd0) ? final_mant__h6965 : 7'b0 ;
  assign _theResult_____1_snd__h8032 =
	     (!tmp__h7790[7] && tmp__h7790 != 9'd0) ?
	       _theResult_____1_snd__h8037 :
	       8'd0 ;
  assign _theResult_____1_snd__h8037 =
	     (!tmp__h7790[6] && tmp__h7790[7:0] != 8'd0) ?
	       _theResult_____1_snd__h8074 :
	       8'd1 ;
  assign _theResult_____1_snd__h8074 =
	     (!tmp__h7790[5] && { tmp__h7790[6:0], 1'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8111 :
	       8'd2 ;
  assign _theResult_____1_snd__h8111 =
	     (!tmp__h7790[4] && { tmp__h7790[5:0], 2'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8148 :
	       8'd3 ;
  assign _theResult_____1_snd__h8148 =
	     (!tmp__h7790[3] && { tmp__h7790[4:0], 3'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8185 :
	       8'd4 ;
  assign _theResult_____1_snd__h8185 =
	     (!tmp__h7790[2] && { tmp__h7790[3:0], 4'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8222 :
	       8'd5 ;
  assign _theResult_____1_snd__h8222 =
	     (!tmp__h7790[1] && { tmp__h7790[2:0], 5'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8259 :
	       8'd6 ;
  assign _theResult_____1_snd__h8259 =
	     (!tmp__h7790[0] && { tmp__h7790[1:0], 6'd0 } != 8'd0) ?
	       8'd8 :
	       8'd7 ;
  assign _theResult_____1_snd__h8707 =
	     (!tmp__h8446[7] && tmp__h8446 != 9'd0) ?
	       _theResult_____1_snd__h8712 :
	       8'd0 ;
  assign _theResult_____1_snd__h8712 =
	     (!tmp__h8446[6] && tmp__h8446[7:0] != 8'd0) ?
	       _theResult_____1_snd__h8749 :
	       8'd1 ;
  assign _theResult_____1_snd__h8749 =
	     (!tmp__h8446[5] && { tmp__h8446[6:0], 1'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8786 :
	       8'd2 ;
  assign _theResult_____1_snd__h8786 =
	     (!tmp__h8446[4] && { tmp__h8446[5:0], 2'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8823 :
	       8'd3 ;
  assign _theResult_____1_snd__h8823 =
	     (!tmp__h8446[3] && { tmp__h8446[4:0], 3'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8860 :
	       8'd4 ;
  assign _theResult_____1_snd__h8860 =
	     (!tmp__h8446[2] && { tmp__h8446[3:0], 4'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8897 :
	       8'd5 ;
  assign _theResult_____1_snd__h8897 =
	     (!tmp__h8446[1] && { tmp__h8446[2:0], 5'd0 } != 8'd0) ?
	       _theResult_____1_snd__h8934 :
	       8'd6 ;
  assign _theResult_____1_snd__h8934 =
	     (!tmp__h8446[0] && { tmp__h8446[1:0], 6'd0 } != 8'd0) ?
	       8'd8 :
	       8'd7 ;
  assign _theResult_____2_fst__h7871 =
	     _0b1_CONCAT_IF_s2_input_z_93_BITS_14_TO_7_94_UL_ETC___d845 ?
	       result_sign__h7939 :
	       result_sign__h7844 ;
  assign _theResult_____2_fst__h8528 =
	     IF_IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AN_ETC___d959 ?
	       result_sign__h8613 :
	       result_sign__h8499 ;
  assign _theResult_____2_snd__h7872 =
	     _0b1_CONCAT_IF_s2_input_z_93_BITS_14_TO_7_94_UL_ETC___d845 ?
	       man_result__h7938 :
	       man_result__h7936 ;
  assign _theResult_____2_snd__h8529 =
	     IF_IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AN_ETC___d959 ?
	       man_result__h8612 :
	       man_result__h8610 ;
  assign _theResult___fst__h1118 =
	     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[14] ?
	       _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[13:7] :
	       IF_NOT_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_ETC__q1[13:7] ;
  assign _theResult___fst__h1156 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[12] &&
	      _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[14:0] !=
	      15'd0) ?
	       _theResult___fst__h1194 :
	       shifted_exp___13__h1154 ;
  assign _theResult___fst__h1194 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[11] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[13:0],
		1'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1231 :
	       shifted_exp___12__h1192 ;
  assign _theResult___fst__h1231 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[10] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[12:0],
		2'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1268 :
	       shifted_exp___11__h1229 ;
  assign _theResult___fst__h1268 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[9] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[11:0],
		3'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1305 :
	       shifted_exp___10__h1266 ;
  assign _theResult___fst__h1305 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[8] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[10:0],
		4'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1342 :
	       shifted_exp___9__h1303 ;
  assign _theResult___fst__h1342 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[7] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[9:0],
		5'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1379 :
	       shifted_exp___8__h1340 ;
  assign _theResult___fst__h1379 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[6] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[8:0],
		6'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1416 :
	       shifted_exp___7__h1377 ;
  assign _theResult___fst__h1416 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[5] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[7:0],
		7'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1453 :
	       shifted_exp___6__h1414 ;
  assign _theResult___fst__h1453 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[4] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[6:0],
		8'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1490 :
	       shifted_exp___5__h1451 ;
  assign _theResult___fst__h1490 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[3] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[5:0],
		9'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1527 :
	       shifted_exp___4__h1488 ;
  assign _theResult___fst__h1527 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[2] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[4:0],
		10'd0 } !=
	      15'd0) ?
	       _theResult___fst__h1564 :
	       shifted_exp___3__h1525 ;
  assign _theResult___fst__h1564 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[1] &&
	      { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[3:0],
		11'd0 } !=
	      15'd0) ?
	       shifted_exp___1__h1599 :
	       shifted_exp___2__h1562 ;
  assign _theResult___fst__h4455 =
	     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[14] ?
	       _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[13:7] :
	       IF_NOT_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1__ETC__q2[13:7] ;
  assign _theResult___fst__h4493 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[12] &&
	      _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[14:0] !=
	      15'd0) ?
	       _theResult___fst__h4530 :
	       shifted_exp___13__h4491 ;
  assign _theResult___fst__h4530 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[11] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[13:0],
		1'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4567 :
	       shifted_exp___12__h4528 ;
  assign _theResult___fst__h4567 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[10] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[12:0],
		2'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4604 :
	       shifted_exp___11__h4565 ;
  assign _theResult___fst__h4604 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[9] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[11:0],
		3'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4641 :
	       shifted_exp___10__h4602 ;
  assign _theResult___fst__h4641 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[8] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[10:0],
		4'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4678 :
	       shifted_exp___9__h4639 ;
  assign _theResult___fst__h4678 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[7] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[9:0],
		5'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4715 :
	       shifted_exp___8__h4676 ;
  assign _theResult___fst__h4715 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[6] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[8:0],
		6'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4752 :
	       shifted_exp___7__h4713 ;
  assign _theResult___fst__h4752 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[5] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[7:0],
		7'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4789 :
	       shifted_exp___6__h4750 ;
  assign _theResult___fst__h4789 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[4] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[6:0],
		8'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4826 :
	       shifted_exp___5__h4787 ;
  assign _theResult___fst__h4826 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[3] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[5:0],
		9'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4863 :
	       shifted_exp___4__h4824 ;
  assign _theResult___fst__h4863 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[2] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[4:0],
		10'd0 } !=
	      15'd0) ?
	       _theResult___fst__h4900 :
	       shifted_exp___3__h4861 ;
  assign _theResult___fst__h4900 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[1] &&
	      { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[3:0],
		11'd0 } !=
	      15'd0) ?
	       shifted_exp___1__h4935 :
	       shifted_exp___2__h4898 ;
  assign _theResult___fst__h7086 =
	     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[14] ?
	       _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[13:7] :
	       IF_NOT_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0__ETC__q4[13:7] ;
  assign _theResult___fst__h7124 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[12] &&
	      _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[14:0] !=
	      15'd0) ?
	       _theResult___fst__h7161 :
	       shifted_exp___13__h7122 ;
  assign _theResult___fst__h7161 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[11] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[13:0],
		1'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7198 :
	       shifted_exp___12__h7159 ;
  assign _theResult___fst__h7198 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[10] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[12:0],
		2'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7235 :
	       shifted_exp___11__h7196 ;
  assign _theResult___fst__h7235 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[9] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[11:0],
		3'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7272 :
	       shifted_exp___10__h7233 ;
  assign _theResult___fst__h7272 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[8] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[10:0],
		4'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7309 :
	       shifted_exp___9__h7270 ;
  assign _theResult___fst__h7309 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[7] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[9:0],
		5'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7346 :
	       shifted_exp___8__h7307 ;
  assign _theResult___fst__h7346 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[6] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[8:0],
		6'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7383 :
	       shifted_exp___7__h7344 ;
  assign _theResult___fst__h7383 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[5] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[7:0],
		7'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7420 :
	       shifted_exp___6__h7381 ;
  assign _theResult___fst__h7420 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[4] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[6:0],
		8'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7457 :
	       shifted_exp___5__h7418 ;
  assign _theResult___fst__h7457 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[3] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[5:0],
		9'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7494 :
	       shifted_exp___4__h7455 ;
  assign _theResult___fst__h7494 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[2] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[4:0],
		10'd0 } !=
	      15'd0) ?
	       _theResult___fst__h7531 :
	       shifted_exp___3__h7492 ;
  assign _theResult___fst__h7531 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[1] &&
	      { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[3:0],
		11'd0 } !=
	      15'd0) ?
	       shifted_exp___1__h7566 :
	       shifted_exp___2__h7529 ;
  assign _theResult___fst__h9514 =
	     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[14] ?
	       _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[13:7] :
	       IF_NOT_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068__ETC__q6[13:7] ;
  assign _theResult___fst__h9552 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[12] &&
	      _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[14:0] !=
	      15'd0) ?
	       _theResult___fst__h9589 :
	       shifted_exp___13__h9550 ;
  assign _theResult___fst__h9589 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[11] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[13:0],
		1'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9626 :
	       shifted_exp___12__h9587 ;
  assign _theResult___fst__h9626 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[10] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[12:0],
		2'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9663 :
	       shifted_exp___11__h9624 ;
  assign _theResult___fst__h9663 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[9] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[11:0],
		3'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9700 :
	       shifted_exp___10__h9661 ;
  assign _theResult___fst__h9700 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[8] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[10:0],
		4'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9737 :
	       shifted_exp___9__h9698 ;
  assign _theResult___fst__h9737 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[7] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[9:0],
		5'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9774 :
	       shifted_exp___8__h9735 ;
  assign _theResult___fst__h9774 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[6] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[8:0],
		6'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9811 :
	       shifted_exp___7__h9772 ;
  assign _theResult___fst__h9811 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[5] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[7:0],
		7'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9848 :
	       shifted_exp___6__h9809 ;
  assign _theResult___fst__h9848 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[4] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[6:0],
		8'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9885 :
	       shifted_exp___5__h9846 ;
  assign _theResult___fst__h9885 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[3] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[5:0],
		9'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9922 :
	       shifted_exp___4__h9883 ;
  assign _theResult___fst__h9922 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[2] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[4:0],
		10'd0 } !=
	      15'd0) ?
	       _theResult___fst__h9959 :
	       shifted_exp___3__h9920 ;
  assign _theResult___fst__h9959 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[1] &&
	      { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[3:0],
		11'd0 } !=
	      15'd0) ?
	       shifted_exp___1__h9994 :
	       shifted_exp___2__h9957 ;
  assign _theResult___fst_exp__h7868 =
	     s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2_n_9_ETC___d834 ?
	       IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[14:7] :
	       s2_input_z[14:7] ;
  assign _theResult___fst_exp__h8523 =
	     IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d951 ?
	       8'd127 :
	       IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[14:7] ;
  assign _theResult___snd__h1119 =
	     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[14] ?
	       raw_exp_10__h993 :
	       final_exp_10__h1122 ;
  assign _theResult___snd__h1157 =
	     { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[12] &&
		_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[14:0] !=
		15'd0) ?
		 { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[11] &&
		    { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[13:0],
		      1'd0 } !=
		    15'd0) ?
		     { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[10] &&
			{ _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[12:0],
			  2'd0 } !=
			15'd0) ?
			 { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[9] &&
			    { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[11:0],
			      3'd0 } !=
			    15'd0) ?
			     { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[8] &&
				{ _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[10:0],
				  4'd0 } !=
				15'd0) ?
				 { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[7] &&
				    { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[9:0],
				      5'd0 } !=
				    15'd0) ?
				     { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[6] &&
					{ _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[8:0],
					  6'd0 } !=
					15'd0) ?
					 { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[5] &&
					    { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[7:0],
					      7'd0 } !=
					    15'd0) ?
					     { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[4] &&
						{ _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[6:0],
						  8'd0 } !=
						15'd0) ?
						 { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[3] &&
						    { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[5:0],
						      9'd0 } !=
						    15'd0) ?
						     { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[2] &&
							{ _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[4:0],
							  10'd0 } !=
							15'd0) ?
							 { (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[1] &&
							    { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[3:0],
							      11'd0 } !=
							    15'd0) ?
							     { _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[2:0],
							       1'd0 } :
							     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[3:0],
							   1'd0 } :
							 _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[4:0],
						       1'd0 } :
						     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[5:0],
						   1'd0 } :
						 _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[6:0],
					       1'd0 } :
					     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[7:0],
					   1'd0 } :
					 _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[8:0],
				       1'd0 } :
				     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[9:0],
				   1'd0 } :
				 _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[10:0],
			       1'd0 } :
			     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[11:0],
			   1'd0 } :
			 _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[12:0],
		       1'd0 } :
		     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[13:0],
		   1'd0 } :
		 _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[14:0],
	       1'd0 } ;
  assign _theResult___snd__h4456 =
	     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[14] ?
	       raw_exp_10__h4342 :
	       final_exp_10__h4459 ;
  assign _theResult___snd__h4494 =
	     { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[12] &&
		_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[14:0] !=
		15'd0) ?
		 { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[11] &&
		    { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[13:0],
		      1'd0 } !=
		    15'd0) ?
		     { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[10] &&
			{ _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[12:0],
			  2'd0 } !=
			15'd0) ?
			 { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[9] &&
			    { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[11:0],
			      3'd0 } !=
			    15'd0) ?
			     { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[8] &&
				{ _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[10:0],
				  4'd0 } !=
				15'd0) ?
				 { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[7] &&
				    { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[9:0],
				      5'd0 } !=
				    15'd0) ?
				     { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[6] &&
					{ _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[8:0],
					  6'd0 } !=
					15'd0) ?
					 { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[5] &&
					    { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[7:0],
					      7'd0 } !=
					    15'd0) ?
					     { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[4] &&
						{ _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[6:0],
						  8'd0 } !=
						15'd0) ?
						 { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[3] &&
						    { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[5:0],
						      9'd0 } !=
						    15'd0) ?
						     { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[2] &&
							{ _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[4:0],
							  10'd0 } !=
							15'd0) ?
							 { (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[1] &&
							    { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[3:0],
							      11'd0 } !=
							    15'd0) ?
							     { _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[2:0],
							       1'd0 } :
							     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[3:0],
							   1'd0 } :
							 _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[4:0],
						       1'd0 } :
						     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[5:0],
						   1'd0 } :
						 _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[6:0],
					       1'd0 } :
					     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[7:0],
					   1'd0 } :
					 _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[8:0],
				       1'd0 } :
				     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[9:0],
				   1'd0 } :
				 _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[10:0],
			       1'd0 } :
			     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[11:0],
			   1'd0 } :
			 _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[12:0],
		       1'd0 } :
		     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[13:0],
		   1'd0 } :
		 _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[14:0],
	       1'd0 } ;
  assign _theResult___snd__h7087 =
	     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[14] ?
	       raw_exp_10__h6961 :
	       final_exp_10__h7090 ;
  assign _theResult___snd__h7125 =
	     { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[12] &&
		_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[14:0] !=
		15'd0) ?
		 { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[11] &&
		    { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[13:0],
		      1'd0 } !=
		    15'd0) ?
		     { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[10] &&
			{ _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[12:0],
			  2'd0 } !=
			15'd0) ?
			 { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[9] &&
			    { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[11:0],
			      3'd0 } !=
			    15'd0) ?
			     { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[8] &&
				{ _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[10:0],
				  4'd0 } !=
				15'd0) ?
				 { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[7] &&
				    { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[9:0],
				      5'd0 } !=
				    15'd0) ?
				     { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[6] &&
					{ _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[8:0],
					  6'd0 } !=
					15'd0) ?
					 { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[5] &&
					    { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[7:0],
					      7'd0 } !=
					    15'd0) ?
					     { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[4] &&
						{ _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[6:0],
						  8'd0 } !=
						15'd0) ?
						 { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[3] &&
						    { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[5:0],
						      9'd0 } !=
						    15'd0) ?
						     { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[2] &&
							{ _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[4:0],
							  10'd0 } !=
							15'd0) ?
							 { (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[1] &&
							    { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[3:0],
							      11'd0 } !=
							    15'd0) ?
							     { _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[2:0],
							       1'd0 } :
							     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[3:0],
							   1'd0 } :
							 _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[4:0],
						       1'd0 } :
						     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[5:0],
						   1'd0 } :
						 _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[6:0],
					       1'd0 } :
					     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[7:0],
					   1'd0 } :
					 _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[8:0],
				       1'd0 } :
				     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[9:0],
				   1'd0 } :
				 _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[10:0],
			       1'd0 } :
			     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[11:0],
			   1'd0 } :
			 _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[12:0],
		       1'd0 } :
		     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[13:0],
		   1'd0 } :
		 _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[14:0],
	       1'd0 } ;
  assign _theResult___snd__h9515 =
	     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[14] ?
	       raw_exp_10__h9401 :
	       final_exp_10__h9518 ;
  assign _theResult___snd__h9553 =
	     { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[12] &&
		_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[14:0] !=
		15'd0) ?
		 { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[11] &&
		    { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[13:0],
		      1'd0 } !=
		    15'd0) ?
		     { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[10] &&
			{ _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[12:0],
			  2'd0 } !=
			15'd0) ?
			 { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[9] &&
			    { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[11:0],
			      3'd0 } !=
			    15'd0) ?
			     { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[8] &&
				{ _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[10:0],
				  4'd0 } !=
				15'd0) ?
				 { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[7] &&
				    { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[9:0],
				      5'd0 } !=
				    15'd0) ?
				     { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[6] &&
					{ _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[8:0],
					  6'd0 } !=
					15'd0) ?
					 { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[5] &&
					    { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[7:0],
					      7'd0 } !=
					    15'd0) ?
					     { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[4] &&
						{ _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[6:0],
						  8'd0 } !=
						15'd0) ?
						 { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[3] &&
						    { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[5:0],
						      9'd0 } !=
						    15'd0) ?
						     { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[2] &&
							{ _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[4:0],
							  10'd0 } !=
							15'd0) ?
							 { (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[1] &&
							    { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[3:0],
							      11'd0 } !=
							    15'd0) ?
							     { _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[2:0],
							       1'd0 } :
							     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[3:0],
							   1'd0 } :
							 _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[4:0],
						       1'd0 } :
						     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[5:0],
						   1'd0 } :
						 _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[6:0],
					       1'd0 } :
					     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[7:0],
					   1'd0 } :
					 _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[8:0],
				       1'd0 } :
				     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[9:0],
				   1'd0 } :
				 _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[10:0],
			       1'd0 } :
			     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[11:0],
			   1'd0 } :
			 _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[12:0],
		       1'd0 } :
		     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[13:0],
		   1'd0 } :
		 _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[14:0],
	       1'd0 } ;
  assign a_exp__h2199 =
	     ((_127_MINUS_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCA_ETC___d267 ^
	       16'h8000) <=
	      16'd32768) ?
	       8'd0 :
	       (((_127_MINUS_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCA_ETC___d267 ^
		  16'h8000) <
		 16'd33023) ?
		  _127_MINUS_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCA_ETC___d267[7:0] :
		  8'd255) ;
  assign a_exp_eff__h4338 =
	     (a_exp__h2199 == 8'd0) ? 9'd1 : { 1'd0, a_exp__h2199 } ;
  assign a_exp_eff__h6957 =
	     (IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623[14:7] ==
	      8'd0) ?
	       9'd1 :
	       { 1'd0,
		 IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623[14:7] } ;
  assign a_exp_eff__h9397 =
	     (s3_y[14:7] == 8'd0) ? 9'd1 : { 1'd0, s3_y[14:7] } ;
  assign a_exp_eff__h989 =
	     (stage1[15:8] == 8'd0) ? 9'd1 : { 1'd0, stage1[15:8] } ;
  assign a_full_mant__h4335 = { a_exp__h2199 != 8'd0, 7'd0 } ;
  assign a_full_mant__h6954 =
	     { IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623[14:7] !=
	       8'd0,
	       IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_s2_ETC___d623[6:0] } ;
  assign a_full_mant__h9394 = { s3_y[14:7] != 8'd0, s3_y[6:0] } ;
  assign a_full_mant__h986 = { stage1[15:8] != 8'd0, stage1[7:1] } ;
  assign abs_val617_SL_x799__q3 = abs_val__h5617 << x__h6799 ;
  assign abs_val__h5617 = s2_n[15] ? -s2_n : s2_n ;
  assign b_exp_eff__h4339 =
	     (b_exp__h2202 == 8'd0) ? 9'd1 : { 1'd0, b_exp__h2202 } ;
  assign b_exp_eff__h9398 =
	     (s3_x[14:7] == 8'd0) ? 9'd1 : { 1'd0, s3_x[14:7] } ;
  assign b_full_mant__h4336 = { b_exp__h2202 != 8'd0, b_mant__h2203 } ;
  assign b_full_mant__h9395 = { s3_x[14:7] != 8'd0, s3_x[6:0] } ;
  assign bigger_m__h7783 =
	     { 1'b1,
	       IF_s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2__ETC___d836 } ;
  assign bigger_m__h8439 =
	     IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d951 ?
	       8'd128 :
	       bigger_m__h8519 ;
  assign bigger_m__h8519 =
	     { 1'b1,
	       IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[6:0] } ;
  assign exp_diff__h7859 =
	     s2_input_z[14:7] -
	     IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[14:7] ;
  assign exp_diff__h7863 =
	     IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[14:7] -
	     s2_input_z[14:7] ;
  assign exp_diff__h8514 =
	     8'd127 -
	     IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[14:7] ;
  assign exp_diff__h8518 =
	     IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[14:7] -
	     8'd127 ;
  assign exp_sum__h4340 = a_exp_eff__h4338 + b_exp_eff__h4339 ;
  assign exp_sum__h6959 = a_exp_eff__h6957 + 9'd122 ;
  assign exp_sum__h9399 = a_exp_eff__h9397 + b_exp_eff__h9398 ;
  assign exp_sum__h991 = a_exp_eff__h989 + 9'd131 ;
  assign exp_temp__h4341 = { 1'd0, exp_sum__h4340 } ;
  assign exp_temp__h6960 = { 1'd0, exp_sum__h6959 } ;
  assign exp_temp__h9400 = { 1'd0, exp_sum__h9399 } ;
  assign exp_temp__h992 = { 1'd0, exp_sum__h991 } ;
  assign final_exp_10__h1084 = raw_exp_10__h993 + 10'd1 ;
  assign final_exp_10__h1122 =
	     (!_0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[13] &&
	      _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[15:0] !=
	      16'd0) ?
	       _theResult___fst__h1156 :
	       raw_exp_10__h993 ;
  assign final_exp_10__h4347 =
	     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[15] ?
	       final_exp_10__h4420 :
	       _theResult___snd__h4456 ;
  assign final_exp_10__h4420 = raw_exp_10__h4342 + 10'd1 ;
  assign final_exp_10__h4459 =
	     (!_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[13] &&
	      _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[15:0] !=
	      16'd0) ?
	       _theResult___fst__h4493 :
	       raw_exp_10__h4342 ;
  assign final_exp_10__h6966 =
	     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[15] ?
	       final_exp_10__h7052 :
	       _theResult___snd__h7087 ;
  assign final_exp_10__h7052 = raw_exp_10__h6961 + 10'd1 ;
  assign final_exp_10__h7090 =
	     (!_0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[13] &&
	      _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[15:0] !=
	      16'd0) ?
	       _theResult___fst__h7124 :
	       raw_exp_10__h6961 ;
  assign final_exp_10__h9406 =
	     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[15] ?
	       final_exp_10__h9479 :
	       _theResult___snd__h9515 ;
  assign final_exp_10__h9479 = raw_exp_10__h9401 + 10'd1 ;
  assign final_exp_10__h9518 =
	     (!_0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[13] &&
	      _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[15:0] !=
	      16'd0) ?
	       _theResult___fst__h9552 :
	       raw_exp_10__h9401 ;
  assign final_exp_10__h998 =
	     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[15] ?
	       final_exp_10__h1084 :
	       _theResult___snd__h1119 ;
  assign final_exp__h7996 = _theResult___fst_exp__h7868 + 8'd1 ;
  assign final_exp__h8001 =
	     _theResult___fst_exp__h7868 - _theResult_____1_snd__h8032 ;
  assign final_exp__h8671 = _theResult___fst_exp__h8523 + 8'd1 ;
  assign final_exp__h8676 =
	     _theResult___fst_exp__h8523 - _theResult_____1_snd__h8707 ;
  assign final_mant__h4346 =
	     _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[15] ?
	       _0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_15_EQ_0_ETC___d289[14:8] :
	       _theResult___fst__h4455 ;
  assign final_mant__h6965 =
	     _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[15] ?
	       _0_CONCAT_NOT_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_ETC___d632[14:8] :
	       _theResult___fst__h7086 ;
  assign final_mant__h9405 =
	     _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[15] ?
	       _0_CONCAT_NOT_s3_y_063_BITS_14_TO_7_068_EQ_0_06_ETC___d1085[14:8] :
	       _theResult___fst__h9514 ;
  assign final_mant__h997 =
	     _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[15] ?
	       _0_CONCAT_NOT_stage1_BITS_15_TO_8_EQ_0_2_CONCAT_ETC___d15[14:8] :
	       _theResult___fst__h1118 ;
  assign final_result_sign__h9204 = s3_y[15] ^ s3_x[15] ;
  assign integer_part__h1962 =
	     mantissa_with_implicit__h1955 >>
	     _15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_ETC___d223 ;
  assign integer_part__h2009 = mantissa_with_implicit__h1955 << x__h2087 ;
  assign man_result__h7843 =
	     { 2'd1,
	       IF_s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2__ETC___d836 } +
	     { 1'd0, smaller_m__h7784 } ;
  assign man_result__h7936 =
	     { 2'd1,
	       IF_s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2__ETC___d836 } -
	     { 1'd0, smaller_m__h7784 } ;
  assign man_result__h7938 =
	     { 1'd0, smaller_m__h7784 } -
	     { 2'd1,
	       IF_s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2__ETC___d836 } ;
  assign man_result__h8498 =
	     { 1'd0, bigger_m__h8439 } + { 1'd0, smaller_m__h8440 } ;
  assign man_result__h8610 =
	     { 1'd0, bigger_m__h8439 } - { 1'd0, smaller_m__h8440 } ;
  assign man_result__h8612 =
	     { 1'd0, smaller_m__h8440 } - { 1'd0, bigger_m__h8439 } ;
  assign mantissa_with_implicit__h1955 = { 1'b1, s1_zc1[6:0], 8'b0 } ;
  assign neg_b__h5476 =
	     { ~zn_sign__h5558,
	       IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825 } ;
  assign raw_exp_10__h4342 = exp_temp__h4341 - 10'd127 ;
  assign raw_exp_10__h6961 = exp_temp__h6960 - 10'd127 ;
  assign raw_exp_10__h9401 = exp_temp__h9400 - 10'd127 ;
  assign raw_exp_10__h993 = exp_temp__h992 - 10'd127 ;
  assign result__h4350 =
	     { 1'd0,
	       IF_IF_0_CONCAT_NOT_IF_127_MINUS_IF_IF_s1_zc1_1_ETC___d483 } ;
  assign result_raw__h7793 =
	     { result_sign__h7794,
	       IF_IF_s2_input_z_93_BIT_15_32_EQ_INV_NOT_s2_n__ETC___d940 } ;
  assign result_raw__h8449 =
	     { result_sign__h8450,
	       IF_IF_INV_IF_s2_input_z_93_BITS_14_TO_7_94_EQ__ETC___d1056 } ;
  assign result_sign__h7794 =
	     s2_input_z_93_BIT_15_32_EQ_INV_NOT_s2_n_91_EQ__ETC___d833 ?
	       result_sign__h7844 :
	       _theResult_____2_fst__h7871 ;
  assign result_sign__h7844 =
	     s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2_n_9_ETC___d834 ?
	       ~zn_sign__h5558 :
	       s2_input_z[15] ;
  assign result_sign__h7939 =
	     s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2_n_9_ETC___d834 ?
	       s2_input_z[15] :
	       ~zn_sign__h5558 ;
  assign result_sign__h8450 =
	     (~IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[15]) ?
	       _theResult_____2_fst__h8528 :
	       result_sign__h8499 ;
  assign result_sign__h8499 =
	     !IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d951 &&
	     ~IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[15] ;
  assign result_sign__h8613 =
	     IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d951 &&
	     ~IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[15] ;
  assign s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2_n_9_ETC___d834 =
	     s2_input_z[14:7] <
	     IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[14:7] ;
  assign s2_input_z_93_BIT_15_32_EQ_INV_NOT_s2_n_91_EQ__ETC___d833 =
	     s2_input_z[15] == ~zn_sign__h5558 ;
  assign shifted_exp___10__h1266 = shifted_exp___11__h1229 - 10'd1 ;
  assign shifted_exp___10__h4602 = shifted_exp___11__h4565 - 10'd1 ;
  assign shifted_exp___10__h7233 = shifted_exp___11__h7196 - 10'd1 ;
  assign shifted_exp___10__h9661 = shifted_exp___11__h9624 - 10'd1 ;
  assign shifted_exp___11__h1229 = shifted_exp___12__h1192 - 10'd1 ;
  assign shifted_exp___11__h4565 = shifted_exp___12__h4528 - 10'd1 ;
  assign shifted_exp___11__h7196 = shifted_exp___12__h7159 - 10'd1 ;
  assign shifted_exp___11__h9624 = shifted_exp___12__h9587 - 10'd1 ;
  assign shifted_exp___12__h1192 = shifted_exp___13__h1154 - 10'd1 ;
  assign shifted_exp___12__h4528 = shifted_exp___13__h4491 - 10'd1 ;
  assign shifted_exp___12__h7159 = shifted_exp___13__h7122 - 10'd1 ;
  assign shifted_exp___12__h9587 = shifted_exp___13__h9550 - 10'd1 ;
  assign shifted_exp___13__h1154 = raw_exp_10__h993 - 10'd1 ;
  assign shifted_exp___13__h4491 = raw_exp_10__h4342 - 10'd1 ;
  assign shifted_exp___13__h7122 = raw_exp_10__h6961 - 10'd1 ;
  assign shifted_exp___13__h9550 = raw_exp_10__h9401 - 10'd1 ;
  assign shifted_exp___1__h1599 = shifted_exp___2__h1562 - 10'd1 ;
  assign shifted_exp___1__h4935 = shifted_exp___2__h4898 - 10'd1 ;
  assign shifted_exp___1__h7566 = shifted_exp___2__h7529 - 10'd1 ;
  assign shifted_exp___1__h9994 = shifted_exp___2__h9957 - 10'd1 ;
  assign shifted_exp___2__h1562 = shifted_exp___3__h1525 - 10'd1 ;
  assign shifted_exp___2__h4898 = shifted_exp___3__h4861 - 10'd1 ;
  assign shifted_exp___2__h7529 = shifted_exp___3__h7492 - 10'd1 ;
  assign shifted_exp___2__h9957 = shifted_exp___3__h9920 - 10'd1 ;
  assign shifted_exp___3__h1525 = shifted_exp___4__h1488 - 10'd1 ;
  assign shifted_exp___3__h4861 = shifted_exp___4__h4824 - 10'd1 ;
  assign shifted_exp___3__h7492 = shifted_exp___4__h7455 - 10'd1 ;
  assign shifted_exp___3__h9920 = shifted_exp___4__h9883 - 10'd1 ;
  assign shifted_exp___4__h1488 = shifted_exp___5__h1451 - 10'd1 ;
  assign shifted_exp___4__h4824 = shifted_exp___5__h4787 - 10'd1 ;
  assign shifted_exp___4__h7455 = shifted_exp___5__h7418 - 10'd1 ;
  assign shifted_exp___4__h9883 = shifted_exp___5__h9846 - 10'd1 ;
  assign shifted_exp___5__h1451 = shifted_exp___6__h1414 - 10'd1 ;
  assign shifted_exp___5__h4787 = shifted_exp___6__h4750 - 10'd1 ;
  assign shifted_exp___5__h7418 = shifted_exp___6__h7381 - 10'd1 ;
  assign shifted_exp___5__h9846 = shifted_exp___6__h9809 - 10'd1 ;
  assign shifted_exp___6__h1414 = shifted_exp___7__h1377 - 10'd1 ;
  assign shifted_exp___6__h4750 = shifted_exp___7__h4713 - 10'd1 ;
  assign shifted_exp___6__h7381 = shifted_exp___7__h7344 - 10'd1 ;
  assign shifted_exp___6__h9809 = shifted_exp___7__h9772 - 10'd1 ;
  assign shifted_exp___7__h1377 = shifted_exp___8__h1340 - 10'd1 ;
  assign shifted_exp___7__h4713 = shifted_exp___8__h4676 - 10'd1 ;
  assign shifted_exp___7__h7344 = shifted_exp___8__h7307 - 10'd1 ;
  assign shifted_exp___7__h9772 = shifted_exp___8__h9735 - 10'd1 ;
  assign shifted_exp___8__h1340 = shifted_exp___9__h1303 - 10'd1 ;
  assign shifted_exp___8__h4676 = shifted_exp___9__h4639 - 10'd1 ;
  assign shifted_exp___8__h7307 = shifted_exp___9__h7270 - 10'd1 ;
  assign shifted_exp___8__h9735 = shifted_exp___9__h9698 - 10'd1 ;
  assign shifted_exp___9__h1303 = shifted_exp___10__h1266 - 10'd1 ;
  assign shifted_exp___9__h4639 = shifted_exp___10__h4602 - 10'd1 ;
  assign shifted_exp___9__h7270 = shifted_exp___10__h7233 - 10'd1 ;
  assign shifted_exp___9__h9698 = shifted_exp___10__h9661 - 10'd1 ;
  assign smaller_m__h7784 =
	     s2_input_z_93_BITS_14_TO_7_94_ULT_IF_IF_s2_n_9_ETC___d834 ?
	       smaller_m__h7865 :
	       smaller_m__h7861 ;
  assign smaller_m__h7861 =
	     { 1'b1,
	       IF_IF_s2_n_91_EQ_0_99_THEN_0_ELSE_IF_NOT_IF_IF_ETC___d825[6:0] } >>
	     exp_diff__h7859 ;
  assign smaller_m__h7865 = { 1'b1, s2_input_z[6:0] } >> exp_diff__h7863 ;
  assign smaller_m__h8440 =
	     IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d951 ?
	       smaller_m__h8516 :
	       smaller_m__h8520 ;
  assign smaller_m__h8516 = bigger_m__h8519 >> exp_diff__h8514 ;
  assign smaller_m__h8520 = 8'd128 >> exp_diff__h8518 ;
  assign tmp__h7790 =
	     s2_input_z_93_BIT_15_32_EQ_INV_NOT_s2_n_91_EQ__ETC___d833 ?
	       man_result__h7843 :
	       _theResult_____2_snd__h7872 ;
  assign tmp__h8446 =
	     (~IF_s2_input_z_93_BITS_14_TO_7_94_EQ_0_95_AND_s_ETC___d943[15]) ?
	       _theResult_____2_snd__h8529 :
	       man_result__h8498 ;
  assign x__h1999 =
	     _15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_ETC___d223 -
	     16'd1 ;
  assign x__h2087 =
	     -_15_MINUS_0_CONCAT_s1_zc1_15_BITS_14_TO_7_17_18_ETC___d223 ;
  assign x__h6799 =
	     16'd15 -
	     IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d606 ;
  assign zn_sign__h5558 =
	     (IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d607 ^
	      16'h8000) >
	     16'd32768 &&
	     (IF_IF_s2_n_91_BIT_15_01_THEN_NEG_s2_n_91_02_EL_ETC___d607 ^
	      16'h8000) <
	     16'd33023 &&
	     s2_n[15] ;
  always@(IF_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc_ETC___d259)
  begin
    case (IF_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc_ETC___d259[3:0])
      4'd0: b_exp__h2202 = 8'd127;
      4'd1,
      4'd2,
      4'd3,
      4'd4,
      4'd5,
      4'd6,
      4'd7,
      4'd8,
      4'd9,
      4'd10,
      4'd11,
      4'd12,
      4'd13,
      4'd14,
      4'd15:
	  b_exp__h2202 = 8'd126;
    endcase
  end
  always@(IF_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc_ETC___d259)
  begin
    case (IF_IF_IF_s1_zc1_15_EQ_0x0_16_OR_0_CONCAT_s1_zc_ETC___d259[3:0])
      4'd0: b_mant__h2203 = 7'd0;
      4'd1: b_mant__h2203 = 7'd117;
      4'd2: b_mant__h2203 = 7'd107;
      4'd3: b_mant__h2203 = 7'd97;
      4'd4: b_mant__h2203 = 7'd87;
      4'd5: b_mant__h2203 = 7'd78;
      4'd6: b_mant__h2203 = 7'd70;
      4'd7: b_mant__h2203 = 7'd61;
      4'd8: b_mant__h2203 = 7'd53;
      4'd9: b_mant__h2203 = 7'd46;
      4'd10: b_mant__h2203 = 7'd38;
      4'd11: b_mant__h2203 = 7'd31;
      4'd12: b_mant__h2203 = 7'd24;
      4'd13: b_mant__h2203 = 7'd18;
      4'd14: b_mant__h2203 = 7'd12;
      4'd15: b_mant__h2203 = 7'd6;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        result_valid <= `BSV_ASSIGNMENT_DELAY 1'd0;
	stage1 <= `BSV_ASSIGNMENT_DELAY 17'd0;
	stage2 <= `BSV_ASSIGNMENT_DELAY 17'd0;
	stage3 <= `BSV_ASSIGNMENT_DELAY 17'd0;
	stage4 <= `BSV_ASSIGNMENT_DELAY 17'd0;
      end
    else
      begin
        if (result_valid$EN)
	  result_valid <= `BSV_ASSIGNMENT_DELAY result_valid$D_IN;
	if (stage1$EN) stage1 <= `BSV_ASSIGNMENT_DELAY stage1$D_IN;
	if (stage2$EN) stage2 <= `BSV_ASSIGNMENT_DELAY stage2$D_IN;
	if (stage3$EN) stage3 <= `BSV_ASSIGNMENT_DELAY stage3$D_IN;
	if (stage4$EN) stage4 <= `BSV_ASSIGNMENT_DELAY stage4$D_IN;
      end
    if (result_data$EN) result_data <= `BSV_ASSIGNMENT_DELAY result_data$D_IN;
    if (s1_input_z$EN) s1_input_z <= `BSV_ASSIGNMENT_DELAY s1_input_z$D_IN;
    if (s1_zc1$EN) s1_zc1 <= `BSV_ASSIGNMENT_DELAY s1_zc1$D_IN;
    if (s2_input_z$EN) s2_input_z <= `BSV_ASSIGNMENT_DELAY s2_input_z$D_IN;
    if (s2_n$EN) s2_n <= `BSV_ASSIGNMENT_DELAY s2_n$D_IN;
    if (s2_y$EN) s2_y <= `BSV_ASSIGNMENT_DELAY s2_y$D_IN;
    if (s3_n$EN) s3_n <= `BSV_ASSIGNMENT_DELAY s3_n$D_IN;
    if (s3_x$EN) s3_x <= `BSV_ASSIGNMENT_DELAY s3_x$D_IN;
    if (s3_y$EN) s3_y <= `BSV_ASSIGNMENT_DELAY s3_y$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    result_data = 16'hAAAA;
    result_valid = 1'h0;
    s1_input_z = 16'hAAAA;
    s1_zc1 = 16'hAAAA;
    s2_input_z = 16'hAAAA;
    s2_n = 16'hAAAA;
    s2_y = 16'hAAAA;
    s3_n = 16'hAAAA;
    s3_x = 16'hAAAA;
    s3_y = 16'hAAAA;
    stage1 = 17'h0AAAA;
    stage2 = 17'h0AAAA;
    stage3 = 17'h0AAAA;
    stage4 = 17'h0AAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkBF16Exp

