//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e9)
//
// On Fri Nov 14 08:26:12 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb_COP(CLK,
		RST_N);
  input  CLK;
  input  RST_N;

  // register cycle
  reg [31 : 0] cycle;
  wire [31 : 0] cycle$D_IN;
  wire cycle$EN;

  // register started
  reg started;
  wire started$D_IN, started$EN;

  // ports of submodule cop
  wire cop$EN_start_computation,
       cop$RDY_start_computation,
       cop$computation_done;

  // rule scheduling signals
  wire WILL_FIRE_RL_check_done, WILL_FIRE_RL_start_cop, WILL_FIRE_RL_timeout;

  // submodule cop
  mkCOP cop(.CLK(CLK),
	    .RST_N(RST_N),
	    .EN_start_computation(cop$EN_start_computation),
	    .RDY_start_computation(cop$RDY_start_computation),
	    .get_result_k(),
	    .RDY_get_result_k(),
	    .get_output(),
	    .RDY_get_output(),
	    .computation_done(cop$computation_done),
	    .RDY_computation_done());

  // rule RL_start_cop
  assign WILL_FIRE_RL_start_cop =
	     cop$RDY_start_computation && !started && cycle == 32'd5 ;

  // rule RL_check_done
  assign WILL_FIRE_RL_check_done = started && cop$computation_done ;

  // rule RL_timeout
  assign WILL_FIRE_RL_timeout = cycle > 32'd200000 ;

  // register cycle
  assign cycle$D_IN = cycle + 32'd1 ;
  assign cycle$EN = 1'd1 ;

  // register started
  assign started$D_IN = 1'd1 ;
  assign started$EN = WILL_FIRE_RL_start_cop ;

  // submodule cop
  assign cop$EN_start_computation = WILL_FIRE_RL_start_cop ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        cycle <= `BSV_ASSIGNMENT_DELAY 32'd0;
	started <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (cycle$EN) cycle <= `BSV_ASSIGNMENT_DELAY cycle$D_IN;
	if (started$EN) started <= `BSV_ASSIGNMENT_DELAY started$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    cycle = 32'hAAAAAAAA;
    started = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_start_cop)
	$display("[Cycle %0d] Testbench: Started COP computation", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_start_cop)
	$display("[Cycle %0d] TB: Weights will be loaded from BRAM internally",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("[Cycle %0d] Total cycles taken: %0d", cycle, cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("\n[Cycle %0d] Testbench: Finishing simulation", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done) $finish(32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_timeout)
	$display("[Cycle %0d] ERROR: Timeout! Computation didn't complete.",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE) if (WILL_FIRE_RL_timeout) $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // mkTb_COP

