//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e9)
//
// On Fri Nov 14 08:21:54 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// getMax                         O    16
// RDY_getMax                     O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// getMax_a                       I    16
// getMax_b                       I    16
//
// Combinational paths from inputs to outputs:
//   (getMax_a, getMax_b) -> getMax
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTorchMaximum(CLK,
		      RST_N,

		      getMax_a,
		      getMax_b,
		      getMax,
		      RDY_getMax);
  input  CLK;
  input  RST_N;

  // value method getMax
  input  [15 : 0] getMax_a;
  input  [15 : 0] getMax_b;
  output [15 : 0] getMax;
  output RDY_getMax;

  // signals for module outputs
  wire [15 : 0] getMax;
  wire RDY_getMax;

  // remaining internal signals
  wire [15 : 0] IF_getMax_a_BIT_15_AND_getMax_b_BIT_15_THEN_IF_ETC___d11;
  wire getMax_a_ULE_getMax_b___d6;

  // value method getMax
  assign getMax =
	     (!getMax_a[15] && !getMax_b[15]) ?
	       (getMax_a_ULE_getMax_b___d6 ? getMax_b : getMax_a) :
	       IF_getMax_a_BIT_15_AND_getMax_b_BIT_15_THEN_IF_ETC___d11 ;
  assign RDY_getMax = 1'd1 ;

  // remaining internal signals
  assign IF_getMax_a_BIT_15_AND_getMax_b_BIT_15_THEN_IF_ETC___d11 =
	     (getMax_a[15] && getMax_b[15]) ?
	       (getMax_a_ULE_getMax_b___d6 ? getMax_a : getMax_b) :
	       (getMax_a[15] ? getMax_b : getMax_a) ;
  assign getMax_a_ULE_getMax_b___d6 = getMax_a <= getMax_b ;
endmodule  // mkTorchMaximum

