//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e9)
//
// On Fri Nov 14 08:21:54 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// findMax                        O   512
// RDY_findMax                    O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// findMax_vec_a                  I   512
// findMax_vec_b                  I   512
//
// Combinational paths from inputs to outputs:
//   (findMax_vec_a, findMax_vec_b) -> findMax
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTorchMaximum32(CLK,
			RST_N,

			findMax_vec_a,
			findMax_vec_b,
			findMax,
			RDY_findMax);
  input  CLK;
  input  RST_N;

  // value method findMax
  input  [511 : 0] findMax_vec_a;
  input  [511 : 0] findMax_vec_b;
  output [511 : 0] findMax;
  output RDY_findMax;

  // signals for module outputs
  wire [511 : 0] findMax;
  wire RDY_findMax;

  // remaining internal signals
  wire [15 : 0] IF_NOT_findMax_vec_a_BIT_111_63_64_AND_NOT_fin_ETC___d376,
		IF_NOT_findMax_vec_a_BIT_127_49_50_AND_NOT_fin_ETC___d362,
		IF_NOT_findMax_vec_a_BIT_143_34_35_AND_NOT_fin_ETC___d347,
		IF_NOT_findMax_vec_a_BIT_159_20_21_AND_NOT_fin_ETC___d333,
		IF_NOT_findMax_vec_a_BIT_15_50_51_AND_NOT_find_ETC___d463,
		IF_NOT_findMax_vec_a_BIT_175_05_06_AND_NOT_fin_ETC___d318,
		IF_NOT_findMax_vec_a_BIT_191_91_92_AND_NOT_fin_ETC___d304,
		IF_NOT_findMax_vec_a_BIT_207_76_77_AND_NOT_fin_ETC___d289,
		IF_NOT_findMax_vec_a_BIT_223_62_63_AND_NOT_fin_ETC___d275,
		IF_NOT_findMax_vec_a_BIT_239_47_48_AND_NOT_fin_ETC___d260,
		IF_NOT_findMax_vec_a_BIT_255_33_34_AND_NOT_fin_ETC___d246,
		IF_NOT_findMax_vec_a_BIT_271_18_19_AND_NOT_fin_ETC___d231,
		IF_NOT_findMax_vec_a_BIT_287_04_05_AND_NOT_fin_ETC___d217,
		IF_NOT_findMax_vec_a_BIT_303_89_90_AND_NOT_fin_ETC___d202,
		IF_NOT_findMax_vec_a_BIT_319_75_76_AND_NOT_fin_ETC___d188,
		IF_NOT_findMax_vec_a_BIT_31_36_37_AND_NOT_find_ETC___d449,
		IF_NOT_findMax_vec_a_BIT_335_60_61_AND_NOT_fin_ETC___d173,
		IF_NOT_findMax_vec_a_BIT_351_46_47_AND_NOT_fin_ETC___d159,
		IF_NOT_findMax_vec_a_BIT_367_31_32_AND_NOT_fin_ETC___d144,
		IF_NOT_findMax_vec_a_BIT_383_17_18_AND_NOT_fin_ETC___d130,
		IF_NOT_findMax_vec_a_BIT_399_02_03_AND_NOT_fin_ETC___d115,
		IF_NOT_findMax_vec_a_BIT_415_8_9_AND_NOT_findM_ETC___d101,
		IF_NOT_findMax_vec_a_BIT_431_3_4_AND_NOT_findM_ETC___d86,
		IF_NOT_findMax_vec_a_BIT_447_9_0_AND_NOT_findM_ETC___d72,
		IF_NOT_findMax_vec_a_BIT_463_4_5_AND_NOT_findM_ETC___d57,
		IF_NOT_findMax_vec_a_BIT_479_0_1_AND_NOT_findM_ETC___d43,
		IF_NOT_findMax_vec_a_BIT_47_21_22_AND_NOT_find_ETC___d434,
		IF_NOT_findMax_vec_a_BIT_495_5_6_AND_NOT_findM_ETC___d28,
		IF_NOT_findMax_vec_a_BIT_511_AND_NOT_findMax_v_ETC___d14,
		IF_NOT_findMax_vec_a_BIT_63_07_08_AND_NOT_find_ETC___d420,
		IF_NOT_findMax_vec_a_BIT_79_92_93_AND_NOT_find_ETC___d405,
		IF_NOT_findMax_vec_a_BIT_95_78_79_AND_NOT_find_ETC___d391,
		IF_findMax_vec_a_BIT_111_63_AND_findMax_vec_b__ETC___d375,
		IF_findMax_vec_a_BIT_127_49_AND_findMax_vec_b__ETC___d361,
		IF_findMax_vec_a_BIT_143_34_AND_findMax_vec_b__ETC___d346,
		IF_findMax_vec_a_BIT_159_20_AND_findMax_vec_b__ETC___d332,
		IF_findMax_vec_a_BIT_15_50_AND_findMax_vec_b_B_ETC___d462,
		IF_findMax_vec_a_BIT_175_05_AND_findMax_vec_b__ETC___d317,
		IF_findMax_vec_a_BIT_191_91_AND_findMax_vec_b__ETC___d303,
		IF_findMax_vec_a_BIT_207_76_AND_findMax_vec_b__ETC___d288,
		IF_findMax_vec_a_BIT_223_62_AND_findMax_vec_b__ETC___d274,
		IF_findMax_vec_a_BIT_239_47_AND_findMax_vec_b__ETC___d259,
		IF_findMax_vec_a_BIT_255_33_AND_findMax_vec_b__ETC___d245,
		IF_findMax_vec_a_BIT_271_18_AND_findMax_vec_b__ETC___d230,
		IF_findMax_vec_a_BIT_287_04_AND_findMax_vec_b__ETC___d216,
		IF_findMax_vec_a_BIT_303_89_AND_findMax_vec_b__ETC___d201,
		IF_findMax_vec_a_BIT_319_75_AND_findMax_vec_b__ETC___d187,
		IF_findMax_vec_a_BIT_31_36_AND_findMax_vec_b_B_ETC___d448,
		IF_findMax_vec_a_BIT_335_60_AND_findMax_vec_b__ETC___d172,
		IF_findMax_vec_a_BIT_351_46_AND_findMax_vec_b__ETC___d158,
		IF_findMax_vec_a_BIT_367_31_AND_findMax_vec_b__ETC___d143,
		IF_findMax_vec_a_BIT_383_17_AND_findMax_vec_b__ETC___d129,
		IF_findMax_vec_a_BIT_399_02_AND_findMax_vec_b__ETC___d114,
		IF_findMax_vec_a_BIT_415_8_AND_findMax_vec_b_B_ETC___d100,
		IF_findMax_vec_a_BIT_431_3_AND_findMax_vec_b_B_ETC___d85,
		IF_findMax_vec_a_BIT_447_9_AND_findMax_vec_b_B_ETC___d71,
		IF_findMax_vec_a_BIT_463_4_AND_findMax_vec_b_B_ETC___d56,
		IF_findMax_vec_a_BIT_479_0_AND_findMax_vec_b_B_ETC___d42,
		IF_findMax_vec_a_BIT_47_21_AND_findMax_vec_b_B_ETC___d433,
		IF_findMax_vec_a_BIT_495_5_AND_findMax_vec_b_B_ETC___d27,
		IF_findMax_vec_a_BIT_511_AND_findMax_vec_b_BIT_ETC___d13,
		IF_findMax_vec_a_BIT_63_07_AND_findMax_vec_b_B_ETC___d419,
		IF_findMax_vec_a_BIT_79_92_AND_findMax_vec_b_B_ETC___d404,
		IF_findMax_vec_a_BIT_95_78_AND_findMax_vec_b_B_ETC___d390;
  wire findMax_vec_a_BITS_111_TO_96_68_ULE_findMax_ve_ETC___d370,
       findMax_vec_a_BITS_127_TO_112_54_ULE_findMax_v_ETC___d356,
       findMax_vec_a_BITS_143_TO_128_39_ULE_findMax_v_ETC___d341,
       findMax_vec_a_BITS_159_TO_144_25_ULE_findMax_v_ETC___d327,
       findMax_vec_a_BITS_15_TO_0_55_ULE_findMax_vec__ETC___d457,
       findMax_vec_a_BITS_175_TO_160_10_ULE_findMax_v_ETC___d312,
       findMax_vec_a_BITS_191_TO_176_96_ULE_findMax_v_ETC___d298,
       findMax_vec_a_BITS_207_TO_192_81_ULE_findMax_v_ETC___d283,
       findMax_vec_a_BITS_223_TO_208_67_ULE_findMax_v_ETC___d269,
       findMax_vec_a_BITS_239_TO_224_52_ULE_findMax_v_ETC___d254,
       findMax_vec_a_BITS_255_TO_240_38_ULE_findMax_v_ETC___d240,
       findMax_vec_a_BITS_271_TO_256_23_ULE_findMax_v_ETC___d225,
       findMax_vec_a_BITS_287_TO_272_09_ULE_findMax_v_ETC___d211,
       findMax_vec_a_BITS_303_TO_288_94_ULE_findMax_v_ETC___d196,
       findMax_vec_a_BITS_319_TO_304_80_ULE_findMax_v_ETC___d182,
       findMax_vec_a_BITS_31_TO_16_41_ULE_findMax_vec_ETC___d443,
       findMax_vec_a_BITS_335_TO_320_65_ULE_findMax_v_ETC___d167,
       findMax_vec_a_BITS_351_TO_336_51_ULE_findMax_v_ETC___d153,
       findMax_vec_a_BITS_367_TO_352_36_ULE_findMax_v_ETC___d138,
       findMax_vec_a_BITS_383_TO_368_22_ULE_findMax_v_ETC___d124,
       findMax_vec_a_BITS_399_TO_384_07_ULE_findMax_v_ETC___d109,
       findMax_vec_a_BITS_415_TO_400_3_ULE_findMax_ve_ETC___d95,
       findMax_vec_a_BITS_431_TO_416_8_ULE_findMax_ve_ETC___d80,
       findMax_vec_a_BITS_447_TO_432_4_ULE_findMax_ve_ETC___d66,
       findMax_vec_a_BITS_463_TO_448_9_ULE_findMax_ve_ETC___d51,
       findMax_vec_a_BITS_479_TO_464_5_ULE_findMax_ve_ETC___d37,
       findMax_vec_a_BITS_47_TO_32_26_ULE_findMax_vec_ETC___d428,
       findMax_vec_a_BITS_495_TO_480_0_ULE_findMax_ve_ETC___d22,
       findMax_vec_a_BITS_511_TO_496_ULE_findMax_vec__ETC___d8,
       findMax_vec_a_BITS_63_TO_48_12_ULE_findMax_vec_ETC___d414,
       findMax_vec_a_BITS_79_TO_64_97_ULE_findMax_vec_ETC___d399,
       findMax_vec_a_BITS_95_TO_80_83_ULE_findMax_vec_ETC___d385;

  // value method findMax
  assign findMax =
	     { IF_NOT_findMax_vec_a_BIT_511_AND_NOT_findMax_v_ETC___d14,
	       IF_NOT_findMax_vec_a_BIT_495_5_6_AND_NOT_findM_ETC___d28,
	       IF_NOT_findMax_vec_a_BIT_479_0_1_AND_NOT_findM_ETC___d43,
	       IF_NOT_findMax_vec_a_BIT_463_4_5_AND_NOT_findM_ETC___d57,
	       IF_NOT_findMax_vec_a_BIT_447_9_0_AND_NOT_findM_ETC___d72,
	       IF_NOT_findMax_vec_a_BIT_431_3_4_AND_NOT_findM_ETC___d86,
	       IF_NOT_findMax_vec_a_BIT_415_8_9_AND_NOT_findM_ETC___d101,
	       IF_NOT_findMax_vec_a_BIT_399_02_03_AND_NOT_fin_ETC___d115,
	       IF_NOT_findMax_vec_a_BIT_383_17_18_AND_NOT_fin_ETC___d130,
	       IF_NOT_findMax_vec_a_BIT_367_31_32_AND_NOT_fin_ETC___d144,
	       IF_NOT_findMax_vec_a_BIT_351_46_47_AND_NOT_fin_ETC___d159,
	       IF_NOT_findMax_vec_a_BIT_335_60_61_AND_NOT_fin_ETC___d173,
	       IF_NOT_findMax_vec_a_BIT_319_75_76_AND_NOT_fin_ETC___d188,
	       IF_NOT_findMax_vec_a_BIT_303_89_90_AND_NOT_fin_ETC___d202,
	       IF_NOT_findMax_vec_a_BIT_287_04_05_AND_NOT_fin_ETC___d217,
	       IF_NOT_findMax_vec_a_BIT_271_18_19_AND_NOT_fin_ETC___d231,
	       IF_NOT_findMax_vec_a_BIT_255_33_34_AND_NOT_fin_ETC___d246,
	       IF_NOT_findMax_vec_a_BIT_239_47_48_AND_NOT_fin_ETC___d260,
	       IF_NOT_findMax_vec_a_BIT_223_62_63_AND_NOT_fin_ETC___d275,
	       IF_NOT_findMax_vec_a_BIT_207_76_77_AND_NOT_fin_ETC___d289,
	       IF_NOT_findMax_vec_a_BIT_191_91_92_AND_NOT_fin_ETC___d304,
	       IF_NOT_findMax_vec_a_BIT_175_05_06_AND_NOT_fin_ETC___d318,
	       IF_NOT_findMax_vec_a_BIT_159_20_21_AND_NOT_fin_ETC___d333,
	       IF_NOT_findMax_vec_a_BIT_143_34_35_AND_NOT_fin_ETC___d347,
	       IF_NOT_findMax_vec_a_BIT_127_49_50_AND_NOT_fin_ETC___d362,
	       IF_NOT_findMax_vec_a_BIT_111_63_64_AND_NOT_fin_ETC___d376,
	       IF_NOT_findMax_vec_a_BIT_95_78_79_AND_NOT_find_ETC___d391,
	       IF_NOT_findMax_vec_a_BIT_79_92_93_AND_NOT_find_ETC___d405,
	       IF_NOT_findMax_vec_a_BIT_63_07_08_AND_NOT_find_ETC___d420,
	       IF_NOT_findMax_vec_a_BIT_47_21_22_AND_NOT_find_ETC___d434,
	       IF_NOT_findMax_vec_a_BIT_31_36_37_AND_NOT_find_ETC___d449,
	       IF_NOT_findMax_vec_a_BIT_15_50_51_AND_NOT_find_ETC___d463 } ;
  assign RDY_findMax = 1'd1 ;

  // remaining internal signals
  assign IF_NOT_findMax_vec_a_BIT_111_63_64_AND_NOT_fin_ETC___d376 =
	     (!findMax_vec_a[111] && !findMax_vec_b[111]) ?
	       (findMax_vec_a_BITS_111_TO_96_68_ULE_findMax_ve_ETC___d370 ?
		  findMax_vec_b[111:96] :
		  findMax_vec_a[111:96]) :
	       IF_findMax_vec_a_BIT_111_63_AND_findMax_vec_b__ETC___d375 ;
  assign IF_NOT_findMax_vec_a_BIT_127_49_50_AND_NOT_fin_ETC___d362 =
	     (!findMax_vec_a[127] && !findMax_vec_b[127]) ?
	       (findMax_vec_a_BITS_127_TO_112_54_ULE_findMax_v_ETC___d356 ?
		  findMax_vec_b[127:112] :
		  findMax_vec_a[127:112]) :
	       IF_findMax_vec_a_BIT_127_49_AND_findMax_vec_b__ETC___d361 ;
  assign IF_NOT_findMax_vec_a_BIT_143_34_35_AND_NOT_fin_ETC___d347 =
	     (!findMax_vec_a[143] && !findMax_vec_b[143]) ?
	       (findMax_vec_a_BITS_143_TO_128_39_ULE_findMax_v_ETC___d341 ?
		  findMax_vec_b[143:128] :
		  findMax_vec_a[143:128]) :
	       IF_findMax_vec_a_BIT_143_34_AND_findMax_vec_b__ETC___d346 ;
  assign IF_NOT_findMax_vec_a_BIT_159_20_21_AND_NOT_fin_ETC___d333 =
	     (!findMax_vec_a[159] && !findMax_vec_b[159]) ?
	       (findMax_vec_a_BITS_159_TO_144_25_ULE_findMax_v_ETC___d327 ?
		  findMax_vec_b[159:144] :
		  findMax_vec_a[159:144]) :
	       IF_findMax_vec_a_BIT_159_20_AND_findMax_vec_b__ETC___d332 ;
  assign IF_NOT_findMax_vec_a_BIT_15_50_51_AND_NOT_find_ETC___d463 =
	     (!findMax_vec_a[15] && !findMax_vec_b[15]) ?
	       (findMax_vec_a_BITS_15_TO_0_55_ULE_findMax_vec__ETC___d457 ?
		  findMax_vec_b[15:0] :
		  findMax_vec_a[15:0]) :
	       IF_findMax_vec_a_BIT_15_50_AND_findMax_vec_b_B_ETC___d462 ;
  assign IF_NOT_findMax_vec_a_BIT_175_05_06_AND_NOT_fin_ETC___d318 =
	     (!findMax_vec_a[175] && !findMax_vec_b[175]) ?
	       (findMax_vec_a_BITS_175_TO_160_10_ULE_findMax_v_ETC___d312 ?
		  findMax_vec_b[175:160] :
		  findMax_vec_a[175:160]) :
	       IF_findMax_vec_a_BIT_175_05_AND_findMax_vec_b__ETC___d317 ;
  assign IF_NOT_findMax_vec_a_BIT_191_91_92_AND_NOT_fin_ETC___d304 =
	     (!findMax_vec_a[191] && !findMax_vec_b[191]) ?
	       (findMax_vec_a_BITS_191_TO_176_96_ULE_findMax_v_ETC___d298 ?
		  findMax_vec_b[191:176] :
		  findMax_vec_a[191:176]) :
	       IF_findMax_vec_a_BIT_191_91_AND_findMax_vec_b__ETC___d303 ;
  assign IF_NOT_findMax_vec_a_BIT_207_76_77_AND_NOT_fin_ETC___d289 =
	     (!findMax_vec_a[207] && !findMax_vec_b[207]) ?
	       (findMax_vec_a_BITS_207_TO_192_81_ULE_findMax_v_ETC___d283 ?
		  findMax_vec_b[207:192] :
		  findMax_vec_a[207:192]) :
	       IF_findMax_vec_a_BIT_207_76_AND_findMax_vec_b__ETC___d288 ;
  assign IF_NOT_findMax_vec_a_BIT_223_62_63_AND_NOT_fin_ETC___d275 =
	     (!findMax_vec_a[223] && !findMax_vec_b[223]) ?
	       (findMax_vec_a_BITS_223_TO_208_67_ULE_findMax_v_ETC___d269 ?
		  findMax_vec_b[223:208] :
		  findMax_vec_a[223:208]) :
	       IF_findMax_vec_a_BIT_223_62_AND_findMax_vec_b__ETC___d274 ;
  assign IF_NOT_findMax_vec_a_BIT_239_47_48_AND_NOT_fin_ETC___d260 =
	     (!findMax_vec_a[239] && !findMax_vec_b[239]) ?
	       (findMax_vec_a_BITS_239_TO_224_52_ULE_findMax_v_ETC___d254 ?
		  findMax_vec_b[239:224] :
		  findMax_vec_a[239:224]) :
	       IF_findMax_vec_a_BIT_239_47_AND_findMax_vec_b__ETC___d259 ;
  assign IF_NOT_findMax_vec_a_BIT_255_33_34_AND_NOT_fin_ETC___d246 =
	     (!findMax_vec_a[255] && !findMax_vec_b[255]) ?
	       (findMax_vec_a_BITS_255_TO_240_38_ULE_findMax_v_ETC___d240 ?
		  findMax_vec_b[255:240] :
		  findMax_vec_a[255:240]) :
	       IF_findMax_vec_a_BIT_255_33_AND_findMax_vec_b__ETC___d245 ;
  assign IF_NOT_findMax_vec_a_BIT_271_18_19_AND_NOT_fin_ETC___d231 =
	     (!findMax_vec_a[271] && !findMax_vec_b[271]) ?
	       (findMax_vec_a_BITS_271_TO_256_23_ULE_findMax_v_ETC___d225 ?
		  findMax_vec_b[271:256] :
		  findMax_vec_a[271:256]) :
	       IF_findMax_vec_a_BIT_271_18_AND_findMax_vec_b__ETC___d230 ;
  assign IF_NOT_findMax_vec_a_BIT_287_04_05_AND_NOT_fin_ETC___d217 =
	     (!findMax_vec_a[287] && !findMax_vec_b[287]) ?
	       (findMax_vec_a_BITS_287_TO_272_09_ULE_findMax_v_ETC___d211 ?
		  findMax_vec_b[287:272] :
		  findMax_vec_a[287:272]) :
	       IF_findMax_vec_a_BIT_287_04_AND_findMax_vec_b__ETC___d216 ;
  assign IF_NOT_findMax_vec_a_BIT_303_89_90_AND_NOT_fin_ETC___d202 =
	     (!findMax_vec_a[303] && !findMax_vec_b[303]) ?
	       (findMax_vec_a_BITS_303_TO_288_94_ULE_findMax_v_ETC___d196 ?
		  findMax_vec_b[303:288] :
		  findMax_vec_a[303:288]) :
	       IF_findMax_vec_a_BIT_303_89_AND_findMax_vec_b__ETC___d201 ;
  assign IF_NOT_findMax_vec_a_BIT_319_75_76_AND_NOT_fin_ETC___d188 =
	     (!findMax_vec_a[319] && !findMax_vec_b[319]) ?
	       (findMax_vec_a_BITS_319_TO_304_80_ULE_findMax_v_ETC___d182 ?
		  findMax_vec_b[319:304] :
		  findMax_vec_a[319:304]) :
	       IF_findMax_vec_a_BIT_319_75_AND_findMax_vec_b__ETC___d187 ;
  assign IF_NOT_findMax_vec_a_BIT_31_36_37_AND_NOT_find_ETC___d449 =
	     (!findMax_vec_a[31] && !findMax_vec_b[31]) ?
	       (findMax_vec_a_BITS_31_TO_16_41_ULE_findMax_vec_ETC___d443 ?
		  findMax_vec_b[31:16] :
		  findMax_vec_a[31:16]) :
	       IF_findMax_vec_a_BIT_31_36_AND_findMax_vec_b_B_ETC___d448 ;
  assign IF_NOT_findMax_vec_a_BIT_335_60_61_AND_NOT_fin_ETC___d173 =
	     (!findMax_vec_a[335] && !findMax_vec_b[335]) ?
	       (findMax_vec_a_BITS_335_TO_320_65_ULE_findMax_v_ETC___d167 ?
		  findMax_vec_b[335:320] :
		  findMax_vec_a[335:320]) :
	       IF_findMax_vec_a_BIT_335_60_AND_findMax_vec_b__ETC___d172 ;
  assign IF_NOT_findMax_vec_a_BIT_351_46_47_AND_NOT_fin_ETC___d159 =
	     (!findMax_vec_a[351] && !findMax_vec_b[351]) ?
	       (findMax_vec_a_BITS_351_TO_336_51_ULE_findMax_v_ETC___d153 ?
		  findMax_vec_b[351:336] :
		  findMax_vec_a[351:336]) :
	       IF_findMax_vec_a_BIT_351_46_AND_findMax_vec_b__ETC___d158 ;
  assign IF_NOT_findMax_vec_a_BIT_367_31_32_AND_NOT_fin_ETC___d144 =
	     (!findMax_vec_a[367] && !findMax_vec_b[367]) ?
	       (findMax_vec_a_BITS_367_TO_352_36_ULE_findMax_v_ETC___d138 ?
		  findMax_vec_b[367:352] :
		  findMax_vec_a[367:352]) :
	       IF_findMax_vec_a_BIT_367_31_AND_findMax_vec_b__ETC___d143 ;
  assign IF_NOT_findMax_vec_a_BIT_383_17_18_AND_NOT_fin_ETC___d130 =
	     (!findMax_vec_a[383] && !findMax_vec_b[383]) ?
	       (findMax_vec_a_BITS_383_TO_368_22_ULE_findMax_v_ETC___d124 ?
		  findMax_vec_b[383:368] :
		  findMax_vec_a[383:368]) :
	       IF_findMax_vec_a_BIT_383_17_AND_findMax_vec_b__ETC___d129 ;
  assign IF_NOT_findMax_vec_a_BIT_399_02_03_AND_NOT_fin_ETC___d115 =
	     (!findMax_vec_a[399] && !findMax_vec_b[399]) ?
	       (findMax_vec_a_BITS_399_TO_384_07_ULE_findMax_v_ETC___d109 ?
		  findMax_vec_b[399:384] :
		  findMax_vec_a[399:384]) :
	       IF_findMax_vec_a_BIT_399_02_AND_findMax_vec_b__ETC___d114 ;
  assign IF_NOT_findMax_vec_a_BIT_415_8_9_AND_NOT_findM_ETC___d101 =
	     (!findMax_vec_a[415] && !findMax_vec_b[415]) ?
	       (findMax_vec_a_BITS_415_TO_400_3_ULE_findMax_ve_ETC___d95 ?
		  findMax_vec_b[415:400] :
		  findMax_vec_a[415:400]) :
	       IF_findMax_vec_a_BIT_415_8_AND_findMax_vec_b_B_ETC___d100 ;
  assign IF_NOT_findMax_vec_a_BIT_431_3_4_AND_NOT_findM_ETC___d86 =
	     (!findMax_vec_a[431] && !findMax_vec_b[431]) ?
	       (findMax_vec_a_BITS_431_TO_416_8_ULE_findMax_ve_ETC___d80 ?
		  findMax_vec_b[431:416] :
		  findMax_vec_a[431:416]) :
	       IF_findMax_vec_a_BIT_431_3_AND_findMax_vec_b_B_ETC___d85 ;
  assign IF_NOT_findMax_vec_a_BIT_447_9_0_AND_NOT_findM_ETC___d72 =
	     (!findMax_vec_a[447] && !findMax_vec_b[447]) ?
	       (findMax_vec_a_BITS_447_TO_432_4_ULE_findMax_ve_ETC___d66 ?
		  findMax_vec_b[447:432] :
		  findMax_vec_a[447:432]) :
	       IF_findMax_vec_a_BIT_447_9_AND_findMax_vec_b_B_ETC___d71 ;
  assign IF_NOT_findMax_vec_a_BIT_463_4_5_AND_NOT_findM_ETC___d57 =
	     (!findMax_vec_a[463] && !findMax_vec_b[463]) ?
	       (findMax_vec_a_BITS_463_TO_448_9_ULE_findMax_ve_ETC___d51 ?
		  findMax_vec_b[463:448] :
		  findMax_vec_a[463:448]) :
	       IF_findMax_vec_a_BIT_463_4_AND_findMax_vec_b_B_ETC___d56 ;
  assign IF_NOT_findMax_vec_a_BIT_479_0_1_AND_NOT_findM_ETC___d43 =
	     (!findMax_vec_a[479] && !findMax_vec_b[479]) ?
	       (findMax_vec_a_BITS_479_TO_464_5_ULE_findMax_ve_ETC___d37 ?
		  findMax_vec_b[479:464] :
		  findMax_vec_a[479:464]) :
	       IF_findMax_vec_a_BIT_479_0_AND_findMax_vec_b_B_ETC___d42 ;
  assign IF_NOT_findMax_vec_a_BIT_47_21_22_AND_NOT_find_ETC___d434 =
	     (!findMax_vec_a[47] && !findMax_vec_b[47]) ?
	       (findMax_vec_a_BITS_47_TO_32_26_ULE_findMax_vec_ETC___d428 ?
		  findMax_vec_b[47:32] :
		  findMax_vec_a[47:32]) :
	       IF_findMax_vec_a_BIT_47_21_AND_findMax_vec_b_B_ETC___d433 ;
  assign IF_NOT_findMax_vec_a_BIT_495_5_6_AND_NOT_findM_ETC___d28 =
	     (!findMax_vec_a[495] && !findMax_vec_b[495]) ?
	       (findMax_vec_a_BITS_495_TO_480_0_ULE_findMax_ve_ETC___d22 ?
		  findMax_vec_b[495:480] :
		  findMax_vec_a[495:480]) :
	       IF_findMax_vec_a_BIT_495_5_AND_findMax_vec_b_B_ETC___d27 ;
  assign IF_NOT_findMax_vec_a_BIT_511_AND_NOT_findMax_v_ETC___d14 =
	     (!findMax_vec_a[511] && !findMax_vec_b[511]) ?
	       (findMax_vec_a_BITS_511_TO_496_ULE_findMax_vec__ETC___d8 ?
		  findMax_vec_b[511:496] :
		  findMax_vec_a[511:496]) :
	       IF_findMax_vec_a_BIT_511_AND_findMax_vec_b_BIT_ETC___d13 ;
  assign IF_NOT_findMax_vec_a_BIT_63_07_08_AND_NOT_find_ETC___d420 =
	     (!findMax_vec_a[63] && !findMax_vec_b[63]) ?
	       (findMax_vec_a_BITS_63_TO_48_12_ULE_findMax_vec_ETC___d414 ?
		  findMax_vec_b[63:48] :
		  findMax_vec_a[63:48]) :
	       IF_findMax_vec_a_BIT_63_07_AND_findMax_vec_b_B_ETC___d419 ;
  assign IF_NOT_findMax_vec_a_BIT_79_92_93_AND_NOT_find_ETC___d405 =
	     (!findMax_vec_a[79] && !findMax_vec_b[79]) ?
	       (findMax_vec_a_BITS_79_TO_64_97_ULE_findMax_vec_ETC___d399 ?
		  findMax_vec_b[79:64] :
		  findMax_vec_a[79:64]) :
	       IF_findMax_vec_a_BIT_79_92_AND_findMax_vec_b_B_ETC___d404 ;
  assign IF_NOT_findMax_vec_a_BIT_95_78_79_AND_NOT_find_ETC___d391 =
	     (!findMax_vec_a[95] && !findMax_vec_b[95]) ?
	       (findMax_vec_a_BITS_95_TO_80_83_ULE_findMax_vec_ETC___d385 ?
		  findMax_vec_b[95:80] :
		  findMax_vec_a[95:80]) :
	       IF_findMax_vec_a_BIT_95_78_AND_findMax_vec_b_B_ETC___d390 ;
  assign IF_findMax_vec_a_BIT_111_63_AND_findMax_vec_b__ETC___d375 =
	     (findMax_vec_a[111] && findMax_vec_b[111]) ?
	       (findMax_vec_a_BITS_111_TO_96_68_ULE_findMax_ve_ETC___d370 ?
		  findMax_vec_a[111:96] :
		  findMax_vec_b[111:96]) :
	       (findMax_vec_a[111] ?
		  findMax_vec_b[111:96] :
		  findMax_vec_a[111:96]) ;
  assign IF_findMax_vec_a_BIT_127_49_AND_findMax_vec_b__ETC___d361 =
	     (findMax_vec_a[127] && findMax_vec_b[127]) ?
	       (findMax_vec_a_BITS_127_TO_112_54_ULE_findMax_v_ETC___d356 ?
		  findMax_vec_a[127:112] :
		  findMax_vec_b[127:112]) :
	       (findMax_vec_a[127] ?
		  findMax_vec_b[127:112] :
		  findMax_vec_a[127:112]) ;
  assign IF_findMax_vec_a_BIT_143_34_AND_findMax_vec_b__ETC___d346 =
	     (findMax_vec_a[143] && findMax_vec_b[143]) ?
	       (findMax_vec_a_BITS_143_TO_128_39_ULE_findMax_v_ETC___d341 ?
		  findMax_vec_a[143:128] :
		  findMax_vec_b[143:128]) :
	       (findMax_vec_a[143] ?
		  findMax_vec_b[143:128] :
		  findMax_vec_a[143:128]) ;
  assign IF_findMax_vec_a_BIT_159_20_AND_findMax_vec_b__ETC___d332 =
	     (findMax_vec_a[159] && findMax_vec_b[159]) ?
	       (findMax_vec_a_BITS_159_TO_144_25_ULE_findMax_v_ETC___d327 ?
		  findMax_vec_a[159:144] :
		  findMax_vec_b[159:144]) :
	       (findMax_vec_a[159] ?
		  findMax_vec_b[159:144] :
		  findMax_vec_a[159:144]) ;
  assign IF_findMax_vec_a_BIT_15_50_AND_findMax_vec_b_B_ETC___d462 =
	     (findMax_vec_a[15] && findMax_vec_b[15]) ?
	       (findMax_vec_a_BITS_15_TO_0_55_ULE_findMax_vec__ETC___d457 ?
		  findMax_vec_a[15:0] :
		  findMax_vec_b[15:0]) :
	       (findMax_vec_a[15] ?
		  findMax_vec_b[15:0] :
		  findMax_vec_a[15:0]) ;
  assign IF_findMax_vec_a_BIT_175_05_AND_findMax_vec_b__ETC___d317 =
	     (findMax_vec_a[175] && findMax_vec_b[175]) ?
	       (findMax_vec_a_BITS_175_TO_160_10_ULE_findMax_v_ETC___d312 ?
		  findMax_vec_a[175:160] :
		  findMax_vec_b[175:160]) :
	       (findMax_vec_a[175] ?
		  findMax_vec_b[175:160] :
		  findMax_vec_a[175:160]) ;
  assign IF_findMax_vec_a_BIT_191_91_AND_findMax_vec_b__ETC___d303 =
	     (findMax_vec_a[191] && findMax_vec_b[191]) ?
	       (findMax_vec_a_BITS_191_TO_176_96_ULE_findMax_v_ETC___d298 ?
		  findMax_vec_a[191:176] :
		  findMax_vec_b[191:176]) :
	       (findMax_vec_a[191] ?
		  findMax_vec_b[191:176] :
		  findMax_vec_a[191:176]) ;
  assign IF_findMax_vec_a_BIT_207_76_AND_findMax_vec_b__ETC___d288 =
	     (findMax_vec_a[207] && findMax_vec_b[207]) ?
	       (findMax_vec_a_BITS_207_TO_192_81_ULE_findMax_v_ETC___d283 ?
		  findMax_vec_a[207:192] :
		  findMax_vec_b[207:192]) :
	       (findMax_vec_a[207] ?
		  findMax_vec_b[207:192] :
		  findMax_vec_a[207:192]) ;
  assign IF_findMax_vec_a_BIT_223_62_AND_findMax_vec_b__ETC___d274 =
	     (findMax_vec_a[223] && findMax_vec_b[223]) ?
	       (findMax_vec_a_BITS_223_TO_208_67_ULE_findMax_v_ETC___d269 ?
		  findMax_vec_a[223:208] :
		  findMax_vec_b[223:208]) :
	       (findMax_vec_a[223] ?
		  findMax_vec_b[223:208] :
		  findMax_vec_a[223:208]) ;
  assign IF_findMax_vec_a_BIT_239_47_AND_findMax_vec_b__ETC___d259 =
	     (findMax_vec_a[239] && findMax_vec_b[239]) ?
	       (findMax_vec_a_BITS_239_TO_224_52_ULE_findMax_v_ETC___d254 ?
		  findMax_vec_a[239:224] :
		  findMax_vec_b[239:224]) :
	       (findMax_vec_a[239] ?
		  findMax_vec_b[239:224] :
		  findMax_vec_a[239:224]) ;
  assign IF_findMax_vec_a_BIT_255_33_AND_findMax_vec_b__ETC___d245 =
	     (findMax_vec_a[255] && findMax_vec_b[255]) ?
	       (findMax_vec_a_BITS_255_TO_240_38_ULE_findMax_v_ETC___d240 ?
		  findMax_vec_a[255:240] :
		  findMax_vec_b[255:240]) :
	       (findMax_vec_a[255] ?
		  findMax_vec_b[255:240] :
		  findMax_vec_a[255:240]) ;
  assign IF_findMax_vec_a_BIT_271_18_AND_findMax_vec_b__ETC___d230 =
	     (findMax_vec_a[271] && findMax_vec_b[271]) ?
	       (findMax_vec_a_BITS_271_TO_256_23_ULE_findMax_v_ETC___d225 ?
		  findMax_vec_a[271:256] :
		  findMax_vec_b[271:256]) :
	       (findMax_vec_a[271] ?
		  findMax_vec_b[271:256] :
		  findMax_vec_a[271:256]) ;
  assign IF_findMax_vec_a_BIT_287_04_AND_findMax_vec_b__ETC___d216 =
	     (findMax_vec_a[287] && findMax_vec_b[287]) ?
	       (findMax_vec_a_BITS_287_TO_272_09_ULE_findMax_v_ETC___d211 ?
		  findMax_vec_a[287:272] :
		  findMax_vec_b[287:272]) :
	       (findMax_vec_a[287] ?
		  findMax_vec_b[287:272] :
		  findMax_vec_a[287:272]) ;
  assign IF_findMax_vec_a_BIT_303_89_AND_findMax_vec_b__ETC___d201 =
	     (findMax_vec_a[303] && findMax_vec_b[303]) ?
	       (findMax_vec_a_BITS_303_TO_288_94_ULE_findMax_v_ETC___d196 ?
		  findMax_vec_a[303:288] :
		  findMax_vec_b[303:288]) :
	       (findMax_vec_a[303] ?
		  findMax_vec_b[303:288] :
		  findMax_vec_a[303:288]) ;
  assign IF_findMax_vec_a_BIT_319_75_AND_findMax_vec_b__ETC___d187 =
	     (findMax_vec_a[319] && findMax_vec_b[319]) ?
	       (findMax_vec_a_BITS_319_TO_304_80_ULE_findMax_v_ETC___d182 ?
		  findMax_vec_a[319:304] :
		  findMax_vec_b[319:304]) :
	       (findMax_vec_a[319] ?
		  findMax_vec_b[319:304] :
		  findMax_vec_a[319:304]) ;
  assign IF_findMax_vec_a_BIT_31_36_AND_findMax_vec_b_B_ETC___d448 =
	     (findMax_vec_a[31] && findMax_vec_b[31]) ?
	       (findMax_vec_a_BITS_31_TO_16_41_ULE_findMax_vec_ETC___d443 ?
		  findMax_vec_a[31:16] :
		  findMax_vec_b[31:16]) :
	       (findMax_vec_a[31] ?
		  findMax_vec_b[31:16] :
		  findMax_vec_a[31:16]) ;
  assign IF_findMax_vec_a_BIT_335_60_AND_findMax_vec_b__ETC___d172 =
	     (findMax_vec_a[335] && findMax_vec_b[335]) ?
	       (findMax_vec_a_BITS_335_TO_320_65_ULE_findMax_v_ETC___d167 ?
		  findMax_vec_a[335:320] :
		  findMax_vec_b[335:320]) :
	       (findMax_vec_a[335] ?
		  findMax_vec_b[335:320] :
		  findMax_vec_a[335:320]) ;
  assign IF_findMax_vec_a_BIT_351_46_AND_findMax_vec_b__ETC___d158 =
	     (findMax_vec_a[351] && findMax_vec_b[351]) ?
	       (findMax_vec_a_BITS_351_TO_336_51_ULE_findMax_v_ETC___d153 ?
		  findMax_vec_a[351:336] :
		  findMax_vec_b[351:336]) :
	       (findMax_vec_a[351] ?
		  findMax_vec_b[351:336] :
		  findMax_vec_a[351:336]) ;
  assign IF_findMax_vec_a_BIT_367_31_AND_findMax_vec_b__ETC___d143 =
	     (findMax_vec_a[367] && findMax_vec_b[367]) ?
	       (findMax_vec_a_BITS_367_TO_352_36_ULE_findMax_v_ETC___d138 ?
		  findMax_vec_a[367:352] :
		  findMax_vec_b[367:352]) :
	       (findMax_vec_a[367] ?
		  findMax_vec_b[367:352] :
		  findMax_vec_a[367:352]) ;
  assign IF_findMax_vec_a_BIT_383_17_AND_findMax_vec_b__ETC___d129 =
	     (findMax_vec_a[383] && findMax_vec_b[383]) ?
	       (findMax_vec_a_BITS_383_TO_368_22_ULE_findMax_v_ETC___d124 ?
		  findMax_vec_a[383:368] :
		  findMax_vec_b[383:368]) :
	       (findMax_vec_a[383] ?
		  findMax_vec_b[383:368] :
		  findMax_vec_a[383:368]) ;
  assign IF_findMax_vec_a_BIT_399_02_AND_findMax_vec_b__ETC___d114 =
	     (findMax_vec_a[399] && findMax_vec_b[399]) ?
	       (findMax_vec_a_BITS_399_TO_384_07_ULE_findMax_v_ETC___d109 ?
		  findMax_vec_a[399:384] :
		  findMax_vec_b[399:384]) :
	       (findMax_vec_a[399] ?
		  findMax_vec_b[399:384] :
		  findMax_vec_a[399:384]) ;
  assign IF_findMax_vec_a_BIT_415_8_AND_findMax_vec_b_B_ETC___d100 =
	     (findMax_vec_a[415] && findMax_vec_b[415]) ?
	       (findMax_vec_a_BITS_415_TO_400_3_ULE_findMax_ve_ETC___d95 ?
		  findMax_vec_a[415:400] :
		  findMax_vec_b[415:400]) :
	       (findMax_vec_a[415] ?
		  findMax_vec_b[415:400] :
		  findMax_vec_a[415:400]) ;
  assign IF_findMax_vec_a_BIT_431_3_AND_findMax_vec_b_B_ETC___d85 =
	     (findMax_vec_a[431] && findMax_vec_b[431]) ?
	       (findMax_vec_a_BITS_431_TO_416_8_ULE_findMax_ve_ETC___d80 ?
		  findMax_vec_a[431:416] :
		  findMax_vec_b[431:416]) :
	       (findMax_vec_a[431] ?
		  findMax_vec_b[431:416] :
		  findMax_vec_a[431:416]) ;
  assign IF_findMax_vec_a_BIT_447_9_AND_findMax_vec_b_B_ETC___d71 =
	     (findMax_vec_a[447] && findMax_vec_b[447]) ?
	       (findMax_vec_a_BITS_447_TO_432_4_ULE_findMax_ve_ETC___d66 ?
		  findMax_vec_a[447:432] :
		  findMax_vec_b[447:432]) :
	       (findMax_vec_a[447] ?
		  findMax_vec_b[447:432] :
		  findMax_vec_a[447:432]) ;
  assign IF_findMax_vec_a_BIT_463_4_AND_findMax_vec_b_B_ETC___d56 =
	     (findMax_vec_a[463] && findMax_vec_b[463]) ?
	       (findMax_vec_a_BITS_463_TO_448_9_ULE_findMax_ve_ETC___d51 ?
		  findMax_vec_a[463:448] :
		  findMax_vec_b[463:448]) :
	       (findMax_vec_a[463] ?
		  findMax_vec_b[463:448] :
		  findMax_vec_a[463:448]) ;
  assign IF_findMax_vec_a_BIT_479_0_AND_findMax_vec_b_B_ETC___d42 =
	     (findMax_vec_a[479] && findMax_vec_b[479]) ?
	       (findMax_vec_a_BITS_479_TO_464_5_ULE_findMax_ve_ETC___d37 ?
		  findMax_vec_a[479:464] :
		  findMax_vec_b[479:464]) :
	       (findMax_vec_a[479] ?
		  findMax_vec_b[479:464] :
		  findMax_vec_a[479:464]) ;
  assign IF_findMax_vec_a_BIT_47_21_AND_findMax_vec_b_B_ETC___d433 =
	     (findMax_vec_a[47] && findMax_vec_b[47]) ?
	       (findMax_vec_a_BITS_47_TO_32_26_ULE_findMax_vec_ETC___d428 ?
		  findMax_vec_a[47:32] :
		  findMax_vec_b[47:32]) :
	       (findMax_vec_a[47] ?
		  findMax_vec_b[47:32] :
		  findMax_vec_a[47:32]) ;
  assign IF_findMax_vec_a_BIT_495_5_AND_findMax_vec_b_B_ETC___d27 =
	     (findMax_vec_a[495] && findMax_vec_b[495]) ?
	       (findMax_vec_a_BITS_495_TO_480_0_ULE_findMax_ve_ETC___d22 ?
		  findMax_vec_a[495:480] :
		  findMax_vec_b[495:480]) :
	       (findMax_vec_a[495] ?
		  findMax_vec_b[495:480] :
		  findMax_vec_a[495:480]) ;
  assign IF_findMax_vec_a_BIT_511_AND_findMax_vec_b_BIT_ETC___d13 =
	     (findMax_vec_a[511] && findMax_vec_b[511]) ?
	       (findMax_vec_a_BITS_511_TO_496_ULE_findMax_vec__ETC___d8 ?
		  findMax_vec_a[511:496] :
		  findMax_vec_b[511:496]) :
	       (findMax_vec_a[511] ?
		  findMax_vec_b[511:496] :
		  findMax_vec_a[511:496]) ;
  assign IF_findMax_vec_a_BIT_63_07_AND_findMax_vec_b_B_ETC___d419 =
	     (findMax_vec_a[63] && findMax_vec_b[63]) ?
	       (findMax_vec_a_BITS_63_TO_48_12_ULE_findMax_vec_ETC___d414 ?
		  findMax_vec_a[63:48] :
		  findMax_vec_b[63:48]) :
	       (findMax_vec_a[63] ?
		  findMax_vec_b[63:48] :
		  findMax_vec_a[63:48]) ;
  assign IF_findMax_vec_a_BIT_79_92_AND_findMax_vec_b_B_ETC___d404 =
	     (findMax_vec_a[79] && findMax_vec_b[79]) ?
	       (findMax_vec_a_BITS_79_TO_64_97_ULE_findMax_vec_ETC___d399 ?
		  findMax_vec_a[79:64] :
		  findMax_vec_b[79:64]) :
	       (findMax_vec_a[79] ?
		  findMax_vec_b[79:64] :
		  findMax_vec_a[79:64]) ;
  assign IF_findMax_vec_a_BIT_95_78_AND_findMax_vec_b_B_ETC___d390 =
	     (findMax_vec_a[95] && findMax_vec_b[95]) ?
	       (findMax_vec_a_BITS_95_TO_80_83_ULE_findMax_vec_ETC___d385 ?
		  findMax_vec_a[95:80] :
		  findMax_vec_b[95:80]) :
	       (findMax_vec_a[95] ?
		  findMax_vec_b[95:80] :
		  findMax_vec_a[95:80]) ;
  assign findMax_vec_a_BITS_111_TO_96_68_ULE_findMax_ve_ETC___d370 =
	     findMax_vec_a[111:96] <= findMax_vec_b[111:96] ;
  assign findMax_vec_a_BITS_127_TO_112_54_ULE_findMax_v_ETC___d356 =
	     findMax_vec_a[127:112] <= findMax_vec_b[127:112] ;
  assign findMax_vec_a_BITS_143_TO_128_39_ULE_findMax_v_ETC___d341 =
	     findMax_vec_a[143:128] <= findMax_vec_b[143:128] ;
  assign findMax_vec_a_BITS_159_TO_144_25_ULE_findMax_v_ETC___d327 =
	     findMax_vec_a[159:144] <= findMax_vec_b[159:144] ;
  assign findMax_vec_a_BITS_15_TO_0_55_ULE_findMax_vec__ETC___d457 =
	     findMax_vec_a[15:0] <= findMax_vec_b[15:0] ;
  assign findMax_vec_a_BITS_175_TO_160_10_ULE_findMax_v_ETC___d312 =
	     findMax_vec_a[175:160] <= findMax_vec_b[175:160] ;
  assign findMax_vec_a_BITS_191_TO_176_96_ULE_findMax_v_ETC___d298 =
	     findMax_vec_a[191:176] <= findMax_vec_b[191:176] ;
  assign findMax_vec_a_BITS_207_TO_192_81_ULE_findMax_v_ETC___d283 =
	     findMax_vec_a[207:192] <= findMax_vec_b[207:192] ;
  assign findMax_vec_a_BITS_223_TO_208_67_ULE_findMax_v_ETC___d269 =
	     findMax_vec_a[223:208] <= findMax_vec_b[223:208] ;
  assign findMax_vec_a_BITS_239_TO_224_52_ULE_findMax_v_ETC___d254 =
	     findMax_vec_a[239:224] <= findMax_vec_b[239:224] ;
  assign findMax_vec_a_BITS_255_TO_240_38_ULE_findMax_v_ETC___d240 =
	     findMax_vec_a[255:240] <= findMax_vec_b[255:240] ;
  assign findMax_vec_a_BITS_271_TO_256_23_ULE_findMax_v_ETC___d225 =
	     findMax_vec_a[271:256] <= findMax_vec_b[271:256] ;
  assign findMax_vec_a_BITS_287_TO_272_09_ULE_findMax_v_ETC___d211 =
	     findMax_vec_a[287:272] <= findMax_vec_b[287:272] ;
  assign findMax_vec_a_BITS_303_TO_288_94_ULE_findMax_v_ETC___d196 =
	     findMax_vec_a[303:288] <= findMax_vec_b[303:288] ;
  assign findMax_vec_a_BITS_319_TO_304_80_ULE_findMax_v_ETC___d182 =
	     findMax_vec_a[319:304] <= findMax_vec_b[319:304] ;
  assign findMax_vec_a_BITS_31_TO_16_41_ULE_findMax_vec_ETC___d443 =
	     findMax_vec_a[31:16] <= findMax_vec_b[31:16] ;
  assign findMax_vec_a_BITS_335_TO_320_65_ULE_findMax_v_ETC___d167 =
	     findMax_vec_a[335:320] <= findMax_vec_b[335:320] ;
  assign findMax_vec_a_BITS_351_TO_336_51_ULE_findMax_v_ETC___d153 =
	     findMax_vec_a[351:336] <= findMax_vec_b[351:336] ;
  assign findMax_vec_a_BITS_367_TO_352_36_ULE_findMax_v_ETC___d138 =
	     findMax_vec_a[367:352] <= findMax_vec_b[367:352] ;
  assign findMax_vec_a_BITS_383_TO_368_22_ULE_findMax_v_ETC___d124 =
	     findMax_vec_a[383:368] <= findMax_vec_b[383:368] ;
  assign findMax_vec_a_BITS_399_TO_384_07_ULE_findMax_v_ETC___d109 =
	     findMax_vec_a[399:384] <= findMax_vec_b[399:384] ;
  assign findMax_vec_a_BITS_415_TO_400_3_ULE_findMax_ve_ETC___d95 =
	     findMax_vec_a[415:400] <= findMax_vec_b[415:400] ;
  assign findMax_vec_a_BITS_431_TO_416_8_ULE_findMax_ve_ETC___d80 =
	     findMax_vec_a[431:416] <= findMax_vec_b[431:416] ;
  assign findMax_vec_a_BITS_447_TO_432_4_ULE_findMax_ve_ETC___d66 =
	     findMax_vec_a[447:432] <= findMax_vec_b[447:432] ;
  assign findMax_vec_a_BITS_463_TO_448_9_ULE_findMax_ve_ETC___d51 =
	     findMax_vec_a[463:448] <= findMax_vec_b[463:448] ;
  assign findMax_vec_a_BITS_479_TO_464_5_ULE_findMax_ve_ETC___d37 =
	     findMax_vec_a[479:464] <= findMax_vec_b[479:464] ;
  assign findMax_vec_a_BITS_47_TO_32_26_ULE_findMax_vec_ETC___d428 =
	     findMax_vec_a[47:32] <= findMax_vec_b[47:32] ;
  assign findMax_vec_a_BITS_495_TO_480_0_ULE_findMax_ve_ETC___d22 =
	     findMax_vec_a[495:480] <= findMax_vec_b[495:480] ;
  assign findMax_vec_a_BITS_511_TO_496_ULE_findMax_vec__ETC___d8 =
	     findMax_vec_a[511:496] <= findMax_vec_b[511:496] ;
  assign findMax_vec_a_BITS_63_TO_48_12_ULE_findMax_vec_ETC___d414 =
	     findMax_vec_a[63:48] <= findMax_vec_b[63:48] ;
  assign findMax_vec_a_BITS_79_TO_64_97_ULE_findMax_vec_ETC___d399 =
	     findMax_vec_a[79:64] <= findMax_vec_b[79:64] ;
  assign findMax_vec_a_BITS_95_TO_80_83_ULE_findMax_vec_ETC___d385 =
	     findMax_vec_a[95:80] <= findMax_vec_b[95:80] ;
endmodule  // mkTorchMaximum32

