//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sun Sep 13 00:07:44 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_put_operand                O     1 const
// get_result                     O    16 reg
// RDY_get_result                 O     1 reg
// hasResult                      O     1 reg
// RDY_hasResult                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_operand_x                  I    16
// EN_put_operand                 I     1
// EN_get_result                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBF16Sigmoid_SIMD(CLK,
			  RST_N,

			  put_operand_x,
			  EN_put_operand,
			  RDY_put_operand,

			  EN_get_result,
			  get_result,
			  RDY_get_result,

			  hasResult,
			  RDY_hasResult);
  input  CLK;
  input  RST_N;

  // action method put_operand
  input  [15 : 0] put_operand_x;
  input  EN_put_operand;
  output RDY_put_operand;

  // actionvalue method get_result
  input  EN_get_result;
  output [15 : 0] get_result;
  output RDY_get_result;

  // value method hasResult
  output hasResult;
  output RDY_hasResult;

  // signals for module outputs
  wire [15 : 0] get_result;
  wire RDY_get_result, RDY_hasResult, RDY_put_operand, hasResult;

  // ports of submodule sig_core
  wire [15 : 0] sig_core$getResult, sig_core$put_data_data;
  wire sig_core$EN_getResult,
       sig_core$EN_put_data,
       sig_core$RDY_getResult,
       sig_core$hasResult;

  // action method put_operand
  assign RDY_put_operand = 1'd1 ;

  // actionvalue method get_result
  assign get_result = sig_core$getResult ;
  assign RDY_get_result = sig_core$RDY_getResult ;

  // value method hasResult
  assign hasResult = sig_core$hasResult ;
  assign RDY_hasResult = 1'd1 ;

  // submodule sig_core
  mkBF16Sigmoid sig_core(.CLK(CLK),
			 .RST_N(RST_N),
			 .put_data_data(sig_core$put_data_data),
			 .EN_put_data(sig_core$EN_put_data),
			 .EN_getResult(sig_core$EN_getResult),
			 .RDY_put_data(),
			 .getResult(sig_core$getResult),
			 .RDY_getResult(sig_core$RDY_getResult),
			 .hasResult(sig_core$hasResult),
			 .RDY_hasResult());

  // submodule sig_core
  assign sig_core$put_data_data = put_operand_x ;
  assign sig_core$EN_put_data = EN_put_operand ;
  assign sig_core$EN_getResult = EN_get_result ;
endmodule  // mkBF16Sigmoid_SIMD

