//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sun Sep 13 00:07:44 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_put_operands               O     1 const
// get_result                     O    16 reg
// RDY_get_result                 O     1 reg
// hasResult                      O     1 reg
// RDY_hasResult                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_operands_x                 I    16
// EN_put_operands                I     1
// EN_get_result                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSigmoidAblation_r1(CLK,
			    RST_N,

			    put_operands_x,
			    EN_put_operands,
			    RDY_put_operands,

			    EN_get_result,
			    get_result,
			    RDY_get_result,

			    hasResult,
			    RDY_hasResult);
  input  CLK;
  input  RST_N;

  // action method put_operands
  input  [15 : 0] put_operands_x;
  input  EN_put_operands;
  output RDY_put_operands;

  // actionvalue method get_result
  input  EN_get_result;
  output [15 : 0] get_result;
  output RDY_get_result;

  // value method hasResult
  output hasResult;
  output RDY_hasResult;

  // signals for module outputs
  wire [15 : 0] get_result;
  wire RDY_get_result, RDY_hasResult, RDY_put_operands, hasResult;

  // ports of submodule i_lanes_0
  wire [15 : 0] i_lanes_0$get_result, i_lanes_0$put_operand_x;
  wire i_lanes_0$EN_get_result,
       i_lanes_0$EN_put_operand,
       i_lanes_0$RDY_get_result,
       i_lanes_0$hasResult;

  // action method put_operands
  assign RDY_put_operands = 1'd1 ;

  // actionvalue method get_result
  assign get_result = i_lanes_0$get_result ;
  assign RDY_get_result = i_lanes_0$RDY_get_result ;

  // value method hasResult
  assign hasResult = i_lanes_0$hasResult ;
  assign RDY_hasResult = 1'd1 ;

  // submodule i_lanes_0
  mkBF16Sigmoid_SIMD i_lanes_0(.CLK(CLK),
			       .RST_N(RST_N),
			       .put_operand_x(i_lanes_0$put_operand_x),
			       .EN_put_operand(i_lanes_0$EN_put_operand),
			       .EN_get_result(i_lanes_0$EN_get_result),
			       .RDY_put_operand(),
			       .get_result(i_lanes_0$get_result),
			       .RDY_get_result(i_lanes_0$RDY_get_result),
			       .hasResult(i_lanes_0$hasResult),
			       .RDY_hasResult());

  // submodule i_lanes_0
  assign i_lanes_0$put_operand_x = put_operands_x ;
  assign i_lanes_0$EN_put_operand = EN_put_operands ;
  assign i_lanes_0$EN_get_result = EN_get_result ;
endmodule  // mkSigmoidAblation_r1

