//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
//
// On Tue Jan 20 17:28:22 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb_COP(CLK,
		RST_N);
  input  CLK;
  input  RST_N;

  // register current_bram
  reg [3 : 0] current_bram;
  reg [3 : 0] current_bram$D_IN;
  wire current_bram$EN;

  // register current_chunk
  reg [1 : 0] current_chunk;
  wire [1 : 0] current_chunk$D_IN;
  wire current_chunk$EN;

  // register cycle
  reg [31 : 0] cycle;
  wire [31 : 0] cycle$D_IN;
  wire cycle$EN;

  // register started
  reg started;
  wire started$D_IN, started$EN;

  // register tb_state
  reg [2 : 0] tb_state;
  reg [2 : 0] tb_state$D_IN;
  wire tb_state$EN;

  // ports of submodule cop
  reg [4095 : 0] cop$write_bram_data;
  reg [9 : 0] cop$write_bram_base_addr;
  wire [3 : 0] cop$write_bram_bram_id;
  wire cop$EN_start_computation,
       cop$EN_write_bram,
       cop$RDY_start_computation,
       cop$RDY_write_bram,
       cop$computation_done,
       cop$ready_for_write;

  // rule scheduling signals
  wire WILL_FIRE_RL_check_done,
       WILL_FIRE_RL_start_cop,
       WILL_FIRE_RL_timeout,
       WILL_FIRE_RL_wait_for_write_ready,
       WILL_FIRE_RL_write_chunk0,
       WILL_FIRE_RL_write_chunk1,
       WILL_FIRE_RL_write_chunk2;

  // inputs to muxes for submodule ports
  wire [4095 : 0] MUX_cop$write_bram_2__VAL_1,
		  MUX_cop$write_bram_2__VAL_2,
		  MUX_cop$write_bram_2__VAL_3;
  wire [3 : 0] MUX_current_bram$write_1__VAL_2;
  wire MUX_current_bram$write_1__SEL_1,
       MUX_current_bram$write_1__SEL_2,
       MUX_tb_state$write_1__SEL_1,
       MUX_tb_state$write_1__SEL_2,
       MUX_tb_state$write_1__SEL_3;

  // remaining internal signals
  reg [7 : 0] CASE_current_bram_0_127_1_128_2_128_3_129_4_12_ETC__q3,
	      CASE_current_bram_0_132_1_132_2_132_3_132_4_13_ETC__q5,
	      CASE_current_bram_1_131_2_131_3_131_4_132_5_13_ETC__q1;
  reg [6 : 0] CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4,
	      CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6,
	      CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2;
  wire [15 : 0] _0_CONCAT_IF_current_bram_5_EQ_0_9_OR_current_b_ETC___d363,
		_0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_127_ELS_ETC___d58,
		_0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_16736_E_ETC___d213;
  wire [3 : 0] x__h83422;
  wire current_bram_5_ULT_13___d16;

  // submodule cop
  mkCOP cop(.CLK(CLK),
	    .RST_N(RST_N),
	    .write_bram_base_addr(cop$write_bram_base_addr),
	    .write_bram_bram_id(cop$write_bram_bram_id),
	    .write_bram_data(cop$write_bram_data),
	    .EN_start_computation(cop$EN_start_computation),
	    .EN_write_bram(cop$EN_write_bram),
	    .RDY_start_computation(cop$RDY_start_computation),
	    .get_result_k(),
	    .RDY_get_result_k(),
	    .get_output(),
	    .RDY_get_output(),
	    .computation_done(cop$computation_done),
	    .RDY_computation_done(),
	    .RDY_write_bram(cop$RDY_write_bram),
	    .ready_for_write(cop$ready_for_write),
	    .RDY_ready_for_write());

  // rule RL_wait_for_write_ready
  assign WILL_FIRE_RL_wait_for_write_ready =
	     tb_state == 3'd2 && cop$ready_for_write ;

  // rule RL_write_chunk0
  assign WILL_FIRE_RL_write_chunk0 =
	     cop$RDY_write_bram && tb_state == 3'd3 && cop$ready_for_write &&
	     current_bram_5_ULT_13___d16 ;

  // rule RL_write_chunk1
  assign WILL_FIRE_RL_write_chunk1 =
	     cop$RDY_write_bram && tb_state == 3'd4 && cop$ready_for_write &&
	     current_bram_5_ULT_13___d16 ;

  // rule RL_write_chunk2
  assign WILL_FIRE_RL_write_chunk2 =
	     cop$RDY_write_bram && tb_state == 3'd5 && cop$ready_for_write &&
	     current_bram_5_ULT_13___d16 ;

  // rule RL_check_done
  assign WILL_FIRE_RL_check_done = started && cop$computation_done ;

  // rule RL_start_cop
  assign WILL_FIRE_RL_start_cop =
	     cop$RDY_start_computation && tb_state == 3'd0 && cycle == 32'd5 ;

  // rule RL_timeout
  assign WILL_FIRE_RL_timeout = cycle > 32'd200000 ;

  // inputs to muxes for submodule ports
  assign MUX_current_bram$write_1__SEL_1 =
	     WILL_FIRE_RL_write_chunk2 && current_bram != 4'd12 ;
  assign MUX_current_bram$write_1__SEL_2 =
	     WILL_FIRE_RL_write_chunk1 || WILL_FIRE_RL_write_chunk0 ;
  assign MUX_tb_state$write_1__SEL_1 =
	     WILL_FIRE_RL_write_chunk0 && current_bram == 4'd12 ;
  assign MUX_tb_state$write_1__SEL_2 =
	     WILL_FIRE_RL_write_chunk1 && current_bram == 4'd12 ;
  assign MUX_tb_state$write_1__SEL_3 =
	     WILL_FIRE_RL_write_chunk2 && current_bram == 4'd12 ;
  assign MUX_cop$write_bram_2__VAL_1 =
	     {256{_0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_127_ELS_ETC___d58}} ;
  assign MUX_cop$write_bram_2__VAL_2 =
	     {256{_0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_16736_E_ETC___d213}} ;
  assign MUX_cop$write_bram_2__VAL_3 =
	     {256{_0_CONCAT_IF_current_bram_5_EQ_0_9_OR_current_b_ETC___d363}} ;
  assign MUX_current_bram$write_1__VAL_2 =
	     (current_bram == 4'd12) ? 4'd0 : x__h83422 ;

  // register current_bram
  always@(MUX_current_bram$write_1__SEL_1 or
	  x__h83422 or
	  MUX_current_bram$write_1__SEL_2 or
	  MUX_current_bram$write_1__VAL_2 or
	  WILL_FIRE_RL_wait_for_write_ready)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_current_bram$write_1__SEL_1: current_bram$D_IN = x__h83422;
      MUX_current_bram$write_1__SEL_2:
	  current_bram$D_IN = MUX_current_bram$write_1__VAL_2;
      WILL_FIRE_RL_wait_for_write_ready: current_bram$D_IN = 4'd0;
      default: current_bram$D_IN = 4'b1010 /* unspecified value */ ;
    endcase
  end
  assign current_bram$EN =
	     WILL_FIRE_RL_write_chunk2 && current_bram != 4'd12 ||
	     WILL_FIRE_RL_write_chunk1 ||
	     WILL_FIRE_RL_write_chunk0 ||
	     WILL_FIRE_RL_wait_for_write_ready ;

  // register current_chunk
  assign current_chunk$D_IN = 2'd0 ;
  assign current_chunk$EN = WILL_FIRE_RL_wait_for_write_ready ;

  // register cycle
  assign cycle$D_IN = cycle + 32'd1 ;
  assign cycle$EN = 1'd1 ;

  // register started
  assign started$D_IN = 1'd1 ;
  assign started$EN = WILL_FIRE_RL_start_cop ;

  // register tb_state
  always@(MUX_tb_state$write_1__SEL_1 or
	  MUX_tb_state$write_1__SEL_2 or
	  MUX_tb_state$write_1__SEL_3 or
	  WILL_FIRE_RL_start_cop or WILL_FIRE_RL_wait_for_write_ready)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_tb_state$write_1__SEL_1: tb_state$D_IN = 3'd4;
      MUX_tb_state$write_1__SEL_2: tb_state$D_IN = 3'd5;
      MUX_tb_state$write_1__SEL_3: tb_state$D_IN = 3'd6;
      WILL_FIRE_RL_start_cop: tb_state$D_IN = 3'd2;
      WILL_FIRE_RL_wait_for_write_ready: tb_state$D_IN = 3'd3;
      default: tb_state$D_IN = 3'b010 /* unspecified value */ ;
    endcase
  end
  assign tb_state$EN =
	     WILL_FIRE_RL_write_chunk0 && current_bram == 4'd12 ||
	     WILL_FIRE_RL_write_chunk1 && current_bram == 4'd12 ||
	     WILL_FIRE_RL_write_chunk2 && current_bram == 4'd12 ||
	     WILL_FIRE_RL_start_cop ||
	     WILL_FIRE_RL_wait_for_write_ready ;

  // submodule cop
  always@(WILL_FIRE_RL_write_chunk0 or
	  WILL_FIRE_RL_write_chunk1 or WILL_FIRE_RL_write_chunk2)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_write_chunk0: cop$write_bram_base_addr = 10'd0;
      WILL_FIRE_RL_write_chunk1: cop$write_bram_base_addr = 10'd256;
      WILL_FIRE_RL_write_chunk2: cop$write_bram_base_addr = 10'd512;
      default: cop$write_bram_base_addr =
		   10'b1010101010 /* unspecified value */ ;
    endcase
  end
  assign cop$write_bram_bram_id = current_bram ;
  always@(WILL_FIRE_RL_write_chunk0 or
	  MUX_cop$write_bram_2__VAL_1 or
	  WILL_FIRE_RL_write_chunk1 or
	  MUX_cop$write_bram_2__VAL_2 or
	  WILL_FIRE_RL_write_chunk2 or MUX_cop$write_bram_2__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_write_chunk0:
	  cop$write_bram_data = MUX_cop$write_bram_2__VAL_1;
      WILL_FIRE_RL_write_chunk1:
	  cop$write_bram_data = MUX_cop$write_bram_2__VAL_2;
      WILL_FIRE_RL_write_chunk2:
	  cop$write_bram_data = MUX_cop$write_bram_2__VAL_3;
      default: cop$write_bram_data =
		   4096'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign cop$EN_start_computation = WILL_FIRE_RL_start_cop ;
  assign cop$EN_write_bram =
	     WILL_FIRE_RL_write_chunk0 || WILL_FIRE_RL_write_chunk1 ||
	     WILL_FIRE_RL_write_chunk2 ;

  // remaining internal signals
  assign _0_CONCAT_IF_current_bram_5_EQ_0_9_OR_current_b_ETC___d363 =
	     { 1'd0,
	       CASE_current_bram_0_132_1_132_2_132_3_132_4_13_ETC__q5,
	       CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 } ;
  assign _0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_127_ELS_ETC___d58 =
	     { 1'd0,
	       CASE_current_bram_0_127_1_128_2_128_3_129_4_12_ETC__q3,
	       CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 } ;
  assign _0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_16736_E_ETC___d213 =
	     { 1'd0,
	       (current_bram == 4'd0) ?
		 15'd16736 :
		 { CASE_current_bram_1_131_2_131_3_131_4_132_5_13_ETC__q1,
		   CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 } } ;
  assign current_bram_5_ULT_13___d16 = current_bram < 4'd13 ;
  assign x__h83422 = current_bram + 4'd1 ;
  always@(current_bram)
  begin
    case (current_bram)
      4'd1, 4'd2, 4'd3, 4'd11:
	  CASE_current_bram_1_131_2_131_3_131_4_132_5_13_ETC__q1 = 8'd131;
      4'd4, 4'd5, 4'd6, 4'd7, 4'd8, 4'd9, 4'd10, 4'd12:
	  CASE_current_bram_1_131_2_131_3_131_4_132_5_13_ETC__q1 = 8'd132;
      default: CASE_current_bram_1_131_2_131_3_131_4_132_5_13_ETC__q1 = 8'd0;
    endcase
  end
  always@(current_bram)
  begin
    case (current_bram)
      4'd1: CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd0;
      4'd2, 4'd4:
	  CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd16;
      4'd3, 4'd5:
	  CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd32;
      4'd6, 4'd11:
	  CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd48;
      4'd7: CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd64;
      4'd8: CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd80;
      4'd9: CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd96;
      4'd10: CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd112;
      default: CASE_current_bram_1_0_2_16_3_32_4_16_5_32_6_48_ETC__q2 = 7'd0;
    endcase
  end
  always@(current_bram)
  begin
    case (current_bram)
      4'd0: CASE_current_bram_0_127_1_128_2_128_3_129_4_12_ETC__q3 = 8'd127;
      4'd1, 4'd2:
	  CASE_current_bram_0_127_1_128_2_128_3_129_4_12_ETC__q3 = 8'd128;
      4'd3, 4'd4, 4'd11, 4'd12:
	  CASE_current_bram_0_127_1_128_2_128_3_129_4_12_ETC__q3 = 8'd129;
      4'd5, 4'd6, 4'd7, 4'd8, 4'd9, 4'd10:
	  CASE_current_bram_0_127_1_128_2_128_3_129_4_12_ETC__q3 = 8'd130;
      default: CASE_current_bram_0_127_1_128_2_128_3_129_4_12_ETC__q3 = 8'd0;
    endcase
  end
  always@(current_bram)
  begin
    case (current_bram)
      4'd0, 4'd1, 4'd3, 4'd5:
	  CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 = 7'd0;
      4'd2, 4'd9, 4'd12:
	  CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 = 7'd64;
      4'd4, 4'd7, 4'd11:
	  CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 = 7'd32;
      4'd6: CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 = 7'd16;
      4'd8: CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 = 7'd48;
      4'd10: CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 = 7'd80;
      default: CASE_current_bram_0_0_1_0_2_64_3_0_4_32_5_0_6__ETC__q4 = 7'd0;
    endcase
  end
  always@(current_bram)
  begin
    case (current_bram)
      4'd0, 4'd1, 4'd2, 4'd3, 4'd11, 4'd12:
	  CASE_current_bram_0_132_1_132_2_132_3_132_4_13_ETC__q5 = 8'd132;
      4'd4, 4'd5, 4'd6, 4'd7, 4'd8, 4'd9, 4'd10:
	  CASE_current_bram_0_132_1_132_2_132_3_132_4_13_ETC__q5 = 8'd133;
      default: CASE_current_bram_0_132_1_132_2_132_3_132_4_13_ETC__q5 = 8'd0;
    endcase
  end
  always@(current_bram)
  begin
    case (current_bram)
      4'd0, 4'd5:
	  CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd24;
      4'd1, 4'd7:
	  CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd40;
      4'd2, 4'd9:
	  CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd56;
      4'd3: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd72;
      4'd4: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd8;
      4'd6: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd32;
      4'd8: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd48;
      4'd10: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd64;
      4'd11: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd96;
      4'd12: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd104;
      default: CASE_current_bram_0_24_1_40_2_56_3_72_4_8_5_24_ETC__q6 = 7'd0;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        current_bram <= `BSV_ASSIGNMENT_DELAY 4'd0;
	current_chunk <= `BSV_ASSIGNMENT_DELAY 2'd0;
	cycle <= `BSV_ASSIGNMENT_DELAY 32'd0;
	started <= `BSV_ASSIGNMENT_DELAY 1'd0;
	tb_state <= `BSV_ASSIGNMENT_DELAY 3'd0;
      end
    else
      begin
        if (current_bram$EN)
	  current_bram <= `BSV_ASSIGNMENT_DELAY current_bram$D_IN;
	if (current_chunk$EN)
	  current_chunk <= `BSV_ASSIGNMENT_DELAY current_chunk$D_IN;
	if (cycle$EN) cycle <= `BSV_ASSIGNMENT_DELAY cycle$D_IN;
	if (started$EN) started <= `BSV_ASSIGNMENT_DELAY started$D_IN;
	if (tb_state$EN) tb_state <= `BSV_ASSIGNMENT_DELAY tb_state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    current_bram = 4'hA;
    current_chunk = 2'h2;
    cycle = 32'hAAAAAAAA;
    started = 1'h0;
    tb_state = 3'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_wait_for_write_ready)
	$display("[Cycle %0d] Testbench: COP ready for writes, starting chunk 0",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_chunk0)
	$display("[Cycle %0d] Testbench: Writing chunk 0 to BRAM %0d, value=%h",
		 cycle,
		 current_bram,
		 _0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_127_ELS_ETC___d58);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_chunk0 && current_bram == 4'd12)
	$display("[Cycle %0d] Testbench: Chunk 0 writes complete", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_chunk1)
	$display("[Cycle %0d] Testbench: Writing chunk 1 to BRAM %0d, value=%h",
		 cycle,
		 current_bram,
		 _0_CONCAT_IF_current_bram_5_EQ_0_9_THEN_16736_E_ETC___d213);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_chunk1 && current_bram == 4'd12)
	$display("[Cycle %0d] Testbench: Chunk 1 writes complete", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_chunk2)
	$display("[Cycle %0d] Testbench: Writing chunk 2 to BRAM %0d, value=%h",
		 cycle,
		 current_bram,
		 _0_CONCAT_IF_current_bram_5_EQ_0_9_OR_current_b_ETC___d363);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_write_chunk2 && current_bram == 4'd12)
	$display("[Cycle %0d] Testbench: ALL BRAM writes complete!", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("[Cycle %0d] Total cycles taken: %0d", cycle, cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("\n[Cycle %0d] Testbench: Finishing simulation", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done) $finish(32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_start_cop)
	$display("[Cycle %0d] Testbench: Started COP computation", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_timeout)
	$display("[Cycle %0d] ERROR: Timeout! Computation didn't complete.",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE) if (WILL_FIRE_RL_timeout) $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // mkTb_COP

