//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
//
// On Tue Jan 20 17:48:30 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_request                    O     1
// response                       O    16 reg
// RDY_response                   O     1 const
// response_valid                 O     1 reg
// RDY_response_valid             O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_opcode                 I     4
// request_data_in                I    16 reg
// EN_request                     I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCOP_Wrapper(CLK,
		     RST_N,

		     request_opcode,
		     request_data_in,
		     EN_request,
		     RDY_request,

		     response,
		     RDY_response,

		     response_valid,
		     RDY_response_valid);
  input  CLK;
  input  RST_N;

  // action method request
  input  [3 : 0] request_opcode;
  input  [15 : 0] request_data_in;
  input  EN_request;
  output RDY_request;

  // value method response
  output [15 : 0] response;
  output RDY_response;

  // value method response_valid
  output response_valid;
  output RDY_response_valid;

  // signals for module outputs
  wire [15 : 0] response;
  wire RDY_request, RDY_response, RDY_response_valid, response_valid;

  // register bram_addr_reg
  reg [9 : 0] bram_addr_reg;
  wire [9 : 0] bram_addr_reg$D_IN;
  wire bram_addr_reg$EN;

  // register bram_id_reg
  reg [3 : 0] bram_id_reg;
  wire [3 : 0] bram_id_reg$D_IN;
  wire bram_id_reg$EN;

  // register buffer_index
  reg [8 : 0] buffer_index;
  wire [8 : 0] buffer_index$D_IN;
  wire buffer_index$EN;

  // register current_op
  reg [3 : 0] current_op;
  wire [3 : 0] current_op$D_IN;
  wire current_op$EN;

  // register response_reg
  reg [15 : 0] response_reg;
  reg [15 : 0] response_reg$D_IN;
  wire response_reg$EN;

  // register response_valid_reg
  reg response_valid_reg;
  wire response_valid_reg$D_IN, response_valid_reg$EN;

  // register stream_buffer_0
  reg [15 : 0] stream_buffer_0;
  wire [15 : 0] stream_buffer_0$D_IN;
  wire stream_buffer_0$EN;

  // register stream_buffer_1
  reg [15 : 0] stream_buffer_1;
  wire [15 : 0] stream_buffer_1$D_IN;
  wire stream_buffer_1$EN;

  // register stream_buffer_10
  reg [15 : 0] stream_buffer_10;
  wire [15 : 0] stream_buffer_10$D_IN;
  wire stream_buffer_10$EN;

  // register stream_buffer_11
  reg [15 : 0] stream_buffer_11;
  wire [15 : 0] stream_buffer_11$D_IN;
  wire stream_buffer_11$EN;

  // register stream_buffer_12
  reg [15 : 0] stream_buffer_12;
  wire [15 : 0] stream_buffer_12$D_IN;
  wire stream_buffer_12$EN;

  // register stream_buffer_13
  reg [15 : 0] stream_buffer_13;
  wire [15 : 0] stream_buffer_13$D_IN;
  wire stream_buffer_13$EN;

  // register stream_buffer_14
  reg [15 : 0] stream_buffer_14;
  wire [15 : 0] stream_buffer_14$D_IN;
  wire stream_buffer_14$EN;

  // register stream_buffer_15
  reg [15 : 0] stream_buffer_15;
  wire [15 : 0] stream_buffer_15$D_IN;
  wire stream_buffer_15$EN;

  // register stream_buffer_2
  reg [15 : 0] stream_buffer_2;
  wire [15 : 0] stream_buffer_2$D_IN;
  wire stream_buffer_2$EN;

  // register stream_buffer_3
  reg [15 : 0] stream_buffer_3;
  wire [15 : 0] stream_buffer_3$D_IN;
  wire stream_buffer_3$EN;

  // register stream_buffer_4
  reg [15 : 0] stream_buffer_4;
  wire [15 : 0] stream_buffer_4$D_IN;
  wire stream_buffer_4$EN;

  // register stream_buffer_5
  reg [15 : 0] stream_buffer_5;
  wire [15 : 0] stream_buffer_5$D_IN;
  wire stream_buffer_5$EN;

  // register stream_buffer_6
  reg [15 : 0] stream_buffer_6;
  wire [15 : 0] stream_buffer_6$D_IN;
  wire stream_buffer_6$EN;

  // register stream_buffer_7
  reg [15 : 0] stream_buffer_7;
  wire [15 : 0] stream_buffer_7$D_IN;
  wire stream_buffer_7$EN;

  // register stream_buffer_8
  reg [15 : 0] stream_buffer_8;
  wire [15 : 0] stream_buffer_8$D_IN;
  wire stream_buffer_8$EN;

  // register stream_buffer_9
  reg [15 : 0] stream_buffer_9;
  wire [15 : 0] stream_buffer_9$D_IN;
  wire stream_buffer_9$EN;

  // register write_complete
  reg write_complete;
  wire write_complete$D_IN, write_complete$EN;

  // register write_index
  reg [8 : 0] write_index;
  wire [8 : 0] write_index$D_IN;
  wire write_index$EN;

  // register writing_bram
  reg writing_bram;
  wire writing_bram$D_IN, writing_bram$EN;

  // ports of submodule cop
  wire [4095 : 0] cop$write_bram_data;
  wire [9 : 0] cop$write_bram_base_addr;
  wire [3 : 0] cop$write_bram_bram_id;
  wire cop$EN_start_computation,
       cop$EN_write_bram,
       cop$RDY_start_computation,
       cop$computation_done,
       cop$ready_for_write;

  // rule scheduling signals
  wire WILL_FIRE_RL_handle_computation_done,
       WILL_FIRE_RL_handle_ready_check,
       WILL_FIRE_RL_perform_buffered_write;

  // inputs to muxes for submodule ports
  reg [15 : 0] MUX_response_reg$write_1__VAL_4;
  reg [3 : 0] MUX_current_op$write_1__VAL_4;
  wire [15 : 0] MUX_response_reg$write_1__VAL_1,
		MUX_response_reg$write_1__VAL_2,
		MUX_response_reg$write_1__VAL_3;
  wire [8 : 0] MUX_buffer_index$write_1__VAL_1,
	       MUX_write_index$write_1__VAL_2;
  wire MUX_buffer_index$write_1__SEL_1,
       MUX_current_op$write_1__SEL_1,
       MUX_response_reg$write_1__SEL_4,
       MUX_write_complete$write_1__SEL_2;

  // remaining internal signals
  wire [15 : 0] IF_writing_bram_2_AND_write_index_6_ULT_256_2__ETC___d42,
		x__h1893,
		x__h3474;
  wire [8 : 0] x__h3326, x__h3375;
  wire request_opcode_EQ_2_0_OR_request_opcode_EQ_3_1_ETC___d54;

  // action method request
  assign RDY_request = !response_valid_reg && cop$RDY_start_computation ;

  // value method response
  assign response = response_reg ;
  assign RDY_response = 1'd1 ;

  // value method response_valid
  assign response_valid = response_valid_reg ;
  assign RDY_response_valid = 1'd1 ;

  // submodule cop
  mkCOP cop(.CLK(CLK),
	    .RST_N(RST_N),
	    .write_bram_base_addr(cop$write_bram_base_addr),
	    .write_bram_bram_id(cop$write_bram_bram_id),
	    .write_bram_data(cop$write_bram_data),
	    .EN_start_computation(cop$EN_start_computation),
	    .EN_write_bram(cop$EN_write_bram),
	    .RDY_start_computation(cop$RDY_start_computation),
	    .get_result_k(),
	    .RDY_get_result_k(),
	    .get_output(),
	    .RDY_get_output(),
	    .computation_done(cop$computation_done),
	    .RDY_computation_done(),
	    .RDY_write_bram(),
	    .ready_for_write(cop$ready_for_write),
	    .RDY_ready_for_write());

  // rule RL_handle_computation_done
  assign WILL_FIRE_RL_handle_computation_done =
	     current_op == 4'd1 && !response_valid_reg && !EN_request ;

  // rule RL_handle_ready_check
  assign WILL_FIRE_RL_handle_ready_check =
	     current_op == 4'd4 && !response_valid_reg && !EN_request ;

  // rule RL_perform_buffered_write
  assign WILL_FIRE_RL_perform_buffered_write =
	     writing_bram && buffer_index == 9'd16 && !EN_request ;

  // inputs to muxes for submodule ports
  assign MUX_buffer_index$write_1__SEL_1 =
	     EN_request && request_opcode != 4'd0 && request_opcode != 4'd1 &&
	     request_opcode_EQ_2_0_OR_request_opcode_EQ_3_1_ETC___d54 ;
  assign MUX_current_op$write_1__SEL_1 =
	     WILL_FIRE_RL_perform_buffered_write && write_index == 9'd256 ;
  assign MUX_response_reg$write_1__SEL_4 =
	     EN_request && request_opcode != 4'd1 && request_opcode != 4'd4 ;
  assign MUX_write_complete$write_1__SEL_2 =
	     EN_request && request_opcode == 4'd2 ;
  assign MUX_buffer_index$write_1__VAL_1 =
	     (request_opcode == 4'd2) ? 9'd0 : x__h3326 ;
  always@(request_opcode)
  begin
    case (request_opcode)
      4'd0, 4'd2: MUX_current_op$write_1__VAL_4 = 4'd15;
      4'd1: MUX_current_op$write_1__VAL_4 = request_opcode;
      default: MUX_current_op$write_1__VAL_4 = 4'd4;
    endcase
  end
  assign MUX_response_reg$write_1__VAL_1 =
	     (write_index == 9'd256) ? 16'd1 : x__h1893 ;
  assign MUX_response_reg$write_1__VAL_2 =
	     cop$ready_for_write ? 16'd1 : 16'd0 ;
  assign MUX_response_reg$write_1__VAL_3 =
	     cop$computation_done ? 16'd1 : 16'd0 ;
  always@(request_opcode or
	  IF_writing_bram_2_AND_write_index_6_ULT_256_2__ETC___d42)
  begin
    case (request_opcode)
      4'd0: MUX_response_reg$write_1__VAL_4 = 16'd1;
      4'd2: MUX_response_reg$write_1__VAL_4 = 16'hBEEF;
      4'd3:
	  MUX_response_reg$write_1__VAL_4 =
	      IF_writing_bram_2_AND_write_index_6_ULT_256_2__ETC___d42;
      default: MUX_response_reg$write_1__VAL_4 = 16'hDEAD;
    endcase
  end
  assign MUX_write_index$write_1__VAL_2 =
	     (request_opcode == 4'd2) ? 9'd0 : x__h3375 ;

  // register bram_addr_reg
  assign bram_addr_reg$D_IN = request_data_in[11:2] ;
  assign bram_addr_reg$EN = MUX_write_complete$write_1__SEL_2 ;

  // register bram_id_reg
  assign bram_id_reg$D_IN = request_data_in[15:12] ;
  assign bram_id_reg$EN = MUX_write_complete$write_1__SEL_2 ;

  // register buffer_index
  assign buffer_index$D_IN =
	     MUX_buffer_index$write_1__SEL_1 ?
	       MUX_buffer_index$write_1__VAL_1 :
	       9'd0 ;
  assign buffer_index$EN =
	     EN_request && request_opcode != 4'd0 && request_opcode != 4'd1 &&
	     request_opcode_EQ_2_0_OR_request_opcode_EQ_3_1_ETC___d54 ||
	     WILL_FIRE_RL_perform_buffered_write ;

  // register current_op
  assign current_op$D_IN =
	     (MUX_current_op$write_1__SEL_1 ||
	      WILL_FIRE_RL_handle_ready_check ||
	      WILL_FIRE_RL_handle_computation_done) ?
	       4'd15 :
	       MUX_current_op$write_1__VAL_4 ;
  assign current_op$EN =
	     WILL_FIRE_RL_perform_buffered_write && write_index == 9'd256 ||
	     EN_request &&
	     (request_opcode == 4'd0 || request_opcode == 4'd1 ||
	      request_opcode == 4'd2 ||
	      request_opcode == 4'd4) ||
	     WILL_FIRE_RL_handle_ready_check ||
	     WILL_FIRE_RL_handle_computation_done ;

  // register response_reg
  always@(WILL_FIRE_RL_perform_buffered_write or
	  MUX_response_reg$write_1__VAL_1 or
	  WILL_FIRE_RL_handle_ready_check or
	  MUX_response_reg$write_1__VAL_2 or
	  WILL_FIRE_RL_handle_computation_done or
	  MUX_response_reg$write_1__VAL_3 or
	  MUX_response_reg$write_1__SEL_4 or MUX_response_reg$write_1__VAL_4)
  case (1'b1)
    WILL_FIRE_RL_perform_buffered_write:
	response_reg$D_IN = MUX_response_reg$write_1__VAL_1;
    WILL_FIRE_RL_handle_ready_check:
	response_reg$D_IN = MUX_response_reg$write_1__VAL_2;
    WILL_FIRE_RL_handle_computation_done:
	response_reg$D_IN = MUX_response_reg$write_1__VAL_3;
    MUX_response_reg$write_1__SEL_4:
	response_reg$D_IN = MUX_response_reg$write_1__VAL_4;
    default: response_reg$D_IN =
		 16'b1010101010101010 /* unspecified value */ ;
  endcase
  assign response_reg$EN =
	     EN_request && request_opcode != 4'd1 && request_opcode != 4'd4 ||
	     WILL_FIRE_RL_handle_computation_done ||
	     WILL_FIRE_RL_handle_ready_check ||
	     WILL_FIRE_RL_perform_buffered_write ;

  // register response_valid_reg
  assign response_valid_reg$D_IN = 1'd1 ;
  assign response_valid_reg$EN =
	     EN_request && request_opcode != 4'd1 && request_opcode != 4'd4 ||
	     WILL_FIRE_RL_perform_buffered_write ||
	     WILL_FIRE_RL_handle_ready_check ||
	     WILL_FIRE_RL_handle_computation_done ;

  // register stream_buffer_0
  assign stream_buffer_0$D_IN = request_data_in ;
  assign stream_buffer_0$EN =
	     EN_request && buffer_index == 9'd0 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_1
  assign stream_buffer_1$D_IN = request_data_in ;
  assign stream_buffer_1$EN =
	     EN_request && buffer_index == 9'd1 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_10
  assign stream_buffer_10$D_IN = request_data_in ;
  assign stream_buffer_10$EN =
	     EN_request && buffer_index == 9'd10 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_11
  assign stream_buffer_11$D_IN = request_data_in ;
  assign stream_buffer_11$EN =
	     EN_request && buffer_index == 9'd11 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_12
  assign stream_buffer_12$D_IN = request_data_in ;
  assign stream_buffer_12$EN =
	     EN_request && buffer_index == 9'd12 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_13
  assign stream_buffer_13$D_IN = request_data_in ;
  assign stream_buffer_13$EN =
	     EN_request && buffer_index == 9'd13 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_14
  assign stream_buffer_14$D_IN = request_data_in ;
  assign stream_buffer_14$EN =
	     EN_request && buffer_index == 9'd14 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_15
  assign stream_buffer_15$D_IN = request_data_in ;
  assign stream_buffer_15$EN =
	     EN_request && buffer_index == 9'd15 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_2
  assign stream_buffer_2$D_IN = request_data_in ;
  assign stream_buffer_2$EN =
	     EN_request && buffer_index == 9'd2 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_3
  assign stream_buffer_3$D_IN = request_data_in ;
  assign stream_buffer_3$EN =
	     EN_request && buffer_index == 9'd3 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_4
  assign stream_buffer_4$D_IN = request_data_in ;
  assign stream_buffer_4$EN =
	     EN_request && buffer_index == 9'd4 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_5
  assign stream_buffer_5$D_IN = request_data_in ;
  assign stream_buffer_5$EN =
	     EN_request && buffer_index == 9'd5 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_6
  assign stream_buffer_6$D_IN = request_data_in ;
  assign stream_buffer_6$EN =
	     EN_request && buffer_index == 9'd6 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_7
  assign stream_buffer_7$D_IN = request_data_in ;
  assign stream_buffer_7$EN =
	     EN_request && buffer_index == 9'd7 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_8
  assign stream_buffer_8$D_IN = request_data_in ;
  assign stream_buffer_8$EN =
	     EN_request && buffer_index == 9'd8 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register stream_buffer_9
  assign stream_buffer_9$D_IN = request_data_in ;
  assign stream_buffer_9$EN =
	     EN_request && buffer_index == 9'd9 && request_opcode == 4'd3 &&
	     writing_bram &&
	     write_index < 9'd256 ;

  // register write_complete
  assign write_complete$D_IN = MUX_current_op$write_1__SEL_1 ;
  assign write_complete$EN =
	     WILL_FIRE_RL_perform_buffered_write && write_index == 9'd256 ||
	     EN_request && request_opcode == 4'd2 ;

  // register write_index
  assign write_index$D_IN =
	     MUX_current_op$write_1__SEL_1 ?
	       9'd0 :
	       MUX_write_index$write_1__VAL_2 ;
  assign write_index$EN =
	     WILL_FIRE_RL_perform_buffered_write && write_index == 9'd256 ||
	     EN_request && request_opcode != 4'd0 && request_opcode != 4'd1 &&
	     request_opcode_EQ_2_0_OR_request_opcode_EQ_3_1_ETC___d54 ;

  // register writing_bram
  assign writing_bram$D_IN = !MUX_current_op$write_1__SEL_1 ;
  assign writing_bram$EN =
	     WILL_FIRE_RL_perform_buffered_write && write_index == 9'd256 ||
	     EN_request && request_opcode == 4'd2 ;

  // submodule cop
  assign cop$write_bram_base_addr = 10'h0 ;
  assign cop$write_bram_bram_id = 4'h0 ;
  assign cop$write_bram_data = 4096'h0 ;
  assign cop$EN_start_computation = EN_request && request_opcode == 4'd0 ;
  assign cop$EN_write_bram = 1'b0 ;

  // remaining internal signals
  assign IF_writing_bram_2_AND_write_index_6_ULT_256_2__ETC___d42 =
	     (writing_bram && write_index < 9'd256) ?
	       ((buffer_index == 9'd15) ? 16'hBFF0 : x__h3474) :
	       16'h0 ;
  assign request_opcode_EQ_2_0_OR_request_opcode_EQ_3_1_ETC___d54 =
	     request_opcode == 4'd2 ||
	     request_opcode == 4'd3 && writing_bram && write_index < 9'd256 ;
  assign x__h1893 = { 11'd1383, write_index[4:0] } ;
  assign x__h3326 = buffer_index + 9'd1 ;
  assign x__h3375 = write_index + 9'd1 ;
  assign x__h3474 =
	     { 7'd109,
	       buffer_index[8:7],
	       4'd15,
	       buffer_index[2],
	       1'd1,
	       buffer_index[0] } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        bram_addr_reg <= `BSV_ASSIGNMENT_DELAY 10'd0;
	bram_id_reg <= `BSV_ASSIGNMENT_DELAY 4'd0;
	buffer_index <= `BSV_ASSIGNMENT_DELAY 9'd0;
	current_op <= `BSV_ASSIGNMENT_DELAY 4'd15;
	response_reg <= `BSV_ASSIGNMENT_DELAY 16'd0;
	response_valid_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	stream_buffer_0 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_10 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_11 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_12 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_13 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_14 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_15 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_2 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_3 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_4 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_5 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_6 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_7 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_8 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	stream_buffer_9 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	write_complete <= `BSV_ASSIGNMENT_DELAY 1'd0;
	write_index <= `BSV_ASSIGNMENT_DELAY 9'd0;
	writing_bram <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (bram_addr_reg$EN)
	  bram_addr_reg <= `BSV_ASSIGNMENT_DELAY bram_addr_reg$D_IN;
	if (bram_id_reg$EN)
	  bram_id_reg <= `BSV_ASSIGNMENT_DELAY bram_id_reg$D_IN;
	if (buffer_index$EN)
	  buffer_index <= `BSV_ASSIGNMENT_DELAY buffer_index$D_IN;
	if (current_op$EN)
	  current_op <= `BSV_ASSIGNMENT_DELAY current_op$D_IN;
	if (response_reg$EN)
	  response_reg <= `BSV_ASSIGNMENT_DELAY response_reg$D_IN;
	if (response_valid_reg$EN)
	  response_valid_reg <= `BSV_ASSIGNMENT_DELAY response_valid_reg$D_IN;
	if (stream_buffer_0$EN)
	  stream_buffer_0 <= `BSV_ASSIGNMENT_DELAY stream_buffer_0$D_IN;
	if (stream_buffer_1$EN)
	  stream_buffer_1 <= `BSV_ASSIGNMENT_DELAY stream_buffer_1$D_IN;
	if (stream_buffer_10$EN)
	  stream_buffer_10 <= `BSV_ASSIGNMENT_DELAY stream_buffer_10$D_IN;
	if (stream_buffer_11$EN)
	  stream_buffer_11 <= `BSV_ASSIGNMENT_DELAY stream_buffer_11$D_IN;
	if (stream_buffer_12$EN)
	  stream_buffer_12 <= `BSV_ASSIGNMENT_DELAY stream_buffer_12$D_IN;
	if (stream_buffer_13$EN)
	  stream_buffer_13 <= `BSV_ASSIGNMENT_DELAY stream_buffer_13$D_IN;
	if (stream_buffer_14$EN)
	  stream_buffer_14 <= `BSV_ASSIGNMENT_DELAY stream_buffer_14$D_IN;
	if (stream_buffer_15$EN)
	  stream_buffer_15 <= `BSV_ASSIGNMENT_DELAY stream_buffer_15$D_IN;
	if (stream_buffer_2$EN)
	  stream_buffer_2 <= `BSV_ASSIGNMENT_DELAY stream_buffer_2$D_IN;
	if (stream_buffer_3$EN)
	  stream_buffer_3 <= `BSV_ASSIGNMENT_DELAY stream_buffer_3$D_IN;
	if (stream_buffer_4$EN)
	  stream_buffer_4 <= `BSV_ASSIGNMENT_DELAY stream_buffer_4$D_IN;
	if (stream_buffer_5$EN)
	  stream_buffer_5 <= `BSV_ASSIGNMENT_DELAY stream_buffer_5$D_IN;
	if (stream_buffer_6$EN)
	  stream_buffer_6 <= `BSV_ASSIGNMENT_DELAY stream_buffer_6$D_IN;
	if (stream_buffer_7$EN)
	  stream_buffer_7 <= `BSV_ASSIGNMENT_DELAY stream_buffer_7$D_IN;
	if (stream_buffer_8$EN)
	  stream_buffer_8 <= `BSV_ASSIGNMENT_DELAY stream_buffer_8$D_IN;
	if (stream_buffer_9$EN)
	  stream_buffer_9 <= `BSV_ASSIGNMENT_DELAY stream_buffer_9$D_IN;
	if (write_complete$EN)
	  write_complete <= `BSV_ASSIGNMENT_DELAY write_complete$D_IN;
	if (write_index$EN)
	  write_index <= `BSV_ASSIGNMENT_DELAY write_index$D_IN;
	if (writing_bram$EN)
	  writing_bram <= `BSV_ASSIGNMENT_DELAY writing_bram$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    bram_addr_reg = 10'h2AA;
    bram_id_reg = 4'hA;
    buffer_index = 9'h0AA;
    current_op = 4'hA;
    response_reg = 16'hAAAA;
    response_valid_reg = 1'h0;
    stream_buffer_0 = 16'hAAAA;
    stream_buffer_1 = 16'hAAAA;
    stream_buffer_10 = 16'hAAAA;
    stream_buffer_11 = 16'hAAAA;
    stream_buffer_12 = 16'hAAAA;
    stream_buffer_13 = 16'hAAAA;
    stream_buffer_14 = 16'hAAAA;
    stream_buffer_15 = 16'hAAAA;
    stream_buffer_2 = 16'hAAAA;
    stream_buffer_3 = 16'hAAAA;
    stream_buffer_4 = 16'hAAAA;
    stream_buffer_5 = 16'hAAAA;
    stream_buffer_6 = 16'hAAAA;
    stream_buffer_7 = 16'hAAAA;
    stream_buffer_8 = 16'hAAAA;
    stream_buffer_9 = 16'hAAAA;
    write_complete = 1'h0;
    write_index = 9'h0AA;
    writing_bram = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request && request_opcode == 4'd2)
	$display("WRAPPER: Starting BRAM write - BRAM %0d, base_addr %0d",
		 request_data_in[15:12],
		 request_data_in[11:2]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_perform_buffered_write && write_index == 9'd256)
	$display("WRAPPER: Completed BRAM write for BRAM %0d at base_addr %0d",
		 bram_id_reg,
		 bram_addr_reg);
  end
  // synopsys translate_on
endmodule  // mkCOP_Wrapper

