//
// Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
//
// On Sun Nov  2 15:22:00 UTC 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_start_computation          O     1
// get_result                     O  1024 reg
// RDY_get_result                 O     1
// computation_done               O     1
// RDY_computation_done           O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// start_computation_a            I  1024 reg
// start_computation_b            I  1024 reg
// start_computation_c            I  1024 reg
// start_computation_d            I  1024 reg
// EN_start_computation           I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBF16_SIMD(CLK,
		   RST_N,

		   start_computation_a,
		   start_computation_b,
		   start_computation_c,
		   start_computation_d,
		   EN_start_computation,
		   RDY_start_computation,

		   get_result,
		   RDY_get_result,

		   computation_done,
		   RDY_computation_done);
  input  CLK;
  input  RST_N;

  // action method start_computation
  input  [1023 : 0] start_computation_a;
  input  [1023 : 0] start_computation_b;
  input  [1023 : 0] start_computation_c;
  input  [1023 : 0] start_computation_d;
  input  EN_start_computation;
  output RDY_start_computation;

  // value method get_result
  output [1023 : 0] get_result;
  output RDY_get_result;

  // value method computation_done
  output computation_done;
  output RDY_computation_done;

  // signals for module outputs
  wire [1023 : 0] get_result;
  wire RDY_computation_done,
       RDY_get_result,
       RDY_start_computation,
       computation_done;

  // register active
  reg active;
  wire active$D_IN, active$EN;

  // register complete_count
  reg [6 : 0] complete_count;
  wire [6 : 0] complete_count$D_IN;
  wire complete_count$EN;

  // register issue_index
  reg [6 : 0] issue_index;
  wire [6 : 0] issue_index$D_IN;
  wire issue_index$EN;

  // register pipeline_stage
  reg [39 : 0] pipeline_stage;
  wire [39 : 0] pipeline_stage$D_IN;
  wire pipeline_stage$EN;

  // register reg_a
  reg [1023 : 0] reg_a;
  wire [1023 : 0] reg_a$D_IN;
  wire reg_a$EN;

  // register reg_b
  reg [1023 : 0] reg_b;
  wire [1023 : 0] reg_b$D_IN;
  wire reg_b$EN;

  // register reg_c
  reg [1023 : 0] reg_c;
  wire [1023 : 0] reg_c$D_IN;
  wire reg_c$EN;

  // register reg_d
  reg [1023 : 0] reg_d;
  wire [1023 : 0] reg_d$D_IN;
  wire reg_d$EN;

  // register result_regs_0
  reg [15 : 0] result_regs_0;
  wire [15 : 0] result_regs_0$D_IN;
  wire result_regs_0$EN;

  // register result_regs_1
  reg [15 : 0] result_regs_1;
  wire [15 : 0] result_regs_1$D_IN;
  wire result_regs_1$EN;

  // register result_regs_10
  reg [15 : 0] result_regs_10;
  wire [15 : 0] result_regs_10$D_IN;
  wire result_regs_10$EN;

  // register result_regs_11
  reg [15 : 0] result_regs_11;
  wire [15 : 0] result_regs_11$D_IN;
  wire result_regs_11$EN;

  // register result_regs_12
  reg [15 : 0] result_regs_12;
  wire [15 : 0] result_regs_12$D_IN;
  wire result_regs_12$EN;

  // register result_regs_13
  reg [15 : 0] result_regs_13;
  wire [15 : 0] result_regs_13$D_IN;
  wire result_regs_13$EN;

  // register result_regs_14
  reg [15 : 0] result_regs_14;
  wire [15 : 0] result_regs_14$D_IN;
  wire result_regs_14$EN;

  // register result_regs_15
  reg [15 : 0] result_regs_15;
  wire [15 : 0] result_regs_15$D_IN;
  wire result_regs_15$EN;

  // register result_regs_16
  reg [15 : 0] result_regs_16;
  wire [15 : 0] result_regs_16$D_IN;
  wire result_regs_16$EN;

  // register result_regs_17
  reg [15 : 0] result_regs_17;
  wire [15 : 0] result_regs_17$D_IN;
  wire result_regs_17$EN;

  // register result_regs_18
  reg [15 : 0] result_regs_18;
  wire [15 : 0] result_regs_18$D_IN;
  wire result_regs_18$EN;

  // register result_regs_19
  reg [15 : 0] result_regs_19;
  wire [15 : 0] result_regs_19$D_IN;
  wire result_regs_19$EN;

  // register result_regs_2
  reg [15 : 0] result_regs_2;
  wire [15 : 0] result_regs_2$D_IN;
  wire result_regs_2$EN;

  // register result_regs_20
  reg [15 : 0] result_regs_20;
  wire [15 : 0] result_regs_20$D_IN;
  wire result_regs_20$EN;

  // register result_regs_21
  reg [15 : 0] result_regs_21;
  wire [15 : 0] result_regs_21$D_IN;
  wire result_regs_21$EN;

  // register result_regs_22
  reg [15 : 0] result_regs_22;
  wire [15 : 0] result_regs_22$D_IN;
  wire result_regs_22$EN;

  // register result_regs_23
  reg [15 : 0] result_regs_23;
  wire [15 : 0] result_regs_23$D_IN;
  wire result_regs_23$EN;

  // register result_regs_24
  reg [15 : 0] result_regs_24;
  wire [15 : 0] result_regs_24$D_IN;
  wire result_regs_24$EN;

  // register result_regs_25
  reg [15 : 0] result_regs_25;
  wire [15 : 0] result_regs_25$D_IN;
  wire result_regs_25$EN;

  // register result_regs_26
  reg [15 : 0] result_regs_26;
  wire [15 : 0] result_regs_26$D_IN;
  wire result_regs_26$EN;

  // register result_regs_27
  reg [15 : 0] result_regs_27;
  wire [15 : 0] result_regs_27$D_IN;
  wire result_regs_27$EN;

  // register result_regs_28
  reg [15 : 0] result_regs_28;
  wire [15 : 0] result_regs_28$D_IN;
  wire result_regs_28$EN;

  // register result_regs_29
  reg [15 : 0] result_regs_29;
  wire [15 : 0] result_regs_29$D_IN;
  wire result_regs_29$EN;

  // register result_regs_3
  reg [15 : 0] result_regs_3;
  wire [15 : 0] result_regs_3$D_IN;
  wire result_regs_3$EN;

  // register result_regs_30
  reg [15 : 0] result_regs_30;
  wire [15 : 0] result_regs_30$D_IN;
  wire result_regs_30$EN;

  // register result_regs_31
  reg [15 : 0] result_regs_31;
  wire [15 : 0] result_regs_31$D_IN;
  wire result_regs_31$EN;

  // register result_regs_32
  reg [15 : 0] result_regs_32;
  wire [15 : 0] result_regs_32$D_IN;
  wire result_regs_32$EN;

  // register result_regs_33
  reg [15 : 0] result_regs_33;
  wire [15 : 0] result_regs_33$D_IN;
  wire result_regs_33$EN;

  // register result_regs_34
  reg [15 : 0] result_regs_34;
  wire [15 : 0] result_regs_34$D_IN;
  wire result_regs_34$EN;

  // register result_regs_35
  reg [15 : 0] result_regs_35;
  wire [15 : 0] result_regs_35$D_IN;
  wire result_regs_35$EN;

  // register result_regs_36
  reg [15 : 0] result_regs_36;
  wire [15 : 0] result_regs_36$D_IN;
  wire result_regs_36$EN;

  // register result_regs_37
  reg [15 : 0] result_regs_37;
  wire [15 : 0] result_regs_37$D_IN;
  wire result_regs_37$EN;

  // register result_regs_38
  reg [15 : 0] result_regs_38;
  wire [15 : 0] result_regs_38$D_IN;
  wire result_regs_38$EN;

  // register result_regs_39
  reg [15 : 0] result_regs_39;
  wire [15 : 0] result_regs_39$D_IN;
  wire result_regs_39$EN;

  // register result_regs_4
  reg [15 : 0] result_regs_4;
  wire [15 : 0] result_regs_4$D_IN;
  wire result_regs_4$EN;

  // register result_regs_40
  reg [15 : 0] result_regs_40;
  wire [15 : 0] result_regs_40$D_IN;
  wire result_regs_40$EN;

  // register result_regs_41
  reg [15 : 0] result_regs_41;
  wire [15 : 0] result_regs_41$D_IN;
  wire result_regs_41$EN;

  // register result_regs_42
  reg [15 : 0] result_regs_42;
  wire [15 : 0] result_regs_42$D_IN;
  wire result_regs_42$EN;

  // register result_regs_43
  reg [15 : 0] result_regs_43;
  wire [15 : 0] result_regs_43$D_IN;
  wire result_regs_43$EN;

  // register result_regs_44
  reg [15 : 0] result_regs_44;
  wire [15 : 0] result_regs_44$D_IN;
  wire result_regs_44$EN;

  // register result_regs_45
  reg [15 : 0] result_regs_45;
  wire [15 : 0] result_regs_45$D_IN;
  wire result_regs_45$EN;

  // register result_regs_46
  reg [15 : 0] result_regs_46;
  wire [15 : 0] result_regs_46$D_IN;
  wire result_regs_46$EN;

  // register result_regs_47
  reg [15 : 0] result_regs_47;
  wire [15 : 0] result_regs_47$D_IN;
  wire result_regs_47$EN;

  // register result_regs_48
  reg [15 : 0] result_regs_48;
  wire [15 : 0] result_regs_48$D_IN;
  wire result_regs_48$EN;

  // register result_regs_49
  reg [15 : 0] result_regs_49;
  wire [15 : 0] result_regs_49$D_IN;
  wire result_regs_49$EN;

  // register result_regs_5
  reg [15 : 0] result_regs_5;
  wire [15 : 0] result_regs_5$D_IN;
  wire result_regs_5$EN;

  // register result_regs_50
  reg [15 : 0] result_regs_50;
  wire [15 : 0] result_regs_50$D_IN;
  wire result_regs_50$EN;

  // register result_regs_51
  reg [15 : 0] result_regs_51;
  wire [15 : 0] result_regs_51$D_IN;
  wire result_regs_51$EN;

  // register result_regs_52
  reg [15 : 0] result_regs_52;
  wire [15 : 0] result_regs_52$D_IN;
  wire result_regs_52$EN;

  // register result_regs_53
  reg [15 : 0] result_regs_53;
  wire [15 : 0] result_regs_53$D_IN;
  wire result_regs_53$EN;

  // register result_regs_54
  reg [15 : 0] result_regs_54;
  wire [15 : 0] result_regs_54$D_IN;
  wire result_regs_54$EN;

  // register result_regs_55
  reg [15 : 0] result_regs_55;
  wire [15 : 0] result_regs_55$D_IN;
  wire result_regs_55$EN;

  // register result_regs_56
  reg [15 : 0] result_regs_56;
  wire [15 : 0] result_regs_56$D_IN;
  wire result_regs_56$EN;

  // register result_regs_57
  reg [15 : 0] result_regs_57;
  wire [15 : 0] result_regs_57$D_IN;
  wire result_regs_57$EN;

  // register result_regs_58
  reg [15 : 0] result_regs_58;
  wire [15 : 0] result_regs_58$D_IN;
  wire result_regs_58$EN;

  // register result_regs_59
  reg [15 : 0] result_regs_59;
  wire [15 : 0] result_regs_59$D_IN;
  wire result_regs_59$EN;

  // register result_regs_6
  reg [15 : 0] result_regs_6;
  wire [15 : 0] result_regs_6$D_IN;
  wire result_regs_6$EN;

  // register result_regs_60
  reg [15 : 0] result_regs_60;
  wire [15 : 0] result_regs_60$D_IN;
  wire result_regs_60$EN;

  // register result_regs_61
  reg [15 : 0] result_regs_61;
  wire [15 : 0] result_regs_61$D_IN;
  wire result_regs_61$EN;

  // register result_regs_62
  reg [15 : 0] result_regs_62;
  wire [15 : 0] result_regs_62$D_IN;
  wire result_regs_62$EN;

  // register result_regs_63
  reg [15 : 0] result_regs_63;
  wire [15 : 0] result_regs_63$D_IN;
  wire result_regs_63$EN;

  // register result_regs_7
  reg [15 : 0] result_regs_7;
  wire [15 : 0] result_regs_7$D_IN;
  wire result_regs_7$EN;

  // register result_regs_8
  reg [15 : 0] result_regs_8;
  wire [15 : 0] result_regs_8$D_IN;
  wire result_regs_8$EN;

  // register result_regs_9
  reg [15 : 0] result_regs_9;
  wire [15 : 0] result_regs_9$D_IN;
  wire result_regs_9$EN;

  // inputs to muxes for submodule ports
  wire [6 : 0] MUX_complete_count$write_1__VAL_1,
	       MUX_issue_index$write_1__VAL_1;
  wire MUX_active$write_1__SEL_1,
       MUX_complete_count$write_1__SEL_1,
       MUX_issue_index$write_1__SEL_1;

  // remaining internal signals
  reg [7 : 0] x__h18911, x__h18913, x__h26010, x__h26012;
  reg [6 : 0] a_mantissa__h11974,
	      a_mantissa__h19076,
	      b_mantissa__h15422,
	      b_mantissa__h22521;
  reg a_sign__h11972, a_sign__h19074, b_sign__h15420, b_sign__h22519;
  wire [31 : 0] _1_CONCAT_SEL_ARR_reg_a_05_BITS_6_TO_0_80_reg_a_ETC___d614,
		_1_CONCAT_SEL_ARR_reg_c_30_BITS_6_TO_0_05_reg_c_ETC___d1039;
  wire [15 : 0] IF_pipeline_stage_BITS_15_TO_0_EQ_0x0_0_THEN_p_ETC___d70,
		result__h7351,
		x__h11949,
		x__h19051;
  wire [14 : 0] IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d63,
		IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d64,
		IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d65,
		IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d67;
  wire [8 : 0] _1_CONCAT_IF_pipeline_stage_BITS_30_TO_23_2_ULT_ETC___d23,
	       _theResult____h7167,
	       exp_sum__h11963,
	       exp_sum__h19065,
	       man_result__h7262,
	       man_result__h7337,
	       raw_exp__h11964,
	       raw_exp__h19066,
	       x__h19006,
	       x__h26105;
  wire [7 : 0] _theResult___fst__h19000,
	       _theResult___fst__h26099,
	       exp_diff__h7162,
	       final_exp___1__h7382,
	       final_exp__h18925,
	       final_exp__h26024,
	       final_exp__h7440,
	       final_exp__h7469,
	       final_exp__h7498,
	       final_exp__h7500,
	       larger_exp__h7216,
	       result_exp__h18863,
	       result_exp__h25962,
	       shift_amount__h7163,
	       shifted_smaller__h7164,
	       smaller_exp__h7257,
	       smaller_man__h7161,
	       val_exp__h18865,
	       val_exp__h25964;
  wire [6 : 0] _theResult___snd__h19001,
	       _theResult___snd__h26100,
	       final_mantissa__h7441,
	       final_mantissa__h7470,
	       final_mantissa__h7499,
	       final_mantissa__h7501,
	       val_mantissa__h18866,
	       val_mantissa__h25965;
  wire _0_CONCAT_SEL_ARR_reg_a_05_BITS_14_TO_7_40_reg__ETC___d479,
       _0_CONCAT_SEL_ARR_reg_c_30_BITS_14_TO_7_65_reg__ETC___d904,
       issue_index_03_ULT_64___d204,
       larger_sign__h7215,
       pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14,
       result_sign__h11959,
       result_sign__h19061,
       smaller_sign__h7256;

  // action method start_computation
  assign RDY_start_computation = !active ;

  // value method get_result
  assign get_result =
	     { result_regs_63,
	       result_regs_62,
	       result_regs_61,
	       result_regs_60,
	       result_regs_59,
	       result_regs_58,
	       result_regs_57,
	       result_regs_56,
	       result_regs_55,
	       result_regs_54,
	       result_regs_53,
	       result_regs_52,
	       result_regs_51,
	       result_regs_50,
	       result_regs_49,
	       result_regs_48,
	       result_regs_47,
	       result_regs_46,
	       result_regs_45,
	       result_regs_44,
	       result_regs_43,
	       result_regs_42,
	       result_regs_41,
	       result_regs_40,
	       result_regs_39,
	       result_regs_38,
	       result_regs_37,
	       result_regs_36,
	       result_regs_35,
	       result_regs_34,
	       result_regs_33,
	       result_regs_32,
	       result_regs_31,
	       result_regs_30,
	       result_regs_29,
	       result_regs_28,
	       result_regs_27,
	       result_regs_26,
	       result_regs_25,
	       result_regs_24,
	       result_regs_23,
	       result_regs_22,
	       result_regs_21,
	       result_regs_20,
	       result_regs_19,
	       result_regs_18,
	       result_regs_17,
	       result_regs_16,
	       result_regs_15,
	       result_regs_14,
	       result_regs_13,
	       result_regs_12,
	       result_regs_11,
	       result_regs_10,
	       result_regs_9,
	       result_regs_8,
	       result_regs_7,
	       result_regs_6,
	       result_regs_5,
	       result_regs_4,
	       result_regs_3,
	       result_regs_2,
	       result_regs_1,
	       result_regs_0 } ;
  assign RDY_get_result = !active && complete_count == 7'd64 ;

  // value method computation_done
  assign computation_done = !active && complete_count == 7'd64 ;
  assign RDY_computation_done = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_active$write_1__SEL_1 =
	     active && pipeline_stage[39] && complete_count == 7'd63 ;
  assign MUX_complete_count$write_1__SEL_1 = active && pipeline_stage[39] ;
  assign MUX_issue_index$write_1__SEL_1 =
	     active && issue_index_03_ULT_64___d204 ;
  assign MUX_complete_count$write_1__VAL_1 = complete_count + 7'd1 ;
  assign MUX_issue_index$write_1__VAL_1 = issue_index + 7'd1 ;

  // register active
  assign active$D_IN = !MUX_active$write_1__SEL_1 ;
  assign active$EN =
	     active && pipeline_stage[39] && complete_count == 7'd63 ||
	     EN_start_computation ;

  // register complete_count
  assign complete_count$D_IN =
	     MUX_complete_count$write_1__SEL_1 ?
	       MUX_complete_count$write_1__VAL_1 :
	       7'd0 ;
  assign complete_count$EN =
	     active && pipeline_stage[39] || EN_start_computation ;

  // register issue_index
  assign issue_index$D_IN =
	     MUX_issue_index$write_1__SEL_1 ?
	       MUX_issue_index$write_1__VAL_1 :
	       7'd0 ;
  assign issue_index$EN =
	     active && issue_index_03_ULT_64___d204 || EN_start_computation ;

  // register pipeline_stage
  assign pipeline_stage$D_IN =
	     { issue_index_03_ULT_64___d204,
	       issue_index,
	       x__h11949,
	       x__h19051 } ;
  assign pipeline_stage$EN = active ;

  // register reg_a
  assign reg_a$D_IN = start_computation_a ;
  assign reg_a$EN = EN_start_computation ;

  // register reg_b
  assign reg_b$D_IN = start_computation_b ;
  assign reg_b$EN = EN_start_computation ;

  // register reg_c
  assign reg_c$D_IN = start_computation_c ;
  assign reg_c$EN = EN_start_computation ;

  // register reg_d
  assign reg_d$D_IN = start_computation_d ;
  assign reg_d$EN = EN_start_computation ;

  // register result_regs_0
  assign result_regs_0$D_IN =
	     (pipeline_stage[31:16] == 16'h0 &&
	      pipeline_stage[15:0] == 16'h0) ?
	       16'h0 :
	       ((pipeline_stage[31:16] == 16'h0) ?
		  pipeline_stage[15:0] :
		  IF_pipeline_stage_BITS_15_TO_0_EQ_0x0_0_THEN_p_ETC___d70) ;
  assign result_regs_0$EN =
	     active && pipeline_stage[38:32] == 7'd0 && pipeline_stage[39] ;

  // register result_regs_1
  assign result_regs_1$D_IN = result_regs_0$D_IN ;
  assign result_regs_1$EN =
	     active && pipeline_stage[38:32] == 7'd1 && pipeline_stage[39] ;

  // register result_regs_10
  assign result_regs_10$D_IN = result_regs_0$D_IN ;
  assign result_regs_10$EN =
	     active && pipeline_stage[38:32] == 7'd10 && pipeline_stage[39] ;

  // register result_regs_11
  assign result_regs_11$D_IN = result_regs_0$D_IN ;
  assign result_regs_11$EN =
	     active && pipeline_stage[38:32] == 7'd11 && pipeline_stage[39] ;

  // register result_regs_12
  assign result_regs_12$D_IN = result_regs_0$D_IN ;
  assign result_regs_12$EN =
	     active && pipeline_stage[38:32] == 7'd12 && pipeline_stage[39] ;

  // register result_regs_13
  assign result_regs_13$D_IN = result_regs_0$D_IN ;
  assign result_regs_13$EN =
	     active && pipeline_stage[38:32] == 7'd13 && pipeline_stage[39] ;

  // register result_regs_14
  assign result_regs_14$D_IN = result_regs_0$D_IN ;
  assign result_regs_14$EN =
	     active && pipeline_stage[38:32] == 7'd14 && pipeline_stage[39] ;

  // register result_regs_15
  assign result_regs_15$D_IN = result_regs_0$D_IN ;
  assign result_regs_15$EN =
	     active && pipeline_stage[38:32] == 7'd15 && pipeline_stage[39] ;

  // register result_regs_16
  assign result_regs_16$D_IN = result_regs_0$D_IN ;
  assign result_regs_16$EN =
	     active && pipeline_stage[38:32] == 7'd16 && pipeline_stage[39] ;

  // register result_regs_17
  assign result_regs_17$D_IN = result_regs_0$D_IN ;
  assign result_regs_17$EN =
	     active && pipeline_stage[38:32] == 7'd17 && pipeline_stage[39] ;

  // register result_regs_18
  assign result_regs_18$D_IN = result_regs_0$D_IN ;
  assign result_regs_18$EN =
	     active && pipeline_stage[38:32] == 7'd18 && pipeline_stage[39] ;

  // register result_regs_19
  assign result_regs_19$D_IN = result_regs_0$D_IN ;
  assign result_regs_19$EN =
	     active && pipeline_stage[38:32] == 7'd19 && pipeline_stage[39] ;

  // register result_regs_2
  assign result_regs_2$D_IN = result_regs_0$D_IN ;
  assign result_regs_2$EN =
	     active && pipeline_stage[38:32] == 7'd2 && pipeline_stage[39] ;

  // register result_regs_20
  assign result_regs_20$D_IN = result_regs_0$D_IN ;
  assign result_regs_20$EN =
	     active && pipeline_stage[38:32] == 7'd20 && pipeline_stage[39] ;

  // register result_regs_21
  assign result_regs_21$D_IN = result_regs_0$D_IN ;
  assign result_regs_21$EN =
	     active && pipeline_stage[38:32] == 7'd21 && pipeline_stage[39] ;

  // register result_regs_22
  assign result_regs_22$D_IN = result_regs_0$D_IN ;
  assign result_regs_22$EN =
	     active && pipeline_stage[38:32] == 7'd22 && pipeline_stage[39] ;

  // register result_regs_23
  assign result_regs_23$D_IN = result_regs_0$D_IN ;
  assign result_regs_23$EN =
	     active && pipeline_stage[38:32] == 7'd23 && pipeline_stage[39] ;

  // register result_regs_24
  assign result_regs_24$D_IN = result_regs_0$D_IN ;
  assign result_regs_24$EN =
	     active && pipeline_stage[38:32] == 7'd24 && pipeline_stage[39] ;

  // register result_regs_25
  assign result_regs_25$D_IN = result_regs_0$D_IN ;
  assign result_regs_25$EN =
	     active && pipeline_stage[38:32] == 7'd25 && pipeline_stage[39] ;

  // register result_regs_26
  assign result_regs_26$D_IN = result_regs_0$D_IN ;
  assign result_regs_26$EN =
	     active && pipeline_stage[38:32] == 7'd26 && pipeline_stage[39] ;

  // register result_regs_27
  assign result_regs_27$D_IN = result_regs_0$D_IN ;
  assign result_regs_27$EN =
	     active && pipeline_stage[38:32] == 7'd27 && pipeline_stage[39] ;

  // register result_regs_28
  assign result_regs_28$D_IN = result_regs_0$D_IN ;
  assign result_regs_28$EN =
	     active && pipeline_stage[38:32] == 7'd28 && pipeline_stage[39] ;

  // register result_regs_29
  assign result_regs_29$D_IN = result_regs_0$D_IN ;
  assign result_regs_29$EN =
	     active && pipeline_stage[38:32] == 7'd29 && pipeline_stage[39] ;

  // register result_regs_3
  assign result_regs_3$D_IN = result_regs_0$D_IN ;
  assign result_regs_3$EN =
	     active && pipeline_stage[38:32] == 7'd3 && pipeline_stage[39] ;

  // register result_regs_30
  assign result_regs_30$D_IN = result_regs_0$D_IN ;
  assign result_regs_30$EN =
	     active && pipeline_stage[38:32] == 7'd30 && pipeline_stage[39] ;

  // register result_regs_31
  assign result_regs_31$D_IN = result_regs_0$D_IN ;
  assign result_regs_31$EN =
	     active && pipeline_stage[38:32] == 7'd31 && pipeline_stage[39] ;

  // register result_regs_32
  assign result_regs_32$D_IN = result_regs_0$D_IN ;
  assign result_regs_32$EN =
	     active && pipeline_stage[38:32] == 7'd32 && pipeline_stage[39] ;

  // register result_regs_33
  assign result_regs_33$D_IN = result_regs_0$D_IN ;
  assign result_regs_33$EN =
	     active && pipeline_stage[38:32] == 7'd33 && pipeline_stage[39] ;

  // register result_regs_34
  assign result_regs_34$D_IN = result_regs_0$D_IN ;
  assign result_regs_34$EN =
	     active && pipeline_stage[38:32] == 7'd34 && pipeline_stage[39] ;

  // register result_regs_35
  assign result_regs_35$D_IN = result_regs_0$D_IN ;
  assign result_regs_35$EN =
	     active && pipeline_stage[38:32] == 7'd35 && pipeline_stage[39] ;

  // register result_regs_36
  assign result_regs_36$D_IN = result_regs_0$D_IN ;
  assign result_regs_36$EN =
	     active && pipeline_stage[38:32] == 7'd36 && pipeline_stage[39] ;

  // register result_regs_37
  assign result_regs_37$D_IN = result_regs_0$D_IN ;
  assign result_regs_37$EN =
	     active && pipeline_stage[38:32] == 7'd37 && pipeline_stage[39] ;

  // register result_regs_38
  assign result_regs_38$D_IN = result_regs_0$D_IN ;
  assign result_regs_38$EN =
	     active && pipeline_stage[38:32] == 7'd38 && pipeline_stage[39] ;

  // register result_regs_39
  assign result_regs_39$D_IN = result_regs_0$D_IN ;
  assign result_regs_39$EN =
	     active && pipeline_stage[38:32] == 7'd39 && pipeline_stage[39] ;

  // register result_regs_4
  assign result_regs_4$D_IN = result_regs_0$D_IN ;
  assign result_regs_4$EN =
	     active && pipeline_stage[38:32] == 7'd4 && pipeline_stage[39] ;

  // register result_regs_40
  assign result_regs_40$D_IN = result_regs_0$D_IN ;
  assign result_regs_40$EN =
	     active && pipeline_stage[38:32] == 7'd40 && pipeline_stage[39] ;

  // register result_regs_41
  assign result_regs_41$D_IN = result_regs_0$D_IN ;
  assign result_regs_41$EN =
	     active && pipeline_stage[38:32] == 7'd41 && pipeline_stage[39] ;

  // register result_regs_42
  assign result_regs_42$D_IN = result_regs_0$D_IN ;
  assign result_regs_42$EN =
	     active && pipeline_stage[38:32] == 7'd42 && pipeline_stage[39] ;

  // register result_regs_43
  assign result_regs_43$D_IN = result_regs_0$D_IN ;
  assign result_regs_43$EN =
	     active && pipeline_stage[38:32] == 7'd43 && pipeline_stage[39] ;

  // register result_regs_44
  assign result_regs_44$D_IN = result_regs_0$D_IN ;
  assign result_regs_44$EN =
	     active && pipeline_stage[38:32] == 7'd44 && pipeline_stage[39] ;

  // register result_regs_45
  assign result_regs_45$D_IN = result_regs_0$D_IN ;
  assign result_regs_45$EN =
	     active && pipeline_stage[38:32] == 7'd45 && pipeline_stage[39] ;

  // register result_regs_46
  assign result_regs_46$D_IN = result_regs_0$D_IN ;
  assign result_regs_46$EN =
	     active && pipeline_stage[38:32] == 7'd46 && pipeline_stage[39] ;

  // register result_regs_47
  assign result_regs_47$D_IN = result_regs_0$D_IN ;
  assign result_regs_47$EN =
	     active && pipeline_stage[38:32] == 7'd47 && pipeline_stage[39] ;

  // register result_regs_48
  assign result_regs_48$D_IN = result_regs_0$D_IN ;
  assign result_regs_48$EN =
	     active && pipeline_stage[38:32] == 7'd48 && pipeline_stage[39] ;

  // register result_regs_49
  assign result_regs_49$D_IN = result_regs_0$D_IN ;
  assign result_regs_49$EN =
	     active && pipeline_stage[38:32] == 7'd49 && pipeline_stage[39] ;

  // register result_regs_5
  assign result_regs_5$D_IN = result_regs_0$D_IN ;
  assign result_regs_5$EN =
	     active && pipeline_stage[38:32] == 7'd5 && pipeline_stage[39] ;

  // register result_regs_50
  assign result_regs_50$D_IN = result_regs_0$D_IN ;
  assign result_regs_50$EN =
	     active && pipeline_stage[38:32] == 7'd50 && pipeline_stage[39] ;

  // register result_regs_51
  assign result_regs_51$D_IN = result_regs_0$D_IN ;
  assign result_regs_51$EN =
	     active && pipeline_stage[38:32] == 7'd51 && pipeline_stage[39] ;

  // register result_regs_52
  assign result_regs_52$D_IN = result_regs_0$D_IN ;
  assign result_regs_52$EN =
	     active && pipeline_stage[38:32] == 7'd52 && pipeline_stage[39] ;

  // register result_regs_53
  assign result_regs_53$D_IN = result_regs_0$D_IN ;
  assign result_regs_53$EN =
	     active && pipeline_stage[38:32] == 7'd53 && pipeline_stage[39] ;

  // register result_regs_54
  assign result_regs_54$D_IN = result_regs_0$D_IN ;
  assign result_regs_54$EN =
	     active && pipeline_stage[38:32] == 7'd54 && pipeline_stage[39] ;

  // register result_regs_55
  assign result_regs_55$D_IN = result_regs_0$D_IN ;
  assign result_regs_55$EN =
	     active && pipeline_stage[38:32] == 7'd55 && pipeline_stage[39] ;

  // register result_regs_56
  assign result_regs_56$D_IN = result_regs_0$D_IN ;
  assign result_regs_56$EN =
	     active && pipeline_stage[38:32] == 7'd56 && pipeline_stage[39] ;

  // register result_regs_57
  assign result_regs_57$D_IN = result_regs_0$D_IN ;
  assign result_regs_57$EN =
	     active && pipeline_stage[38:32] == 7'd57 && pipeline_stage[39] ;

  // register result_regs_58
  assign result_regs_58$D_IN = result_regs_0$D_IN ;
  assign result_regs_58$EN =
	     active && pipeline_stage[38:32] == 7'd58 && pipeline_stage[39] ;

  // register result_regs_59
  assign result_regs_59$D_IN = result_regs_0$D_IN ;
  assign result_regs_59$EN =
	     active && pipeline_stage[38:32] == 7'd59 && pipeline_stage[39] ;

  // register result_regs_6
  assign result_regs_6$D_IN = result_regs_0$D_IN ;
  assign result_regs_6$EN =
	     active && pipeline_stage[38:32] == 7'd6 && pipeline_stage[39] ;

  // register result_regs_60
  assign result_regs_60$D_IN = result_regs_0$D_IN ;
  assign result_regs_60$EN =
	     active && pipeline_stage[38:32] == 7'd60 && pipeline_stage[39] ;

  // register result_regs_61
  assign result_regs_61$D_IN = result_regs_0$D_IN ;
  assign result_regs_61$EN =
	     active && pipeline_stage[38:32] == 7'd61 && pipeline_stage[39] ;

  // register result_regs_62
  assign result_regs_62$D_IN = result_regs_0$D_IN ;
  assign result_regs_62$EN =
	     active && pipeline_stage[38:32] == 7'd62 && pipeline_stage[39] ;

  // register result_regs_63
  assign result_regs_63$D_IN = result_regs_0$D_IN ;
  assign result_regs_63$EN =
	     active && pipeline_stage[38:32] == 7'd63 && pipeline_stage[39] ;

  // register result_regs_7
  assign result_regs_7$D_IN = result_regs_0$D_IN ;
  assign result_regs_7$EN =
	     active && pipeline_stage[38:32] == 7'd7 && pipeline_stage[39] ;

  // register result_regs_8
  assign result_regs_8$D_IN = result_regs_0$D_IN ;
  assign result_regs_8$EN =
	     active && pipeline_stage[38:32] == 7'd8 && pipeline_stage[39] ;

  // register result_regs_9
  assign result_regs_9$D_IN = result_regs_0$D_IN ;
  assign result_regs_9$EN =
	     active && pipeline_stage[38:32] == 7'd9 && pipeline_stage[39] ;

  // remaining internal signals
  assign IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d63 =
	     _theResult____h7167[4] ?
	       { final_exp__h7498, final_mantissa__h7499 } :
	       { final_exp__h7500, final_mantissa__h7501 } ;
  assign IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d64 =
	     _theResult____h7167[5] ?
	       { final_exp__h7469, final_mantissa__h7470 } :
	       IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d63 ;
  assign IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d65 =
	     _theResult____h7167[6] ?
	       { final_exp__h7440, final_mantissa__h7441 } :
	       IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d64 ;
  assign IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d67 =
	     _theResult____h7167[8] ?
	       { final_exp___1__h7382, _theResult____h7167[7:1] } :
	       (_theResult____h7167[7] ?
		  { larger_exp__h7216, _theResult____h7167[6:0] } :
		  IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d65) ;
  assign IF_pipeline_stage_BITS_15_TO_0_EQ_0x0_0_THEN_p_ETC___d70 =
	     (pipeline_stage[15:0] == 16'h0) ?
	       pipeline_stage[31:16] :
	       ((_theResult____h7167 == 9'd0) ? 16'h0 : result__h7351) ;
  assign _0_CONCAT_SEL_ARR_reg_a_05_BITS_14_TO_7_40_reg__ETC___d479 =
	     raw_exp__h11964 <= 9'd255 ;
  assign _0_CONCAT_SEL_ARR_reg_c_30_BITS_14_TO_7_65_reg__ETC___d904 =
	     raw_exp__h19066 <= 9'd255 ;
  assign _1_CONCAT_IF_pipeline_stage_BITS_30_TO_23_2_ULT_ETC___d23 =
	     { 2'd1,
	       pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14 ?
		 pipeline_stage[6:0] :
		 pipeline_stage[22:16] } ;
  assign _1_CONCAT_SEL_ARR_reg_a_05_BITS_6_TO_0_80_reg_a_ETC___d614 =
	     { 9'd1, a_mantissa__h11974 } * { 9'd1, b_mantissa__h15422 } ;
  assign _1_CONCAT_SEL_ARR_reg_c_30_BITS_6_TO_0_05_reg_c_ETC___d1039 =
	     { 9'd1, a_mantissa__h19076 } * { 9'd1, b_mantissa__h22521 } ;
  assign _theResult____h7167 =
	     (larger_sign__h7215 == smaller_sign__h7256) ?
	       man_result__h7337 :
	       man_result__h7262 ;
  assign _theResult___fst__h19000 =
	     _1_CONCAT_SEL_ARR_reg_a_05_BITS_6_TO_0_80_reg_a_ETC___d614[15] ?
	       x__h19006[7:0] :
	       raw_exp__h11964[7:0] ;
  assign _theResult___fst__h26099 =
	     _1_CONCAT_SEL_ARR_reg_c_30_BITS_6_TO_0_05_reg_c_ETC___d1039[15] ?
	       x__h26105[7:0] :
	       raw_exp__h19066[7:0] ;
  assign _theResult___snd__h19001 =
	     _1_CONCAT_SEL_ARR_reg_a_05_BITS_6_TO_0_80_reg_a_ETC___d614[15] ?
	       _1_CONCAT_SEL_ARR_reg_a_05_BITS_6_TO_0_80_reg_a_ETC___d614[14:8] :
	       _1_CONCAT_SEL_ARR_reg_a_05_BITS_6_TO_0_80_reg_a_ETC___d614[13:7] ;
  assign _theResult___snd__h26100 =
	     _1_CONCAT_SEL_ARR_reg_c_30_BITS_6_TO_0_05_reg_c_ETC___d1039[15] ?
	       _1_CONCAT_SEL_ARR_reg_c_30_BITS_6_TO_0_05_reg_c_ETC___d1039[14:8] :
	       _1_CONCAT_SEL_ARR_reg_c_30_BITS_6_TO_0_05_reg_c_ETC___d1039[13:7] ;
  assign exp_diff__h7162 = larger_exp__h7216 - smaller_exp__h7257 ;
  assign exp_sum__h11963 = { 1'd0, x__h18911 } + { 1'd0, x__h18913 } ;
  assign exp_sum__h19065 = { 1'd0, x__h26010 } + { 1'd0, x__h26012 } ;
  assign final_exp___1__h7382 = larger_exp__h7216 + 8'd1 ;
  assign final_exp__h18925 =
	     _0_CONCAT_SEL_ARR_reg_a_05_BITS_14_TO_7_40_reg__ETC___d479 ?
	       8'b0 :
	       8'hFF ;
  assign final_exp__h26024 =
	     _0_CONCAT_SEL_ARR_reg_c_30_BITS_14_TO_7_65_reg__ETC___d904 ?
	       8'b0 :
	       8'hFF ;
  assign final_exp__h7440 = larger_exp__h7216 - 8'd1 ;
  assign final_exp__h7469 = larger_exp__h7216 - 8'd2 ;
  assign final_exp__h7498 = larger_exp__h7216 - 8'd3 ;
  assign final_exp__h7500 = larger_exp__h7216 - 8'd4 ;
  assign final_mantissa__h7441 = { _theResult____h7167[5:0], 1'b0 } ;
  assign final_mantissa__h7470 = { _theResult____h7167[4:0], 2'b0 } ;
  assign final_mantissa__h7499 = { _theResult____h7167[3:0], 3'b0 } ;
  assign final_mantissa__h7501 = { _theResult____h7167[2:0], 4'b0 } ;
  assign issue_index_03_ULT_64___d204 = issue_index < 7'd64 ;
  assign larger_exp__h7216 =
	     pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14 ?
	       pipeline_stage[14:7] :
	       pipeline_stage[30:23] ;
  assign larger_sign__h7215 =
	     pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14 ?
	       pipeline_stage[15] :
	       pipeline_stage[31] ;
  assign man_result__h7262 =
	     _1_CONCAT_IF_pipeline_stage_BITS_30_TO_23_2_ULT_ETC___d23 -
	     { 1'd0, shifted_smaller__h7164 } ;
  assign man_result__h7337 =
	     _1_CONCAT_IF_pipeline_stage_BITS_30_TO_23_2_ULT_ETC___d23 +
	     { 1'd0, shifted_smaller__h7164 } ;
  assign pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14 =
	     pipeline_stage[30:23] < pipeline_stage[14:7] ;
  assign raw_exp__h11964 = exp_sum__h11963 - 9'd127 ;
  assign raw_exp__h19066 = exp_sum__h19065 - 9'd127 ;
  assign result__h7351 =
	     { larger_sign__h7215,
	       IF_IF_IF_pipeline_stage_BITS_30_TO_23_2_ULT_pi_ETC___d67 } ;
  assign result_exp__h18863 =
	     _0_CONCAT_SEL_ARR_reg_a_05_BITS_14_TO_7_40_reg__ETC___d479 ?
	       _theResult___fst__h19000 :
	       final_exp__h18925 ;
  assign result_exp__h25962 =
	     _0_CONCAT_SEL_ARR_reg_c_30_BITS_14_TO_7_65_reg__ETC___d904 ?
	       _theResult___fst__h26099 :
	       final_exp__h26024 ;
  assign result_sign__h11959 = a_sign__h11972 ^ b_sign__h15420 ;
  assign result_sign__h19061 = a_sign__h19074 ^ b_sign__h22519 ;
  assign shift_amount__h7163 =
	     (exp_diff__h7162 <= 8'd8) ? exp_diff__h7162 : 8'd8 ;
  assign shifted_smaller__h7164 = smaller_man__h7161 >> shift_amount__h7163 ;
  assign smaller_exp__h7257 =
	     pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14 ?
	       pipeline_stage[30:23] :
	       pipeline_stage[14:7] ;
  assign smaller_man__h7161 =
	     { 1'b1,
	       pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14 ?
		 pipeline_stage[22:16] :
		 pipeline_stage[6:0] } ;
  assign smaller_sign__h7256 =
	     pipeline_stage_BITS_30_TO_23_2_ULT_pipeline_st_ETC___d14 ?
	       pipeline_stage[31] :
	       pipeline_stage[15] ;
  assign val_exp__h18865 =
	     (x__h18911 == 8'd0 || x__h18913 == 8'd0) ?
	       8'b0 :
	       result_exp__h18863 ;
  assign val_exp__h25964 =
	     (x__h26010 == 8'd0 || x__h26012 == 8'd0) ?
	       8'b0 :
	       result_exp__h25962 ;
  assign val_mantissa__h18866 =
	     (x__h18911 == 8'd0 || x__h18913 == 8'd0 ||
	      !_0_CONCAT_SEL_ARR_reg_a_05_BITS_14_TO_7_40_reg__ETC___d479) ?
	       7'b0 :
	       _theResult___snd__h19001 ;
  assign val_mantissa__h25965 =
	     (x__h26010 == 8'd0 || x__h26012 == 8'd0 ||
	      !_0_CONCAT_SEL_ARR_reg_c_30_BITS_14_TO_7_65_reg__ETC___d904) ?
	       7'b0 :
	       _theResult___snd__h26100 ;
  assign x__h11949 =
	     { result_sign__h11959, val_exp__h18865, val_mantissa__h18866 } ;
  assign x__h19006 = raw_exp__h11964 + 9'd1 ;
  assign x__h19051 =
	     { result_sign__h19061, val_exp__h25964, val_mantissa__h25965 } ;
  assign x__h26105 = raw_exp__h19066 + 9'd1 ;
  always@(issue_index or reg_a)
  begin
    case (issue_index)
      7'd0: x__h18911 = reg_a[14:7];
      7'd1: x__h18911 = reg_a[30:23];
      7'd2: x__h18911 = reg_a[46:39];
      7'd3: x__h18911 = reg_a[62:55];
      7'd4: x__h18911 = reg_a[78:71];
      7'd5: x__h18911 = reg_a[94:87];
      7'd6: x__h18911 = reg_a[110:103];
      7'd7: x__h18911 = reg_a[126:119];
      7'd8: x__h18911 = reg_a[142:135];
      7'd9: x__h18911 = reg_a[158:151];
      7'd10: x__h18911 = reg_a[174:167];
      7'd11: x__h18911 = reg_a[190:183];
      7'd12: x__h18911 = reg_a[206:199];
      7'd13: x__h18911 = reg_a[222:215];
      7'd14: x__h18911 = reg_a[238:231];
      7'd15: x__h18911 = reg_a[254:247];
      7'd16: x__h18911 = reg_a[270:263];
      7'd17: x__h18911 = reg_a[286:279];
      7'd18: x__h18911 = reg_a[302:295];
      7'd19: x__h18911 = reg_a[318:311];
      7'd20: x__h18911 = reg_a[334:327];
      7'd21: x__h18911 = reg_a[350:343];
      7'd22: x__h18911 = reg_a[366:359];
      7'd23: x__h18911 = reg_a[382:375];
      7'd24: x__h18911 = reg_a[398:391];
      7'd25: x__h18911 = reg_a[414:407];
      7'd26: x__h18911 = reg_a[430:423];
      7'd27: x__h18911 = reg_a[446:439];
      7'd28: x__h18911 = reg_a[462:455];
      7'd29: x__h18911 = reg_a[478:471];
      7'd30: x__h18911 = reg_a[494:487];
      7'd31: x__h18911 = reg_a[510:503];
      7'd32: x__h18911 = reg_a[526:519];
      7'd33: x__h18911 = reg_a[542:535];
      7'd34: x__h18911 = reg_a[558:551];
      7'd35: x__h18911 = reg_a[574:567];
      7'd36: x__h18911 = reg_a[590:583];
      7'd37: x__h18911 = reg_a[606:599];
      7'd38: x__h18911 = reg_a[622:615];
      7'd39: x__h18911 = reg_a[638:631];
      7'd40: x__h18911 = reg_a[654:647];
      7'd41: x__h18911 = reg_a[670:663];
      7'd42: x__h18911 = reg_a[686:679];
      7'd43: x__h18911 = reg_a[702:695];
      7'd44: x__h18911 = reg_a[718:711];
      7'd45: x__h18911 = reg_a[734:727];
      7'd46: x__h18911 = reg_a[750:743];
      7'd47: x__h18911 = reg_a[766:759];
      7'd48: x__h18911 = reg_a[782:775];
      7'd49: x__h18911 = reg_a[798:791];
      7'd50: x__h18911 = reg_a[814:807];
      7'd51: x__h18911 = reg_a[830:823];
      7'd52: x__h18911 = reg_a[846:839];
      7'd53: x__h18911 = reg_a[862:855];
      7'd54: x__h18911 = reg_a[878:871];
      7'd55: x__h18911 = reg_a[894:887];
      7'd56: x__h18911 = reg_a[910:903];
      7'd57: x__h18911 = reg_a[926:919];
      7'd58: x__h18911 = reg_a[942:935];
      7'd59: x__h18911 = reg_a[958:951];
      7'd60: x__h18911 = reg_a[974:967];
      7'd61: x__h18911 = reg_a[990:983];
      7'd62: x__h18911 = reg_a[1006:999];
      7'd63: x__h18911 = reg_a[1022:1015];
      default: x__h18911 = 8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_b)
  begin
    case (issue_index)
      7'd0: x__h18913 = reg_b[14:7];
      7'd1: x__h18913 = reg_b[30:23];
      7'd2: x__h18913 = reg_b[46:39];
      7'd3: x__h18913 = reg_b[62:55];
      7'd4: x__h18913 = reg_b[78:71];
      7'd5: x__h18913 = reg_b[94:87];
      7'd6: x__h18913 = reg_b[110:103];
      7'd7: x__h18913 = reg_b[126:119];
      7'd8: x__h18913 = reg_b[142:135];
      7'd9: x__h18913 = reg_b[158:151];
      7'd10: x__h18913 = reg_b[174:167];
      7'd11: x__h18913 = reg_b[190:183];
      7'd12: x__h18913 = reg_b[206:199];
      7'd13: x__h18913 = reg_b[222:215];
      7'd14: x__h18913 = reg_b[238:231];
      7'd15: x__h18913 = reg_b[254:247];
      7'd16: x__h18913 = reg_b[270:263];
      7'd17: x__h18913 = reg_b[286:279];
      7'd18: x__h18913 = reg_b[302:295];
      7'd19: x__h18913 = reg_b[318:311];
      7'd20: x__h18913 = reg_b[334:327];
      7'd21: x__h18913 = reg_b[350:343];
      7'd22: x__h18913 = reg_b[366:359];
      7'd23: x__h18913 = reg_b[382:375];
      7'd24: x__h18913 = reg_b[398:391];
      7'd25: x__h18913 = reg_b[414:407];
      7'd26: x__h18913 = reg_b[430:423];
      7'd27: x__h18913 = reg_b[446:439];
      7'd28: x__h18913 = reg_b[462:455];
      7'd29: x__h18913 = reg_b[478:471];
      7'd30: x__h18913 = reg_b[494:487];
      7'd31: x__h18913 = reg_b[510:503];
      7'd32: x__h18913 = reg_b[526:519];
      7'd33: x__h18913 = reg_b[542:535];
      7'd34: x__h18913 = reg_b[558:551];
      7'd35: x__h18913 = reg_b[574:567];
      7'd36: x__h18913 = reg_b[590:583];
      7'd37: x__h18913 = reg_b[606:599];
      7'd38: x__h18913 = reg_b[622:615];
      7'd39: x__h18913 = reg_b[638:631];
      7'd40: x__h18913 = reg_b[654:647];
      7'd41: x__h18913 = reg_b[670:663];
      7'd42: x__h18913 = reg_b[686:679];
      7'd43: x__h18913 = reg_b[702:695];
      7'd44: x__h18913 = reg_b[718:711];
      7'd45: x__h18913 = reg_b[734:727];
      7'd46: x__h18913 = reg_b[750:743];
      7'd47: x__h18913 = reg_b[766:759];
      7'd48: x__h18913 = reg_b[782:775];
      7'd49: x__h18913 = reg_b[798:791];
      7'd50: x__h18913 = reg_b[814:807];
      7'd51: x__h18913 = reg_b[830:823];
      7'd52: x__h18913 = reg_b[846:839];
      7'd53: x__h18913 = reg_b[862:855];
      7'd54: x__h18913 = reg_b[878:871];
      7'd55: x__h18913 = reg_b[894:887];
      7'd56: x__h18913 = reg_b[910:903];
      7'd57: x__h18913 = reg_b[926:919];
      7'd58: x__h18913 = reg_b[942:935];
      7'd59: x__h18913 = reg_b[958:951];
      7'd60: x__h18913 = reg_b[974:967];
      7'd61: x__h18913 = reg_b[990:983];
      7'd62: x__h18913 = reg_b[1006:999];
      7'd63: x__h18913 = reg_b[1022:1015];
      default: x__h18913 = 8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_c)
  begin
    case (issue_index)
      7'd0: x__h26010 = reg_c[14:7];
      7'd1: x__h26010 = reg_c[30:23];
      7'd2: x__h26010 = reg_c[46:39];
      7'd3: x__h26010 = reg_c[62:55];
      7'd4: x__h26010 = reg_c[78:71];
      7'd5: x__h26010 = reg_c[94:87];
      7'd6: x__h26010 = reg_c[110:103];
      7'd7: x__h26010 = reg_c[126:119];
      7'd8: x__h26010 = reg_c[142:135];
      7'd9: x__h26010 = reg_c[158:151];
      7'd10: x__h26010 = reg_c[174:167];
      7'd11: x__h26010 = reg_c[190:183];
      7'd12: x__h26010 = reg_c[206:199];
      7'd13: x__h26010 = reg_c[222:215];
      7'd14: x__h26010 = reg_c[238:231];
      7'd15: x__h26010 = reg_c[254:247];
      7'd16: x__h26010 = reg_c[270:263];
      7'd17: x__h26010 = reg_c[286:279];
      7'd18: x__h26010 = reg_c[302:295];
      7'd19: x__h26010 = reg_c[318:311];
      7'd20: x__h26010 = reg_c[334:327];
      7'd21: x__h26010 = reg_c[350:343];
      7'd22: x__h26010 = reg_c[366:359];
      7'd23: x__h26010 = reg_c[382:375];
      7'd24: x__h26010 = reg_c[398:391];
      7'd25: x__h26010 = reg_c[414:407];
      7'd26: x__h26010 = reg_c[430:423];
      7'd27: x__h26010 = reg_c[446:439];
      7'd28: x__h26010 = reg_c[462:455];
      7'd29: x__h26010 = reg_c[478:471];
      7'd30: x__h26010 = reg_c[494:487];
      7'd31: x__h26010 = reg_c[510:503];
      7'd32: x__h26010 = reg_c[526:519];
      7'd33: x__h26010 = reg_c[542:535];
      7'd34: x__h26010 = reg_c[558:551];
      7'd35: x__h26010 = reg_c[574:567];
      7'd36: x__h26010 = reg_c[590:583];
      7'd37: x__h26010 = reg_c[606:599];
      7'd38: x__h26010 = reg_c[622:615];
      7'd39: x__h26010 = reg_c[638:631];
      7'd40: x__h26010 = reg_c[654:647];
      7'd41: x__h26010 = reg_c[670:663];
      7'd42: x__h26010 = reg_c[686:679];
      7'd43: x__h26010 = reg_c[702:695];
      7'd44: x__h26010 = reg_c[718:711];
      7'd45: x__h26010 = reg_c[734:727];
      7'd46: x__h26010 = reg_c[750:743];
      7'd47: x__h26010 = reg_c[766:759];
      7'd48: x__h26010 = reg_c[782:775];
      7'd49: x__h26010 = reg_c[798:791];
      7'd50: x__h26010 = reg_c[814:807];
      7'd51: x__h26010 = reg_c[830:823];
      7'd52: x__h26010 = reg_c[846:839];
      7'd53: x__h26010 = reg_c[862:855];
      7'd54: x__h26010 = reg_c[878:871];
      7'd55: x__h26010 = reg_c[894:887];
      7'd56: x__h26010 = reg_c[910:903];
      7'd57: x__h26010 = reg_c[926:919];
      7'd58: x__h26010 = reg_c[942:935];
      7'd59: x__h26010 = reg_c[958:951];
      7'd60: x__h26010 = reg_c[974:967];
      7'd61: x__h26010 = reg_c[990:983];
      7'd62: x__h26010 = reg_c[1006:999];
      7'd63: x__h26010 = reg_c[1022:1015];
      default: x__h26010 = 8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_d)
  begin
    case (issue_index)
      7'd0: x__h26012 = reg_d[14:7];
      7'd1: x__h26012 = reg_d[30:23];
      7'd2: x__h26012 = reg_d[46:39];
      7'd3: x__h26012 = reg_d[62:55];
      7'd4: x__h26012 = reg_d[78:71];
      7'd5: x__h26012 = reg_d[94:87];
      7'd6: x__h26012 = reg_d[110:103];
      7'd7: x__h26012 = reg_d[126:119];
      7'd8: x__h26012 = reg_d[142:135];
      7'd9: x__h26012 = reg_d[158:151];
      7'd10: x__h26012 = reg_d[174:167];
      7'd11: x__h26012 = reg_d[190:183];
      7'd12: x__h26012 = reg_d[206:199];
      7'd13: x__h26012 = reg_d[222:215];
      7'd14: x__h26012 = reg_d[238:231];
      7'd15: x__h26012 = reg_d[254:247];
      7'd16: x__h26012 = reg_d[270:263];
      7'd17: x__h26012 = reg_d[286:279];
      7'd18: x__h26012 = reg_d[302:295];
      7'd19: x__h26012 = reg_d[318:311];
      7'd20: x__h26012 = reg_d[334:327];
      7'd21: x__h26012 = reg_d[350:343];
      7'd22: x__h26012 = reg_d[366:359];
      7'd23: x__h26012 = reg_d[382:375];
      7'd24: x__h26012 = reg_d[398:391];
      7'd25: x__h26012 = reg_d[414:407];
      7'd26: x__h26012 = reg_d[430:423];
      7'd27: x__h26012 = reg_d[446:439];
      7'd28: x__h26012 = reg_d[462:455];
      7'd29: x__h26012 = reg_d[478:471];
      7'd30: x__h26012 = reg_d[494:487];
      7'd31: x__h26012 = reg_d[510:503];
      7'd32: x__h26012 = reg_d[526:519];
      7'd33: x__h26012 = reg_d[542:535];
      7'd34: x__h26012 = reg_d[558:551];
      7'd35: x__h26012 = reg_d[574:567];
      7'd36: x__h26012 = reg_d[590:583];
      7'd37: x__h26012 = reg_d[606:599];
      7'd38: x__h26012 = reg_d[622:615];
      7'd39: x__h26012 = reg_d[638:631];
      7'd40: x__h26012 = reg_d[654:647];
      7'd41: x__h26012 = reg_d[670:663];
      7'd42: x__h26012 = reg_d[686:679];
      7'd43: x__h26012 = reg_d[702:695];
      7'd44: x__h26012 = reg_d[718:711];
      7'd45: x__h26012 = reg_d[734:727];
      7'd46: x__h26012 = reg_d[750:743];
      7'd47: x__h26012 = reg_d[766:759];
      7'd48: x__h26012 = reg_d[782:775];
      7'd49: x__h26012 = reg_d[798:791];
      7'd50: x__h26012 = reg_d[814:807];
      7'd51: x__h26012 = reg_d[830:823];
      7'd52: x__h26012 = reg_d[846:839];
      7'd53: x__h26012 = reg_d[862:855];
      7'd54: x__h26012 = reg_d[878:871];
      7'd55: x__h26012 = reg_d[894:887];
      7'd56: x__h26012 = reg_d[910:903];
      7'd57: x__h26012 = reg_d[926:919];
      7'd58: x__h26012 = reg_d[942:935];
      7'd59: x__h26012 = reg_d[958:951];
      7'd60: x__h26012 = reg_d[974:967];
      7'd61: x__h26012 = reg_d[990:983];
      7'd62: x__h26012 = reg_d[1006:999];
      7'd63: x__h26012 = reg_d[1022:1015];
      default: x__h26012 = 8'b10101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_a)
  begin
    case (issue_index)
      7'd0: a_mantissa__h11974 = reg_a[6:0];
      7'd1: a_mantissa__h11974 = reg_a[22:16];
      7'd2: a_mantissa__h11974 = reg_a[38:32];
      7'd3: a_mantissa__h11974 = reg_a[54:48];
      7'd4: a_mantissa__h11974 = reg_a[70:64];
      7'd5: a_mantissa__h11974 = reg_a[86:80];
      7'd6: a_mantissa__h11974 = reg_a[102:96];
      7'd7: a_mantissa__h11974 = reg_a[118:112];
      7'd8: a_mantissa__h11974 = reg_a[134:128];
      7'd9: a_mantissa__h11974 = reg_a[150:144];
      7'd10: a_mantissa__h11974 = reg_a[166:160];
      7'd11: a_mantissa__h11974 = reg_a[182:176];
      7'd12: a_mantissa__h11974 = reg_a[198:192];
      7'd13: a_mantissa__h11974 = reg_a[214:208];
      7'd14: a_mantissa__h11974 = reg_a[230:224];
      7'd15: a_mantissa__h11974 = reg_a[246:240];
      7'd16: a_mantissa__h11974 = reg_a[262:256];
      7'd17: a_mantissa__h11974 = reg_a[278:272];
      7'd18: a_mantissa__h11974 = reg_a[294:288];
      7'd19: a_mantissa__h11974 = reg_a[310:304];
      7'd20: a_mantissa__h11974 = reg_a[326:320];
      7'd21: a_mantissa__h11974 = reg_a[342:336];
      7'd22: a_mantissa__h11974 = reg_a[358:352];
      7'd23: a_mantissa__h11974 = reg_a[374:368];
      7'd24: a_mantissa__h11974 = reg_a[390:384];
      7'd25: a_mantissa__h11974 = reg_a[406:400];
      7'd26: a_mantissa__h11974 = reg_a[422:416];
      7'd27: a_mantissa__h11974 = reg_a[438:432];
      7'd28: a_mantissa__h11974 = reg_a[454:448];
      7'd29: a_mantissa__h11974 = reg_a[470:464];
      7'd30: a_mantissa__h11974 = reg_a[486:480];
      7'd31: a_mantissa__h11974 = reg_a[502:496];
      7'd32: a_mantissa__h11974 = reg_a[518:512];
      7'd33: a_mantissa__h11974 = reg_a[534:528];
      7'd34: a_mantissa__h11974 = reg_a[550:544];
      7'd35: a_mantissa__h11974 = reg_a[566:560];
      7'd36: a_mantissa__h11974 = reg_a[582:576];
      7'd37: a_mantissa__h11974 = reg_a[598:592];
      7'd38: a_mantissa__h11974 = reg_a[614:608];
      7'd39: a_mantissa__h11974 = reg_a[630:624];
      7'd40: a_mantissa__h11974 = reg_a[646:640];
      7'd41: a_mantissa__h11974 = reg_a[662:656];
      7'd42: a_mantissa__h11974 = reg_a[678:672];
      7'd43: a_mantissa__h11974 = reg_a[694:688];
      7'd44: a_mantissa__h11974 = reg_a[710:704];
      7'd45: a_mantissa__h11974 = reg_a[726:720];
      7'd46: a_mantissa__h11974 = reg_a[742:736];
      7'd47: a_mantissa__h11974 = reg_a[758:752];
      7'd48: a_mantissa__h11974 = reg_a[774:768];
      7'd49: a_mantissa__h11974 = reg_a[790:784];
      7'd50: a_mantissa__h11974 = reg_a[806:800];
      7'd51: a_mantissa__h11974 = reg_a[822:816];
      7'd52: a_mantissa__h11974 = reg_a[838:832];
      7'd53: a_mantissa__h11974 = reg_a[854:848];
      7'd54: a_mantissa__h11974 = reg_a[870:864];
      7'd55: a_mantissa__h11974 = reg_a[886:880];
      7'd56: a_mantissa__h11974 = reg_a[902:896];
      7'd57: a_mantissa__h11974 = reg_a[918:912];
      7'd58: a_mantissa__h11974 = reg_a[934:928];
      7'd59: a_mantissa__h11974 = reg_a[950:944];
      7'd60: a_mantissa__h11974 = reg_a[966:960];
      7'd61: a_mantissa__h11974 = reg_a[982:976];
      7'd62: a_mantissa__h11974 = reg_a[998:992];
      7'd63: a_mantissa__h11974 = reg_a[1014:1008];
      default: a_mantissa__h11974 = 7'b0101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_b)
  begin
    case (issue_index)
      7'd0: b_mantissa__h15422 = reg_b[6:0];
      7'd1: b_mantissa__h15422 = reg_b[22:16];
      7'd2: b_mantissa__h15422 = reg_b[38:32];
      7'd3: b_mantissa__h15422 = reg_b[54:48];
      7'd4: b_mantissa__h15422 = reg_b[70:64];
      7'd5: b_mantissa__h15422 = reg_b[86:80];
      7'd6: b_mantissa__h15422 = reg_b[102:96];
      7'd7: b_mantissa__h15422 = reg_b[118:112];
      7'd8: b_mantissa__h15422 = reg_b[134:128];
      7'd9: b_mantissa__h15422 = reg_b[150:144];
      7'd10: b_mantissa__h15422 = reg_b[166:160];
      7'd11: b_mantissa__h15422 = reg_b[182:176];
      7'd12: b_mantissa__h15422 = reg_b[198:192];
      7'd13: b_mantissa__h15422 = reg_b[214:208];
      7'd14: b_mantissa__h15422 = reg_b[230:224];
      7'd15: b_mantissa__h15422 = reg_b[246:240];
      7'd16: b_mantissa__h15422 = reg_b[262:256];
      7'd17: b_mantissa__h15422 = reg_b[278:272];
      7'd18: b_mantissa__h15422 = reg_b[294:288];
      7'd19: b_mantissa__h15422 = reg_b[310:304];
      7'd20: b_mantissa__h15422 = reg_b[326:320];
      7'd21: b_mantissa__h15422 = reg_b[342:336];
      7'd22: b_mantissa__h15422 = reg_b[358:352];
      7'd23: b_mantissa__h15422 = reg_b[374:368];
      7'd24: b_mantissa__h15422 = reg_b[390:384];
      7'd25: b_mantissa__h15422 = reg_b[406:400];
      7'd26: b_mantissa__h15422 = reg_b[422:416];
      7'd27: b_mantissa__h15422 = reg_b[438:432];
      7'd28: b_mantissa__h15422 = reg_b[454:448];
      7'd29: b_mantissa__h15422 = reg_b[470:464];
      7'd30: b_mantissa__h15422 = reg_b[486:480];
      7'd31: b_mantissa__h15422 = reg_b[502:496];
      7'd32: b_mantissa__h15422 = reg_b[518:512];
      7'd33: b_mantissa__h15422 = reg_b[534:528];
      7'd34: b_mantissa__h15422 = reg_b[550:544];
      7'd35: b_mantissa__h15422 = reg_b[566:560];
      7'd36: b_mantissa__h15422 = reg_b[582:576];
      7'd37: b_mantissa__h15422 = reg_b[598:592];
      7'd38: b_mantissa__h15422 = reg_b[614:608];
      7'd39: b_mantissa__h15422 = reg_b[630:624];
      7'd40: b_mantissa__h15422 = reg_b[646:640];
      7'd41: b_mantissa__h15422 = reg_b[662:656];
      7'd42: b_mantissa__h15422 = reg_b[678:672];
      7'd43: b_mantissa__h15422 = reg_b[694:688];
      7'd44: b_mantissa__h15422 = reg_b[710:704];
      7'd45: b_mantissa__h15422 = reg_b[726:720];
      7'd46: b_mantissa__h15422 = reg_b[742:736];
      7'd47: b_mantissa__h15422 = reg_b[758:752];
      7'd48: b_mantissa__h15422 = reg_b[774:768];
      7'd49: b_mantissa__h15422 = reg_b[790:784];
      7'd50: b_mantissa__h15422 = reg_b[806:800];
      7'd51: b_mantissa__h15422 = reg_b[822:816];
      7'd52: b_mantissa__h15422 = reg_b[838:832];
      7'd53: b_mantissa__h15422 = reg_b[854:848];
      7'd54: b_mantissa__h15422 = reg_b[870:864];
      7'd55: b_mantissa__h15422 = reg_b[886:880];
      7'd56: b_mantissa__h15422 = reg_b[902:896];
      7'd57: b_mantissa__h15422 = reg_b[918:912];
      7'd58: b_mantissa__h15422 = reg_b[934:928];
      7'd59: b_mantissa__h15422 = reg_b[950:944];
      7'd60: b_mantissa__h15422 = reg_b[966:960];
      7'd61: b_mantissa__h15422 = reg_b[982:976];
      7'd62: b_mantissa__h15422 = reg_b[998:992];
      7'd63: b_mantissa__h15422 = reg_b[1014:1008];
      default: b_mantissa__h15422 = 7'b0101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_c)
  begin
    case (issue_index)
      7'd0: a_mantissa__h19076 = reg_c[6:0];
      7'd1: a_mantissa__h19076 = reg_c[22:16];
      7'd2: a_mantissa__h19076 = reg_c[38:32];
      7'd3: a_mantissa__h19076 = reg_c[54:48];
      7'd4: a_mantissa__h19076 = reg_c[70:64];
      7'd5: a_mantissa__h19076 = reg_c[86:80];
      7'd6: a_mantissa__h19076 = reg_c[102:96];
      7'd7: a_mantissa__h19076 = reg_c[118:112];
      7'd8: a_mantissa__h19076 = reg_c[134:128];
      7'd9: a_mantissa__h19076 = reg_c[150:144];
      7'd10: a_mantissa__h19076 = reg_c[166:160];
      7'd11: a_mantissa__h19076 = reg_c[182:176];
      7'd12: a_mantissa__h19076 = reg_c[198:192];
      7'd13: a_mantissa__h19076 = reg_c[214:208];
      7'd14: a_mantissa__h19076 = reg_c[230:224];
      7'd15: a_mantissa__h19076 = reg_c[246:240];
      7'd16: a_mantissa__h19076 = reg_c[262:256];
      7'd17: a_mantissa__h19076 = reg_c[278:272];
      7'd18: a_mantissa__h19076 = reg_c[294:288];
      7'd19: a_mantissa__h19076 = reg_c[310:304];
      7'd20: a_mantissa__h19076 = reg_c[326:320];
      7'd21: a_mantissa__h19076 = reg_c[342:336];
      7'd22: a_mantissa__h19076 = reg_c[358:352];
      7'd23: a_mantissa__h19076 = reg_c[374:368];
      7'd24: a_mantissa__h19076 = reg_c[390:384];
      7'd25: a_mantissa__h19076 = reg_c[406:400];
      7'd26: a_mantissa__h19076 = reg_c[422:416];
      7'd27: a_mantissa__h19076 = reg_c[438:432];
      7'd28: a_mantissa__h19076 = reg_c[454:448];
      7'd29: a_mantissa__h19076 = reg_c[470:464];
      7'd30: a_mantissa__h19076 = reg_c[486:480];
      7'd31: a_mantissa__h19076 = reg_c[502:496];
      7'd32: a_mantissa__h19076 = reg_c[518:512];
      7'd33: a_mantissa__h19076 = reg_c[534:528];
      7'd34: a_mantissa__h19076 = reg_c[550:544];
      7'd35: a_mantissa__h19076 = reg_c[566:560];
      7'd36: a_mantissa__h19076 = reg_c[582:576];
      7'd37: a_mantissa__h19076 = reg_c[598:592];
      7'd38: a_mantissa__h19076 = reg_c[614:608];
      7'd39: a_mantissa__h19076 = reg_c[630:624];
      7'd40: a_mantissa__h19076 = reg_c[646:640];
      7'd41: a_mantissa__h19076 = reg_c[662:656];
      7'd42: a_mantissa__h19076 = reg_c[678:672];
      7'd43: a_mantissa__h19076 = reg_c[694:688];
      7'd44: a_mantissa__h19076 = reg_c[710:704];
      7'd45: a_mantissa__h19076 = reg_c[726:720];
      7'd46: a_mantissa__h19076 = reg_c[742:736];
      7'd47: a_mantissa__h19076 = reg_c[758:752];
      7'd48: a_mantissa__h19076 = reg_c[774:768];
      7'd49: a_mantissa__h19076 = reg_c[790:784];
      7'd50: a_mantissa__h19076 = reg_c[806:800];
      7'd51: a_mantissa__h19076 = reg_c[822:816];
      7'd52: a_mantissa__h19076 = reg_c[838:832];
      7'd53: a_mantissa__h19076 = reg_c[854:848];
      7'd54: a_mantissa__h19076 = reg_c[870:864];
      7'd55: a_mantissa__h19076 = reg_c[886:880];
      7'd56: a_mantissa__h19076 = reg_c[902:896];
      7'd57: a_mantissa__h19076 = reg_c[918:912];
      7'd58: a_mantissa__h19076 = reg_c[934:928];
      7'd59: a_mantissa__h19076 = reg_c[950:944];
      7'd60: a_mantissa__h19076 = reg_c[966:960];
      7'd61: a_mantissa__h19076 = reg_c[982:976];
      7'd62: a_mantissa__h19076 = reg_c[998:992];
      7'd63: a_mantissa__h19076 = reg_c[1014:1008];
      default: a_mantissa__h19076 = 7'b0101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_d)
  begin
    case (issue_index)
      7'd0: b_mantissa__h22521 = reg_d[6:0];
      7'd1: b_mantissa__h22521 = reg_d[22:16];
      7'd2: b_mantissa__h22521 = reg_d[38:32];
      7'd3: b_mantissa__h22521 = reg_d[54:48];
      7'd4: b_mantissa__h22521 = reg_d[70:64];
      7'd5: b_mantissa__h22521 = reg_d[86:80];
      7'd6: b_mantissa__h22521 = reg_d[102:96];
      7'd7: b_mantissa__h22521 = reg_d[118:112];
      7'd8: b_mantissa__h22521 = reg_d[134:128];
      7'd9: b_mantissa__h22521 = reg_d[150:144];
      7'd10: b_mantissa__h22521 = reg_d[166:160];
      7'd11: b_mantissa__h22521 = reg_d[182:176];
      7'd12: b_mantissa__h22521 = reg_d[198:192];
      7'd13: b_mantissa__h22521 = reg_d[214:208];
      7'd14: b_mantissa__h22521 = reg_d[230:224];
      7'd15: b_mantissa__h22521 = reg_d[246:240];
      7'd16: b_mantissa__h22521 = reg_d[262:256];
      7'd17: b_mantissa__h22521 = reg_d[278:272];
      7'd18: b_mantissa__h22521 = reg_d[294:288];
      7'd19: b_mantissa__h22521 = reg_d[310:304];
      7'd20: b_mantissa__h22521 = reg_d[326:320];
      7'd21: b_mantissa__h22521 = reg_d[342:336];
      7'd22: b_mantissa__h22521 = reg_d[358:352];
      7'd23: b_mantissa__h22521 = reg_d[374:368];
      7'd24: b_mantissa__h22521 = reg_d[390:384];
      7'd25: b_mantissa__h22521 = reg_d[406:400];
      7'd26: b_mantissa__h22521 = reg_d[422:416];
      7'd27: b_mantissa__h22521 = reg_d[438:432];
      7'd28: b_mantissa__h22521 = reg_d[454:448];
      7'd29: b_mantissa__h22521 = reg_d[470:464];
      7'd30: b_mantissa__h22521 = reg_d[486:480];
      7'd31: b_mantissa__h22521 = reg_d[502:496];
      7'd32: b_mantissa__h22521 = reg_d[518:512];
      7'd33: b_mantissa__h22521 = reg_d[534:528];
      7'd34: b_mantissa__h22521 = reg_d[550:544];
      7'd35: b_mantissa__h22521 = reg_d[566:560];
      7'd36: b_mantissa__h22521 = reg_d[582:576];
      7'd37: b_mantissa__h22521 = reg_d[598:592];
      7'd38: b_mantissa__h22521 = reg_d[614:608];
      7'd39: b_mantissa__h22521 = reg_d[630:624];
      7'd40: b_mantissa__h22521 = reg_d[646:640];
      7'd41: b_mantissa__h22521 = reg_d[662:656];
      7'd42: b_mantissa__h22521 = reg_d[678:672];
      7'd43: b_mantissa__h22521 = reg_d[694:688];
      7'd44: b_mantissa__h22521 = reg_d[710:704];
      7'd45: b_mantissa__h22521 = reg_d[726:720];
      7'd46: b_mantissa__h22521 = reg_d[742:736];
      7'd47: b_mantissa__h22521 = reg_d[758:752];
      7'd48: b_mantissa__h22521 = reg_d[774:768];
      7'd49: b_mantissa__h22521 = reg_d[790:784];
      7'd50: b_mantissa__h22521 = reg_d[806:800];
      7'd51: b_mantissa__h22521 = reg_d[822:816];
      7'd52: b_mantissa__h22521 = reg_d[838:832];
      7'd53: b_mantissa__h22521 = reg_d[854:848];
      7'd54: b_mantissa__h22521 = reg_d[870:864];
      7'd55: b_mantissa__h22521 = reg_d[886:880];
      7'd56: b_mantissa__h22521 = reg_d[902:896];
      7'd57: b_mantissa__h22521 = reg_d[918:912];
      7'd58: b_mantissa__h22521 = reg_d[934:928];
      7'd59: b_mantissa__h22521 = reg_d[950:944];
      7'd60: b_mantissa__h22521 = reg_d[966:960];
      7'd61: b_mantissa__h22521 = reg_d[982:976];
      7'd62: b_mantissa__h22521 = reg_d[998:992];
      7'd63: b_mantissa__h22521 = reg_d[1014:1008];
      default: b_mantissa__h22521 = 7'b0101010 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_a)
  begin
    case (issue_index)
      7'd0: a_sign__h11972 = reg_a[15];
      7'd1: a_sign__h11972 = reg_a[31];
      7'd2: a_sign__h11972 = reg_a[47];
      7'd3: a_sign__h11972 = reg_a[63];
      7'd4: a_sign__h11972 = reg_a[79];
      7'd5: a_sign__h11972 = reg_a[95];
      7'd6: a_sign__h11972 = reg_a[111];
      7'd7: a_sign__h11972 = reg_a[127];
      7'd8: a_sign__h11972 = reg_a[143];
      7'd9: a_sign__h11972 = reg_a[159];
      7'd10: a_sign__h11972 = reg_a[175];
      7'd11: a_sign__h11972 = reg_a[191];
      7'd12: a_sign__h11972 = reg_a[207];
      7'd13: a_sign__h11972 = reg_a[223];
      7'd14: a_sign__h11972 = reg_a[239];
      7'd15: a_sign__h11972 = reg_a[255];
      7'd16: a_sign__h11972 = reg_a[271];
      7'd17: a_sign__h11972 = reg_a[287];
      7'd18: a_sign__h11972 = reg_a[303];
      7'd19: a_sign__h11972 = reg_a[319];
      7'd20: a_sign__h11972 = reg_a[335];
      7'd21: a_sign__h11972 = reg_a[351];
      7'd22: a_sign__h11972 = reg_a[367];
      7'd23: a_sign__h11972 = reg_a[383];
      7'd24: a_sign__h11972 = reg_a[399];
      7'd25: a_sign__h11972 = reg_a[415];
      7'd26: a_sign__h11972 = reg_a[431];
      7'd27: a_sign__h11972 = reg_a[447];
      7'd28: a_sign__h11972 = reg_a[463];
      7'd29: a_sign__h11972 = reg_a[479];
      7'd30: a_sign__h11972 = reg_a[495];
      7'd31: a_sign__h11972 = reg_a[511];
      7'd32: a_sign__h11972 = reg_a[527];
      7'd33: a_sign__h11972 = reg_a[543];
      7'd34: a_sign__h11972 = reg_a[559];
      7'd35: a_sign__h11972 = reg_a[575];
      7'd36: a_sign__h11972 = reg_a[591];
      7'd37: a_sign__h11972 = reg_a[607];
      7'd38: a_sign__h11972 = reg_a[623];
      7'd39: a_sign__h11972 = reg_a[639];
      7'd40: a_sign__h11972 = reg_a[655];
      7'd41: a_sign__h11972 = reg_a[671];
      7'd42: a_sign__h11972 = reg_a[687];
      7'd43: a_sign__h11972 = reg_a[703];
      7'd44: a_sign__h11972 = reg_a[719];
      7'd45: a_sign__h11972 = reg_a[735];
      7'd46: a_sign__h11972 = reg_a[751];
      7'd47: a_sign__h11972 = reg_a[767];
      7'd48: a_sign__h11972 = reg_a[783];
      7'd49: a_sign__h11972 = reg_a[799];
      7'd50: a_sign__h11972 = reg_a[815];
      7'd51: a_sign__h11972 = reg_a[831];
      7'd52: a_sign__h11972 = reg_a[847];
      7'd53: a_sign__h11972 = reg_a[863];
      7'd54: a_sign__h11972 = reg_a[879];
      7'd55: a_sign__h11972 = reg_a[895];
      7'd56: a_sign__h11972 = reg_a[911];
      7'd57: a_sign__h11972 = reg_a[927];
      7'd58: a_sign__h11972 = reg_a[943];
      7'd59: a_sign__h11972 = reg_a[959];
      7'd60: a_sign__h11972 = reg_a[975];
      7'd61: a_sign__h11972 = reg_a[991];
      7'd62: a_sign__h11972 = reg_a[1007];
      7'd63: a_sign__h11972 = reg_a[1023];
      default: a_sign__h11972 = 1'b0 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_b)
  begin
    case (issue_index)
      7'd0: b_sign__h15420 = reg_b[15];
      7'd1: b_sign__h15420 = reg_b[31];
      7'd2: b_sign__h15420 = reg_b[47];
      7'd3: b_sign__h15420 = reg_b[63];
      7'd4: b_sign__h15420 = reg_b[79];
      7'd5: b_sign__h15420 = reg_b[95];
      7'd6: b_sign__h15420 = reg_b[111];
      7'd7: b_sign__h15420 = reg_b[127];
      7'd8: b_sign__h15420 = reg_b[143];
      7'd9: b_sign__h15420 = reg_b[159];
      7'd10: b_sign__h15420 = reg_b[175];
      7'd11: b_sign__h15420 = reg_b[191];
      7'd12: b_sign__h15420 = reg_b[207];
      7'd13: b_sign__h15420 = reg_b[223];
      7'd14: b_sign__h15420 = reg_b[239];
      7'd15: b_sign__h15420 = reg_b[255];
      7'd16: b_sign__h15420 = reg_b[271];
      7'd17: b_sign__h15420 = reg_b[287];
      7'd18: b_sign__h15420 = reg_b[303];
      7'd19: b_sign__h15420 = reg_b[319];
      7'd20: b_sign__h15420 = reg_b[335];
      7'd21: b_sign__h15420 = reg_b[351];
      7'd22: b_sign__h15420 = reg_b[367];
      7'd23: b_sign__h15420 = reg_b[383];
      7'd24: b_sign__h15420 = reg_b[399];
      7'd25: b_sign__h15420 = reg_b[415];
      7'd26: b_sign__h15420 = reg_b[431];
      7'd27: b_sign__h15420 = reg_b[447];
      7'd28: b_sign__h15420 = reg_b[463];
      7'd29: b_sign__h15420 = reg_b[479];
      7'd30: b_sign__h15420 = reg_b[495];
      7'd31: b_sign__h15420 = reg_b[511];
      7'd32: b_sign__h15420 = reg_b[527];
      7'd33: b_sign__h15420 = reg_b[543];
      7'd34: b_sign__h15420 = reg_b[559];
      7'd35: b_sign__h15420 = reg_b[575];
      7'd36: b_sign__h15420 = reg_b[591];
      7'd37: b_sign__h15420 = reg_b[607];
      7'd38: b_sign__h15420 = reg_b[623];
      7'd39: b_sign__h15420 = reg_b[639];
      7'd40: b_sign__h15420 = reg_b[655];
      7'd41: b_sign__h15420 = reg_b[671];
      7'd42: b_sign__h15420 = reg_b[687];
      7'd43: b_sign__h15420 = reg_b[703];
      7'd44: b_sign__h15420 = reg_b[719];
      7'd45: b_sign__h15420 = reg_b[735];
      7'd46: b_sign__h15420 = reg_b[751];
      7'd47: b_sign__h15420 = reg_b[767];
      7'd48: b_sign__h15420 = reg_b[783];
      7'd49: b_sign__h15420 = reg_b[799];
      7'd50: b_sign__h15420 = reg_b[815];
      7'd51: b_sign__h15420 = reg_b[831];
      7'd52: b_sign__h15420 = reg_b[847];
      7'd53: b_sign__h15420 = reg_b[863];
      7'd54: b_sign__h15420 = reg_b[879];
      7'd55: b_sign__h15420 = reg_b[895];
      7'd56: b_sign__h15420 = reg_b[911];
      7'd57: b_sign__h15420 = reg_b[927];
      7'd58: b_sign__h15420 = reg_b[943];
      7'd59: b_sign__h15420 = reg_b[959];
      7'd60: b_sign__h15420 = reg_b[975];
      7'd61: b_sign__h15420 = reg_b[991];
      7'd62: b_sign__h15420 = reg_b[1007];
      7'd63: b_sign__h15420 = reg_b[1023];
      default: b_sign__h15420 = 1'b0 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_c)
  begin
    case (issue_index)
      7'd0: a_sign__h19074 = reg_c[15];
      7'd1: a_sign__h19074 = reg_c[31];
      7'd2: a_sign__h19074 = reg_c[47];
      7'd3: a_sign__h19074 = reg_c[63];
      7'd4: a_sign__h19074 = reg_c[79];
      7'd5: a_sign__h19074 = reg_c[95];
      7'd6: a_sign__h19074 = reg_c[111];
      7'd7: a_sign__h19074 = reg_c[127];
      7'd8: a_sign__h19074 = reg_c[143];
      7'd9: a_sign__h19074 = reg_c[159];
      7'd10: a_sign__h19074 = reg_c[175];
      7'd11: a_sign__h19074 = reg_c[191];
      7'd12: a_sign__h19074 = reg_c[207];
      7'd13: a_sign__h19074 = reg_c[223];
      7'd14: a_sign__h19074 = reg_c[239];
      7'd15: a_sign__h19074 = reg_c[255];
      7'd16: a_sign__h19074 = reg_c[271];
      7'd17: a_sign__h19074 = reg_c[287];
      7'd18: a_sign__h19074 = reg_c[303];
      7'd19: a_sign__h19074 = reg_c[319];
      7'd20: a_sign__h19074 = reg_c[335];
      7'd21: a_sign__h19074 = reg_c[351];
      7'd22: a_sign__h19074 = reg_c[367];
      7'd23: a_sign__h19074 = reg_c[383];
      7'd24: a_sign__h19074 = reg_c[399];
      7'd25: a_sign__h19074 = reg_c[415];
      7'd26: a_sign__h19074 = reg_c[431];
      7'd27: a_sign__h19074 = reg_c[447];
      7'd28: a_sign__h19074 = reg_c[463];
      7'd29: a_sign__h19074 = reg_c[479];
      7'd30: a_sign__h19074 = reg_c[495];
      7'd31: a_sign__h19074 = reg_c[511];
      7'd32: a_sign__h19074 = reg_c[527];
      7'd33: a_sign__h19074 = reg_c[543];
      7'd34: a_sign__h19074 = reg_c[559];
      7'd35: a_sign__h19074 = reg_c[575];
      7'd36: a_sign__h19074 = reg_c[591];
      7'd37: a_sign__h19074 = reg_c[607];
      7'd38: a_sign__h19074 = reg_c[623];
      7'd39: a_sign__h19074 = reg_c[639];
      7'd40: a_sign__h19074 = reg_c[655];
      7'd41: a_sign__h19074 = reg_c[671];
      7'd42: a_sign__h19074 = reg_c[687];
      7'd43: a_sign__h19074 = reg_c[703];
      7'd44: a_sign__h19074 = reg_c[719];
      7'd45: a_sign__h19074 = reg_c[735];
      7'd46: a_sign__h19074 = reg_c[751];
      7'd47: a_sign__h19074 = reg_c[767];
      7'd48: a_sign__h19074 = reg_c[783];
      7'd49: a_sign__h19074 = reg_c[799];
      7'd50: a_sign__h19074 = reg_c[815];
      7'd51: a_sign__h19074 = reg_c[831];
      7'd52: a_sign__h19074 = reg_c[847];
      7'd53: a_sign__h19074 = reg_c[863];
      7'd54: a_sign__h19074 = reg_c[879];
      7'd55: a_sign__h19074 = reg_c[895];
      7'd56: a_sign__h19074 = reg_c[911];
      7'd57: a_sign__h19074 = reg_c[927];
      7'd58: a_sign__h19074 = reg_c[943];
      7'd59: a_sign__h19074 = reg_c[959];
      7'd60: a_sign__h19074 = reg_c[975];
      7'd61: a_sign__h19074 = reg_c[991];
      7'd62: a_sign__h19074 = reg_c[1007];
      7'd63: a_sign__h19074 = reg_c[1023];
      default: a_sign__h19074 = 1'b0 /* unspecified value */ ;
    endcase
  end
  always@(issue_index or reg_d)
  begin
    case (issue_index)
      7'd0: b_sign__h22519 = reg_d[15];
      7'd1: b_sign__h22519 = reg_d[31];
      7'd2: b_sign__h22519 = reg_d[47];
      7'd3: b_sign__h22519 = reg_d[63];
      7'd4: b_sign__h22519 = reg_d[79];
      7'd5: b_sign__h22519 = reg_d[95];
      7'd6: b_sign__h22519 = reg_d[111];
      7'd7: b_sign__h22519 = reg_d[127];
      7'd8: b_sign__h22519 = reg_d[143];
      7'd9: b_sign__h22519 = reg_d[159];
      7'd10: b_sign__h22519 = reg_d[175];
      7'd11: b_sign__h22519 = reg_d[191];
      7'd12: b_sign__h22519 = reg_d[207];
      7'd13: b_sign__h22519 = reg_d[223];
      7'd14: b_sign__h22519 = reg_d[239];
      7'd15: b_sign__h22519 = reg_d[255];
      7'd16: b_sign__h22519 = reg_d[271];
      7'd17: b_sign__h22519 = reg_d[287];
      7'd18: b_sign__h22519 = reg_d[303];
      7'd19: b_sign__h22519 = reg_d[319];
      7'd20: b_sign__h22519 = reg_d[335];
      7'd21: b_sign__h22519 = reg_d[351];
      7'd22: b_sign__h22519 = reg_d[367];
      7'd23: b_sign__h22519 = reg_d[383];
      7'd24: b_sign__h22519 = reg_d[399];
      7'd25: b_sign__h22519 = reg_d[415];
      7'd26: b_sign__h22519 = reg_d[431];
      7'd27: b_sign__h22519 = reg_d[447];
      7'd28: b_sign__h22519 = reg_d[463];
      7'd29: b_sign__h22519 = reg_d[479];
      7'd30: b_sign__h22519 = reg_d[495];
      7'd31: b_sign__h22519 = reg_d[511];
      7'd32: b_sign__h22519 = reg_d[527];
      7'd33: b_sign__h22519 = reg_d[543];
      7'd34: b_sign__h22519 = reg_d[559];
      7'd35: b_sign__h22519 = reg_d[575];
      7'd36: b_sign__h22519 = reg_d[591];
      7'd37: b_sign__h22519 = reg_d[607];
      7'd38: b_sign__h22519 = reg_d[623];
      7'd39: b_sign__h22519 = reg_d[639];
      7'd40: b_sign__h22519 = reg_d[655];
      7'd41: b_sign__h22519 = reg_d[671];
      7'd42: b_sign__h22519 = reg_d[687];
      7'd43: b_sign__h22519 = reg_d[703];
      7'd44: b_sign__h22519 = reg_d[719];
      7'd45: b_sign__h22519 = reg_d[735];
      7'd46: b_sign__h22519 = reg_d[751];
      7'd47: b_sign__h22519 = reg_d[767];
      7'd48: b_sign__h22519 = reg_d[783];
      7'd49: b_sign__h22519 = reg_d[799];
      7'd50: b_sign__h22519 = reg_d[815];
      7'd51: b_sign__h22519 = reg_d[831];
      7'd52: b_sign__h22519 = reg_d[847];
      7'd53: b_sign__h22519 = reg_d[863];
      7'd54: b_sign__h22519 = reg_d[879];
      7'd55: b_sign__h22519 = reg_d[895];
      7'd56: b_sign__h22519 = reg_d[911];
      7'd57: b_sign__h22519 = reg_d[927];
      7'd58: b_sign__h22519 = reg_d[943];
      7'd59: b_sign__h22519 = reg_d[959];
      7'd60: b_sign__h22519 = reg_d[975];
      7'd61: b_sign__h22519 = reg_d[991];
      7'd62: b_sign__h22519 = reg_d[1007];
      7'd63: b_sign__h22519 = reg_d[1023];
      default: b_sign__h22519 = 1'b0 /* unspecified value */ ;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        active <= `BSV_ASSIGNMENT_DELAY 1'd0;
	complete_count <= `BSV_ASSIGNMENT_DELAY 7'd0;
	issue_index <= `BSV_ASSIGNMENT_DELAY 7'd0;
	pipeline_stage <= `BSV_ASSIGNMENT_DELAY 40'h2AAAAAAAAA;
      end
    else
      begin
        if (active$EN) active <= `BSV_ASSIGNMENT_DELAY active$D_IN;
	if (complete_count$EN)
	  complete_count <= `BSV_ASSIGNMENT_DELAY complete_count$D_IN;
	if (issue_index$EN)
	  issue_index <= `BSV_ASSIGNMENT_DELAY issue_index$D_IN;
	if (pipeline_stage$EN)
	  pipeline_stage <= `BSV_ASSIGNMENT_DELAY pipeline_stage$D_IN;
      end
    if (reg_a$EN) reg_a <= `BSV_ASSIGNMENT_DELAY reg_a$D_IN;
    if (reg_b$EN) reg_b <= `BSV_ASSIGNMENT_DELAY reg_b$D_IN;
    if (reg_c$EN) reg_c <= `BSV_ASSIGNMENT_DELAY reg_c$D_IN;
    if (reg_d$EN) reg_d <= `BSV_ASSIGNMENT_DELAY reg_d$D_IN;
    if (result_regs_0$EN)
      result_regs_0 <= `BSV_ASSIGNMENT_DELAY result_regs_0$D_IN;
    if (result_regs_1$EN)
      result_regs_1 <= `BSV_ASSIGNMENT_DELAY result_regs_1$D_IN;
    if (result_regs_10$EN)
      result_regs_10 <= `BSV_ASSIGNMENT_DELAY result_regs_10$D_IN;
    if (result_regs_11$EN)
      result_regs_11 <= `BSV_ASSIGNMENT_DELAY result_regs_11$D_IN;
    if (result_regs_12$EN)
      result_regs_12 <= `BSV_ASSIGNMENT_DELAY result_regs_12$D_IN;
    if (result_regs_13$EN)
      result_regs_13 <= `BSV_ASSIGNMENT_DELAY result_regs_13$D_IN;
    if (result_regs_14$EN)
      result_regs_14 <= `BSV_ASSIGNMENT_DELAY result_regs_14$D_IN;
    if (result_regs_15$EN)
      result_regs_15 <= `BSV_ASSIGNMENT_DELAY result_regs_15$D_IN;
    if (result_regs_16$EN)
      result_regs_16 <= `BSV_ASSIGNMENT_DELAY result_regs_16$D_IN;
    if (result_regs_17$EN)
      result_regs_17 <= `BSV_ASSIGNMENT_DELAY result_regs_17$D_IN;
    if (result_regs_18$EN)
      result_regs_18 <= `BSV_ASSIGNMENT_DELAY result_regs_18$D_IN;
    if (result_regs_19$EN)
      result_regs_19 <= `BSV_ASSIGNMENT_DELAY result_regs_19$D_IN;
    if (result_regs_2$EN)
      result_regs_2 <= `BSV_ASSIGNMENT_DELAY result_regs_2$D_IN;
    if (result_regs_20$EN)
      result_regs_20 <= `BSV_ASSIGNMENT_DELAY result_regs_20$D_IN;
    if (result_regs_21$EN)
      result_regs_21 <= `BSV_ASSIGNMENT_DELAY result_regs_21$D_IN;
    if (result_regs_22$EN)
      result_regs_22 <= `BSV_ASSIGNMENT_DELAY result_regs_22$D_IN;
    if (result_regs_23$EN)
      result_regs_23 <= `BSV_ASSIGNMENT_DELAY result_regs_23$D_IN;
    if (result_regs_24$EN)
      result_regs_24 <= `BSV_ASSIGNMENT_DELAY result_regs_24$D_IN;
    if (result_regs_25$EN)
      result_regs_25 <= `BSV_ASSIGNMENT_DELAY result_regs_25$D_IN;
    if (result_regs_26$EN)
      result_regs_26 <= `BSV_ASSIGNMENT_DELAY result_regs_26$D_IN;
    if (result_regs_27$EN)
      result_regs_27 <= `BSV_ASSIGNMENT_DELAY result_regs_27$D_IN;
    if (result_regs_28$EN)
      result_regs_28 <= `BSV_ASSIGNMENT_DELAY result_regs_28$D_IN;
    if (result_regs_29$EN)
      result_regs_29 <= `BSV_ASSIGNMENT_DELAY result_regs_29$D_IN;
    if (result_regs_3$EN)
      result_regs_3 <= `BSV_ASSIGNMENT_DELAY result_regs_3$D_IN;
    if (result_regs_30$EN)
      result_regs_30 <= `BSV_ASSIGNMENT_DELAY result_regs_30$D_IN;
    if (result_regs_31$EN)
      result_regs_31 <= `BSV_ASSIGNMENT_DELAY result_regs_31$D_IN;
    if (result_regs_32$EN)
      result_regs_32 <= `BSV_ASSIGNMENT_DELAY result_regs_32$D_IN;
    if (result_regs_33$EN)
      result_regs_33 <= `BSV_ASSIGNMENT_DELAY result_regs_33$D_IN;
    if (result_regs_34$EN)
      result_regs_34 <= `BSV_ASSIGNMENT_DELAY result_regs_34$D_IN;
    if (result_regs_35$EN)
      result_regs_35 <= `BSV_ASSIGNMENT_DELAY result_regs_35$D_IN;
    if (result_regs_36$EN)
      result_regs_36 <= `BSV_ASSIGNMENT_DELAY result_regs_36$D_IN;
    if (result_regs_37$EN)
      result_regs_37 <= `BSV_ASSIGNMENT_DELAY result_regs_37$D_IN;
    if (result_regs_38$EN)
      result_regs_38 <= `BSV_ASSIGNMENT_DELAY result_regs_38$D_IN;
    if (result_regs_39$EN)
      result_regs_39 <= `BSV_ASSIGNMENT_DELAY result_regs_39$D_IN;
    if (result_regs_4$EN)
      result_regs_4 <= `BSV_ASSIGNMENT_DELAY result_regs_4$D_IN;
    if (result_regs_40$EN)
      result_regs_40 <= `BSV_ASSIGNMENT_DELAY result_regs_40$D_IN;
    if (result_regs_41$EN)
      result_regs_41 <= `BSV_ASSIGNMENT_DELAY result_regs_41$D_IN;
    if (result_regs_42$EN)
      result_regs_42 <= `BSV_ASSIGNMENT_DELAY result_regs_42$D_IN;
    if (result_regs_43$EN)
      result_regs_43 <= `BSV_ASSIGNMENT_DELAY result_regs_43$D_IN;
    if (result_regs_44$EN)
      result_regs_44 <= `BSV_ASSIGNMENT_DELAY result_regs_44$D_IN;
    if (result_regs_45$EN)
      result_regs_45 <= `BSV_ASSIGNMENT_DELAY result_regs_45$D_IN;
    if (result_regs_46$EN)
      result_regs_46 <= `BSV_ASSIGNMENT_DELAY result_regs_46$D_IN;
    if (result_regs_47$EN)
      result_regs_47 <= `BSV_ASSIGNMENT_DELAY result_regs_47$D_IN;
    if (result_regs_48$EN)
      result_regs_48 <= `BSV_ASSIGNMENT_DELAY result_regs_48$D_IN;
    if (result_regs_49$EN)
      result_regs_49 <= `BSV_ASSIGNMENT_DELAY result_regs_49$D_IN;
    if (result_regs_5$EN)
      result_regs_5 <= `BSV_ASSIGNMENT_DELAY result_regs_5$D_IN;
    if (result_regs_50$EN)
      result_regs_50 <= `BSV_ASSIGNMENT_DELAY result_regs_50$D_IN;
    if (result_regs_51$EN)
      result_regs_51 <= `BSV_ASSIGNMENT_DELAY result_regs_51$D_IN;
    if (result_regs_52$EN)
      result_regs_52 <= `BSV_ASSIGNMENT_DELAY result_regs_52$D_IN;
    if (result_regs_53$EN)
      result_regs_53 <= `BSV_ASSIGNMENT_DELAY result_regs_53$D_IN;
    if (result_regs_54$EN)
      result_regs_54 <= `BSV_ASSIGNMENT_DELAY result_regs_54$D_IN;
    if (result_regs_55$EN)
      result_regs_55 <= `BSV_ASSIGNMENT_DELAY result_regs_55$D_IN;
    if (result_regs_56$EN)
      result_regs_56 <= `BSV_ASSIGNMENT_DELAY result_regs_56$D_IN;
    if (result_regs_57$EN)
      result_regs_57 <= `BSV_ASSIGNMENT_DELAY result_regs_57$D_IN;
    if (result_regs_58$EN)
      result_regs_58 <= `BSV_ASSIGNMENT_DELAY result_regs_58$D_IN;
    if (result_regs_59$EN)
      result_regs_59 <= `BSV_ASSIGNMENT_DELAY result_regs_59$D_IN;
    if (result_regs_6$EN)
      result_regs_6 <= `BSV_ASSIGNMENT_DELAY result_regs_6$D_IN;
    if (result_regs_60$EN)
      result_regs_60 <= `BSV_ASSIGNMENT_DELAY result_regs_60$D_IN;
    if (result_regs_61$EN)
      result_regs_61 <= `BSV_ASSIGNMENT_DELAY result_regs_61$D_IN;
    if (result_regs_62$EN)
      result_regs_62 <= `BSV_ASSIGNMENT_DELAY result_regs_62$D_IN;
    if (result_regs_63$EN)
      result_regs_63 <= `BSV_ASSIGNMENT_DELAY result_regs_63$D_IN;
    if (result_regs_7$EN)
      result_regs_7 <= `BSV_ASSIGNMENT_DELAY result_regs_7$D_IN;
    if (result_regs_8$EN)
      result_regs_8 <= `BSV_ASSIGNMENT_DELAY result_regs_8$D_IN;
    if (result_regs_9$EN)
      result_regs_9 <= `BSV_ASSIGNMENT_DELAY result_regs_9$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    active = 1'h0;
    complete_count = 7'h2A;
    issue_index = 7'h2A;
    pipeline_stage = 40'hAAAAAAAAAA;
    reg_a =
	1024'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    reg_b =
	1024'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    reg_c =
	1024'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    reg_d =
	1024'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    result_regs_0 = 16'hAAAA;
    result_regs_1 = 16'hAAAA;
    result_regs_10 = 16'hAAAA;
    result_regs_11 = 16'hAAAA;
    result_regs_12 = 16'hAAAA;
    result_regs_13 = 16'hAAAA;
    result_regs_14 = 16'hAAAA;
    result_regs_15 = 16'hAAAA;
    result_regs_16 = 16'hAAAA;
    result_regs_17 = 16'hAAAA;
    result_regs_18 = 16'hAAAA;
    result_regs_19 = 16'hAAAA;
    result_regs_2 = 16'hAAAA;
    result_regs_20 = 16'hAAAA;
    result_regs_21 = 16'hAAAA;
    result_regs_22 = 16'hAAAA;
    result_regs_23 = 16'hAAAA;
    result_regs_24 = 16'hAAAA;
    result_regs_25 = 16'hAAAA;
    result_regs_26 = 16'hAAAA;
    result_regs_27 = 16'hAAAA;
    result_regs_28 = 16'hAAAA;
    result_regs_29 = 16'hAAAA;
    result_regs_3 = 16'hAAAA;
    result_regs_30 = 16'hAAAA;
    result_regs_31 = 16'hAAAA;
    result_regs_32 = 16'hAAAA;
    result_regs_33 = 16'hAAAA;
    result_regs_34 = 16'hAAAA;
    result_regs_35 = 16'hAAAA;
    result_regs_36 = 16'hAAAA;
    result_regs_37 = 16'hAAAA;
    result_regs_38 = 16'hAAAA;
    result_regs_39 = 16'hAAAA;
    result_regs_4 = 16'hAAAA;
    result_regs_40 = 16'hAAAA;
    result_regs_41 = 16'hAAAA;
    result_regs_42 = 16'hAAAA;
    result_regs_43 = 16'hAAAA;
    result_regs_44 = 16'hAAAA;
    result_regs_45 = 16'hAAAA;
    result_regs_46 = 16'hAAAA;
    result_regs_47 = 16'hAAAA;
    result_regs_48 = 16'hAAAA;
    result_regs_49 = 16'hAAAA;
    result_regs_5 = 16'hAAAA;
    result_regs_50 = 16'hAAAA;
    result_regs_51 = 16'hAAAA;
    result_regs_52 = 16'hAAAA;
    result_regs_53 = 16'hAAAA;
    result_regs_54 = 16'hAAAA;
    result_regs_55 = 16'hAAAA;
    result_regs_56 = 16'hAAAA;
    result_regs_57 = 16'hAAAA;
    result_regs_58 = 16'hAAAA;
    result_regs_59 = 16'hAAAA;
    result_regs_6 = 16'hAAAA;
    result_regs_60 = 16'hAAAA;
    result_regs_61 = 16'hAAAA;
    result_regs_62 = 16'hAAAA;
    result_regs_63 = 16'hAAAA;
    result_regs_7 = 16'hAAAA;
    result_regs_8 = 16'hAAAA;
    result_regs_9 = 16'hAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkBF16_SIMD

