//
// Generated by Bluespec Compiler, version 2025.01.1-9-g76db531e (build 76db531e)
//
// On Sun Nov  2 15:23:23 UTC 2025
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb_COP(CLK,
		RST_N);
  input  CLK;
  input  RST_N;

  // register current_operation
  reg [1 : 0] current_operation;
  wire [1 : 0] current_operation$D_IN;
  wire current_operation$EN;

  // register cycle
  reg [31 : 0] cycle;
  wire [31 : 0] cycle$D_IN;
  wire cycle$EN;

  // register printed
  reg printed;
  wire printed$D_IN, printed$EN;

  // register sa1_complete
  reg sa1_complete;
  wire sa1_complete$D_IN, sa1_complete$EN;

  // register sa1_current_input_chunk
  reg [5 : 0] sa1_current_input_chunk;
  wire [5 : 0] sa1_current_input_chunk$D_IN;
  wire sa1_current_input_chunk$EN;

  // register sa1_current_row_group
  reg [3 : 0] sa1_current_row_group;
  wire [3 : 0] sa1_current_row_group$D_IN;
  wire sa1_current_row_group$EN;

  // register sa1_weights_loaded
  reg [9 : 0] sa1_weights_loaded;
  wire [9 : 0] sa1_weights_loaded$D_IN;
  wire sa1_weights_loaded$EN;

  // register sa2_complete
  reg sa2_complete;
  wire sa2_complete$D_IN, sa2_complete$EN;

  // register sa2_current_input_chunk
  reg [3 : 0] sa2_current_input_chunk;
  wire [3 : 0] sa2_current_input_chunk$D_IN;
  wire sa2_current_input_chunk$EN;

  // register sa2_current_row_group
  reg [5 : 0] sa2_current_row_group;
  wire [5 : 0] sa2_current_row_group$D_IN;
  wire sa2_current_row_group$EN;

  // register sa2_weights_loaded
  reg [9 : 0] sa2_weights_loaded;
  wire [9 : 0] sa2_weights_loaded$D_IN;
  wire sa2_weights_loaded$EN;

  // register started
  reg started;
  wire started$D_IN, started$EN;

  // ports of submodule cop
  wire [12287 : 0] cop$get_result_k;
  wire [4095 : 0] cop$load_sa1_weights_w, cop$load_sa2_weights_w;
  wire cop$EN_load_sa1_weights,
       cop$EN_load_sa2_weights,
       cop$EN_start_computation,
       cop$RDY_get_result_k,
       cop$RDY_load_sa1_weights,
       cop$RDY_load_sa2_weights,
       cop$RDY_start_computation,
       cop$computation_done;

  // rule scheduling signals
  wire WILL_FIRE_RL_check_done,
       WILL_FIRE_RL_load_sa1_weights,
       WILL_FIRE_RL_load_sa2_weights,
       WILL_FIRE_RL_prepare_next_operation,
       WILL_FIRE_RL_start_cop,
       WILL_FIRE_RL_timeout;

  // inputs to muxes for submodule ports
  wire [5 : 0] MUX_sa1_current_input_chunk$write_1__VAL_2,
	       MUX_sa2_current_row_group$write_1__VAL_1;
  wire [3 : 0] MUX_sa1_current_row_group$write_1__VAL_2,
	       MUX_sa2_current_input_chunk$write_1__VAL_1;
  wire MUX_sa2_complete$write_1__SEL_1,
       MUX_sa2_current_row_group$write_1__SEL_1;

  // remaining internal signals
  wire [9 : 0] sa1_weights_loaded_5_PLUS_1___d215,
	       sa2_weights_loaded_35_PLUS_1___d555,
	       x__h102565,
	       x__h102632,
	       x__h51411,
	       x__h51479;
  wire [7 : 0] exp__h59950, exp__h8779;
  wire [5 : 0] x__h51676;
  wire [3 : 0] x__h102814;
  wire [1 : 0] x__h103245;
  wire current_operation_18_ULT_2___d569;

  // submodule cop
  mkCOP cop(.CLK(CLK),
	    .RST_N(RST_N),
	    .load_sa1_weights_w(cop$load_sa1_weights_w),
	    .load_sa2_weights_w(cop$load_sa2_weights_w),
	    .EN_start_computation(cop$EN_start_computation),
	    .EN_load_sa1_weights(cop$EN_load_sa1_weights),
	    .EN_load_sa2_weights(cop$EN_load_sa2_weights),
	    .RDY_start_computation(cop$RDY_start_computation),
	    .get_result_k(cop$get_result_k),
	    .RDY_get_result_k(cop$RDY_get_result_k),
	    .RDY_load_sa1_weights(cop$RDY_load_sa1_weights),
	    .RDY_load_sa2_weights(cop$RDY_load_sa2_weights),
	    .computation_done(cop$computation_done),
	    .RDY_computation_done());

  // rule RL_check_done
  assign WILL_FIRE_RL_check_done =
	     cop$RDY_get_result_k && started && cop$computation_done &&
	     !printed ;

  // rule RL_timeout
  assign WILL_FIRE_RL_timeout = cycle > 32'd130000 ;

  // rule RL_load_sa1_weights
  assign WILL_FIRE_RL_load_sa1_weights =
	     cop$RDY_load_sa1_weights && !cop$computation_done &&
	     !sa1_complete &&
	     sa1_weights_loaded < 10'd576 ;

  // rule RL_load_sa2_weights
  assign WILL_FIRE_RL_load_sa2_weights =
	     cop$RDY_load_sa2_weights && !cop$computation_done &&
	     sa1_complete &&
	     !sa2_complete &&
	     sa2_weights_loaded < 10'd576 ;

  // rule RL_prepare_next_operation
  assign WILL_FIRE_RL_prepare_next_operation =
	     sa2_complete && current_operation_18_ULT_2___d569 &&
	     !cop$computation_done ;

  // rule RL_start_cop
  assign WILL_FIRE_RL_start_cop =
	     cop$RDY_start_computation && !started && cycle == 32'd5 ;

  // inputs to muxes for submodule ports
  assign MUX_sa2_complete$write_1__SEL_1 =
	     WILL_FIRE_RL_load_sa2_weights && sa2_weights_loaded == 10'd575 ;
  assign MUX_sa2_current_row_group$write_1__SEL_1 =
	     WILL_FIRE_RL_load_sa2_weights &&
	     sa2_current_input_chunk == 4'd11 ;
  assign MUX_sa1_current_input_chunk$write_1__VAL_2 =
	     (sa1_current_input_chunk == 6'd47) ? 6'd0 : x__h51676 ;
  assign MUX_sa1_current_row_group$write_1__VAL_2 =
	     sa1_current_row_group + 4'd1 ;
  assign MUX_sa2_current_input_chunk$write_1__VAL_1 =
	     (sa2_current_input_chunk == 4'd11) ? 4'd0 : x__h102814 ;
  assign MUX_sa2_current_row_group$write_1__VAL_1 =
	     sa2_current_row_group + 6'd1 ;

  // register current_operation
  assign current_operation$D_IN = x__h103245 ;
  assign current_operation$EN = WILL_FIRE_RL_prepare_next_operation ;

  // register cycle
  assign cycle$D_IN = cycle + 32'd1 ;
  assign cycle$EN = 1'd1 ;

  // register printed
  assign printed$D_IN = 1'd1 ;
  assign printed$EN = WILL_FIRE_RL_check_done ;

  // register sa1_complete
  assign sa1_complete$D_IN = !WILL_FIRE_RL_prepare_next_operation ;
  assign sa1_complete$EN =
	     WILL_FIRE_RL_load_sa1_weights && sa1_weights_loaded == 10'd575 ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register sa1_current_input_chunk
  assign sa1_current_input_chunk$D_IN =
	     WILL_FIRE_RL_prepare_next_operation ?
	       6'd0 :
	       MUX_sa1_current_input_chunk$write_1__VAL_2 ;
  assign sa1_current_input_chunk$EN =
	     WILL_FIRE_RL_load_sa1_weights ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register sa1_current_row_group
  assign sa1_current_row_group$D_IN =
	     WILL_FIRE_RL_prepare_next_operation ?
	       4'd0 :
	       MUX_sa1_current_row_group$write_1__VAL_2 ;
  assign sa1_current_row_group$EN =
	     WILL_FIRE_RL_load_sa1_weights &&
	     sa1_current_input_chunk == 6'd47 ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register sa1_weights_loaded
  assign sa1_weights_loaded$D_IN =
	     WILL_FIRE_RL_prepare_next_operation ?
	       10'd0 :
	       sa1_weights_loaded_5_PLUS_1___d215 ;
  assign sa1_weights_loaded$EN =
	     WILL_FIRE_RL_load_sa1_weights ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register sa2_complete
  assign sa2_complete$D_IN = MUX_sa2_complete$write_1__SEL_1 ;
  assign sa2_complete$EN =
	     WILL_FIRE_RL_load_sa2_weights && sa2_weights_loaded == 10'd575 ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register sa2_current_input_chunk
  assign sa2_current_input_chunk$D_IN =
	     WILL_FIRE_RL_load_sa2_weights ?
	       MUX_sa2_current_input_chunk$write_1__VAL_1 :
	       4'd0 ;
  assign sa2_current_input_chunk$EN =
	     WILL_FIRE_RL_load_sa2_weights ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register sa2_current_row_group
  assign sa2_current_row_group$D_IN =
	     MUX_sa2_current_row_group$write_1__SEL_1 ?
	       MUX_sa2_current_row_group$write_1__VAL_1 :
	       6'd0 ;
  assign sa2_current_row_group$EN =
	     WILL_FIRE_RL_load_sa2_weights &&
	     sa2_current_input_chunk == 4'd11 ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register sa2_weights_loaded
  assign sa2_weights_loaded$D_IN =
	     WILL_FIRE_RL_load_sa2_weights ?
	       sa2_weights_loaded_35_PLUS_1___d555 :
	       10'd0 ;
  assign sa2_weights_loaded$EN =
	     WILL_FIRE_RL_load_sa2_weights ||
	     WILL_FIRE_RL_prepare_next_operation ;

  // register started
  assign started$D_IN = 1'd1 ;
  assign started$EN = WILL_FIRE_RL_start_cop ;

  // submodule cop
  assign cop$load_sa1_weights_w =
	     { 1'd0,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       264'h007800780078007800780078007800780078007800780078007800780078007800,
	       exp__h8779,
	       7'd0 } ;
  assign cop$load_sa2_weights_w =
	     { 1'd0,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       264'h007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A007A00,
	       exp__h59950,
	       7'd0 } ;
  assign cop$EN_start_computation = WILL_FIRE_RL_start_cop ;
  assign cop$EN_load_sa1_weights = WILL_FIRE_RL_load_sa1_weights ;
  assign cop$EN_load_sa2_weights = WILL_FIRE_RL_load_sa2_weights ;

  // remaining internal signals
  assign current_operation_18_ULT_2___d569 = current_operation < 2'd2 ;
  assign exp__h59950 = (sa2_current_input_chunk == 4'd0) ? 8'd127 : 8'd122 ;
  assign exp__h8779 = (sa1_current_input_chunk == 6'd0) ? 8'd127 : 8'd120 ;
  assign sa1_weights_loaded_5_PLUS_1___d215 = sa1_weights_loaded + 10'd1 ;
  assign sa2_weights_loaded_35_PLUS_1___d555 = sa2_weights_loaded + 10'd1 ;
  assign x__h102565 = sa2_weights_loaded_35_PLUS_1___d555 % 10'd12 ;
  assign x__h102632 = sa2_weights_loaded % 10'd12 ;
  assign x__h102814 = sa2_current_input_chunk + 4'd1 ;
  assign x__h103245 = current_operation + 2'd1 ;
  assign x__h51411 = sa1_weights_loaded_5_PLUS_1___d215 % 10'd48 ;
  assign x__h51479 = sa1_weights_loaded % 10'd48 ;
  assign x__h51676 = sa1_current_input_chunk + 6'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        current_operation <= `BSV_ASSIGNMENT_DELAY 2'd0;
	cycle <= `BSV_ASSIGNMENT_DELAY 32'd0;
	printed <= `BSV_ASSIGNMENT_DELAY 1'd0;
	sa1_complete <= `BSV_ASSIGNMENT_DELAY 1'd0;
	sa1_current_input_chunk <= `BSV_ASSIGNMENT_DELAY 6'd0;
	sa1_current_row_group <= `BSV_ASSIGNMENT_DELAY 4'd0;
	sa1_weights_loaded <= `BSV_ASSIGNMENT_DELAY 10'd0;
	sa2_complete <= `BSV_ASSIGNMENT_DELAY 1'd0;
	sa2_current_input_chunk <= `BSV_ASSIGNMENT_DELAY 4'd0;
	sa2_current_row_group <= `BSV_ASSIGNMENT_DELAY 6'd0;
	sa2_weights_loaded <= `BSV_ASSIGNMENT_DELAY 10'd0;
	started <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (current_operation$EN)
	  current_operation <= `BSV_ASSIGNMENT_DELAY current_operation$D_IN;
	if (cycle$EN) cycle <= `BSV_ASSIGNMENT_DELAY cycle$D_IN;
	if (printed$EN) printed <= `BSV_ASSIGNMENT_DELAY printed$D_IN;
	if (sa1_complete$EN)
	  sa1_complete <= `BSV_ASSIGNMENT_DELAY sa1_complete$D_IN;
	if (sa1_current_input_chunk$EN)
	  sa1_current_input_chunk <= `BSV_ASSIGNMENT_DELAY
	      sa1_current_input_chunk$D_IN;
	if (sa1_current_row_group$EN)
	  sa1_current_row_group <= `BSV_ASSIGNMENT_DELAY
	      sa1_current_row_group$D_IN;
	if (sa1_weights_loaded$EN)
	  sa1_weights_loaded <= `BSV_ASSIGNMENT_DELAY sa1_weights_loaded$D_IN;
	if (sa2_complete$EN)
	  sa2_complete <= `BSV_ASSIGNMENT_DELAY sa2_complete$D_IN;
	if (sa2_current_input_chunk$EN)
	  sa2_current_input_chunk <= `BSV_ASSIGNMENT_DELAY
	      sa2_current_input_chunk$D_IN;
	if (sa2_current_row_group$EN)
	  sa2_current_row_group <= `BSV_ASSIGNMENT_DELAY
	      sa2_current_row_group$D_IN;
	if (sa2_weights_loaded$EN)
	  sa2_weights_loaded <= `BSV_ASSIGNMENT_DELAY sa2_weights_loaded$D_IN;
	if (started$EN) started <= `BSV_ASSIGNMENT_DELAY started$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    current_operation = 2'h2;
    cycle = 32'hAAAAAAAA;
    printed = 1'h0;
    sa1_complete = 1'h0;
    sa1_current_input_chunk = 6'h2A;
    sa1_current_row_group = 4'hA;
    sa1_weights_loaded = 10'h2AA;
    sa2_complete = 1'h0;
    sa2_current_input_chunk = 4'hA;
    sa2_current_row_group = 6'h2A;
    sa2_weights_loaded = 10'h2AA;
    started = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("\n[Cycle %0d] ========== ALL OPERATIONS COMPLETE ==========",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("[Cycle %0d] Completed K, V, and R operations through SA1 + SA2",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done) $display("\n=== K Results (First 10) ===");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[0] = 0x%04h", cop$get_result_k[15:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[1] = 0x%04h", cop$get_result_k[31:16]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[2] = 0x%04h", cop$get_result_k[47:32]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[3] = 0x%04h", cop$get_result_k[63:48]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[4] = 0x%04h", cop$get_result_k[79:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[5] = 0x%04h", cop$get_result_k[95:80]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[6] = 0x%04h", cop$get_result_k[111:96]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[7] = 0x%04h", cop$get_result_k[127:112]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[8] = 0x%04h", cop$get_result_k[143:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[9] = 0x%04h", cop$get_result_k[159:144]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done) $display("\n=== K Results (Last 10) ===");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[758] = 0x%04h", cop$get_result_k[12143:12128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[759] = 0x%04h", cop$get_result_k[12159:12144]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[760] = 0x%04h", cop$get_result_k[12175:12160]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[761] = 0x%04h", cop$get_result_k[12191:12176]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[762] = 0x%04h", cop$get_result_k[12207:12192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[763] = 0x%04h", cop$get_result_k[12223:12208]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[764] = 0x%04h", cop$get_result_k[12239:12224]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[765] = 0x%04h", cop$get_result_k[12255:12240]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[766] = 0x%04h", cop$get_result_k[12271:12256]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("result_k[767] = 0x%04h", cop$get_result_k[12287:12272]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done)
	$display("\n[Cycle %0d] Testbench: Finishing simulation", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_done) $finish(32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_timeout)
	$display("[Cycle %0d] ERROR: Timeout! Computation didn't complete.",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_timeout)
	$display("[Cycle %0d] Current operation: %0d, SA1 complete: %0d, SA2 complete: %0d",
		 cycle,
		 current_operation,
		 sa1_complete,
		 sa2_complete);
    if (RST_N != `BSV_RESET_VALUE) if (WILL_FIRE_RL_timeout) $finish(32'd1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa1_weights && x__h51411 == 10'd0)
	$display("[Cycle %0d] TB: *** SA1 [Op %0d] Row group %0d COMPLETE *** (loaded %0d/576 weight matrices)",
		 cycle,
		 current_operation,
		 sa1_current_row_group,
		 sa1_weights_loaded_5_PLUS_1___d215);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa1_weights && x__h51411 != 10'd0 &&
	  x__h51479 == 10'd0)
	$display("[Cycle %0d] TB: SA1 [Op %0d] Starting row_group=%0d (weights %0d-%0d)",
		 cycle,
		 current_operation,
		 sa1_current_row_group,
		 sa1_weights_loaded,
		 sa1_weights_loaded + 10'd47);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa1_weights && sa1_weights_loaded == 10'd575)
	$display("[Cycle %0d] TB: SA1 [Op %0d] COMPLETE - All 576 weight matrices loaded",
		 cycle,
		 current_operation);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa1_weights && sa1_weights_loaded == 10'd575)
	$display("[Cycle %0d] TB: Now waiting for SA2 [Op %0d] to start...",
		 cycle,
		 current_operation);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa2_weights && x__h102565 == 10'd0)
	$display("[Cycle %0d] TB: *** SA2 [Op %0d] Row group %0d COMPLETE *** (loaded %0d/576 weight matrices)",
		 cycle,
		 current_operation,
		 sa2_current_row_group,
		 sa2_weights_loaded_35_PLUS_1___d555);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa2_weights && x__h102565 != 10'd0 &&
	  x__h102632 == 10'd0)
	$display("[Cycle %0d] TB: SA2 [Op %0d] Starting row_group=%0d (weights %0d-%0d)",
		 cycle,
		 current_operation,
		 sa2_current_row_group,
		 sa2_weights_loaded,
		 sa2_weights_loaded + 10'd11);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa2_weights && sa2_weights_loaded == 10'd575)
	$display("[Cycle %0d] TB: SA2 [Op %0d] COMPLETE - All 576 weight matrices loaded",
		 cycle,
		 current_operation);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa2_weights && sa2_weights_loaded == 10'd575 &&
	  current_operation_18_ULT_2___d569)
	$display("[Cycle %0d] TB: Moving to operation %0d (preparing for next SA cycle)",
		 cycle,
		 x__h103245);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_load_sa2_weights && sa2_weights_loaded == 10'd575 &&
	  !current_operation_18_ULT_2___d569)
	$display("[Cycle %0d] TB: ALL OPERATIONS (K, V, R) COMPLETE!", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_prepare_next_operation && current_operation == 2'd0)
	$display("[Cycle %0d] TB: ===== STARTING OPERATION 1 (V) =====",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_prepare_next_operation && current_operation == 2'd1)
	$display("[Cycle %0d] TB: ===== STARTING OPERATION 2 (R) =====",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_prepare_next_operation)
	$display("[Cycle %0d] TB: Counters reset, ready to load weights for next operation",
		 cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_start_cop)
	$display("[Cycle %0d] Testbench: Started COP computation", cycle);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_start_cop)
	$display("[Cycle %0d] TB: ===== STARTING OPERATION 0 (K) =====",
		 cycle);
  end
  // synopsys translate_on
endmodule  // mkTb_COP

