/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
 * 
 * On Thu Sep 10 12:59:14 IST 2026
 * 
 */

/* Generation options: */
#ifndef __mkBF16_SIMD_h__
#define __mkBF16_SIMD_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkBF16_SIMD module */
class MOD_mkBF16_SIMD : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Fifo<tUInt64> INST_in_fifo;
  MOD_Fifo<tUInt32> INST_mid_fifo;
  MOD_Fifo<tUInt32> INST_out_fifo;
 
 /* Constructor */
 public:
  MOD_mkBF16_SIMD(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_rl_multiply();
  void RL_rl_add();
 
 /* Methods */
 public:
  void METH_put_operands(tUInt32 ARG_put_operands_a,
			 tUInt32 ARG_put_operands_b,
			 tUInt32 ARG_put_operands_c,
			 tUInt32 ARG_put_operands_d);
  tUInt8 METH_RDY_put_operands();
  tUInt32 METH_get_result();
  tUInt8 METH_RDY_get_result();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBF16_SIMD &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBF16_SIMD &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBF16_SIMD &backing);
};

#endif /* ifndef __mkBF16_SIMD_h__ */
