/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
 * 
 * On Thu Sep 10 12:59:50 IST 2026
 * 
 */

/* Generation options: */
#ifndef __mkTb_r8_n96_h__
#define __mkTb_r8_n96_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkAblation_r8.h"


/* Class declaration for the mkTb_r8_n96 module */
class MOD_mkTb_r8_n96 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkAblation_r8 INST_d;
  MOD_Reg<tUInt32> INST_t_checked;
  MOD_Reg<tUInt32> INST_t_cyc;
  MOD_Reg<tUInt32> INST_t_errors;
  MOD_Reg<tUInt32> INST_t_first_out;
  MOD_Reg<tUInt32> INST_t_recv_idx;
  MOD_Reg<tUInt32> INST_t_send_idx;
  MOD_Reg<tUInt8> INST_t_started;
 
 /* Constructor */
 public:
  MOD_mkTb_r8_n96(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt32 DEF_x__h60305;
  tUInt32 DEF_x__h26135;
 
 /* Local definitions */
 private:
  tUInt64 DEF_v__h26215;
  tUInt64 DEF_v__h18681;
  tUInt32 DEF_signed_100___d7;
  tUInt32 DEF_signed_96___d6;
  tUInt32 DEF_signed_8___d5;
  tUInt32 DEF_signed_7___d234;
  tUInt32 DEF_signed_6___d233;
  tUInt32 DEF_signed_5___d232;
  tUInt32 DEF_signed_4___d231;
  tUInt32 DEF_signed_3___d230;
  tUInt32 DEF_signed_2___d229;
  tUInt32 DEF_signed_1___d228;
  tUInt32 DEF_signed_0___d227;
  tUWide DEF_d_get_result___d246;
  tUInt32 DEF_x__h60230;
  tUInt32 DEF_x__h60352;
  tUInt32 DEF_x__h60345;
  std::string DEF_IF_t_errors_22_EQ_0_883_THEN_STR_PASS_ELSE_STR_ETC___d4884;
  std::string DEF_IF_t_cyc_EQ_100_880_THEN_STR_MATCH_ELSE_STR_DIFF___d4881;
  std::string DEF_IF_d_get_result_46_BITS_127_TO_112_292_EQ_IF_I_ETC___d4865;
  std::string DEF_IF_d_get_result_46_BITS_127_TO_112_292_EQ_IF_I_ETC___d4855;
  std::string DEF_IF_d_get_result_46_BITS_111_TO_96_720_EQ_IF_IF_ETC___d4283;
  std::string DEF_IF_d_get_result_46_BITS_95_TO_80_140_EQ_IF_IF__ETC___d3711;
  std::string DEF_IF_d_get_result_46_BITS_95_TO_80_140_EQ_IF_IF__ETC___d3703;
  std::string DEF_IF_d_get_result_46_BITS_79_TO_64_562_EQ_IF_IF__ETC___d3131;
  std::string DEF_IF_d_get_result_46_BITS_79_TO_64_562_EQ_IF_IF__ETC___d3125;
  std::string DEF_IF_d_get_result_46_BITS_63_TO_48_984_EQ_IF_IF__ETC___d2553;
  std::string DEF_IF_d_get_result_46_BITS_63_TO_48_984_EQ_IF_IF__ETC___d2547;
  std::string DEF_IF_d_get_result_46_BITS_47_TO_32_406_EQ_IF_IF__ETC___d1975;
  std::string DEF_IF_d_get_result_46_BITS_47_TO_32_406_EQ_IF_IF__ETC___d1969;
  std::string DEF_IF_d_get_result_46_BITS_31_TO_16_28_EQ_IF_IF_S_ETC___d1397;
  std::string DEF_IF_d_get_result_46_BITS_31_TO_16_28_EQ_IF_IF_S_ETC___d1391;
  std::string DEF_IF_d_get_result_46_BITS_15_TO_0_47_EQ_IF_IF_SE_ETC___d820;
  std::string DEF_IF_d_get_result_46_BITS_15_TO_0_47_EQ_IF_IF_SE_ETC___d810;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d225;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d212;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d60;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d49;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d121;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d106;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d173;
  tUWide DEF_SEL_ARR_0_0_1_0_1_0_0_0_0_0_1_1_0_0_1_1_0_0_1__ETC___d160;
 
 /* Rules */
 public:
  void RL_t_rl_tick();
  void RL_t_rl_begin();
  void RL_t_rl_send();
  void RL_t_rl_recv();
  void RL_t_rl_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb_r8_n96 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb_r8_n96 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb_r8_n96 &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTb_r8_n96 &backing);
};

#endif /* ifndef __mkTb_r8_n96_h__ */
