/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
 * 
 * On Thu Sep 10 12:59:14 IST 2026
 * 
 */

/* Generation options: */
#ifndef __mkTb_r1_n64_h__
#define __mkTb_r1_n64_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkAblation_r1.h"


/* Class declaration for the mkTb_r1_n64 module */
class MOD_mkTb_r1_n64 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkAblation_r1 INST_d;
  MOD_Reg<tUInt32> INST_t_checked;
  MOD_Reg<tUInt32> INST_t_cyc;
  MOD_Reg<tUInt32> INST_t_errors;
  MOD_Reg<tUInt32> INST_t_first_out;
  MOD_Reg<tUInt32> INST_t_recv_idx;
  MOD_Reg<tUInt32> INST_t_send_idx;
  MOD_Reg<tUInt8> INST_t_started;
 
 /* Constructor */
 public:
  MOD_mkTb_r1_n64(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt32 DEF_x__h13475;
  tUInt32 DEF_x__h8788;
 
 /* Local definitions */
 private:
  tUInt64 DEF_v__h8868;
  tUInt64 DEF_v__h7782;
  tUInt32 DEF_signed_772___d8;
  tUInt32 DEF_signed_768___d7;
  tUInt32 DEF_signed_64___d6;
  tUInt32 DEF_signed_1___d5;
  tUInt32 DEF_signed_0___d41;
  tUInt32 DEF_x__h13400;
  tUInt32 DEF_x__h13522;
  tUInt32 DEF_x__h13515;
  std::string DEF_IF_t_errors_43_EQ_0_57_THEN_STR_PASS_ELSE_STR__ETC___d658;
  std::string DEF_IF_t_cyc_EQ_772_54_THEN_STR_MATCH_ELSE_STR_DIFF___d655;
  std::string DEF_IF_d_get_result_0_EQ_IF_IF_SEL_ARR_136_136_136_ETC___d641;
  std::string DEF_IF_d_get_result_0_EQ_IF_IF_SEL_ARR_136_136_136_ETC___d613;
 
 /* Rules */
 public:
  void RL_t_rl_tick();
  void RL_t_rl_begin();
  void RL_t_rl_send();
  void RL_t_rl_recv();
  void RL_t_rl_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb_r1_n64 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb_r1_n64 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb_r1_n64 &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTb_r1_n64 &backing);
};

#endif /* ifndef __mkTb_r1_n64_h__ */
