/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
 * 
 * On Thu Sep 10 12:59:22 IST 2026
 * 
 */

/* Generation options: */
#ifndef __mkTb_r3_n64_h__
#define __mkTb_r3_n64_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkAblation_r3.h"


/* Class declaration for the mkTb_r3_n64 module */
class MOD_mkTb_r3_n64 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkAblation_r3 INST_d;
  MOD_Reg<tUInt32> INST_t_checked;
  MOD_Reg<tUInt32> INST_t_cyc;
  MOD_Reg<tUInt32> INST_t_errors;
  MOD_Reg<tUInt32> INST_t_first_out;
  MOD_Reg<tUInt32> INST_t_recv_idx;
  MOD_Reg<tUInt32> INST_t_send_idx;
  MOD_Reg<tUInt8> INST_t_started;
 
 /* Constructor */
 public:
  MOD_mkTb_r3_n64(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt32 DEF_x__h26625;
  tUInt32 DEF_x__h13391;
 
 /* Local definitions */
 private:
  tUInt64 DEF_v__h13471;
  tUInt64 DEF_v__h10545;
  tUInt32 DEF_signed_260___d8;
  tUInt32 DEF_signed_256___d7;
  tUInt32 DEF_signed_64___d6;
  tUInt32 DEF_signed_3___d5;
  tUInt32 DEF_signed_2___d97;
  tUInt32 DEF_signed_1___d96;
  tUInt32 DEF_signed_0___d95;
  tUInt32 DEF_x__h26550;
  tUInt32 DEF_x__h26672;
  tUInt32 DEF_x__h26665;
  std::string DEF_IF_t_errors_02_EQ_0_915_THEN_STR_PASS_ELSE_STR_ETC___d1916;
  std::string DEF_IF_t_cyc_EQ_260_912_THEN_STR_MATCH_ELSE_STR_DIFF___d1913;
  std::string DEF_IF_d_get_result_08_BITS_47_TO_32_307_EQ_IF_IF__ETC___d1897;
  std::string DEF_IF_d_get_result_08_BITS_47_TO_32_307_EQ_IF_IF__ETC___d1870;
  std::string DEF_IF_d_get_result_08_BITS_31_TO_16_08_EQ_IF_IF_S_ETC___d1298;
  std::string DEF_IF_d_get_result_08_BITS_31_TO_16_08_EQ_IF_IF_S_ETC___d1271;
  std::string DEF_IF_d_get_result_08_BITS_15_TO_0_09_EQ_IF_IF_SE_ETC___d700;
  std::string DEF_IF_d_get_result_08_BITS_15_TO_0_09_EQ_IF_IF_SE_ETC___d672;
 
 /* Rules */
 public:
  void RL_t_rl_tick();
  void RL_t_rl_begin();
  void RL_t_rl_send();
  void RL_t_rl_recv();
  void RL_t_rl_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb_r3_n64 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb_r3_n64 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb_r3_n64 &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTb_r3_n64 &backing);
};

#endif /* ifndef __mkTb_r3_n64_h__ */
