/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
 * 
 * On Thu Sep 10 12:59:55 IST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTb_r6_n128.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTb_r6_n128::MODEL_mkTb_r6_n128()
{
  mkTb_r6_n128_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTb_r6_n128()
{
  MODEL_mkTb_r6_n128 *model = new MODEL_mkTb_r6_n128();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTb_r6_n128 &INST_top = *((MOD_mkTb_r6_n128 *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_CAN_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_CAN_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_CAN_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_CAN_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_CAN_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_CAN_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_WILL_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_WILL_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_WILL_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_WILL_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_WILL_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_WILL_FIRE_RL_rl_multiply;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_CAN_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_CAN_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_CAN_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_CAN_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_CAN_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_CAN_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_WILL_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_WILL_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_WILL_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_WILL_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_WILL_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_WILL_FIRE_RL_rl_add;
	 tUInt8 DEF_INST_top_DEF_t_started__h1219;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_tick;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_tick;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_begin;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_begin;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_send;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_send;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_recv;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_recv;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_finish;
	 DEF_INST_top_DEF_t_started__h1219 = INST_top.INST_t_started.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_begin = !DEF_INST_top_DEF_t_started__h1219;
	 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_begin = DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_begin;
	 INST_top.DEF_x__h47142 = INST_top.INST_t_recv_idx.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_finish = DEF_INST_top_DEF_t_started__h1219 && (INST_top.DEF_x__h47142) == 128u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_finish = DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_finish;
	 INST_top.INST_d.INST_i_lanes_0.METH_RDY_get_result();
	 INST_top.INST_d.INST_i_lanes_1.METH_RDY_get_result();
	 INST_top.INST_d.INST_i_lanes_2.METH_RDY_get_result();
	 INST_top.INST_d.INST_i_lanes_3.METH_RDY_get_result();
	 INST_top.INST_d.INST_i_lanes_4.METH_RDY_get_result();
	 INST_top.INST_d.INST_i_lanes_5.METH_RDY_get_result();
	 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_recv = INST_top.INST_d.METH_RDY_get_result() && (DEF_INST_top_DEF_t_started__h1219 && (INST_top.DEF_x__h47142) < 128u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_recv = DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_recv;
	 INST_top.INST_d.INST_i_lanes_0.METH_RDY_put_operands();
	 INST_top.INST_d.INST_i_lanes_1.METH_RDY_put_operands();
	 INST_top.INST_d.INST_i_lanes_2.METH_RDY_put_operands();
	 INST_top.INST_d.INST_i_lanes_3.METH_RDY_put_operands();
	 INST_top.INST_d.INST_i_lanes_4.METH_RDY_put_operands();
	 INST_top.INST_d.INST_i_lanes_5.METH_RDY_put_operands();
	 INST_top.DEF_x__h21023 = INST_top.INST_t_send_idx.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_send = INST_top.INST_d.METH_RDY_put_operands() && (DEF_INST_top_DEF_t_started__h1219 && (INST_top.DEF_x__h21023) < 128u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_send = DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_send;
	 DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_tick = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_tick = DEF_INST_top_DEF_CAN_FIRE_RL_t_rl_tick;
	 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_CAN_FIRE_RL_rl_add = INST_top.INST_d.INST_i_lanes_0.INST_mid_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_0.INST_out_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_WILL_FIRE_RL_rl_add = DEF_INST_top_INST_d_INST_i_lanes_0_DEF_CAN_FIRE_RL_rl_add;
	 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_CAN_FIRE_RL_rl_multiply = INST_top.INST_d.INST_i_lanes_0.INST_in_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_0.INST_mid_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_0_DEF_WILL_FIRE_RL_rl_multiply = DEF_INST_top_INST_d_INST_i_lanes_0_DEF_CAN_FIRE_RL_rl_multiply;
	 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_CAN_FIRE_RL_rl_add = INST_top.INST_d.INST_i_lanes_1.INST_mid_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_1.INST_out_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_WILL_FIRE_RL_rl_add = DEF_INST_top_INST_d_INST_i_lanes_1_DEF_CAN_FIRE_RL_rl_add;
	 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_CAN_FIRE_RL_rl_multiply = INST_top.INST_d.INST_i_lanes_1.INST_in_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_1.INST_mid_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_1_DEF_WILL_FIRE_RL_rl_multiply = DEF_INST_top_INST_d_INST_i_lanes_1_DEF_CAN_FIRE_RL_rl_multiply;
	 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_CAN_FIRE_RL_rl_add = INST_top.INST_d.INST_i_lanes_2.INST_mid_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_2.INST_out_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_WILL_FIRE_RL_rl_add = DEF_INST_top_INST_d_INST_i_lanes_2_DEF_CAN_FIRE_RL_rl_add;
	 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_CAN_FIRE_RL_rl_multiply = INST_top.INST_d.INST_i_lanes_2.INST_in_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_2.INST_mid_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_2_DEF_WILL_FIRE_RL_rl_multiply = DEF_INST_top_INST_d_INST_i_lanes_2_DEF_CAN_FIRE_RL_rl_multiply;
	 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_CAN_FIRE_RL_rl_add = INST_top.INST_d.INST_i_lanes_3.INST_mid_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_3.INST_out_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_WILL_FIRE_RL_rl_add = DEF_INST_top_INST_d_INST_i_lanes_3_DEF_CAN_FIRE_RL_rl_add;
	 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_CAN_FIRE_RL_rl_multiply = INST_top.INST_d.INST_i_lanes_3.INST_in_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_3.INST_mid_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_3_DEF_WILL_FIRE_RL_rl_multiply = DEF_INST_top_INST_d_INST_i_lanes_3_DEF_CAN_FIRE_RL_rl_multiply;
	 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_CAN_FIRE_RL_rl_add = INST_top.INST_d.INST_i_lanes_4.INST_mid_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_4.INST_out_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_WILL_FIRE_RL_rl_add = DEF_INST_top_INST_d_INST_i_lanes_4_DEF_CAN_FIRE_RL_rl_add;
	 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_CAN_FIRE_RL_rl_multiply = INST_top.INST_d.INST_i_lanes_4.INST_in_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_4.INST_mid_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_4_DEF_WILL_FIRE_RL_rl_multiply = DEF_INST_top_INST_d_INST_i_lanes_4_DEF_CAN_FIRE_RL_rl_multiply;
	 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_CAN_FIRE_RL_rl_add = INST_top.INST_d.INST_i_lanes_5.INST_mid_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_5.INST_out_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_WILL_FIRE_RL_rl_add = DEF_INST_top_INST_d_INST_i_lanes_5_DEF_CAN_FIRE_RL_rl_add;
	 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_CAN_FIRE_RL_rl_multiply = INST_top.INST_d.INST_i_lanes_5.INST_in_fifo.METH_i_notEmpty() && INST_top.INST_d.INST_i_lanes_5.INST_mid_fifo.METH_i_notFull();
	 DEF_INST_top_INST_d_INST_i_lanes_5_DEF_WILL_FIRE_RL_rl_multiply = DEF_INST_top_INST_d_INST_i_lanes_5_DEF_CAN_FIRE_RL_rl_multiply;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_begin)
	   INST_top.RL_t_rl_begin();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_send)
	   INST_top.RL_t_rl_send();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_finish)
	   INST_top.RL_t_rl_finish();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_recv)
	   INST_top.RL_t_rl_recv();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_t_rl_tick)
	   INST_top.RL_t_rl_tick();
	 if (DEF_INST_top_INST_d_INST_i_lanes_0_DEF_WILL_FIRE_RL_rl_add)
	   INST_top.INST_d.INST_i_lanes_0.RL_rl_add();
	 if (DEF_INST_top_INST_d_INST_i_lanes_1_DEF_WILL_FIRE_RL_rl_add)
	   INST_top.INST_d.INST_i_lanes_1.RL_rl_add();
	 if (DEF_INST_top_INST_d_INST_i_lanes_0_DEF_WILL_FIRE_RL_rl_multiply)
	   INST_top.INST_d.INST_i_lanes_0.RL_rl_multiply();
	 if (DEF_INST_top_INST_d_INST_i_lanes_1_DEF_WILL_FIRE_RL_rl_multiply)
	   INST_top.INST_d.INST_i_lanes_1.RL_rl_multiply();
	 if (DEF_INST_top_INST_d_INST_i_lanes_2_DEF_WILL_FIRE_RL_rl_add)
	   INST_top.INST_d.INST_i_lanes_2.RL_rl_add();
	 if (DEF_INST_top_INST_d_INST_i_lanes_2_DEF_WILL_FIRE_RL_rl_multiply)
	   INST_top.INST_d.INST_i_lanes_2.RL_rl_multiply();
	 if (DEF_INST_top_INST_d_INST_i_lanes_3_DEF_WILL_FIRE_RL_rl_add)
	   INST_top.INST_d.INST_i_lanes_3.RL_rl_add();
	 if (DEF_INST_top_INST_d_INST_i_lanes_3_DEF_WILL_FIRE_RL_rl_multiply)
	   INST_top.INST_d.INST_i_lanes_3.RL_rl_multiply();
	 if (DEF_INST_top_INST_d_INST_i_lanes_4_DEF_WILL_FIRE_RL_rl_add)
	   INST_top.INST_d.INST_i_lanes_4.RL_rl_add();
	 if (DEF_INST_top_INST_d_INST_i_lanes_4_DEF_WILL_FIRE_RL_rl_multiply)
	   INST_top.INST_d.INST_i_lanes_4.RL_rl_multiply();
	 if (DEF_INST_top_INST_d_INST_i_lanes_5_DEF_WILL_FIRE_RL_rl_add)
	   INST_top.INST_d.INST_i_lanes_5.RL_rl_add();
	 if (DEF_INST_top_INST_d_INST_i_lanes_5_DEF_WILL_FIRE_RL_rl_multiply)
	   INST_top.INST_d.INST_i_lanes_5.RL_rl_multiply();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_d.INST_i_lanes_0.INST_in_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_0.INST_mid_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_0.INST_out_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_1.INST_in_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_1.INST_mid_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_1.INST_out_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_2.INST_in_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_2.INST_mid_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_2.INST_out_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_3.INST_in_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_3.INST_mid_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_3.INST_out_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_4.INST_in_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_4.INST_mid_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_4.INST_out_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_5.INST_in_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_5.INST_mid_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_d.INST_i_lanes_5.INST_out_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_t_cyc.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_t_send_idx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_t_recv_idx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_t_errors.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_t_checked.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_t_started.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_t_first_out.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTb_r6_n128::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTb_r6_n128_instance = new MOD_mkTb_r6_n128(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_0.INST_in_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_0.INST_mid_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_0.INST_out_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_0.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_1.INST_in_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_1.INST_mid_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_1.INST_out_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_1.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_2.INST_in_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_2.INST_mid_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_2.INST_out_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_2.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_3.INST_in_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_3.INST_mid_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_3.INST_out_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_3.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_4.INST_in_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_4.INST_mid_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_4.INST_out_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_4.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_5.INST_in_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_5.INST_mid_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_5.INST_out_fifo.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.INST_i_lanes_5.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->INST_d.set_clk_0)("CLK");
  (mkTb_r6_n128_instance->set_clk_0)("CLK");
}
void MODEL_mkTb_r6_n128::destroy_model()
{
  delete mkTb_r6_n128_instance;
  mkTb_r6_n128_instance = NULL;
}
void MODEL_mkTb_r6_n128::reset_model(bool asserted)
{
  (mkTb_r6_n128_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTb_r6_n128::get_instance()
{
  return mkTb_r6_n128_instance;
}

/* Fill in version numbers */
void MODEL_mkTb_r6_n128::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87";
}

/* Get the model creation time */
time_t MODEL_mkTb_r6_n128::get_creation_time()
{
  
  /* Thu Sep 10 07:29:55 UTC 2026 */
  return 1789025395llu;
}

/* State dumping function */
void MODEL_mkTb_r6_n128::dump_state()
{
  (mkTb_r6_n128_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTb_r6_n128 & mkTb_r6_n128_backing(tSimStateHdl simHdl)
{
  static MOD_mkTb_r6_n128 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTb_r6_n128(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTb_r6_n128::dump_VCD_defs()
{
  (mkTb_r6_n128_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTb_r6_n128::dump_VCD(tVCDDumpType dt)
{
  (mkTb_r6_n128_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTb_r6_n128_backing(sim_hdl));
}
