//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sun Sep 13 00:19:52 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_max                        O   256
// RDY_get_max                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// get_max_a                      I   256
// get_max_b                      I   256
//
// Combinational paths from inputs to outputs:
//   (get_max_a, get_max_b) -> get_max
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMaxAblation_r16(CLK,
			 RST_N,

			 get_max_a,
			 get_max_b,
			 get_max,
			 RDY_get_max);
  input  CLK;
  input  RST_N;

  // value method get_max
  input  [255 : 0] get_max_a;
  input  [255 : 0] get_max_b;
  output [255 : 0] get_max;
  output RDY_get_max;

  // signals for module outputs
  wire [255 : 0] get_max;
  wire RDY_get_max;

  // ports of submodule i_lanes_0
  wire [15 : 0] i_lanes_0$get_max, i_lanes_0$get_max_a, i_lanes_0$get_max_b;

  // ports of submodule i_lanes_1
  wire [15 : 0] i_lanes_1$get_max, i_lanes_1$get_max_a, i_lanes_1$get_max_b;

  // ports of submodule i_lanes_10
  wire [15 : 0] i_lanes_10$get_max,
		i_lanes_10$get_max_a,
		i_lanes_10$get_max_b;

  // ports of submodule i_lanes_11
  wire [15 : 0] i_lanes_11$get_max,
		i_lanes_11$get_max_a,
		i_lanes_11$get_max_b;

  // ports of submodule i_lanes_12
  wire [15 : 0] i_lanes_12$get_max,
		i_lanes_12$get_max_a,
		i_lanes_12$get_max_b;

  // ports of submodule i_lanes_13
  wire [15 : 0] i_lanes_13$get_max,
		i_lanes_13$get_max_a,
		i_lanes_13$get_max_b;

  // ports of submodule i_lanes_14
  wire [15 : 0] i_lanes_14$get_max,
		i_lanes_14$get_max_a,
		i_lanes_14$get_max_b;

  // ports of submodule i_lanes_15
  wire [15 : 0] i_lanes_15$get_max,
		i_lanes_15$get_max_a,
		i_lanes_15$get_max_b;

  // ports of submodule i_lanes_2
  wire [15 : 0] i_lanes_2$get_max, i_lanes_2$get_max_a, i_lanes_2$get_max_b;

  // ports of submodule i_lanes_3
  wire [15 : 0] i_lanes_3$get_max, i_lanes_3$get_max_a, i_lanes_3$get_max_b;

  // ports of submodule i_lanes_4
  wire [15 : 0] i_lanes_4$get_max, i_lanes_4$get_max_a, i_lanes_4$get_max_b;

  // ports of submodule i_lanes_5
  wire [15 : 0] i_lanes_5$get_max, i_lanes_5$get_max_a, i_lanes_5$get_max_b;

  // ports of submodule i_lanes_6
  wire [15 : 0] i_lanes_6$get_max, i_lanes_6$get_max_a, i_lanes_6$get_max_b;

  // ports of submodule i_lanes_7
  wire [15 : 0] i_lanes_7$get_max, i_lanes_7$get_max_a, i_lanes_7$get_max_b;

  // ports of submodule i_lanes_8
  wire [15 : 0] i_lanes_8$get_max, i_lanes_8$get_max_a, i_lanes_8$get_max_b;

  // ports of submodule i_lanes_9
  wire [15 : 0] i_lanes_9$get_max, i_lanes_9$get_max_a, i_lanes_9$get_max_b;

  // value method get_max
  assign get_max =
	     { i_lanes_15$get_max,
	       i_lanes_14$get_max,
	       i_lanes_13$get_max,
	       i_lanes_12$get_max,
	       i_lanes_11$get_max,
	       i_lanes_10$get_max,
	       i_lanes_9$get_max,
	       i_lanes_8$get_max,
	       i_lanes_7$get_max,
	       i_lanes_6$get_max,
	       i_lanes_5$get_max,
	       i_lanes_4$get_max,
	       i_lanes_3$get_max,
	       i_lanes_2$get_max,
	       i_lanes_1$get_max,
	       i_lanes_0$get_max } ;
  assign RDY_get_max = 1'd1 ;

  // submodule i_lanes_0
  mkTorchMaximum_SIMD i_lanes_0(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_0$get_max_a),
				.get_max_b(i_lanes_0$get_max_b),
				.get_max(i_lanes_0$get_max),
				.RDY_get_max());

  // submodule i_lanes_1
  mkTorchMaximum_SIMD i_lanes_1(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_1$get_max_a),
				.get_max_b(i_lanes_1$get_max_b),
				.get_max(i_lanes_1$get_max),
				.RDY_get_max());

  // submodule i_lanes_10
  mkTorchMaximum_SIMD i_lanes_10(.CLK(CLK),
				 .RST_N(RST_N),
				 .get_max_a(i_lanes_10$get_max_a),
				 .get_max_b(i_lanes_10$get_max_b),
				 .get_max(i_lanes_10$get_max),
				 .RDY_get_max());

  // submodule i_lanes_11
  mkTorchMaximum_SIMD i_lanes_11(.CLK(CLK),
				 .RST_N(RST_N),
				 .get_max_a(i_lanes_11$get_max_a),
				 .get_max_b(i_lanes_11$get_max_b),
				 .get_max(i_lanes_11$get_max),
				 .RDY_get_max());

  // submodule i_lanes_12
  mkTorchMaximum_SIMD i_lanes_12(.CLK(CLK),
				 .RST_N(RST_N),
				 .get_max_a(i_lanes_12$get_max_a),
				 .get_max_b(i_lanes_12$get_max_b),
				 .get_max(i_lanes_12$get_max),
				 .RDY_get_max());

  // submodule i_lanes_13
  mkTorchMaximum_SIMD i_lanes_13(.CLK(CLK),
				 .RST_N(RST_N),
				 .get_max_a(i_lanes_13$get_max_a),
				 .get_max_b(i_lanes_13$get_max_b),
				 .get_max(i_lanes_13$get_max),
				 .RDY_get_max());

  // submodule i_lanes_14
  mkTorchMaximum_SIMD i_lanes_14(.CLK(CLK),
				 .RST_N(RST_N),
				 .get_max_a(i_lanes_14$get_max_a),
				 .get_max_b(i_lanes_14$get_max_b),
				 .get_max(i_lanes_14$get_max),
				 .RDY_get_max());

  // submodule i_lanes_15
  mkTorchMaximum_SIMD i_lanes_15(.CLK(CLK),
				 .RST_N(RST_N),
				 .get_max_a(i_lanes_15$get_max_a),
				 .get_max_b(i_lanes_15$get_max_b),
				 .get_max(i_lanes_15$get_max),
				 .RDY_get_max());

  // submodule i_lanes_2
  mkTorchMaximum_SIMD i_lanes_2(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_2$get_max_a),
				.get_max_b(i_lanes_2$get_max_b),
				.get_max(i_lanes_2$get_max),
				.RDY_get_max());

  // submodule i_lanes_3
  mkTorchMaximum_SIMD i_lanes_3(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_3$get_max_a),
				.get_max_b(i_lanes_3$get_max_b),
				.get_max(i_lanes_3$get_max),
				.RDY_get_max());

  // submodule i_lanes_4
  mkTorchMaximum_SIMD i_lanes_4(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_4$get_max_a),
				.get_max_b(i_lanes_4$get_max_b),
				.get_max(i_lanes_4$get_max),
				.RDY_get_max());

  // submodule i_lanes_5
  mkTorchMaximum_SIMD i_lanes_5(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_5$get_max_a),
				.get_max_b(i_lanes_5$get_max_b),
				.get_max(i_lanes_5$get_max),
				.RDY_get_max());

  // submodule i_lanes_6
  mkTorchMaximum_SIMD i_lanes_6(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_6$get_max_a),
				.get_max_b(i_lanes_6$get_max_b),
				.get_max(i_lanes_6$get_max),
				.RDY_get_max());

  // submodule i_lanes_7
  mkTorchMaximum_SIMD i_lanes_7(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_7$get_max_a),
				.get_max_b(i_lanes_7$get_max_b),
				.get_max(i_lanes_7$get_max),
				.RDY_get_max());

  // submodule i_lanes_8
  mkTorchMaximum_SIMD i_lanes_8(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_8$get_max_a),
				.get_max_b(i_lanes_8$get_max_b),
				.get_max(i_lanes_8$get_max),
				.RDY_get_max());

  // submodule i_lanes_9
  mkTorchMaximum_SIMD i_lanes_9(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_9$get_max_a),
				.get_max_b(i_lanes_9$get_max_b),
				.get_max(i_lanes_9$get_max),
				.RDY_get_max());

  // submodule i_lanes_0
  assign i_lanes_0$get_max_a = get_max_a[15:0] ;
  assign i_lanes_0$get_max_b = get_max_b[15:0] ;

  // submodule i_lanes_1
  assign i_lanes_1$get_max_a = get_max_a[31:16] ;
  assign i_lanes_1$get_max_b = get_max_b[31:16] ;

  // submodule i_lanes_10
  assign i_lanes_10$get_max_a = get_max_a[175:160] ;
  assign i_lanes_10$get_max_b = get_max_b[175:160] ;

  // submodule i_lanes_11
  assign i_lanes_11$get_max_a = get_max_a[191:176] ;
  assign i_lanes_11$get_max_b = get_max_b[191:176] ;

  // submodule i_lanes_12
  assign i_lanes_12$get_max_a = get_max_a[207:192] ;
  assign i_lanes_12$get_max_b = get_max_b[207:192] ;

  // submodule i_lanes_13
  assign i_lanes_13$get_max_a = get_max_a[223:208] ;
  assign i_lanes_13$get_max_b = get_max_b[223:208] ;

  // submodule i_lanes_14
  assign i_lanes_14$get_max_a = get_max_a[239:224] ;
  assign i_lanes_14$get_max_b = get_max_b[239:224] ;

  // submodule i_lanes_15
  assign i_lanes_15$get_max_a = get_max_a[255:240] ;
  assign i_lanes_15$get_max_b = get_max_b[255:240] ;

  // submodule i_lanes_2
  assign i_lanes_2$get_max_a = get_max_a[47:32] ;
  assign i_lanes_2$get_max_b = get_max_b[47:32] ;

  // submodule i_lanes_3
  assign i_lanes_3$get_max_a = get_max_a[63:48] ;
  assign i_lanes_3$get_max_b = get_max_b[63:48] ;

  // submodule i_lanes_4
  assign i_lanes_4$get_max_a = get_max_a[79:64] ;
  assign i_lanes_4$get_max_b = get_max_b[79:64] ;

  // submodule i_lanes_5
  assign i_lanes_5$get_max_a = get_max_a[95:80] ;
  assign i_lanes_5$get_max_b = get_max_b[95:80] ;

  // submodule i_lanes_6
  assign i_lanes_6$get_max_a = get_max_a[111:96] ;
  assign i_lanes_6$get_max_b = get_max_b[111:96] ;

  // submodule i_lanes_7
  assign i_lanes_7$get_max_a = get_max_a[127:112] ;
  assign i_lanes_7$get_max_b = get_max_b[127:112] ;

  // submodule i_lanes_8
  assign i_lanes_8$get_max_a = get_max_a[143:128] ;
  assign i_lanes_8$get_max_b = get_max_b[143:128] ;

  // submodule i_lanes_9
  assign i_lanes_9$get_max_a = get_max_a[159:144] ;
  assign i_lanes_9$get_max_b = get_max_b[159:144] ;
endmodule  // mkMaxAblation_r16

