//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sun Sep 13 00:19:51 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_max                        O    48
// RDY_get_max                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// get_max_a                      I    48
// get_max_b                      I    48
//
// Combinational paths from inputs to outputs:
//   (get_max_a, get_max_b) -> get_max
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMaxAblation_r3(CLK,
			RST_N,

			get_max_a,
			get_max_b,
			get_max,
			RDY_get_max);
  input  CLK;
  input  RST_N;

  // value method get_max
  input  [47 : 0] get_max_a;
  input  [47 : 0] get_max_b;
  output [47 : 0] get_max;
  output RDY_get_max;

  // signals for module outputs
  wire [47 : 0] get_max;
  wire RDY_get_max;

  // ports of submodule i_lanes_0
  wire [15 : 0] i_lanes_0$get_max, i_lanes_0$get_max_a, i_lanes_0$get_max_b;

  // ports of submodule i_lanes_1
  wire [15 : 0] i_lanes_1$get_max, i_lanes_1$get_max_a, i_lanes_1$get_max_b;

  // ports of submodule i_lanes_2
  wire [15 : 0] i_lanes_2$get_max, i_lanes_2$get_max_a, i_lanes_2$get_max_b;

  // value method get_max
  assign get_max =
	     { i_lanes_2$get_max, i_lanes_1$get_max, i_lanes_0$get_max } ;
  assign RDY_get_max = 1'd1 ;

  // submodule i_lanes_0
  mkTorchMaximum_SIMD i_lanes_0(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_0$get_max_a),
				.get_max_b(i_lanes_0$get_max_b),
				.get_max(i_lanes_0$get_max),
				.RDY_get_max());

  // submodule i_lanes_1
  mkTorchMaximum_SIMD i_lanes_1(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_1$get_max_a),
				.get_max_b(i_lanes_1$get_max_b),
				.get_max(i_lanes_1$get_max),
				.RDY_get_max());

  // submodule i_lanes_2
  mkTorchMaximum_SIMD i_lanes_2(.CLK(CLK),
				.RST_N(RST_N),
				.get_max_a(i_lanes_2$get_max_a),
				.get_max_b(i_lanes_2$get_max_b),
				.get_max(i_lanes_2$get_max),
				.RDY_get_max());

  // submodule i_lanes_0
  assign i_lanes_0$get_max_a = get_max_a[15:0] ;
  assign i_lanes_0$get_max_b = get_max_b[15:0] ;

  // submodule i_lanes_1
  assign i_lanes_1$get_max_a = get_max_a[31:16] ;
  assign i_lanes_1$get_max_b = get_max_b[31:16] ;

  // submodule i_lanes_2
  assign i_lanes_2$get_max_a = get_max_a[47:32] ;
  assign i_lanes_2$get_max_b = get_max_b[47:32] ;
endmodule  // mkMaxAblation_r3

